### ISSUE TITLE
Create Game shouldn't lose your selection if you change limits

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1010]
If you select a button from the Create Game page, then change the limits (e.g., setting "Tournament legal" from "ANY" to "yes"), then as long as the button you selected still matches the filters, it should still remain selected. At the moment, when you make the change, it reverts to "Choose your button" regardless.

**Comment by irilyth** [comment]
One random note: This currently behaves differently if you create e.g. a reverse game: If I create a reverse, then click on a set, and then click back on ANY, my opponent's button from the previous game is still there. (And likewise if I click on a set that the button isn't in, and then click on the set that the button is in.)

**Comment by blackshadowshade** [comment]
I imagine that this is pretty easy to fix, it's just a matter of storing the button name in the correct way in the onChange event, and then checking to see if it is present in the newly filtered list.
