### ISSUE TITLE
game creation needs a better method for selecting opponent name

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#108]
Opponents are currently selected in create_game via a drop-down of all people who have accounts.  This is unwieldy.  Either get autocomplete of opponent name working again, or come up with some other solution.

**Comment by blackshadowshade** [comment]
For my own reference, the original code used this:

```
$('#opp_player_name').autocomplete({
    source: function(request, response) {
        $.post(
            'responder.php',
            {
                type: 'loadPlayerNamesLike',
                input: request.term
            },
            function(rs) {
                response(rs.nameArray);
            },
            'json'
        );
    },
    delay: 500
});
```

**Comment by blackshadowshade** [comment]
Reading from https://jqueryui.com/autocomplete/, it seems much of that logic either was or is now unnecessary, and I can provide the whole list directly in the source field.

**Comment by blackshadowshade** [comment]
Okay, a question to testers. When I reimplement autocomplete, what would you like to see? Some options I've considered are:
  - an extra autocompleting text field next to the current select
  - an autocompleting text field instead of the current select
  - a button to allow toggling between the current select and an autocompleting text field, with the select as default
  - a button to allow toggling between the current select and an autocompleting text field, with the text field as default

**Comment by blackshadowshade** [comment]
Feel free to answer this specific to both player selection and button selection (#1316) if your answers are different for the two selectors.

**Comment by blackshadowshade** [comment]
Also, consider what you want to happen to the options "Anybody", "Random button", and "Any button".

**Comment by AdmiralJota** [comment]
My main concern is that it's important that the user still be able to see and browse through the full list if they want. If we lose that ability, I'd consider it a regression.

An ideal solution, IMO, would be a javascript control that functions as both at the same time. It looks like https://jqueryui.com/autocomplete/#combobox might be an example of that (minus the "Show underlying select" button, of course).

That said, I don't know if the "This is not a supported or even complete widget." note at the bottom should be a red flag about trying to do this...

**Comment by AdmiralJota** [comment]
Also: if we like this solution for selecting players, then the categories functionality (https://jqueryui.com/autocomplete/#categories) might be appropriate for buttons, since it would let us display what sets they're in.

**Comment by irilyth** [comment]
I've totally forgotten what this used to look like. What did this used to look like, and what does "autocomplete" mean in this context? A text box, and when you type letters in it, it fills in the rest of the letters of someone's username once you type in enough letters for it to be unique?

**Comment by irilyth** [comment]
> When I reimplement autocomplete, what would you like to see?

Two other options would be to have the toggle depend on a user preference, and/or whether the user is on a mobile or desktop device (if e.g. we hypothesize that the dropdown is always useless on a mobile device).

**Comment by blackshadowshade** [comment]
So, what do people think of @AdmiralJota's suggestion of a combination select and text field?

https://jqueryui.com/autocomplete/#combobox

**Comment by blackshadowshade** [comment]
While attempting to implement the combo box, I stumbled across

http://www.melrosesolutions.com/blog/index.cfm/2010/7/16/Turn-SELECTs-into-Comboboxes-with-jQuery-UI-Autocomplete

which further referred me to

https://harvesthq.github.io/chosen/

That Chosen plugin looks pretty nice!


What do you think of the first example on the Chosen page?

**Comment by blackshadowshade** [comment]
Interestingly, the people at Chosen have decided to disable the control for iPhones, iPads, and Android tablets.

https://github.com/harvesthq/chosen/pull/1388

**Comment by AdmiralJota** [comment]
This looks slick!

For mobile devices, does it gracefully degrade back to a regular select list? If so, it sounds like even for those cases, it wouldn't be any worse than what we have now.

**Comment by dwvanstone** [comment]
> So, what do people think of @AdmiralJota's suggestion of a combination select and text field?
> https://jqueryui.com/autocomplete/#combobox

This is an excellent solution! Is it possible to create a test page with several different options to be tested on our mobile devices for feedback?

**Comment by blackshadowshade** [comment]
@AdmiralJota, if you follow the discussion on the pull request, it's possible to re-enable the Chosen plugin for mobile devices. If I'm reading correctly, the major issue with the Chosen plugin was that the search field obscured the list options. Since we're not using search but just autocomplete, I think we wouldn't have any problems with the Chosen plugin.

@dwvanstone, it's possible to test the custom combo box now with mobile devices. However, based on the link at melrosesolutions, it sounds like the custom combo box may actually be incomplete, which is why I'm looking at the Chosen option. I'll see what I can do about getting some sort of demo pull request up once I get it working.

**Comment by blackshadowshade** [comment]
Okay, I have misread. The problem with the plugin is an inherent one, that the keyboard pops up and obscures some of the list options on small screens. This *will* be a problem for us, no matter what solution we implement. The current behaviour of Chosen on small screens is to default back to a standard select, so yes, this would be no worse than current behaviour. However, it wouldn't necessarily be a complete solution for the current issue.

**Comment by AdmiralJota** [comment]
By the way, if this works out well for game creation, should we do the History page too in the same pull? Or should we make a separate issue for that?

**Comment by blackshadowshade** [comment]
I'd suggest making a second pull request for that. The change itself is small enough that a subsequent pull request should be pretty easy to accept.
