### ISSUE TITLE
Change page title in Monitor mode

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1125]
It'd be cool if the page title changed when you were in Monitor mode, so that if you have it in a non-active tab, the title of the tab would change (back to the usual title) if you had active games.

**Comment by cgolubi1** [comment]
We got a ping on this issue on the site forum - http://www.buttonweavers.com/ui/forum.html#!threadId=211

**Comment by irilyth** [comment]
This wasn't actually fully fixed by #1793.

**Comment by dwvanstone** [comment]
What part isn't fixed that you'd like to see fixed?

**Comment by irilyth** [comment]
The page title doesn't change, and the grayscale favicon isn't actually used. So, basically, all of it. :^) All I did was make the icon.

**Comment by dwvanstone** [comment]
It works for me, however.

I am using Safari 9.0.1. on a Mac. Here's what I did:

I play through all my games and I hit Monitor in the top bar. Now the page title is "Button Men Online". I switch to another tab entirely.

A few minutes later, I can see the page title changed to the game page title ("Button Men Online - Game NUMBER • name (Button) vs. name (button) • Round NUMBER").

**Comment by irilyth** [comment]
Yeah, I think we started changing the page title on game pages, which addressed some of this; but folks on that forum thread (http://www.buttonweavers.com/ui/forum.html#!threadId=211) still had some suggestions for improvement. This one in particular:

> Safari tab width depends a bit on how many tabs you have open, and  it just truncates the title generally. Mine all say "Button men..." which is supremely unhelpful for distinguishing.
>
> If you reversed the order so they said "[Other thing] -- Button Men Online" it'd work for Safari at least. THat's the only browser I use so I don't know offhand how others behave.
>
> (If anybody's testing this, Safari tries to be smart and display the distinguishing part of a title if you have >1 tab from the same domain name, so you'll only see the behaviour properly if  you only have one BM tab.)

For my personal purposes, the favicon would be more useful, because I most often have the tab pinned in Firefox, so only the favicon is visible.

**Comment by dwvanstone** [comment]
I have now learned what pinning a tab means by trying it. Now I see what you're after.

Yes, when you use a pinned tab on Firefox you can not distinguish between being in monitor mode and when a game or forum message is new.

Perhaps a fix for the Safari users is to add a special graphic character to the left of the title which indicates that it is in monitor mode...and then that graphic goes away when out of minotor mode. (Such as &rarr; or &Dagger;.)

So, if I understand right, to consider this bug closed we need to provide a different visualization for pinned tabs on Firefox and for Safari users using multiple tabs where only the first N characters get displayed. Are there any other special cases as well we need to consider for this bug?

**Comment by irilyth** [comment]
I think the pinned-tab-in-Firefox case would be solved by having a different favicon when you're in monitor mode. (And likewise any other browser that puts the favicon in a pinned tab.)

I think the Safari case would be solved by (a) reversing the order of the elements of the page title in general, so more like "Game #X blah etc - Button Men Online" than "Button Men Online - Game #X blah etc", for all the pages; (b) having the page title when you're in monitor mode be "* Monitor Active * - Button Men Online". (Or something else; I picked that text because it's what's at the top of the Monitor page itself, but don't feel strongly about it.)

**Comment by dwvanstone** [comment]
At first I was against reversing the order of the elements, but some quick internet research says that isn't a crazy idea. In fact, GitHub's Title Tag does not start with 'GitHub' but with the topic being changed. It's out of scope of this bug to change all of the page titles across the website, but using "Monitor Active: Button Men Online" would seem fine to me.

**Comment by AdmiralJota** [comment]
I think it might be as simple as changing this one method in Overview.js: https://gist.github.com/AdmiralJota/01d30146a5e17650bc50

Anyone wanna give it a try?

**Comment by dwvanstone** [comment]
If someone assigns this to me I'll take a look at it sometime this month. (I'm not sure if someone else is actively working on this.)

**Comment by dwvanstone** [comment]
I think there are four possible monitor modes based on preference:

Basic: refreshes the Overview page every minute but doesn't send you anywhere
Game: automatically sends you from the Overview page to an active game where it's your turn
Forum: automatically sends you from the Overview page to a forum where there's a new message
Game/Forum: combination of Game & Forum

What if you are in Basic monitor mode? Would you want the favicon and the page title to change on the Overview page when a game or forum thread is available to interact with?

**Comment by cgolubi1** [comment]
On Thu, 12 Nov, 2015 at 12:30:49 -0800, dwvanstone wrote:

> What if you are in Basic monitor mode? Would you want the favicon and the page title to change on the Overview page when a game or forum thread is available to interact with?

As a player who uses Basic monitor mode: yes, i would.

Chaos

**Comment by irilyth** [comment]
I don't use Basic monitor mode, but having the title and favicon be different when you do and don't have active things to do, that sounds good to me!

**Comment by dwvanstone** [comment]
Okay, let's say you're in Basic monitor mode. I'm going to assume everyone cares about new games that are available to play. Should it be a preference whether new forum messages changes the favicon and page title?

**Comment by dwvanstone** [comment]
The grayscale version of favicon.ico is a great placeholder to indicate that the user is in monitor mode. I'm even happy to go out with that for now, but if someone wants to play with the icon and make one with an exclamation point or an eyeball or something else that indicates "we're in monitor mode" please do so! (I don't think grayscale indicates monitor, but it does indicate something is different!)

**Comment by irilyth** [comment]
My idea behind the grayscale was that it was like a "grayed out" menu item or button or whatever, i.e. there's nothing you can do right now; and it would spring back to being the normal non-gray thing when there was something you could do.

But, I also don't particularly mind if someone wants to create a different icon for whatever reason. And it's not hard to change later, try different things, etc.

**Comment by blackshadowshade** [comment]
The issue with *just* changing the favicon is that it doesn't help Safari users.

**Comment by dwvanstone** [comment]
yawetag or irilyth: could you make a separate bug request which asks specifically for the favicon change? I've addressed the page titles in #1821.

**Comment by irilyth** [comment]
Done!
