### ISSUE TITLE
Figure out how to handle links inside of spoiler tags

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1153]
At present, if there's a link (e.g. to a game or player profile) inside of a spoiler tag, the link won't be visible as such (since the spoiler is blacked out), the mouse cursor will display as a normal arrow when you mouse over it, and it would be very easy to accidentally follow the link when you're only intending to click on the spoiler to reveal it.

We should decide how we want to handle this. 

One option is to try to override the click, so that clicking on a link inside of concealed spoiler _only_ reveals the spoiler without activating the link. But the problem with that is that if you reveal the spoiler by just highlighting it (as I expect many people normally would, since they wouldn't even know they're supposed to click), you'd never be able to actually use the link. 

Any thoughts on this?

**Comment by blackshadowshade** [comment]
I've recently had a lot of angst with exactly this issue while trying to read spoilers on a recent tournament thread.

I'm going to try to change things so that when spoiler text is hidden, a link inside the spoiler tag won't be followed.
