### ISSUE TITLE
Upgrade to PHP 5.5 or higher

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1167]
We're apparently currently using PHP 5.3.10. We should upgrade to a newer version at some point. (This would particularly help with #884.)

**Comment by blackshadowshade** [comment]
I'm choosing this as my BotM for April.

**Comment by blackshadowshade** [comment]
Looking at https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.7.0, we should probably consider upgrading to PHP 5.6 or higher when we actually do this upgrade.

**Comment by blackshadowshade** [comment]
Okay, adding my September BotM to this.

**Comment by blackshadowshade** [comment]
Just noting for myself that the solution to #1728 that was implemented currently installs PHPUnit 4.8.26, according to Chaos, which is great.

**Comment by blackshadowshade** [comment]
So, on this theme, I've been using with PHP 5.6.30-12 on stats.dev, and have hit the following issues that will need to be addressed when we upgrade our version of Ubuntu (as noted in #2208):

1. /etc/mime.types needs to be checked to see whether the PHP types there have been commented out.
2. PHP-MySQL needs to be upgraded
    
    sudo apt-get install php5.6-mysql

3. The .conf files for Apache need to be updated, because they have been rearranged:

    sudo cp /etc/apache/conf.d/buttonmen /etc/apache/conf.enabled/buttonmen.conf

4. mbstring needs to be installed

    sudo apt-get install php5.6-mbstring

5. The call to crypt() needs to be changed to

    ':password' => password_hash($password, PASSWORD_DEFAULT),

This list is not complete yet, since it's still not possible to create new users, and I'll update the list when I track down the last few issues.

**Comment by blackshadowshade** [comment]
Just a thought that we should actually be aiming for PHP 7 when we upgrade, not PHP 5.6.

A migration guide from PHP 5.6 to PHP 7.0 is here: http://php.net/manual/en/migration70.php

**Comment by blackshadowshade** [comment]
I've updated my stats.dev instance to PHP 7.2, following the instructions here: https://askubuntu.com/questions/109404/how-do-i-install-different-upgrade-or-downgrade-php-version-in-still-supported

I'll be testing PHP 7.2 in parallel on the stats.dev server and my new MAMP 4.0 distribution.

**Comment by blackshadowshade** [comment]
One thing that has changed with PHP 7 is the way it handles indirect access to variables.

See http://php.net/manual/en/migration70.incompatible.php for details

In ApiResponder, we have

    $data = $this->$check['funcname']($interface, $args);

This needs to be changed to

    $data = $this->{$check['funcname']}($interface, $args);

to ensure the correct order of execution.

**Comment by blackshadowshade** [comment]
To check the migration from PHP 5.3 to PHP 7, I've installed php7cc

(see https://github.com/sstalle/php7cc/blob/master/README.md)

After running this on the code, it adds the following warning:

    File: /var/www/engine/BMGame.php
    > Line 3798: [Warning] Nested by-reference foreach loop, make sure that array modifications (if any) do what you expect
        foreach ($valueArray as &$value) {
        }

**Comment by blackshadowshade** [comment]
So, we're now up to PHP 7.0. Closing the issue.

**Comment by blackshadowshade** [comment]
Actually, I'll use this issue as a placeholder for the isset() changes that occurred, and that we're still trying to fix.
