### ISSUE TITLE
make jenkins runs faster

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1168]
When we first stood up jenkins, individual builds were taking a couple of minutes.  Now that's up to 10-13 minutes, depending on branch.  See if we can reasonably make jenkins faster.

**Comment by blackshadowshade** [comment]
So, back to this. Some possible ideas for speeding up PHPUnit that Google found:
- upgrade the PHPUnit version
https://github.com/sebastianbergmann/phpunit/issues/1187
- defer the flushing of transactions to disc http://aventinesolutions.nl/mediawiki2/index.php/PHPUnit:_a_Quick_Way_to_Speed_Up_Test_Suites
- use in-memory database testing
"For database slowness: install another mysql server and have it's entire datafolder in memory-backend mountpoint (e.g. tmpfs in linux). That will speed up db creation & operations remarkably."
http://stackoverflow.com/questions/3697815/best-practices-for-database-testing-with-phpunit

**Comment by irilyth** [comment]
A random side comment that y'all should feel free to ignore: I was recently curious about what Travis was, and how it related to Jenkins, and found https://stackoverflow.com/questions/32422264/jenkins-vs-travis-ci, which mentions that Travis is well-integrated with GitHub and very easy to set up. I don't know how *fast* it is, but if it's fast, switching to it would also save us the hassle of having to run our own Jenkins setup. (The short answer to my original question is "Travis is a hosted service".)

**Comment by blackshadowshade** [comment]
I'm closing this issue because we don't use Jenkins any more.

The issue of updating PHPUnit will be captured in a new issue.
