### ISSUE TITLE
Sort Overview page in reverse chronological order

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1169]
Suggested by nkmcalli at http://www.buttonweavers.com/ui/forum.html#!threadId=3

Nicole would like the "waiting for opponent's turn" section sorted in reverse chronological order, but I think that it wouldn't hurt to apply this to the "waiting for you" section also.

**Comment by cgolubi1** [comment]
Hmm, so, i think this would be an actively bad idea for the "waiting for you" section.  If the games that have been waiting the least long show up first, and you're behind on your games, the games which have been waiting the longest will starve forever.

**Comment by blackshadowshade** [comment]
I've been noticing this more and more in the last couple of months, as my list of idle games gets longer. I agree that this is a useful thing to do for the "waiting for opponent's turn" section, and I'll address it---should be a one-liner.

I agree with Chaos that this shouldn't apply to the "waiting for you" section

**Comment by cgolubi1** [comment]
AFAIK i don't care either way about the waiting for opponent's section, so i think switching that one and seeing what people think is fine.
