### ISSUE TITLE
Create game filters don't work on Chrome/Android

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1197]
When I go to the create game page in Chrome on my Android phone (Google Nexus 5, Android 4.4.4, Chrome 36.0.1985.131), the filters like "Button set" and "Die skill" appear as pop-up menus. When I tap on them, they pop up a list of items with checkboxes, which I can tap to check or uncheck, and an Ok button which I can tap to accept my selections. When I do that, it doesn't change the options on the "Choose your button" menu; e.g. if I select the "1999 Rare / Promo" set, or the Berserk skill, it still shows Avis as a possible button. I expected the "Chose your button" menu to be restricted to buttons that matched the filter criteria, which is what happens when I do the analogous thing on Firefox on my Linux laptop. (Where it shows up as a select-multiple menu (http://www.w3schools.com/tags/att_select_multiple.asp) like any other.)

**Comment by blackshadowshade** [comment]
@irilyth, I'm just going through old issues and came across this one. Is this still a problem for you? Or has it ceased to be relevant?

**Comment by irilyth** [comment]
This seems to work fine now, and it's possible that when I tried it before, I forgot to *uncheck* the "ANY" item at the top. (Which I think should maybe automatically un-check if you check anything else, since why would you ever want "this set or any set"? but that's not this ticket, we can make a new one for that if we want.)

Closing this one out!
