### ISSUE TITLE
Button specials need descriptions

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1200]
Some button specials have been implemented already. Their ```BMBtnSkill``` classes should have a static ```get_description()``` method on them that returns the description of that special as a string. (And as new ones are implemented, they should be given descriptions as well.)

**Comment by blackshadowshade** [comment]
So, two things need to be done here:
- BMGame->get_gameSkillsInfo() needs to be updated to also include button skills
- BMBtnSkills need to be described
