### ISSUE TITLE
Preference to always go to Monitor mode

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1246]
There's a preference "Automatically Monitor after "Next game" runs out" right now, but this doesn't affect other things that would take you to the Overview page, like dismissing a game from the end-of-game page. As a user of this feature, I'd like it to be more like "Always Monitor when sent to Overview page", with an exception for when you actually explicitly click on "Overview" in the header -- but basically anything else that's going to send you to Overview should send you to monitor instead. (Or should go to http://dev.buttonweavers.com/ui/index.html?mode=preference if that's how this is implemented?)

I'd vote for replacing the current preference with this, rather than adding a new one, but we could poll people who use the current one to see if they prefer the current behavior.

**Comment by jimmosk** [comment]
Since I've had some times when I dismissed a game and didn't realize 'til much later that I was no longer in Monitor mode, I'd like to make this my Bugfix of the Month.
