### ISSUE TITLE
incomplete button sets

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#1291]
Magical Witch Critical Miss is not yet in the database with the other 2005 Rare / Promos.  Bridge and Tunnel is short six buttons (three of which are missing recipes, but I'll throw them in there so I can edit the buttons rather than add new ones later).  And Kuni sent me a rare from YoyoDyne that wasn't on any other list.

**Comment by blackshadowshade** [comment]
Closing this one.
