### ISSUE TITLE
Forum doesn't work with IE9

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1300]
In chat in game http://www.buttonweavers.com/ui/game.html?game=1668, Stoooooooo reports that "For whatever reason I cannot see the forum at all.  I believe it is my browser." and "I am on IE9 - when i go to the forum page it is totally blank."

**Comment by blackshadowshade** [comment]
@nkmcalli, is this still an issue, or is it now obsolete?

**Comment by blackshadowshade** [comment]
I would hope that no one is still using IE 9. I'm closing this issue as wontfix.
