### ISSUE TITLE
show a different UI error when a POST gets no response from the server at all

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1315]
Right now, Api.apiParsePost() and Api.apiFormPost() have a generic fail() block that just reports an internal error calling the function.

However, if the POST doesn't get a response from the server at all, it's more likely that the player has a local network issue (or the server is down) than that anything is getting an internal error.  Detect when the error is that no response at all was received from the server, and show the player a different error, suggesting a possible network problem, in that case.

**Comment by blackshadowshade** [comment]
I'm uncertain how to simulate the server failure with my MAMP stack. If I stop the servers, then the requested page doesn't load at all. If I change the server port, I end up with a blank page. If I change the MySQL port, nothing seems to change.

How should I simulate the error that we're aiming to fix?

**Comment by blackshadowshade** [comment]
For my own reference:

http://www.w3schools.com/ajax/ajax_xmlhttprequest_onreadystatechange.asp

Three important properties of the XMLHttpRequest object:

Property	Description
onreadystatechange	Stores a function (or the name of a function) to be called automatically each time the readyState property changes
readyState	Holds the status of the XMLHttpRequest. Changes from 0 to 4: 
0: request not initialized 
1: server connection established
2: request received 
3: processing request 
4: request finished and response is ready
status	200: "OK"
404: Page not found

**Comment by blackshadowshade** [comment]
Ah, I've found how to get the error.

Changing Env.api_location within Firebug and then attempting to submit a game turn gives me the error page.

**Comment by blackshadowshade** [comment]
Okay, when attempting to submit a turn with the servers off, I get the following XMLHttpRequest:

readyState = 0
responseText = ""
status = 0
statusText = "error"

I'll program to deal with this specific status.
