### ISSUE TITLE
finish adding buttons to database

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#1329]
I'm grouping #670 and #1291.  This might also take care of #696.  

I'm doing this so I can keep adding changes to the same branch without having to keep it up to date with upstream/master.  I plan to write out all additions now, keep each change in separate folders, and add each change to the branch as each pull request is merged.  

This should work well (it's been working with the images) as long as no other changes are made to the button or buttonset tables, the button sql scripts.

**Comment by blackshadowshade** [comment]
Closing this one, because the data in the source SQL file contains all the information about both supported and unsupported buttons.
