### ISSUE TITLE
Prompt for confirmation before leaving a forum page with unsaved changes

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1336]
I just lost a long forum post when I accidentally clicked on the button immediately below my post, which is "Mark thread as read", rather than the button way off on the right, "Post reply". In general if the user tries to do something that will navigate them away from an unfinished forum post, it'd be better to prompt for confirmation than to instantly discard it.

**Comment by blackshadowshade** [comment]
So, I'm going to see if I can address this myself with a simple tweak: namely, to shift the "Mark thread as read" button to be flush right instead of flush left.

**Comment by lukehankins** [comment]
I don't have a "this will fix everything" answer, unfortunately.  The thing that trips me up is that it's the opposite of the gmail layout, where send is on the left and trash is on the right.  

I think having them be different colors/shapes might help.  Or if they were next to each other so that it was a conscious choice?  Or hide the submit button until something was added in the text box?

**Comment by blackshadowshade** [comment]
I've already submitted a pull request to shift the "mark thread as read" button to the right. Once this gets accepted and pushed onto the dev site, I'd love feedback on whether this change is enough.

**Comment by blackshadowshade** [comment]
So, we trialled the shift of the "mark thread as read" button, and this was rejected by irilyth. I want to play around with this a bit more. The first thing I'll try is playing around with button/font sizes, making the "mark thread as read" button smaller.

**Comment by blackshadowshade** [comment]
Also, I could colour this button red. What do you all think?

**Comment by lukehankins** [comment]
How about hiding the "mark thread as read" button when something is entered in the text box?

**Comment by cgolubi1** [comment]
> How about hiding the "mark thread as read" button when something is entered in the text box?

I kind of like this approach.

Hiding might be hard, but i wonder if you could grey it and make it unclickable.  This would mirror what we do with Submit type buttons after they're already clicked, and might be pretty simple.  I'll poke around and see if i can find an example and how complicated it is.

**Comment by blackshadowshade** [comment]
Just thinking aloud here:

So, it seems to me that the obvious thing to do here is test if the field is blank
http://stackoverflow.com/questions/8095822/jquery-if-text-input-does-not-equal-blank

If not, then change the "mark thread as read" to gray and unclickable, much like in Api.js
  my.disableSubmitButton = function(button) {
    if (button) {
      $(button).attr('disabled', 'disabled');
    }
  };

I presume that I would do this on the onChange event for the text field.

Am I missing anything here?

**Comment by irilyth** [comment]
That sounds like it would work for the MTAR problem in particular.

If you could do something on any action that would close the page, that would also catch someone clicking on any *other* link by mistake, or closing the window/tab, or whatever. If that's a lot harder, though, this sounds better than nothing.

This is my BFOTM.

**Comment by blackshadowshade** [comment]
So, there are two other obvious instances where this disabling needs to happen, mentioned by Chaos and Josh:
- when creating a new thread
- when editing an existing post
