### ISSUE TITLE
the 20141002 database backup on prod was truncated

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1339]
Cron job e-mail says:

```
Date: Thu,  2 Oct 2014 00:01:01 +0000 (UTC)
Subject: Cron <root@X> /usr/local/bin/backup_buttonmen_database  

mysqldump: Got errno 28 on write
```

and the file itself is less than 10% of the size it should be, and cuts off in the middle of an entry.

**Comment by cgolubi1** [comment]
Slacking about actually solving this.  Compressed older backups today:
$ sudo find /srv/backup -type f -name '*.sql' -mtime +30 -exec bzip2 {} \;

**Comment by blackshadowshade** [comment]
Just noting that this issue popped up again at the beginning of October 2017, and that it's still an open problem to have an automated solution.

**Comment by cgolubi1** [comment]
We're doing prod backups onto an EFS volume right now.  I no longer think we need to care about this issue.
