### ISSUE TITLE
50 States buttonmen has some bad recipes

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#1351]
I know that at least Maryland is busted.  I think the file was truncated somewhere between copying from an email or pm and copying it to a CD for backup.  But even after changing the . . .  at the end of Maryland to something I think would pass Jenkins it failed.  There's probably more than one recipe with problems.  Heh - I just spotted one: Alabama should have an (S) instead of an S.  But even with my blunders in converting this to the right format, I can't really be sure that Maryland isn't the only button recipe that was found unscathed.  Hopefully someone has a copy of Kaufman's original 50 States buttonmen to check this against.  

Thanks for the help. 
___________

Button Name | Recipe
--- | ---
'Alabama' | 'D(6) ^(10) o(14) S (X)'
'Alaska' | 'd(6) s(20) s(30) w(30) (T)'
'Arizona' | 'k(7) g(9) (12) F(15) (X)'
'Arkansas' | 'p(4) H(9) w(12) h(20) (V)'
'California' | '@(10) @(20) $p(20) $q(12) (Y)? (Z)'
'Colorado' | '(4) (6) z(14) (U)? (U)?'
'Connecticut' | 'H(4) v(11) h(20) (4/20)? (R)'
'Delaware' | '(1) (4) h(6) f(8) (T)'
'Florida' | 'g(6) F(10) p(12) (U) r(4) r(6) hr(12) @whr(20)'
'Georgia(US)' | 'oz(10) (4/20) B(X) B(X) q(X)'
'Hawaii' | 'n(4) m(5) k(8)F(13) d(Y)'
'Idaho' | 'B(4) s(6) (8) (Y) (Y)'
'Illinois' | '(10/20) G(12) (8,8) (R) rsd(4) rsd(6)'
'Indiana' | '(4) (8) (12) z(20) (W)'
'Iowa' | 'n^(6) f(8) D(9) (11) k(T)'
'Kansas' | '(9) c(9) F(9) Gz(9) t(9)'
'Kentucky' | 'z(5) (1/4) (9/8) (20) (R)'
'Louisiana' | 'p(2) @(6) G(12) o(12) (X)'
'Maine' | 'f(4) g(6) s(6) (V) (X)'
'Maryland' | 'g(4) m(8) o(10) (W) (X) +@(8) ...'
'Massachusetts' | 'f(6) k(8) o(10) (X) (Y)'
'Michigan' | '(8) s(9) p(10) (Z)! `(2) `(3) +(6)'
'Minnesota' | 'o(6) o(6) (7,7) s(20) (X)'
'Mississippi' | '@(4) H(6) (8) w(13) (W)'
'Missouri' | 'f(4) (10) v(10) H(8,12) (Z)'
'Montana' | 'B(4) H(8) (12) (S) z(Z)'
'Nebraska' | '(11) h(U) (S) k(R) fB(11)'
'Nevada' | 'H(3) C (21) c(36) %(V)'
'New Hampshire' | 'f(4) os(6) Gh(9) (V) (W)?'
'New Jersey' | 'c(4) B(15) z(18) p(20) s(S)'
'New Mexico' | '^(4) (8) %(10) s(12) (X)?'
'New York' | '(12) p(16) z(30) o(X)? rq(6) r(8)'
'North Carolina' | 'pF(10) o(10) (V)! gt(V) h(V)'
'North Dakota' | '(4,4) (8) s(12) n(12) (W)'
'Ohio' | 'H(6) F(7) p(8) (X)? (X)'
'Oklahoma' | 'f(6) f(10) f(12) f(X)'
'Oregon' | 'z(6) (12) u(R) u(W) u(X)'
'Pennsylvania' | '$f(2) $s(6) %(4) (12) t(20) (Y)?'
'Rhode Island' | '(4) (4) d(6) d(10) (R)'
'South Carolina' | '(6) (9) fB(10) G(12) (X)'
'South Dakota' | '(1) (3) (16) (26) @o(Z)'
'Tennessee' | '@(1/5) %(6) F(8) (5/25) rpm(3,3) rpm(4,5)'
'Texas' | '^(10) (10,10) (30) `(8) r(6) r(8) r(10) r(12)'
'Utah' | '(6) (8) w(12) H(S) (X,X)'
'Virginia' | '(4) oBs(8) Fp(12) (20) (W)'
'Vermont' | '(4) G(6) os(8) g(10) (V)'
'Washington' | 'n(4) z(6) (7) F(13) mso(S)'
'West Virginia' | 'q(Y) w(X) B(Y) o(X) Bowq(Z,Z)?'
'Wisconsin' | 'co(W) co(W) cow(S) cow(S) cow(S)'
'Wyoming' | '(4) z(12) kp(20) n(20) (S)'

**Comment by blackshadowshade** [comment]
Closing this one for the moment. If there are other issues that I've missed, feel free to reopen the issue.

**Comment by TheOrgg** [comment]
I can confirm that $ was being used for Select Dice on the old site.
