### ISSUE TITLE
Black Jack, Pai Gow, and Shamrock each have two recipes

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#1352]
Chaos referenced this in another issue: 
http://web.archive.org/web/20080706172140/http://home.att.net/~kerry_and_ryan/LasVegas.html

This seems to be the original source of the set.  It shows additional recipes for some of the buttons.  Should we find a way to incorporate them? 

Black Jack's second recipe has one difference - instead of (20,1) it has (10,10,1). It would mean adding triplet dice. Would that be much more difficult to implement than twin dice? 

Pai Gow's second recipe has just different die sizes.  Shamrock's replaces a basic die and an option. 

name | current recipe | additional recipe 
--- | --- | ---
Black Jack | (1,1) (11) (8,8) (10,11) (T) | (1,1) (11) (8,8) (10,10,1) (T) 
Pai Gow | (6) :(8) :(8) (10) (12) | (4) :(10) :(10) (12) (12)
Shamrock | (2) (7/13) (7/13) (7/13) (7/13) | (2) (9) (7/13) (7/13) (7/13)

Issue #1291 might be delayed until there's a decision about this issue.

**Comment by blackshadowshade** [comment]
This has been dealt with. Closing this issue.
