### ISSUE TITLE
Temp Fix: allow players to block new games with non-TL buttons in their profile.

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#1359]
In regards to a forum on a live site with wanting to play random games but not be subjected to the often unbalanced non-TL buttons, I'm wondering if this would work: 

Create the back-end code that will either only choose randomly among TL buttons, or dismiss any non-TL buttons that are randomly chosen and try again.  Add a field to the player table allowing them to choose whether or not they want TL-only buttons in random open games.  I think the front end for this could easily be hacked by copying  code from another option box, so this could be finished without the expertise needed to do the job properly.  

This will at least partially fix the problem referenced in #1234 .  It won't make the create game problem any less confusing, but it will allow players some control when joining open games with random button selection.

**Comment by blackshadowshade** [comment]
I'm going to close this feature because we have game rejection implemented, and anything further in this direction should probably look like #1234.
