### ISSUE TITLE
decide how zero-sided dice should be treated for initiative

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1363]
Pull request #1353 has a proposed implementation of Dead Guy in which a die value of 0 beats a die value of 1 in initiative comparisons.  Do we want to treat zero-sided dice this way during initiative comparisons?  Decide.

**Comment by blackshadowshade** [comment]
I'm going to close this for the moment. If someone wants to raise the issue again, they can reopen it.
