### ISSUE TITLE
Add "vacation message" to profile

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1378]
If you're "on vacation" (for any value of "vacation"), i.e. you know you're not going to be playing for a while, it'd be cool if you could indicate by setting a preference that would show up in your profile. Perhaps it could also change your color (or italicize your name, or something) in the overview screen.

**Comment by cgolubi1** [comment]
dwvanstone: this issue touches many different parts of the API flow, but in a simple way:
* Add a new preference to Prefs.js so it can be set
* Add the new preference to the arguments of the `savePlayerInfo` API call and the results of the `loadPlayerInfo` API call
* Modify the BMInterface.php functions which handle `savePlayerInfo` and `loadPlayerInfo`
* Add the new preference to the `player` database table (and create a database update file so the change can be applied on deployment)
* Finally modify Profile.js to display the vacation message to other players if there is one

I don't know if you want to take on a project of that size yet, but i think that, as tasks go which touch the entire flow of data from the UI to the database, this is a very straightforward one, and i think it would be useful to have on the site.  So i'll assign it to you and you can put it in your backlog, or start looking at it now if you're curious.

**Comment by dwvanstone** [comment]
I've been able to change the database, the preferences...so now I'm onto the part where something happens on a page which shows that someone is on vacation.

I think we'll be adding player flags in the future -- battle buddies, "enemies" (i.e., someone that we already have a game against) -- so I don't think we should go with a variety of colors. What do you think of a simple character in brackets after the name? I can easily add a tooltip text which says "On vacation" over the text "[V]":

![screen shot 2016-01-17 at 8 28 18 pm](https://cloud.githubusercontent.com/assets/6751265/12381524/86ae92a8-bd59-11e5-968b-6ca0e108575b.png)

I also think the fact that your opponent is on vacation should appear on the game page (for those who bypass the overview page):

![screen shot 2016-01-17 at 8 35 09 pm](https://cloud.githubusercontent.com/assets/6751265/12381540/d2e81a4a-bd59-11e5-9d1b-e7b6aed5382e.png)

Anywhere else that's important for this bug fix? Where would you want a reminder that you are on vacation, or do you think having other people remind you is enough? Thanks!

**Comment by AdmiralJota** [comment]
I think that a reminder on the vacationer's Overview would be a good idea. I know I'd forget to turn it off when I came back.

Is the "[v]" at the end of the name prominent enough for people to notice?

I remember that at one point we were considering having an extra column (or columns) at the left side of the Overview tables to flag things like tournament games, arena games, mentor games, etc. (#866). I wonder if that would be a good way to flag this, as well. Or maybe that should wait until we actually have more than one thing to show an icon for.

**Comment by dwvanstone** [comment]
What about an icon instead of text?

![screen shot 2016-01-18 at 8 33 49 am](https://cloud.githubusercontent.com/assets/6751265/12392620/480a9212-bdbe-11e5-86a1-00083b29ba6e.png)

If so, is there a proper place to put credits for icons? (Or is that not a worry for the alpha release since we may be redoing all of the images at some point?)

**Comment by AdmiralJota** [comment]
Assuming the icons aren't just created by us, I think that something linked from the footer would be the right place. Like the help doc @blackshadowshade is working on.

**Comment by cgolubi1** [comment]
The icon seems like a fine idea --- the suitcase is cute, i might be tempted to go with an airplane, which feels a little more universally recognizable.

I would vote no on extra columns for now.

**Comment by irilyth** [comment]
I might put the icons before the name, although I'm not sure why I think that. Look at it both ways and see what looks good?

**Comment by cgolubi1** [comment]
> I might put the icons before the name, although I'm not sure why I think that.

It changes the visual flow by moving the column, so it makes it more obvious that something is different.  Yeah, i like that idea --- see how it looks.

**Comment by dwvanstone** [comment]
How does this look? Keep in mind that we may be adding icons to people later (such as battle buddies), so my gut says icons go on the right of the name, but I kind of like it better on the left like this!

![screen shot 2016-01-31 at 1 06 06 pm](https://cloud.githubusercontent.com/assets/6751265/12703866/92807c32-c81b-11e5-90ac-533ae88dd411.png)

**Comment by blackshadowshade** [comment]
I like the look of that. I also like the aeroplane icon a lot.
