### ISSUE TITLE
Acquire button images

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#138]
We need images for all the buttons, so that we can display them in the game.

**Comment by blackshadowshade** [comment]
So, I've managed to start up some player-driven button image acquisition and processing, and I'm optimistic that this might actually bring us loads of images.

I've also asked alwayslurking whether he's willing to write a short wiki for us to say how he processes the scanned images within Gimp.

**Comment by Hurtay** [comment]
I've met (via chat) a player with quite a few physical buttons he'll scan for me. Sadly none of them is a button we haven't got the image of yet. So I'll try to improve the images we've got already. If anyone somehow finds new images I now can get them into the right format with lightreflex/shadow etc.

**Comment by blackshadowshade** [comment]
@Hurtay pointed me to some interesting button art online at BoardGameGeek:
- EuroGames set (using Soldiers recipes): https://boardgamegeek.com/image/337399/button-men
- Ameritrash set (using Soldiers recipes): https://boardgamegeek.com/image/337400/button-men
- BoardGameGeek button: https://boardgamegeek.com/image/1411068/button-men

The buttons themselves don't bring any interesting gameplay, in my opinion, but the art might be interesting for some of you.

**Comment by blackshadowshade** [comment]
I'm going to close this, since I think we've pretty much got all the images that we're going to get. Any further images can be added as we find them.
