### ISSUE TITLE
You cannot win could be stronger

### ISSUE THREAD

**Issue by Caligari** [buttonmen-dev/buttonmen#1385]
Not a huge deal, but I noticed a situation like this:

I had left: 12-sider, 20-sider
Was ahead by 7 points

Opponent had: p20-sider, 1-sider, n2-sider

So, one way or another, I had to take the poison 20-sider, or I had to lose the 12 and 20 sider. Either way I could not possibly win.

When I took the poison 20-sider the game told me I couldn't win, but I contend that if it knew the rules it could realize that there wasn't a way for the game to end with a win to my name at that point.

**Comment by blackshadowshade** [comment]
I think this issue has been dealt with as far as we are going to go (because I think making the win condition stronger is going to be difficult from here on), so closing this issue.
