### ISSUE TITLE
glassonion wants to be able to use buttons with the recipes of Shamrock and Craps from the old site

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1402]
The DHS site had these buttons as part of the Las Vegas set:
```
Craps     (6,6) (6,6) (6,6) (6,6) (6,6)
Shamrock  (2) (7/13) (7/13) (7/13) (7/13)
```

I thought these were modestly interesting mid-level recipes, and i enjoyed playing them.  We don't have them on the new site because they had been originally supposed to be implemented with special powers.

Figure out a way that we can get these recipes on the new site, so we can use them.

**Comment by blackshadowshade** [comment]
This has been dealt with, so I'm closing this issue.
