### ISSUE TITLE
Password recovery / reset

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#141]
It should be possible to automatically recover or reset a forgotten password.

Depends on #140.

**Comment by blackshadowshade** [comment]
Right, I've been thinking about this, and I think we should be able to resolve it quite easily.

1. Add a password reset link on the main page. (possibly in the footer)
2. Ask the player to enter their email address and submit this.
3. When the request is received, check for the username. If this exists, change the user's password to a random password, and email the username and password to the email address.
4. Add a confirmation message on the screen that the password has been reset, and that the user should check their email.

Does that sound reasonable?

**Comment by dwvanstone** [comment]
What happens in step 3? I.e., do you check if any username is associated
with that email address and, if so, send the new randomized password for
that username?

Or does the user need to specify both their username and email address in
order to trigger a reset?

-dvs-

**Comment by blackshadowshade** [comment]
We currently have the restriction of one username per email address, and I'm pretty sure that we'll stick to this in the future.

In my mind, we would simply check for the username associated with a given email address, and send the new password for that username. That gets around the issue that someone might not remember their username. Of course, it also makes it easier for some random person to reset the passwords of loads of random accounts, but I'm not sure how much of a problem this really is.

**Comment by irilyth** [comment]
I feel like what I've seen at other sites is often something like:

- If you've forgotten your password, enter your username, and we'll send a reset link to the e-mail address associated with that password.
- If you've forgotten your username, enter your e-mail address, and we'll send a reset link to that address if there's an account with that address associated with it, or not if you don't. (And either tell you or not, depending on whether we want to be more secure or more helpful.)

In our case, I think it'd be fine to skip the second one, and say "if you've forgotten your username, write to help@buttonweavers.com (or whatever it is) and we'll help". Anyone on that list can help someone find a username pretty easily.

**Comment by blackshadowshade** [comment]
I don't agree that we should require input from a sysadmin in the process of password retrieval. I think that we should build this feature to be a standalone, no-maintenance feature that will simply work right whenever it's needed.

**Comment by irilyth** [comment]
You don't need a sysadmin to help find your username, you just need someone who can log in to the site and look at the list of users.

That said, I think it's fine to make it as self-service as possible. I think that if you're going to let people supply an e-mail address without knowing a username, the main constraints are:

- It should never send mail to an e-mail address that doesn't correspond to an account.
- It should never acknowledge whether the e-mail address is valid, so that people can't fish for valid addresses.

Also, just to double-check: I think it should actually reset the password just because you filled out the form, or send you the password via e-mail; I think it should send you a link that you can use to reset the password. Otherwise, as you say, someone can use this to at least annoy other people, and possibly even break in to their accounts (if they have some way to read their (plaintext) e-mail).

**Comment by cgolubi1** [comment]
I agree that it should be self-service, but i *don't* think we should reset passwords simply on provision of an e-mail address.  I would rather put in a bit more design now to avoid opening ourselves to drive-by password reset attacks.  I agree with irilyth that if you provide an e-mail address it should send a reset *link* to that address.  That way if the person who owns the e-mail address didn't request the reset, they can just ignore it.

**Comment by irilyth** [comment]
JBS> Also, just to double-check: I think it should actually reset the password just because you filled out the form, or send you the password via e-mail

Bah, in case this wasn't obvious, I meant "shouldn't" here.

**Comment by blackshadowshade** [comment]
I am trying to avoid the need for an extra Javascript page to deal with this, which for me is currently in the too hard basket, and rather trying to leverage the infrastructure that we currently have, namely, the ability to send email

In the case that we go with a reset link, I think people are anticipating that this will redirect to a page where the user is forced to reset their password. I *cannot* currently do this, since I'm still struggling to get even minor Javascript changes done on the site. I can anticipate that the link might log the user on directly, but I have no idea how we might restrict this to a single logon.

**Comment by irilyth** [comment]
I don't see an obvious way to do this in a way that's secure, self-service, and doesn't require a new page. Sorry. :^(

**Comment by blackshadowshade** [comment]
What about implementing things as I first suggested, but adding username as an extra requirement. Then, in addition, provide a link to retrieve a username (to email) from an email address?

**Comment by cgolubi1** [comment]
Hmm, yeah, i guess i'm not clear on what things are easier or harder than what other things.  If *any* amount of backend complexity is preferable to creating a new UI page, one thing you could do is generate and e-mail the new password, but keep it as a second temporary password for the account.

That is, the backend logic would be that the temporary password would be valid for some amount of time (e.g. an hour), and while it was valid, you could use either the original password or the temporary password for the login screen and for the "current password" section of the preference change dialogue.

So if you were trying to reset your own password, you could get the temporary password, login with it, and use it to change your password to a new thing you knew.

But if someone tried to reset someone else's password, they'd generate a temporary password and it would get mailed to the person, but it would expire harmlessly after an hour (or whatever), and they would not lose the ability to login with their existing password.

I don't know how you feel about that level of database/backend complexity, but it's what i can think of that gets you what you want without an additional page, and without allowing people to DoS other players by changing their passwords.

**Comment by blackshadowshade** [comment]
That sounds reasonable. I don't know about having the temporary password expire, but having a second possible password shouldn't be difficult.

I can imagine that the temporary password would only be deleted on successful password change, and overwritten on a subsequent password recovery request.

**Comment by cgolubi1** [comment]
Yeah, either way --- it seems untidy to have a credential that (potentially) someone hostile caused to be created for you, stick around forever.  But OTOH the hostile person didn't specify the new credential and doesn't in principle have access to your e-mail, so afaict it's not that bad.

**Comment by blackshadowshade** [comment]
If we decide to do any sort of database clean-up, I can see that running as a MySQL script once a day, deleting users who never actually logged in, and deleting stale temporary passwords.

**Comment by cgolubi1** [comment]
Sure, that seems fine.  I think the primary argument for having them eventually expire is to force people to actually reset the temporary passwords, rather than using them indefinitely, so we can later make the assumption that they are in fact temporary.

**Comment by blackshadowshade** [comment]
Ah, okay. Maybe we display an annoying message then if users login with their temporary password, so that people get sick of seeing it. I'm imagining the blink tag here.  :p

**Comment by cgolubi1** [comment]
Heh.  Sure, let's see what's easy.  :>)

**Comment by irilyth** [comment]
I had gone to bed, but this sounds good to me. Sorry for being pessimistic last night. :^/ 

I agree that expiration would be good, but doesn't have to be there on day one.

**Comment by blackshadowshade** [comment]
So, I'm putting my BotM on this. It's quite possible that I'll be doing a lot of the work on it anyway, but I may also need some help or advice from Chaos as I go, and it's one way of prioritising this.

**Comment by cgolubi1** [comment]
I'm going to grab this and do a bit of work on it, since that seems like the nicest approach to a BFotM that shadowshade tagged.

**Comment by cgolubi1** [comment]
Trying to summarize the discussion from when this issue was initially filed, it seems to me that the most *desirable* UI is:
* The initial login header gives you a second option next to "Create an account", labelled "Forgot password?"
* That takes you to a page which asks you for your username, and gives you an "E-mail password reset link" option
* The password reset link allows you to set a new password without knowing the existing one

Implementationwise, this requires two new pages:
* The "forgot password" page, which is functionally similar to the "create account" page (it gathers some information from you, sanity-checks it, and then assembles and sends an e-mail, in the process recording the pseudorandom hash which it sends you)
* The "reset password" page, which is functionally similar to the "verify account" page (it pulls a hash out of the URL, sees if it matches the database, and lets you do stuff if so)

We were trying to talk around this approach initially on the theory that creating new pages is scary, but it's not actually that scary, and these are simple pages.  So my first volley is going to be to suggest that this is the approach we should take.

**Comment by cgolubi1** [comment]
Shadowshade, any objection to (a) me working on this, or (b) the approach outlined in the previous comment?

**Comment by irilyth** [comment]
Do you want the reset-password link to expire after a certain time if it's not used? It'd presumably expire immediately as soon as it's used. I don't have a strong feeling about it, but think that if "this link will expire in 24 hours" (or whatever) is easy to do, it's probably worth doing.

**Comment by cgolubi1** [comment]
> Do you want the reset-password link to expire after a certain time if it's not used?

Sure, that's easy enough.

**Comment by blackshadowshade** [comment]
I'm happy for you to work on this, but remember that it's going to conflict with #1859, since that reworks the login page too.

**Comment by cgolubi1** [comment]
> I'm happy for you to work on this, but remember that it's going to conflict with #1859, since that reworks the login page too.

Yeah, i know --- i think the changes are compatble in principle.
