### ISSUE TITLE
Unsuccessful trip attack targeting radioactive die is logged incorrectly

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1440]
In #1432, there is a screen capture showing that the action logging is incorrect for an unsuccessful trip attack targeting a radioactive die.

**Comment by blackshadowshade** [comment]
Chaos, when you have the time, it would be useful for me to have a responder test that addresses this issue and #1452 before I attempt to fix the underlying problem. It's quite possible that all that is necessary is to modify an existing test where trip attacks occur.

**Comment by cgolubi1** [comment]
Oh, sure, i'd entirely lost track of this issue.  I'll take a look.

**Comment by cgolubi1** [comment]
As demonstrated by https://github.com/buttonmen-dev/buttonmen/pull/1567#issuecomment-84604254, the fix in that pull does in fact address this issue too.

**Comment by blackshadowshade** [comment]
Good, closing this issue then.
