### ISSUE TITLE
Logging for konstant trip dice performing trip attacks is incorrect

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1452]
Konstant trip dice performing attacks against radioactive dice behave correctly, but the splitting doesn't log correctly.

![capture](https://cloud.githubusercontent.com/assets/2898401/5257475/57a964bc-7a2d-11e4-9480-295430a82f55.PNG)

**Comment by cgolubi1** [comment]
Shadowshade: you asked me to write a responder test demonstrating this awhile ago --- if you search for `#1452` in responderTest.php, you'll see that there's already a test step which is flagged as demonstrating this bug.

**Comment by blackshadowshade** [comment]
Thanks for the heads up. I appreciate it.
