### ISSUE TITLE
Trip Attack failed when it should have succeeded

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1497]
http://www.buttonweavers.com/ui/game.html?game=3233, I saw

> irilyth performed Trip attack using [t(T=2,T=2):3] against [s(6):4]; Attacker t(T=2,T=2) rerolled 3 => 2; Defender s(6) rerolled 4 => 3, was not captured

but the UI actually thinks I rolled a three:

![bm](https://cloud.githubusercontent.com/assets/4923138/5647758/e5d4799e-9656-11e4-8492-89d4b427f3c4.png)

James looked in the DB, and found

    JustPerformedTripAttack__2;JustPerformedUnsuccessfulAttack;Twin__{"sides":[2,2],"values":[2,1]}

and also mentioned that this was the full row for the die:

    | 1004709 |        6 |                 6 |    3233 |       1 | t(T,T) |        2 |     3 |          4 | JustPerformedTripAttack__2;JustPerformedUnsuccessfulAttack;Twin__{"sides":[2,2],"values":[2,1]} |

Could be an issue with how Trip Attacks are resolved for Twin Trip dice.

**Comment by cgolubi1** [comment]
So, in the first attack i tried to reproduce this, a trip attack succeeded where the UI shows it should have failed:
![twin_trip_bug](https://cloud.githubusercontent.com/assets/2898207/5733705/20b5bfbe-9b75-11e4-8ff1-3a2f2b720bc3.png)

Let me write up a quick respondertest case for this and see what i learn.

**Comment by cgolubi1** [comment]
Okay, i have an example for this in https://github.com/cgolubi1/buttonmen/tree/1497_reproduce_bug

It doesn't surprise me very much to find that when the trip attack happens, the die roller is rolling 5 dice where it should be rolling 3.  (2 for the attacking twin die's reroll, 1 for the defender's reroll, and 2 for the attacking twin die after the attack, which changes size again.)  I think that's the crux of the bug, and hopefully the test will help find it.
