### ISSUE TITLE
Our Git Icon should be a Button Man :)

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#1509]
I want a pony!  Can we make our Git icon a Button Man?

**Comment by blackshadowshade** [comment]
That's actually a nice idea. I'll take a look. Any preferences?

**Comment by blackshadowshade** [comment]
What about that?

**Comment by nkmcalli** [comment]
I don't have a preference - I think it should be your choice.  :)

**Comment by blackshadowshade** [comment]
I chose Hammer, which is because that's one of our most useful tools as Buttonweavers.  XD

Github tells me that it may take a while to propagate.

**Comment by nkmcalli** [comment]
Looks gorgeous!  It could change based on mood too.  Maybe be a reflection of the current state of the project.  :)

**Comment by nkmcalli** [comment]
I see it when I click myself, in the section where it shows what orgs I'm a member of, but not yet in the buttonweavers project.  I'm going to close the issue and reopen if it never propagates fully.  And it looks great the one place I see it.  :)

**Comment by nkmcalli** [comment]
It propagated.  It looks awesome!  :)
