### ISSUE TITLE
in a warrior game, i wasn't allowed skill as an option

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1538]
In the previous state of this game, i selected my first five dice:
```
(1):1, (2):1, z(12):1, z(20):10, `(4):4
```

and irilyth's first die `z(15,15):17` and clicked "Beat People UP!", and it told me there was no valid attack.
![post_no_skill_offered](https://cloud.githubusercontent.com/assets/2898207/6341413/176a9680-bb98-11e4-8dc3-fb48833a6574.png)

The pulldown did not offer me Skill as an option, only Power and Speed.

I submitted the attack successfully using python:
```python
d = b.load_game_data(1472)
r = b.submit_turn(1472, 0, 1, {
  'playerIdx_0_dieIdx_0': 'true',
  'playerIdx_0_dieIdx_1': 'true',
  'playerIdx_0_dieIdx_2': 'true',
  'playerIdx_0_dieIdx_3': 'true',
  'playerIdx_0_dieIdx_4': 'true',
  'playerIdx_0_dieIdx_5': 'false',
  'playerIdx_0_dieIdx_6': 'false',
  'playerIdx_0_dieIdx_7': 'false',
  'playerIdx_1_dieIdx_0': 'true',
  'playerIdx_1_dieIdx_1': 'false',
  'playerIdx_1_dieIdx_2': 'false',
  'playerIdx_1_dieIdx_3': 'false',
  'playerIdx_1_dieIdx_4': 'false',
  'playerIdx_1_dieIdx_5': 'false',
}, 'Skill', 1, d.data['timestamp'])
```

and now the game is in the state shown.  So the bug is that the API and/or UI didn't offer "Skill Attack" as a valid option during loadGameData.

**Comment by blackshadowshade** [comment]
The pre-play screen shot was: 
![capture](https://cloud.githubusercontent.com/assets/2898401/6341532/5dcae5ee-bc1f-11e4-8c17-f9b08b9b971d.PNG)

**Comment by cgolubi1** [comment]
I can reproduce this exactly: added that test to responderTest in https://github.com/cgolubi1/buttonmen/tree/1538_reproduce_bug

**Comment by cgolubi1** [comment]
So... i tried that loadGameData under xdebug, and the call chain that gets you to find_attack() is:
```
    1.9911   15746836                                   -> BMGame->getJsonData() /buttonmen/src/engine/BMInterface.php:663
    1.9913   15747712                                     -> BMGame->get_validAttackTypeArray() /buttonmen/src/engine/BMGame.php:2887
    1.9913   15747712                                       -> BMGame->valid_attack_types() /buttonmen/src/engine/BMGame.php:3432
    1.9999   15752540                                         -> BMGame->does_valid_attack_exist() /buttonmen/src/engine/BMGame.php:1983
    2.0007   15752720                                           -> BMAttackSkill->find_attack() /buttonmen/src/engine/BMGame.php:2041
```

The thing is, `valid_attack_types()` is explicitly invoking `does_valid_attack_exist()` as:
```php
        foreach ($attackTypeArray as $attackType) {
            if ($this->does_valid_attack_exist($attackerIdx, $defenderIdx, $attackType, FALSE)) {
                $validAttackTypeArray[$attackType] = $attackType;
            }
        }
```

and that last option, `FALSE`, gets passed all the way along to become the `$includeOptional` argument of `find_attack()`.

That's all fine and well, but how does this *ever* work?  There's explicitly an example in responder test 27 in which the server gives me the options of Skill and Pass.  Enh, i'll leave it to you to sort out.
