### ISSUE TITLE
Stinger warrior dice must contribute full value in a skill attack

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1541]
Apparently, stinger warrior dice must contribute their full value in a skill attack, not only a partial value.

This needs to be fixed, both in the implementation and the description (as well as in the interaction description).

**Comment by irilyth** [comment]
The description already says the right thing: "While they are out of play, they are completely out of play: They aren't part of your starting dice, they don't count for initiative, they can't be attacked, none of their other skills can be used, etc." The "none of their other skills can be used" part applies to Stinger, I think.

**Comment by blackshadowshade** [comment]
I think that we can change one of the later sentences:

"The Warrior adds its *full* value to the Skill Attack."

**Comment by irilyth** [comment]
Sure, I think that's an ok clarification.
