### ISSUE TITLE
Warrior dice should be greyed out for the defender

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1548]
As requested by irilyth and devious, it should be more visually obvious that warrior dice cannot be targeted.

**Comment by blackshadowshade** [comment]
The question for me is how much of this should be implemented in the back end, and how much in the front end.

The back end already supplies a full list of skills to the front end, and it is easy enough to do the logic in either place to identify warrior dice for the defender.

Does anyone have any preferences?

**Comment by cgolubi1** [comment]
I don't really have a lot of preferences.  Right now, the code in Game.js which handles "Dizzy" dice is pretty specific to the dizzy/Focus combination.  So it doesn't strike me as any *less* general to have the UI identify "opponent's warrior" dice.  The backend has to tell the UI which particular focus dice are dizzy, but in the case of opponent's warrior dice, the UI already has all the information it needs.

So i think it would be simplest to do it all in the UI, and what you'd do would be to add analogous code in `Game.gamePlayerDice()` similar to what exists for dizzy/Focus.  (Look for both "Dizzy" and "dizzy" in that function.)  Should be straightforward.

**Comment by irilyth** [comment]
Would it be easy to sort the Warrior dice all to one side (probably the left)? I think that'd be advantageous.

**Comment by blackshadowshade** [comment]
I don't know if it's a good idea, even if it were an easy one. I would find it confusing, I think, if the order of the dice changed each round.

**Comment by cgolubi1** [comment]
> Would it be easy to sort the Warrior dice all to one side (probably the left)? I think that'd be advantageous.

I'm sure it wouldn't be impossible, but it would be new logic that doesn't exist right now, whereas making them grey and unclickable is just like the existing focus case.  IMO we should try that, and if we decide we also want "off to one side", make a separate ticket.

Also, frankly, i know not everything is about us, but i think it would make bug analysis substantially more time-consuming for me if i couldn't make the assumption that the order in which the dice appear in the UI corresponded to the index numbers transmitted to the server.  Obviously, that shouldn't be an overwhelming factor, but nonetheless i'm reluctant to do something that makes debugging more painful given how much time i spend debugging.  :>)

**Comment by irilyth** [comment]
Hmm, ok. I don't think it's a big deal, but it is how the old site worked, and it was pretty nice there. But we might as well try one thing at a time, and it's not worth a whole lot of disruption to change.

**Comment by irilyth** [comment]
What about your own Warrior dice? I think it'd be nice if they were also more clearly out-of-play than just the ` mark, but they surely shouldn't be the same gray as dizzy Focus dice. Maybe a pattern rather than a color, like a striped background or something?
