### ISSUE TITLE
Berserk Attack removes Mood Swing?

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1563]
The description of Berserk says

> Once a Berserk Die performs a Berserk Attack, it is replaced with a non-berserk die with half the number of sides it previously had, rounding up. It also loses any Swing/Mood Swing/Mad Swing characteristics it may have had.

In http://www.buttonweavers.com/ui/game.html?game=4726, I made a Berserk Attack, and this didn't happen:

> irilyth performed Berserk attack using [B(X=20)?:11] against [(6):3,(Y=10)?:8]; Defender (6) was captured; Defender (Y=10)? was captured; Attacker B(X=20)? changed size from 20 to 10 sides, recipe changed from B(X=20)? to (X=10)?, rerolled 11 => 9

And then later, when I attacked with the same die, it did in fact change size.

Should a Berserk Attack remove Mood Swing? I vaguely recall discussing it at one point, so maybe we concluded that it shouldn't; but if so, we should fix the help text. (And if we did not conclude that, then we should fix the bug. :^)

**Comment by blackshadowshade** [comment]
Referencing #1050 here. I'm pretty sure that all I have to do here is change the description of Berserk.

**Comment by irilyth** [comment]
Ah, yes; I'd forgotten the conclusion, but it looks familiar now, and seems fine to me. I think we just forgot to update the description. Thanks!

**Comment by jimmosk** [comment]
Hello, anybody want some lovely worms? I'm just about to open a can of them...

See, I want to argue that Berserk dice *should* lose Mood (and Mad) Swing characteristics upon attacking Berserkly, along with Swing. The Berserk skill, like most, has a balance between its benefits and drawbacks; one of the latter is that after it makes its special attack, it's suddenly less powerful - not only in being unable to make that attack again, but in being weaker. (I'm setting aside for the moment that this might not be a drawback in some cases, i.e. poison)
Except, with a swing die of any flavor, that's no longer true. The weakening that happens upon attacking Berserkly is undone a move later, when it once again can change back to any value it could have had before said attack.  Which I don't think does good things for balance.

**Comment by irilyth** [comment]
I'm not convinced that the shrinking is necessarily about weakness, although it'd be interesting to hear from the designers what they had in mind. Smaller dice are perhaps mostly better for initiative, but they're also good for not giving your opponents a lot of points to capture... And especially if you just took a couple of dice with a large Berserk die, shrinking it down to half size can actually be advantageous in that it prevents your opponent from recovering those points quickly. (They can do it by capturing multiple of your dice, but having more medium-sized targets rather than a few big targets, especially when they're probably now behind on the number of dice they have, is likely to be harder.)

I've always thought of Beserk as being a more balanced version of Speed, where the main drawbacks are that it only fires once, and it can't make Skill Attacks, the latter of which seems like the biggest downside. The half-size thing always just seemed like a weird quirk to me, and I'm really not sure whether it's meant to be an advantage, a disadvantage, or just interesting. :^)

On the other hand... One argument in favor of having it strip off Mood and Turbo is faithfulness to the old site, and its stats. I have not historically been all that big a fan of that argument, but I've become persuaded that it's very important to some people, so.

**Comment by irilyth** [comment]
Also, a B(Z=30)? that splits to 15 is much more likely to get smaller (4 6 8 10 or 12) than larger (20 or 30) anyway, so if you think smaller is weaker, leaving Mood on there is likely to make big Berserk dice weaker. It's 50/50 with a B(X=20)?. A Berserk Mood Swing die that starts smaller is more likely to get bigger, but is also less likely to get a chance to Berserk, and the "no Skill Attacks" drawback is harsher for smaller dice.

Also also, Finngall and jeffboyardy are the only currently-active buttons with Berserk Mood. I don't have as easy a way to find not-yet-available buttons.

**Comment by cgolubi1** [comment]
I like it the way it is, and think we should just update the description.  IMO it's more fun to have a berserk mood swing moodify after it berserks, than not.  (I'm also not 100% sure it didn't work that way on the old site too, though if others are sure it didn't, i'll defer.)
