### ISSUE TITLE
Capturing a die split by radioactive twice seems to be broken

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1574]
See #1569 for details.

**Comment by blackshadowshade** [comment]
I ran the unit test that Chaos provided up (which is just before the game broke), and I didn't spot anything obvious in the database that was wrong.

I'll wait until we have a simple broken responder test before fixing this one.

**Comment by cgolubi1** [comment]
So, i still want to give you a simpler test, but if you want to see the internal error with the test you've got, add this to the end of the function:
```php
        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(4),
            'responder004 performed Skill attack using [Hog(8):1] against [q(1):1]; Attacker Hog(8) rerolled 1 => 4, defender q(1) was captured. ',
            $retval, array(array(0, 0), array(1, 0)),
            $gameId, 1, 'Skill', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');
```

But i definitely owe you an easier-to-use test.

**Comment by blackshadowshade** [comment]
Thanks, Chaos. The bug triggers now, and I can start chasing it down now.  :)

**Comment by blackshadowshade** [comment]
Right, found the bug. It's very simply triggering when a queer die is being set with a value of zero, which then fails the validation in BMSkillQueer->incompatible_attack_types().

**Comment by blackshadowshade** [comment]
If you'd like, I can cover this with a BMSkillQueer-level test, instead of needing to have a responder test.
