### ISSUE TITLE
Time & Space (1,Y=2) die rolled odd but didn't give another turn

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1593]
In http://dev.buttonweavers.com/ui/game.html?game=1599:

    irilyth performed Skill attack using [gn(X=20):10,`^(1,Y=2):3] against [gn(X=4):4]; Defender gn(X=4) was captured; Attacker gn(X=20) rerolled 10 => 19; Attacker `^(1,Y=2) recipe changed from `^(1,Y=2) to ^(1,Y=2), rerolled 3 => 3

But I didn't get another turn. Screenshot:

![bm](https://cloud.githubusercontent.com/assets/4923138/7094745/2a3b801c-df92-11e4-9ff5-e8079d86bbcc.png)

**Comment by cgolubi1** [comment]
I'd be surprised if this were anything other than the effect of twin, and under that assumption, i've reproduced it using LadyJ.  Responder test forthcoming.

**Comment by blackshadowshade** [comment]
I'm pretty sure that this is a missing die hook in BMDieTwin, and should be fixed with a one-liner.

**Comment by cgolubi1** [comment]
Added a simple LadyJ respondertest in https://github.com/cgolubi1/buttonmen/tree/1593_reproduce_bug --- it's probably a good idea to get a TimeAndSpace respondertest in the corpus anyway.
