### ISSUE TITLE
Konstant Maximum Focus reroll effect contradicts log message

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1597]
In http://www.buttonweavers.com/ui/game.html?game=5283 I have a kfM(20), and during initiative, I used Focus to turn it down to show 14. When I attacked with it, the log said

> irilyth performed Skill attack using [k(20):18,kfM(20):14] against [M(4):4]; Defender M(4) was captured; Attacker k(20) does not reroll; Attacker kfM(20) does not reroll

as if Konstant took precedence over Maximum, but the die changed its showing-value to 20, as if Maximum took precedence.

Here's a screenshot:

![bm](https://cloud.githubusercontent.com/assets/4923138/7107027/ea7e0312-e123-11e4-9489-1b065ccc0c4b.png)

**Comment by irilyth** [comment]
Konstant says that the dice don't reroll, and Maximum says they roll their maximum value when they reroll, so I think Konstant should take precedence here, causing the dice not to reroll, and thus preventing Maximum from taking effect.

**Comment by ManvilleFog** [comment]
Why is this combination even allowed?!  Maximum should not be allowed to be turned down.

**Comment by blackshadowshade** [comment]
If you look at the descriptions, both konstant and maximum are tied to 'rolling' a die, and focus does not trigger a 'roll' event, so the skills are not contradictory.

I'll be changing this such that maximum does not trigger if there is konstant on the die.

**Comment by irilyth** [comment]
> I'll be changing this such that maximum does not trigger if there is konstant on the die.

I wonder if it makes sense to do something more generic, since if Konstant dice aren't rolling at all, nothing *else* that happens at roll time should happen, e.g. a Konstant Mood Swing die shouldn't change size, etc. (I don't if a k(X)? die does change size right now or not, I don't think anyone has one and none of the RandomBM types yet have Swing dice. I bet we'll find a bunch of interesting things once they do. :^)
