### ISSUE TITLE
Differentiate your own out-of-play Warrior dice from in-play dice

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1606]
On #1548, I'd said

> What about your own Warrior dice? I think it'd be nice if they were also more clearly out-of-play than just the ` mark, but they surely shouldn't be the same gray as dizzy Focus dice. Maybe a pattern rather than a color, like a striped background or something?

I still think that'd be a good idea; especially dice with _other_ skills, some of which look like a ` mark (e.g. IIconfused T&S die), it's sometimes confusing to have them intermingled and undifferentiated.

**Comment by irilyth** [comment]
I also still like the idea of sorting them so that the Warrior dice are all together (on the right, presumably), but others didn't like it the first time I suggested it, so, enh. I think some sort of pattern would probably be the least complicated.

**Comment by AdmiralJota** [comment]
One option would be to have a light grey icon overlaid on the die background for out-of-play Warrior dice. Something like this should do the trick, I think:

    <div class="die_img" style="background-image: url(images/die/circle/d10active.png)">
        <div style="width: 100%;  height: 100%; background-image: url(http://i.imgur.com/3Div9Io.jpg); background-position: center; background-size: 32px 32px; background-repeat: no-repeat;">
            <span class="die_overlay die_number_player">9</span>
        </div>
    </div>

(But with a real image that wasn't just stolen from a random Google image search with no concern for usage rights.)

Example of the above in action:

![image](https://cloud.githubusercontent.com/assets/5848173/25569694/cc8f3a5a-2de9-11e7-9519-df2bc4b2ab85.png)

**Comment by nkmcalli** [comment]
I need this also.  I just played almost a whole match thinking my warrior die was in play when it wasn't.  It was a rage die, so I avoided attacking with it and I thought my opponent was avoiding capturing it.  When I finally tried to use it in a power attack I couldn't.  If I'd known I'd have played differently.  :(

**Comment by irilyth** [comment]
I love Jota's idea, and think it'd be great to get it in place soon, with more Fanatics showing up, at least some of which have Warrior dice. If I had a BFOTM to use, I'd use it on this. :^ ) If it's not too complicated, any chance it could get done for a November or December release?

**Comment by AdmiralJota** [comment]
And let me guess -- you'd be happy to test this new feature out on transient in the meantime?

**Comment by irilyth** [comment]
Hey, that's a great idea! :^ )

**Comment by nkmcalli** [comment]
I still need this - just yesterday I played another game and mistook out of play for in play.  The ` mark is just not enough to distinguish in play versus out of play.  

What I really want is the same artwork that appears for your opponent's warrior dice.  I *get* that the grey means you can't attack it, so if your die is greyed out you might think you can't use it.  That's *good* - because you can't use it - or at least you can't use it like a normal die.  My problem yesterday was a warrior stinger die - I couldn't figure out why I couldn't use the stinger skill.  The grey will make you think about why your die is grey.

![image](https://user-images.githubusercontent.com/8868032/85792232-04f42b00-b6e8-11ea-8bdb-8c6dae374bcf.png)

**Comment by irilyth** [comment]
I still really like Jota's idea, which has the advantage of being gray, but different from the "die cannot be used" gray.

**Comment by blackshadowshade** [comment]
Right, thanks for the bump, @nkmcalli, I'll see what I can do.

**Comment by nkmcalli** [comment]
THANK YOU!  :)  Also, I'm okay with whatever solution.

**Comment by blackshadowshade** [comment]
Right, step 1: find free clip art.

From http://www.clker.com/clipart-shield-67.html:

![shield-th](https://user-images.githubusercontent.com/2898401/85856043-96ec5880-b7fa-11ea-8fd5-9945a1397743.png)

**Comment by blackshadowshade** [comment]
@nkmcalli, I've got a pull request up, which I believe solves your problem. When we get a dev site up, let me know what you think.  :)

**Comment by nkmcalli** [comment]
There's some feedback that the shield symbol isn't working well on non-circle dice.  *AND* the person that made that comment said "it's odd that the shield symbol goes away, I'd expect it to stay" Which brings us back to square 1: players don't know the difference between a marker that a die is a warrior die, and the fact that the die is already in play (minus warrior).

Here's one more option: you know how after an attack you see your in play dice to one side, and your just-capture dice to the other side (with strikethrough and black color).  What if you separated the dice into 2 groups like that, in play dice to one side, warrior dice to the other side.

**Comment by irilyth** [comment]
I think DVS's comment was that the shield symbol shouldn't go away when it's *not your turn*. I assume we'd want it to go away after the die came into play! @dwvanstone, can you clarify?

**Comment by dwvanstone** [comment]
I was unclear. I changed the comment to: "Also, after I do an attack, the shields disappear from the warrior dice that I didn't use. I'd expect the shield to stay on the warrior dice I haven't used even if it's not my turn." 

I expect the shields to be there whether it was my turn or not. I like that the shields go away after I bring them into play.

**Comment by nkmcalli** [comment]
Thanks for clarifying!  Can the shields be made smaller to fit on non-round dice better?

**Comment by blackshadowshade** [comment]
The issue I had was making the shield work with two-digit values.

For those who are proficient with the debugging tools, you can play with the size of the shields by changing the background-size (currently 30px 35px) for .clickable_warrior. See what you think.

**Comment by blackshadowshade** [comment]
So, I've been thinking about this a little, and I also think that the shields may not work because of the different die backgrounds.

Any suggestions on what might work better? Horizontal or diagonal stripes or another pattern?

**Comment by irilyth** [comment]
Diagonal gray stripes sound good to me! Maybe three stripes total, gray white gray white gray?

**Comment by blackshadowshade** [comment]
What do you think about these then?

![bm_diagonal_circle](https://user-images.githubusercontent.com/2898401/86525265-61b1cb80-bec8-11ea-815e-f04829243876.png)

![bm_diagonal_symmetric](https://user-images.githubusercontent.com/2898401/86525268-65dde900-bec8-11ea-9874-1c088a63e8f3.png)

![bm_diagonal_realistic](https://user-images.githubusercontent.com/2898401/86525270-68d8d980-bec8-11ea-87fe-151898058bb1.png)

**Comment by dwvanstone** [comment]
I love those! That's easy to identify!

**Comment by irilyth** [comment]
Is the stripe the same color as the player mat, or a fixed color that just happens to be close in this case?

I still think gray might be better, but don't feel strongly about it.

**Comment by blackshadowshade** [comment]
The stripe is actually just a transparency mask. I couldn't work out how to get another colour showing. If anyone has any ideas about this (as in, concrete CSS or HTML tricks), I'm happy to try them out.

**Comment by dwvanstone** [comment]
I actually love that it's a transparency mask. That way it's not yet another configurable color.

**Comment by irilyth** [comment]
Yeah, the only drawback of that is that if the player's mat color is dark, the text (the value of the die) may be hard to see. :^( Would it be possible to do the mask the other way, so that the edges of the die were colored, and the middle (where the number is) wasn't?

(I guess it wouldn't be any harder than the other text on the mat, so maybe this isn't a big deal.)

**Comment by blackshadowshade** [comment]
Sure, it would be easy to reverse the colouring. Anyone else want this?

**Comment by blackshadowshade** [comment]
(If you want to play around with it yourself, it's just a matter of changing the CSS in Developer view on Firefox or Chrome).

**Comment by nkmcalli** [comment]
Yeah, the stripe is great.  Agree that for dark mat colors it should be reversed.

**Comment by blackshadowshade** [comment]
Okay, here are images of the reversed stripe colouring:

![bm_diagonal_circle_reversed](https://user-images.githubusercontent.com/2898401/86676303-d0fcfc00-c03d-11ea-88bf-a54379503e2e.png)

![bm_diagonal_symmetric_reversed](https://user-images.githubusercontent.com/2898401/86676325-d5c1b000-c03d-11ea-9a67-f9e0af2e6e3d.png)

![bm_diagonal_realistic_reversed](https://user-images.githubusercontent.com/2898401/86676341-d8bca080-c03d-11ea-993d-18441cf1a521.png)


Personally, I actually think the first suggestion works better than this white stripe, but I don't feel strongly about it.

**Comment by blackshadowshade** [comment]
Let me qualify my comment by saying that I'm mostly disturbed by the appearance of the symmetric 10 and 12, which have the visual illusion happening there implying that the stripe isn't fixed width.

**Comment by irilyth** [comment]
One thing I like about the white stripe is that it looks less like the do-not-enter 🚫 symbol, which to my eye makes it look more like "you can't do anything with this". The white stripe has less of that intuition for me.

Do you think the visual illusion thing is stronger with the white stripe or the colored one? I think it's stronger with the white one but I'm not 100% sure. I didn't notice it with either until you pointed it out, but when I look for it, I do see it.

I'd definitely like to play with both of them on the site, with different mat colors, once the site's updated.

Thanks for working on this!

**Comment by irilyth** [comment]
One other probably-very-dumb question: It's not possible, I take it, to have a shield image that auto-sizes to be the same size as the number inside the die image? It could even be the mat color, rather than gray, if people like that better. :^)

**Comment by blackshadowshade** [comment]
The issue is getting a shield symbol that entirely contains the number and also fits within the symmetric 4 shape.

**Comment by irilyth** [comment]
Hm, I remember that from https://github.com/buttonmen-dev/buttonmen/pull/2573 . I tried changing it to 20px x 25 px, and it looked pretty ok to me?

**Comment by blackshadowshade** [comment]
These are the 20 x 25 px shields:

![bm_shield_20_25](https://user-images.githubusercontent.com/2898401/86691071-d8c39d00-c04b-11ea-8573-6de2e0e45b00.png)

I think they're too small to actually make out when there are double-digit values.

**Comment by irilyth** [comment]
Yeah, I feel like they're not necessarily a clear image of a shield behind the double-digit values, but it seems clear that there's *something* there. :^)

I'm relatively indifferent to shield vs stripes at this point. I'd like to play with the stripes once the dev site is updated, but if others have strong preferences either way, they all seem mostly fine to me.

**Comment by irilyth** [comment]
The dev site's been updated -- what's the trick to reversing which parts of the stripe are transparent?

**Comment by blackshadowshade** [comment]
Okay, here's how you do the change:

Currently, if you go into inspector, you'll see that the CSS for the stripe is in .die_img.clickable_warrior {...}. One of the options here (either webkit-mask-image or mask-image) will be enabled, depending on browser.

![screenshot_change_css](https://user-images.githubusercontent.com/2898401/87099419-04819580-c28d-11ea-9c2f-6b748dbf0556.png)

The content needs to change to

     -webkit-mask-image: linear-gradient(
       -45deg,
       rgba(0, 0, 0, 0.5),
       rgba(0, 0, 0, 0.5) 39%,
       black 39%,
       black 61%,
       rgba(0, 0, 0, 0.5) 61%
    )

**Comment by dwvanstone** [comment]
I'd suggest we try it as is (with the stripe going through the text) and throw it up on a dev site so we can fiddle with it. 

I'd be curious what happens if the player mat is black, for instance, to see if the number becomes unreadable. However, the same problem might happen if it's a white diagonal stripe - some of the numbers might be obscured. It may also depend on font size in the browser.

**Comment by blackshadowshade** [comment]
@dwvanstone, it's currently up on blip.dev for testing. Take a look.  :)

**Comment by dwvanstone** [comment]
Okay. I'm looking at blip.dev.

Unfortunately, I have to think hard to figure out what's going on and why some dice have stripes through them. It looks like they're crossed out so I shouldn't be able to click on them. I don't think having a white stripe will change my feeling about this.

<img width="1097" alt="Screen Shot 2020-07-12 at 3 20 07 PM" src="https://user-images.githubusercontent.com/6751265/87254791-33496880-c453-11ea-9c1f-b5e420eb16f2.png">

I tried out a bunch of variations in a graphic program and nothing really works. 

The question is whether this makes it more confusing or less confusing.


Here's a simple suggestion. What if you grey out the buttons on the attacking side? They still can be clicked (and a red square will go around it). That also matches the grey box in the opponent's warrior die.

<img width="1091" alt="SAMPLE" src="https://user-images.githubusercontent.com/6751265/87255444-c2a54a80-c458-11ea-9abc-fb612ed289a6.png">

**Comment by blackshadowshade** [comment]
What would you think about half white (e.g., top left half), half gray?

**Comment by irilyth** [comment]
DVS, what do you think about the smaller shield icons? (https://github.com/buttonmen-dev/buttonmen/issues/1606#issuecomment-654558270)

**Comment by dwvanstone** [comment]
> What would you think about half white (e.g., top left half), half gray?
> DVS, what do you think about the smaller shield icons? 

In both cases, we're introducing a new UI element which, in my opinion, takes more time to visually parse.

In my lower example (three comments above) I've simply greyed out the dice which are not-yet-in-play Warrior dice on the current player's side. It is consistent across the player and the opponent's side and not adding a new visual element. I think this is a strong option. (So greyed-out buttons means they are out of play and do not count for scoring at the end. I'm not worried players will think they are not clickable, since clicking on them will teach that UI element quickly.)

**Comment by AdmiralJota** [comment]
If I were new to the game, I would definitely think that greyed out dice weren't clickable, since that's what greyed out UI elements usually indicate. I might click on them anyway, since I'm the kind of person who intentionally tries to do things that the UI doesn't want me to do, but not everyone is like that. And I'd be confused if it worked and would probably think it was a bug.

**Comment by blackshadowshade** [comment]
I wonder if putting a small shield in the corner, *outside* of the die image would work, or if that would be confusing.

**Comment by irilyth** [comment]
The thing I like about the half-gray options (whether a shield or a stripe or whatever) is that they seem to me to capture the idea that the dice are in this unusual state where they aren't usable by themselves, but are usable in conjunction with other things.

One advantage of a new UI element is that it prompts the user to say "huh, what's that" and figure it out, rather than "oh, that's grayed out (or whatever), I bet I know what that means" and be wrong.

If one concern about the stripe is that it looks too much like the do-not-enter sign, what if it were straight vertical or horizontal?

If one concern about the small gray shields is that they're too small to notice, what if they were a transparency, showing the color of the mat?

(I'm no longer concerned that the color of the mat might obscure the number showing on the die; if the mat color is so dark that you can't read black text on it, you already can't read much of anything.)

**Comment by dwvanstone** [comment]
Okay - it makes sense that grey means "disabled", particularly since it's used in the dizzy focus dice. Never mind that idea. 

There already is a visual clue that your own out-of-play Warrior dice differs from your in-play dice -- there is no backtick next to the die description.  What if there were a backtick next to the number on the die?   `8 
  
If we do decide do have a new graphical interface (vertical sign, gray shield), can it also be on the opponent's out-of-play Warrior die? 

I like that the gray shield represents a "Warrior" in a way, but then why don't we have a special graphic for a speed die or a Berserk die. I think what we're more representing is that these buttons are "out of play" rather than that they are warriors.

One way to represent that they are out of play is to move them to their own physically separated section. Maybe they are lower than the other dice by 20 pixels. Maybe they are veiled in some way. 

> I wonder if putting a small shield in the corner, outside of the die image would work, or if that would be confusing.

Maybe in the upper left, so it looks like like a large back-tick mark? 

Sorry I don't have any great answers, but this is a really tricky problem.

**Comment by irilyth** [comment]
> I like that the gray shield represents a "Warrior" in a way, but then why don't we have a special graphic for a speed die or a Berserk die. I think what we're more representing is that these buttons are "out of play" rather than that they are warriors.

Well, I think we're trying to represent that they're out of play but could be brought into play. As it turns out, Warrior is the only skill that works that way, but sure, there could be other skills in the future like that, so I suppose it doesn't have to be a shield. The general idea of having the die image be half gray (or mat-colored) and half white seems promising to me, whether it's a shield or a backtick character or a stripe (diagonal or otherwise) or a pattern of dots or whatever.

I suppose another possible approach would be to make them *entirely* mat-colored, which would be different from anything else. I think "half gray, half white" is a more intuitive way to say "not entirely in play, but not entirely out of play either".

**Comment by dwvanstone** [comment]
>  I think "half gray, half white" is a more intuitive way to say "not entirely in play, but not entirely out of play either".

But we should leave gray to mean that you can't click on it, i.e., disabled in some way.

> I suppose another possible approach would be to make them entirely mat-colored, which would be different from anything else

Actually, I like that idea a lot. Here's how it would look:

<img width="1091" alt="sample2" src="https://user-images.githubusercontent.com/6751265/87345301-e088b300-c51d-11ea-9294-0fa80db45bdc.png">

That's my favorite suggestion by far. It's not using any new elements and it's not using grey.

**Comment by irilyth** [comment]
I think it would look a little better with a stripe or a picture of some kind, but I think this looks all right too.

**Comment by dwvanstone** [comment]
What about underlines on the dice that are not yet in play, just as a quick visual clue that they are set aside/different in some way?

<img width="1091" alt="sample3" src="https://user-images.githubusercontent.com/6751265/87418660-0c4c7d00-c5a0-11ea-9bba-d7fb88e08159.png">

**Comment by dwvanstone** [comment]
Maybe the background rectangle behind the button can be grey? We don't want to make the button itself grey (since that indicates the UI notion of unclickable), but maybe grey can be used to indicate it currently doesn't count for scoring?

<img width="1091" alt="BMEN" src="https://user-images.githubusercontent.com/6751265/91300956-20c08f80-e772-11ea-9e6f-b50556d8c8bf.png">

**Comment by blackshadowshade** [comment]
I think I'll go with implementing top half gray, bottom half white.

My thinking goes like this: I'm imagining soldiers in trenches, ducking for cover. They can't attack until they stick their heads out and make themselves at least partially visible.

**Comment by blackshadowshade** [comment]
So, what do you all think about this?

![warrior_horizontal_fade](https://user-images.githubusercontent.com/2898401/91560942-08bd5b80-e97e-11ea-8052-7f0417fa7aaf.png)

**Comment by dwvanstone** [comment]
Heart. This captures a little bit of everything while still being a softer (less visually intrusive). Well done!

**Comment by blackshadowshade** [comment]
If others like this too, @cgolubi1 can just update the site, the code for it is already on the pull request.
