### ISSUE TITLE
assertion failure on dev site

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1631]
Uh oh: apache logs say:

```
[Mon Jun 01 21:13:05 2015] [error] [client X.X.X.X] PHP Warning: assert(): Assertion failed in /var/www/engine/BMGame.php on line 666, referer: http://dev.buttonweavers.com/ui/game.html?game=1664
[Mon Jun 01 21:13:05 2015] [error] [client X.X.X.X] PHP Fatal error: Call to undefined method BMDie::set_optionValue() in /var/www/engine/BMGame.php on line 667, referer: http://dev.buttonweavers.com/ui/game.html?game=1664
```

This happened several times over a period of a few minutes, all with the same details and game number.

**Comment by cgolubi1** [comment]
Hah, okay, without even knowing what the issue is, i'm entertained, because the game in question involves bobby 5150, source of so many exciting broken games on the DHS site.

**Comment by cgolubi1** [comment]
So i wonder if reserve option dice are broken.  Since bobby 5150 is the only button who has one, that would explain why we haven't seen this before (and that would make it not a prod blocker).

**Comment by cgolubi1** [comment]
Yeah, i'm reasonably sure this is what's going on.  This is going to be kind of a bear to write a responder test for, but the mechanism seems to be:
* bobby 5150 loses a round, and adds the r(1/30) as his reserve die
* bobby 5150 gets to the point where he's about to make an attack which would lead to him winning a round.
* submitTurn on that attack yields an internal error

![bobby_5150_submitturn_internal_error](https://cloud.githubusercontent.com/assets/2898207/7926775/11054b6e-08a5-11e5-868d-7083bea02055.png)

**Comment by cgolubi1** [comment]
Here ya go --- not the most concise test (i let RandomAI do most of the work), but it'll get the job done --- see test 34 in https://github.com/cgolubi1/buttonmen/blob/1631_reproduce_bug/test/src/api/responderTest.php

**Comment by blackshadowshade** [comment]
Okay, I know what the problem is. The issue here is that the addition of the reserve dice at beginning of round changes the effective dieIdx of the (1/30) option die, meaning that the code that maintains the option die values across rounds tries to assign the option values to the new reserve die. This hasn't been an issue before because there haven't been any option dice to the right hand side of a reserve die.

I'm thinking that this should be reasonably easy to fix.
