### ISSUE TITLE
Berserk Mood Swing die not halving after Berserk attack

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1634]
In http://dev.buttonweavers.com/ui/game.html?game=1686 I just did a Berserk attack and this was the result:

jimmosk performed Berserk attack using [B(X=4)?:3] against [^(3):3]; Defender ^(3) was captured; Attacker B(X=4)? remained the same size, recipe changed from B(X=4)? to (X=4)?, rerolled 3 => 2

When losing its Berserk skill (which it did), shouldn't it be replaced by a die half its size (in this case, 2)?  Even if it mood swings back to 4 sides, which may have been what happened in this case, the wording "remained the same size" implies the halving didn't happen. Is that true (and shouldn't it have), or did it happen (but the wording should mention it)?

**Comment by blackshadowshade** [comment]
Duplicate of #1620.
