### ISSUE TITLE
Make Mad Swing '&' position in recipe consistent

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1643]
In #1641, the responder test shows that the Mad Swing '&' acts exactly like the Mood Swing '?', in that it comes after the brackets. However, in the database, the recipes are stored with the '&' before the brackets.

Determine which of these is preferred, and then go with that.

**Comment by blackshadowshade** [comment]
So, does anyone have any preferences on this? I'd be marginally inclined to follow Mood Swing and go for the post-fix position, but I don't feel strongly on this.

**Comment by cgolubi1** [comment]
Agree, also don't feel strongly.

**Comment by irilyth** [comment]
I don't feel strongly either, but am used to after, so I I vote for that.
