### ISSUE TITLE
Boom vs Radioactive

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1645]
In http://dev.buttonweavers.com/ui/game.html?game=1712, I did

> irilyth performed Boom attack using [b(4):4] against [%Ho(1,8):6]; Defender %Ho(1,8) recipe changed to %Ho(2,10), rerolled 6 => 3, was not captured; Attacker b(4) showing 4 split into: b(2) showing 1, and b(2) showing 1

That seems pretty correct, as both halves of my Boom die vanished, but only one of them is showing up on the out-of-play line; probably both should.

**Comment by irilyth** [comment]
Also, the log doesn't include the "Attacker b([size]) does not reroll, was taken out of play" text for either die; it probably should for both.

**Comment by irilyth** [comment]
Actually, I think they're *not* leaving play correctly. I thought at a glance that I had one fewer die, but then I noticed that they were both there after all.

I'll open another game with blackshadowshade so he can see for himself.

**Comment by irilyth** [comment]
http://dev.buttonweavers.com/ui/game.html?game=1714

This is definitely wrong. :^) As I said there (now with typos corrected):

"Before, I have [(4) b(4) (10) b(12) (Y=1)%].

> Attacker b(4) showing 2 split into: b(2) showing 2, and b(2) showing 1

After, I have [b(2) b(2) (10) b(12) (Y=1)&]. My (4) seems to have vanished!" And my b(4) didn't actually leave play, it split into 2 x b(2) and remained in play.

**Comment by blackshadowshade** [comment]
My thought here is that the easy solution is to have the boom die NOT split before leaving play. Does this sound reasonable?

**Comment by blackshadowshade** [comment]
Okay, after discussing this a bit with irilyth, I'll go with the idea that the boom die leaves play *before* any other effects can occur to the die. That would include morphing, doppelganger, radioactive, etc.
