### ISSUE TITLE
Chance mighty/weak die size change logging

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1668]
A chance mighty/weak die changes size on chance reroll, but this isn't currently logged.

**Comment by cgolubi1** [comment]
What's the bug: the size change, or the missing logging?  Also, does this affect other size-changing skills like Mood?

**Comment by blackshadowshade** [comment]
The bug is a logging bug only. I imagine that it probably does occur also with Mood/Mad too.

**Comment by jbscare** [comment]
Is this a duplicate of #1626?

**Comment by blackshadowshade** [comment]
Good catch, yes it's a duplicate.
