### ISSUE TITLE
Konstant Weak die shrinks when used

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1679]
In http://www.buttonweavers.com/ui/game.html?game=6922, I got this result:

> irilyth performed Skill attack using [k(8):8,hk(8):6] against [nq(4):2]; Defender nq(4) was captured; Attacker k(8) does not reroll; Attacker hk(8) changed size from 8 to 6 sides, recipe changed from hk(8) to hk(6), does not reroll

Konstant says "These dice do not reroll after an attack"; Weak says "When a weak die rerolls for any reason". I think the hk(8) should not have rerolled (as the log says it didn't), and thus also should not have changed size.

(When I used it again, I got

> irilyth performed Skill attack using [k(8):8,(8):7,hk(6):5] against [M(10):10]; Defender M(10) was captured; Attacker k(8) does not reroll; Attacker (8) rerolled 7 => 4; Attacker hk(6) changed size from 6 to 4 sides, recipe changed from hk(6) to hk(4), does not reroll

and it was changed to show 4 -- I was guessing it might turn into hk(4):5. Not relevant to the bug, but I was curious.)

**Comment by blackshadowshade** [comment]
Just checking: is this also true for a mood/mad swing die with konstant?

**Comment by irilyth** [comment]
I didn't see it with Mood/Mad Swing, and I agree that #1601 looks like it should have fixed them.
