### ISSUE TITLE
Using space bar to select dice also scrolls page

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1683]
I often do things like this:

* Click on a die. That die is now selected (outlined in red).
* Hit tab. The next die to the right is now outlined in a thin dotted blue line.
* Hit the space bar.

Previously, that last step would select the outlined die (changing it to being outlined in red), which was great. As of a recent Firefox update (I think from 39.x to 40.0), that last step now selects the die and *also* scrolls the page, typically taking the entire battlemat area of the page out of view.

This doesn't happen when navigating with the keyboard among HTML forms, e.g. if I go to http://www.buttonweavers.com/ui/prefs.html, click in the "Real name" text box, hit tab (now the checkbox by "Make email address public" is selected, and hit the space bar, the checkbox is toggled and the page doesn't scroll.

Issue #180 originally introduced the keyboard navigation stuff, FWIW.

**Comment by blackshadowshade** [comment]
The easiest solution, as far as I can see, is to enable another key or multiple keys that can do the same job as the space bar in this situation. What do you think about this solution?

**Comment by irilyth** [comment]
Hmm, that seems non-ideal -- the space bar is nice because it mimics exactly how forms behave.

Huh, in other news, this seems to be happening with Chrome too, and not just Firefox; I had assumed it was some sort of a Firefox change. I'm not sure if that sheds any light on anything...

**Comment by blackshadowshade** [comment]
Does anyone have any idea how to deal with this correctly? I've seen something about deleting the default behaviour for the space keydown action.

Input especially appreciated from all you JS experts out there.  :)

**Comment by blackshadowshade** [comment]
I'm wondering whether it would help to update our version of JQuery. That would be a possible easy fix, and probably also easy enough to test.

**Comment by blackshadowshade** [comment]
I've just tried this, and it doesn't fix the problem.
