### ISSUE TITLE
make forum topic visible from the bottom of the page

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1684]
This is just a thought, and i'm open to ideas --- when you get taken to the end of a long thread by clicking the "New Post" link, you go to the end of the thread, and thus it may not be obvious what the thread is.  That seems non-ideal.

What if we repeated the thread topic banner at the bottom of the post?  Alternately, maybe we could put the thread topic in the page title?

**Comment by irilyth** [comment]
Another idea along these lines: For long threads, it'd be nice if there was a "go to top of page" type link at the bottom of the page. It's easy to hit the "Home" key (or whatever) on desktop browsers, but mobile browsers (as far as I know) don't have an easier option than going scroll scroll scroll scroll scroll.

(I can make a separate ticket for that if it's insufficiently related to this one.)

**Comment by cgolubi1** [comment]
> (I can make a separate ticket for that if it's insufficiently related to this one.)

Yeah, i think that's probably a good idea, but is different from this and the implementation is likely to need a different piece of web-design knowhow.  So let's keep them separate.

**Comment by cgolubi1** [comment]
dwvanstone: this one is a little more involved, but i think not too much, especially if you take the tack of putting the forum topic in the page header (which i think would be perfectly reasonable).  There's other code which sets the page header, so it should be easy to borrow.

**Comment by dwvanstone** [comment]
The forum topic in the page title would be the easiest solution. Have you folks played around the CSS tricks on freezing the header? (I'm not convinced this is a portable solution across platforms but I might look into that, but I won't bother if it's already been tried and discarded.)

**Comment by cgolubi1** [comment]
No, we haven't.  James recently changed the div structure of the page (see #1666) to make it so that we can have a footer that doesn't move.  He has a first attempt at such a footer out for review in #1702 (it's been out for review for awhile, but got backburnered behind the fire overshooting push last month, and the reject-game push this month --- i haven't looked at it at all, so i don't know whether it works).  If it does, it might be possible to use a similar trick to make a non-moving header in the forum, and it certainly seems like we're going in the direction of at least exploring parts of the page that don't move, so if you want to look at it here, go for it.

You could also go ahead and do the page title solution now and look into more things down the line, whatever you prefer.

**Comment by dwvanstone** [comment]
Here's a small question. I'm trying to get the forum title into the page title for this bug. I noticed that multiple spaces in a forum title get merged into one space. I.e., if I create a new forum topic: "A       B" it becomes "A B" on the website. Would it be okay if I put the spaces back in? Is it intentional to strip out spaces between words?

**Comment by cgolubi1** [comment]
Hmm.  You didn't say why you want to put the spaces back in.

I would err on the side of not doing that, because i think compression of whitespace between words is what users expect on webpages (and is less brittle than introducing a bunch of `&nbsp;`).  So if your argument is that inserting visible spaces is what web users expect to have happen, i think i disagree.

Or is inserting the visible spaces advantageous for some other reason?

**Comment by dwvanstone** [comment]
It's not particularly advantageous -- I'm trying to get the forum title to match between the rendered HTML and the page title. They're slightly different in how they're being rendering. So that made me test a lot of cases and I found myself surprised by this difference. I'm happy to keep it as is.
