### ISSUE TITLE
Auto-pass doesn't work with the first round of dead guy playing

### ISSUE THREAD

**Issue by ericeslinger** [buttonmen-dev/buttonmen#1690]
First of all, dead guy shows up in random-button lists which is in itself kind of a bummer. 

But also, in game http://www.buttonweavers.com/ui/game.html?game=7093 my opponent had head guy and had to go first each time and manually pass his turn before the automatic pass logic kicked in. Not sure if this is always the case with very low rolls grabbing initiative against someone who rolls all their dice out of range or not.

**Comment by irilyth** [comment]
#990 is somewhat related to this, and has some discussion about why it might be a good thing to have it work this way.

**Comment by cgolubi1** [comment]
On Wed, 26 Aug, 2015 at 16:38:42 -0700, Eric Eslinger wrote:

> First of all, dead guy shows up in random-button lists which is in itself kind of a bummer. 

Try Dead Guy vs Envy sometime...

**Comment by irilyth** [comment]
In case it's not clear, it's not just Dead Guy, it's any situation in which a button wins initiative but can't attack.

The general problem of Dead Guy showing up in "random button" games will probably get taken care of by some combination of #1211, #1234, and #205, the various things designed to let you limit who shows up in a "random buttons" game.
