### ISSUE TITLE
Make "Skills in this game" section more user-friendly

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1697]
There are two main points here, suggested by @irilyth and @nkmcalli, amongst others:

- Button skills should be visually separated from Die skills
- Die skills should show their single character abbreviation

**Comment by nkmcalli** [comment]
Love your idea of having the letter with the skill in the skill list like: Mighty(H)(info) Speed(z)(info)

**Comment by irilyth** [comment]
Is there another ticket somewhere suggesting that they should pop up the help hovertext if you click on them as well as hover on them? I like that because "hovering" isn't really a thing if all you've got is a touchscreen.

**Comment by blackshadowshade** [comment]
No, there isn't, but we can certainly add this to this issue.  :)

**Comment by irilyth** [comment]
I also really think we shouldn't call button special abilities "skills". If the internal stuff in the code does that, I don't think it needs to be changed, but on the UI side, I think it's confusing to have "button skills" and die skills". Especially when we've got "button special abilities" as a perfectly serviceable phrase. :^)

**Comment by blackshadowshade** [comment]
Except that sometimes, they're disabilities.  ;)

**Comment by irilyth** [comment]
"Differently abled". :^)

(We don't call Slow an "unskill", so I think it's fine to call the TFS button special and "ability".)

(I think it'd also be be fine to call them "button specials", if no one objects to nounifying "special". I don't like it as much, but don't hate it.)

**Comment by blackshadowshade** [comment]
http://www.prowebdesign.ro/how-to-deal-with-hover-on-touch-screen-devices/

This seems to imply that a double-click on the hover area should bring up the info on an iPhone. Can anyone confirm or deny this?

**Comment by irilyth** [comment]
In Chrome (45.0.2454.84) on Android (4.4.4), double-tapping zooms.

**Comment by blackshadowshade** [comment]
According to http://designshack.net/articles/css/are-hover-events-extinct/, iOS triggers the hover event on the first click, and require a second click to trigger the tap event.

Thus, it looks like the hints should work on iOS.

**Comment by blackshadowshade** [comment]
Perhaps something like this might work for Android:
http://stackoverflow.com/questions/11272621/android-button-hover-event

**Comment by blackshadowshade** [comment]
And here are JQuery solutions:
http://www.hnldesign.nl/work/code/mouseover-hover-on-touch-devices-using-jquery/
http://stackoverflow.com/questions/20818863/handling-hover-events-on-a-touch-screen

**Comment by blackshadowshade** [comment]
And this looks like it might be the simplest solution:

http://stackoverflow.com/questions/2851663/how-do-i-simulate-a-hover-with-a-touch-in-touch-enabled-browsers

**Comment by blackshadowshade** [comment]
I've had feedback that the tooltip font is too small. I think that this is because the player normally has their monitor font very large, and that the tooltip font doesn't scale up with the monitor font.

Also, the player has mentioned that the tooltip text disappears too quickly. I think that this will be resolved when the skill text is actually clickable to bring up the help text.

**Comment by danlangford** [comment]
along the same lines it take too long for the system default hover title to
pop up. making the skill clickable will solve that

also add that my die just has a "^" next to it i need to hover every single
skill down the line and hunt for the skill that shows "^" in the
description. when we make them clickable i would suggest also having the
abbreviation exist next to the title. maybe something along the lines of:

(f)ocus (s)hadow Speed(z) Stealth(d) TimeAndSpace(^)
or
Focus(f) Shadow(s) Speed(z) Stealth(d) TimeAndSpace(^)

**Comment by blackshadowshade** [comment]
Ah, interesting, another new player who hasn't noticed that you can hover over the die in question to get a full description of that die, with the skills spelt out in full.

Definitely something to add to the help once we get those files linked from the footer.

**Comment by danlangford** [comment]
Fwiw I mostly play on my phone where hovering isn't even a possibility.

**Comment by blackshadowshade** [comment]
Ha, after spending *hours* on this, I've finally found a solution online that works and looks okay:

http://jsfiddle.net/YS7ft/269/

It uses the JQuery UI tooltip widget.


-----

<!DOCTYPE html>
<body>

<div>
Skills in this game:
<span class="skill_desc" title="Fire (F): Fire Dice cannot make Power Attacks.">Fire</span>
</div>

</body>




$( ".skill_desc" )
  .tooltip({
    content: $( ".skill_desc" ).attr( "title" ),
    items: 'span'
    })
  .on( "click", function(){
      $( this ).tooltip( "open" );
      return false;
    })
  .attr( "title", "" );

**Comment by blackshadowshade** [comment]
Jota's suggestion: http://jsfiddle.net/u6kmvynf/

**Comment by danlangford** [comment]
the skills in the game cannot be viewed at all on iOS

> According to http://designshack.net/articles/css/are-hover-events-extinct/, iOS triggers the hover event on the first click, and require a second click to trigger the tap event.
>
>Thus, it looks like the hints should work on iOS.

i have never observed this behavior in iOS and i tested it just to be sure i didnt miss it. and sure enough i cannot trigger hover event in iOS. as a result i cant read the skills. (also worth noting i cannot hover the dice either to see which skills that particular die has in case i forgot what ` or ^ meant.)

in fact to quote that article that you mentioned regarding iOS and Tap / Hover the author goes on to say:
> Should You Abandon Hover Events? ... the answer is a resounding “yes,” ... I still absolutely recommend against relying on hover events  ... my advice is to always assume, regardless of the truth of the statement, that the hover interaction model won’t work for smarthphone and tablet users

even though the article is quite dated (almost 4 years and many versions of iOS and android) its still a good read. 

the suggested jsfiddle is better than we currently have it (nothing) and if its a quick means to getting the information for all users then i think its great however i think a responsive design would be a better long term solution. 

so far everybody i have introduced to the game is trying to play on mobile (while on the bus/train, in a meeting or in carpool)

i almost exclusively play on touch screen devices. let me know if there is something you would like me to check out on the Dev site to validate an interaction.

**Comment by cgolubi1** [comment]
Okay, let me try to make myself marginally useful here and collect some stuff about what we want which has been mentioned on this ticket:
* We want some option for people to be able to see skill descriptions on mobile --- i don't think "skill popups should be clickable" is so much a goal per se, as a possible implementation of how we could do that
* We want to be able to satisfy players who don't like the size, shape, and/or behavior of the existing browser hover text --- quoting shadowshade: "I've had feedback that the tooltip font is too small" and "the player has mentioned that the tooltip text disappears too quickly"
* We want to be able to satisfy players who like the size, shape, and behavior of the existing browser hover text

What other requirements do we have?

Also, do we want to keep discussing this on this ticket, or would we rather spin off another ticket given that the things in the description of this ticket have in fact been done?  I don't care much either way.

**Comment by blackshadowshade** [comment]
I'll open a couple of new tickets, and close this one.
