### ISSUE TITLE
support unicode in button flavor text

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1699]
We should be able to display Unicode characters as part of the flavor text for various buttons, e.g. Zoe and Paul Erdos.  Figure out how to store Unicode characters in the database source files, load them into the live database on at least vagrant-managed sites, and make sure they display reasonably in browsers.

**Comment by drransom** [comment]
It looks like mySQL defaults to encoding a varchar field as latin1 rather
than the full UTF-8, which doesn't include Eastern European characters, so
we get something strange if we try to save the character ő to the database.
So there needs to be some sort of database migration to change the encoding
of that field to UTF-8. But I am an ignorant n00b and have no idea how this
is done.

Elliot C. Reed
Software Engineer
github <https://github.com/drransom> | linkedin
<http://www.linkedin.com/in/elliotcreed>
www.elliotreed.com
2236 Channing Way #205
Berkeley, CA 94704
240.888.1347

**Comment by blackshadowshade** [comment]
I think that you're exactly right, since I've seen this encoding in the live database recently.
