### ISSUE TITLE
Fire overshooting cancel option text incorrect

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1709]
When I use a power attack with optional Fire dice, the third option in the dropdown message is incorrect.

The first option says: "Submit attack without turning down fire dice"
The third option says:  "Don't turn down fire dice (cancelling the attack in progress)"

The third option implies that not turning down the fire die will cancel the attack.

**Comment by dwvanstone** [comment]
My suggested solution would be to have a Cancel button next to the Submit button. I find Cancel buttons very comforting and prefer not to find them under a dropdown list.

**Comment by irilyth** [comment]
I'm not sure what you mean here -- if you pick the third option, "Don't turn down fire dice (cancelling the attack in progress)", then it cancels the attack and you can make a new attack, right?

**Comment by dwvanstone** [comment]
The quibble is in the wording -- perhaps just "Cancel the attack in progress" would be fine. Or maybe they could be parallel: "Don't turn down fire dice and submit attack" and "Don't turn down fire dice and cancel attack".

I read the third item as "Don't turn down the fire dice which will cause the attack to be canceled" and the quibble is that it is not a cause and effect.
