### ISSUE TITLE
Attack not specified on FIre turndown page (outside of history)

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1710]
When I go to the Fire turndown page, nothing specifies what kind of attack I'm in the middle of performing (skill versus power). 

I did recently find it in the history, but I was expecting to find it in the attack area.

This becomes important if a user did a "Default Attack" which became a power attack allowing overshooting with Fire dice. A newbie may not know what is happening.

**Comment by dwvanstone** [comment]
Perhaps the text "Your turn to complete an attack by adjusting fire dice" could include the type of attack.

**Comment by blackshadowshade** [comment]
Would this be resolved by reworking the description of Fire to address overshooting?

**Comment by cgolubi1** [comment]
> Would this be resolved by reworking the description of Fire to address overshooting?

I don't think so --- the point is when you're in the turndown screen, you actually do need to know whether the backend thinks you're making a Power attack or a Skill attack.  You can probably figure it out on the basis of whether you're being given a range or a single value, but why not just modify the text?  The UI knows what type of attack it is, right?

**Comment by blackshadowshade** [comment]
Okay, I'll tackle this one soon then.

**Comment by dwvanstone** [comment]
The point was that a user may stumble across the Fire screen without knowing what caused it. (I think in my case I had a Berserk die doing a single attack and I came across this screen, but in my mind Berserk dice can't do skill attacks and thus shouldn't trigger the Fire page...so I was trying to find an easy way to clarify what's happening.l)

**Comment by blackshadowshade** [comment]
That's fair enough, I'll add something like:

You need to turn your fire dice down by 3 - 5 points to complete your power attack.

**Comment by dwvanstone** [comment]
Perfect!
