### ISSUE TITLE
Ambiguous default attack, unclear that overshooting is option

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1711]
In the following screen shot, I am performing a default attack which can either be a skill attack or a power-with-overshooting attack:

![screen shot 2015-09-13 at 11 09 18 am](https://cloud.githubusercontent.com/assets/6751265/9837276/f390c34c-5a07-11e5-9a1b-b3aea6f26e1b.png)

When I read through the Fire die description nothing says that I can overshoot. (The word "assist" is not clear -- why do I need Fire die to assist me since I have a high enough value?) If I didn't know I could overshoot it looks like a bug.

**Comment by blackshadowshade** [comment]
I think this could be resolved by reworking the Fire description to include the concept of overshooting. Any suggestions?

**Comment by dwvanstone** [comment]
I think this won't be an issue once the user has a preference. A power user (with the preference on) will know what's happening. The newbie won't get this error at all - the game will proceed with a power attack. I say it's a very low priority to be fixed when the Fire UI gets revamped.

**Comment by blackshadowshade** [comment]
Okay, I'll mark this as wontfix for the moment and close it.
