### ISSUE TITLE
Skill Attack allowed even though attacking total doesn't equal defending value

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1714]
In http://dev.buttonweavers.com/ui/game.html?game=1844, Devious and I each made an attack that should have been illegal:

> Devious performed Skill attack using [m(5):3,k(8):8,d(Y=8):5] against [d(Y=1):1]; Defender d(Y=1) was captured; Attacker m(5) changed size from 5 to 1 sides, recipe changed from m(5) to m(Y=1), rerolled 3 => 1; Attacker k(8) does not reroll; Attacker d(Y=8) rerolled 5 => 3

3 + 5 + k8 can't equal 1, whether the k8 adds or subtracts.

> irilyth performed Skill attack using [n(4):3,m(5):3,k(8):7] against [m(Y=1):1]; Defender m(Y=1) recipe changed to mn(Y=1), was captured; Attacker n(4) rerolled 3 => 4; Attacker m(5) changed size from 5 to 1 sides, recipe changed from m(5) to m(Y=1), rerolled 3 => 1; Attacker k(8) does not reroll

Similarly, 3 + 3 + k7 doesn't equal 1.

**Comment by blackshadowshade** [comment]
I'm going to wait until I have a responder test before fixing this bug.

**Comment by cgolubi1** [comment]
Here you go - test 041 in https://github.com/cgolubi1/buttonmen/tree/1714_reproduce_bug
