### ISSUE TITLE
Unexpected internal error during trip attack with mood swing die

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1723]
I was attempting to do a trip attack on the dev site, and somehow, I got an internal error.

![capture](https://cloud.githubusercontent.com/assets/2898401/10182757/339061a8-676b-11e5-907e-e3212e225fa5.PNG)

**Comment by blackshadowshade** [comment]
According to the die table, I should have an st(S=6)? with a value of 13. *That* would cause an error.

Looks like a trip mood swing bug.

**Comment by blackshadowshade** [comment]
I'm guessing that we haven't seen this before because the only buttons I can see that have trip mood swing are fnord and Jenniegirl, both only available on dev.

**Comment by cgolubi1** [comment]
Yeah, indeed:
```
[Wed Sep 30 02:01:08 2015] [error] [client X.X.X.X] Caught exception in BMInterface::load_game: Invalid die value: 13 is not between 1 and 6 for die st(S)?, referer: http://dev.buttonweavers.com/ui/game.html?game=1857
```

**Comment by blackshadowshade** [comment]
So, I'm looking at this one at the moment, and the issue seems to be that mood should trigger at the beginning of the trip attack, not at the end.
