### ISSUE TITLE
Boom Time & Space dice get an extra turn if they Boom Attack while odd

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1729]
In http://www.buttonweavers.com/ui/game.html?game=7561, I did this attack:

> irilyth performed Boom attack using [b^(20):5] against [q(12):11]; Defender q(12) rerolled 11 => 5, was not captured; Attacker b^(20) does not reroll, was taken out of play

That seems fine, but then it said

> irilyth gets another turn because a Time and Space die rolled odd

That seems wrong: My b^(20):5 was odd when it made its Boom Attack, and it's true that it didn't reroll, but that also means that it didn't "roll odd".

**Comment by blackshadowshade** [comment]
From my reading of the die skill descriptions, the fix here should apply both for (i) a boom T&S die performing a boom attack and (ii) an attacking konstant T&S die.

If anyone disagrees, I'd like to hear why.
