### ISSUE TITLE
Adding empty chat message in game gives unclear error message

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1735]
[This is such a minor bug...]

After I've completed an attack I still have the opportunity to add to the chat.

I click on Add/Edit Chat.

I don't add any text and instead hit "Change game message".

The error message in red above says "No game message specified".

**Comment by blackshadowshade** [comment]
What would you expect/prefer?

**Comment by dwvanstone** [comment]
If there is no text and text is added, it says: "Added game message" in green

If there is text and text is modified, it says: "Updated previous game message" in green

If there is text and all text is deleted, it says: "Deleted previous game message" ing reen

How about "No game message added" in green. (It's not an error - someone just changed their mind.)

**Comment by blackshadowshade** [comment]
Sounds reasonable. That should be pretty easy to fix.
