### ISSUE TITLE
Overview page: "Next game" goes to unstarted game

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1736]
I have five new games to accept or reject..

![screen shot 2015-10-09 at 11 21 09 am](https://cloud.githubusercontent.com/assets/6751265/10397874/e7ca536e-6e77-11e5-8d63-ccf7847578be.png)

When I hit "Next Game" in the header or "Go to your next pending game" it takes me to game 1889 with the message "This game hasn't started yet."

**Comment by blackshadowshade** [comment]
I think that this one will be fixed best by addressing #1731, and allowing the option there to accept the game, so I'll mark this one wontfix in favour of getting #1731 fixed quicker.
