### ISSUE TITLE
Canceling an accepted game gives incorrect "Loaded data" error.

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1757]
Player 1 creates a game, then goes to the Overview page and sees the game listed in "New Games".

Player 2 accepts the game.

Player 1 hits "Cancel". 

The error message for player 1 is "Loaded data for game ##."

**Comment by cgolubi1** [comment]
"Loaded game" API error messages should always be fixed quickly and are usually not hard to fix.  Not a prod-blocker because we're trying to get out the door, but a must-have for December.

**Comment by cgolubi1** [comment]
We should be able to nail down this behavior using the test we create for #1834
