### ISSUE TITLE
horizontal line between Rejected/Completed games and New/Active games

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1763]
In the Overview page, i'd like to see a visual separation between the tables which are just there for your information and have no action for you to take (Rejected and Completed) and the tables which are potentially waiting for your move (New and Active).

* One option is to reintroduce the horizontal line between those tables, which initially had that function.
* Another option might be to use coloring -- right now all the table header backgrounds are grey.  Maybe the table header backgrounds for "New" and "Active" could be a more active-looking color instead.

**Comment by cgolubi1** [comment]
Screencap of the page with four undifferentiated tables:

![four_tables](https://cloud.githubusercontent.com/assets/2898207/10908061/daa8a864-81fc-11e5-96db-a1c306b18886.png)

**Comment by irilyth** [comment]
I think both the HR and the color would be nice, the better to appeal to people with different visual styles (have a hard time seeing thin lines, have a hard time distinguishing colors).

**Comment by cgolubi1** [comment]
Since we had the HR before and it is semantically meaningful to the player, i think losing it is a regression, and fixing that regression is a must-have for December and should be very easy.

If it's easy enough to do something with color as well or instead, great.

**Comment by blackshadowshade** [comment]
For the record, I think that the horizontal line will be difficult, because we'll need to somehow work out whether we have any of the categories either above or below the line before deciding whether to generate the line. Colour is trivial in comparison.

**Comment by cgolubi1** [comment]
> For the record, I think that the horizontal line will be difficult, because we'll need to somehow work out whether we have any of the categories either above or below the line before deciding whether to generate the line

You could, or you could move the HR into `Overview.pageAddGameTables()`, and just put it exactly where you want it.

**Comment by blackshadowshade** [comment]
... meaning that it's always there, even if there's nothing above it?

Sure, I could do that, but I thought that that would look odd.

**Comment by cgolubi1** [comment]
Hmm, yeah, good point --- i think the overall point, that the HR doesn't belong in `Overview.pageAddGameTable()`, is correct.  But it is the case that the Overview page has access to all of the relevant objects.  So it shouldn't be too hard to make a little function that just checks the lengths of the various arrays, and makes the line if A + B is nonzero and C + D is as well.

**Comment by dwvanstone** [comment]
> In the Overview page, i'd like to see a visual separation between the tables which are just there for your information and have no action for you to take (Rejected and Completed) and the tables which are potentially waiting for your move (New and Active).

In my mind, the Rejected and Completed tables are waiting for my action -- to dismiss. All the boxes are waiting for me to do something, so I don't see as much of a need for separation (horizontal rule or color).

**Comment by cgolubi1** [comment]
On Tue, 03 Nov, 2015 at 06:54:50 -0800, dwvanstone wrote:

> In my mind, the Rejected and Completed tables are waiting for my action -- to dismiss. All the boxes are waiting for me to do something, so I don't see as much of a need for separation (horizontal rule or color). 

I disagree --- i think there's a somewhat important difference between whether another player is waiting for me to do something, vs. whether there's something to be done just for my own information/workflow.

**Comment by irilyth** [comment]
> i think there's a somewhat important difference between whether another player is waiting for me to do something, vs. whether there's something to be done just for my own information/workflow.

I agree with Chaos, I think that distinction is interesting and important.

**Comment by AdmiralJota** [comment]
I'm coming late to this discussion, but having thought about it, I would vote for the horizontal line to come above your list of active games, with everything else above it. 

The active games list is the main content of the page, and it'll remain there even after you take your turns. The other tables are just temporary notifications that there's something you need to address, and as soon as you click on them (dismiss/accept/reject), they go away. So I think it makes more sense to separate out "here is the main part of the page" vs. "here are some things to quickly take care of before you deal with the main part of the page".

(And don't forget, most of the time, you won't have all those tables at once tables. Just your main table and maybe one or occasionally two other things. And I think that putting the horizontal line between the main table and whichever minor temporary table is there at the moment makes sense if there's only one, whichever one it is.)

**Comment by blackshadowshade** [comment]
Leaving aside discussion of the line for the moment (where we seem to have no consensus), could any of you imagine the problem being solved with colour? And how?

**Comment by blackshadowshade** [comment]
So, I'm going to start out addressing this by implementing something like Jota's suggestion from http://i.imgur.com/ACaiuv2.png:

Closed games:
- Lost and rejected games, sorted in reverse game order

Active games (waiting for your action):
- New games waiting for your acceptance and games waiting on your action, sorted in order of decreasing staleness

Active games (waiting for opponent's action):
- New games waiting for their acceptance, and games waiting on their action, sorted in order of increasing staleness (possibly hidden because of staleness)
