### ISSUE TITLE
get reject-game ready to release to prod in November

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1765]
Our goal is to do a BM prod release on Nov 6th which contains the functionality to allow players to reject offered games, rather than having all proposed games start immediately (referred to below as "reject-game" functionality).

Look at issues found with reject-game on dev, and get a *rough* consensus classifying those issues (by tagging them or placing them in a milestone) as one of:
* Needs to be fixed before we can make the November release to prod: label "prod-blocker": https://github.com/buttonmen-dev/buttonmen/labels/prod-blocker
* Does not block the November release, but is a high priority to get fixed before the December release: milestone: https://github.com/buttonmen-dev/buttonmen/milestones/Game-rejection%20priorities%20for%20December%20release
* Still desirable, but doesn't need to be addressed in either the November or December releases: no label or milestone

If you move an issue into one of these buckets, or if you think we should move an issue into one of these buckets, please comment on this issue with your thinking.

**Comment by cgolubi1** [comment]
All of the prod-blockers i'm aware of have been addressed to get us to this point.  I put the important reject-game issues i'm aware of into the December milestone.  I'll point testers to the dev site and to this issue.

**Comment by dwvanstone** [comment]
I don't feel strongly about #1766, and it may be fixed by #1731.

**Comment by irilyth** [comment]
I created:

*  #1768 (Change "Max wins" column to "Score // W/L/T (Max)"): If this isn't trivial, or is controversial, I think it's fine to punt it to December, but it seems easy and fits into "it's important that the tables be consistent" principle.
* #1767 (When you cancel a game, include a link to the game, in case you mis-clicked): I think this can wait until December.

**Comment by irilyth** [comment]
I also just created #1770 (Rejected and canceled games should show up in history), which I think is not a high priority for Nov or Dec.

**Comment by blackshadowshade** [comment]
I want to flag #1750, and check that this hasn't dropped beneath the radar for testers. Please test the behaviour for new games with random button selection, and see if this meets your expectations or not.

**Comment by cgolubi1** [comment]
Okay, so with the fixes to the pending-game-count bugs, i think we've hit all the blockers, and i'm hoping to push to prod Friday morning.  Bring out your caveats between now and then.

**Comment by cgolubi1** [comment]
We released reject-game to prod, so it must have been ready.  :>)  Closing this.
