### ISSUE TITLE
Change "Max wins" column to "Score // W/L/T (Max)"

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1768]
The New and Rejected tables should both have "Score // W/L/T (Max)" rather than just "Max wins"; among other things, it makes it easy to tell at a glance what that column is, since "0/0/0 (3)" is instantly recognizable in a way that just "3" isn't.

**Comment by irilyth** [comment]
If this isn't trivial, or is controversial, I think it's fine to punt it to December, but it seems easy and fits into "it's important that the tables be consistent" principle.

**Comment by blackshadowshade** [comment]
I disagree with this suggestion. I think that it is meaningless, and possibly confusing, to put a game score on a game that hasn't started yet.

The change is easy to make, but I'd like us to consider this one a little more.

**Comment by irilyth** [comment]
A game where both players need to select their swing dice but haven't yet also hasn't started yet in some sense and yet there's a score there. I just don't see this as a big problem and I think the visual symmetry is nice. What's the drawback of having it look symmetric?

-Josh (from my phone)

**Comment by cgolubi1** [comment]
Hmm, so i realised i have a spanner to throw in this idea --- i don't currently like "Score\nW/L/T\n(Max)" because it's three lines long, and nothing else in the header is more than two lines long.

So i definitely don't like the idea of putting that header in all the tables --- it'll make the page much taller.  So i don't think we should do this for Nov.

**Comment by cgolubi1** [comment]
Just to demonstrate why i thought there was a newline in here.  Why is firefox wrapping this when the box is so big?  I have no idea:

![extraneous_line_wrapping](https://cloud.githubusercontent.com/assets/2898207/10929196/6d216fec-827e-11e5-9e63-371efdc2c124.png)

**Comment by cgolubi1** [comment]
Okay, we discussed this on IRC, and we lack the will to stand and fight here --- everyone thinks it's not very harmful to punt this to December.  Removing prod-blocker label.

**Comment by cgolubi1** [comment]
FWIW, i agree with Josh that there's no harm in being consistent, and it could help, so we should change the column contents.

Heh, also, if at some point in the future we implemented handicapping by giving the weaker player a free round, that would make the UI show that.  But there were a lot of "ifs" in that sentence.

**Comment by blackshadowshade** [comment]
For interest, the backend already fully  implements handicapping by rounds.

**Comment by cgolubi1** [comment]
So in Jota's example http://i.imgur.com/ACaiuv2.png he displays this as "-/-/- (3)".  Do we like that?  I don't have a philosophical problem with "0/0/0 (3)", but i'd be pretty happy with "-/-/- (3)" as a compromise that maintains the layout while making it clear that the game hasn't started yet.

**Comment by blackshadowshade** [comment]
Yeah, I like that a lot.

**Comment by irilyth** [comment]
I like the dashes too.

**Comment by dwvanstone** [comment]
-- Ditto -- Dashes -- Yes!

**Comment by blackshadowshade** [comment]
So, to be pedantic, does anyone care if I use hyphens, en-dashes, or em-dashes?

**Comment by irilyth** [comment]
I'd vote hyphens unless N-dashes look noticeably better. M-dashes seem likely to be too long.
