### ISSUE TITLE
Move Description column to next-to-last position

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1769]
I think the Description column would look better in the next-to-last position, rather than dividing score from opponent (which blend nicely together on the prod site now).

**Comment by irilyth** [comment]
Marking this as a prod blocker mostly because I think it should be easy to do (unless there's disagreement about it), and I think it's disruptive to move UI elements around unnecessarily (so if we like it, we should get it out there when Description goes live, and not wait a month and then change it).

**Comment by blackshadowshade** [comment]
Does anyone else have views on this? I ask only because I've already shifted the Description column once, and I don't want to have to do it more than once more.

**Comment by cgolubi1** [comment]
I don't really have views on this --- either next to last or third from last is fine with me.

**Comment by dwvanstone** [comment]
I don't have a strong feeling about this.

**Comment by AdmiralJota** [comment]
I agree with irilyth about it being nice to have it next to the opponent column, but I don't think it needs to be a prod blocker.
