### ISSUE TITLE
Rejected and canceled games should show up in history

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1770]
Rejected and canceled games (and, when we have this, forfeited games) should show up in the history page; possibly with a way to include them or not, if we think (or hear) that people don't like that, but it should be *possible* to find them there.

**Comment by AdmiralJota** [comment]
If we do that (and I don't have a strong opinion either way), I'd suggest making this a third option in the same dropdown list as "Completed" "In Progress".

**Comment by irilyth** [comment]
Yeah, I was thinking about that, although if you wanted to show all games *except* rejected/canceled/forfeited games, that's not just a third option. But I bet we can figure out something here that looks nice.
