### ISSUE TITLE
game page displayed in CHOOSE_JOIN_GAME does not show button recipes

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1774]
See image --- the issue is that the API doesn't send dice until the game starts.  So possible fixes would include:
* Have the API send some dice
* Change the look of the page and make it look like the finished game page instead of the swing*-selection page, so there's a slot for the recipes
* Other

![choose_join_game_no_recipe](https://cloud.githubusercontent.com/assets/2898207/10927671/c7162aba-826f-11e5-85dd-654abb842597.png)

**Comment by cgolubi1** [comment]
Proposing this as a December priority, at least provisionally.

**Comment by irilyth** [comment]
I think it'd be interesting to see what it would look like if it were more like the finished-game page. I think there's some risk it would be mistaken for a finished game. :^) But if it weren't, I bet that would look nice.

I agree with December anyway.

**Comment by jimmosk** [comment]
I'd also suggest the "W/L/T" line be eliminated from this screen, since it's useless on an unstarted game.

But hey, how about if instead that line were used to show the win-loss record from when those two buttons have competed previously?

**Comment by cgolubi1** [comment]
> But hey, how about if instead that line were used to show the win-loss record from when those two buttons have competed previously?

This suggestion should be moved to a separate issue, since it needs a new API call, and i don't think it's blocker priority for December.  (I do think getting the recipes on the page at all is an important priority.)

As a general rule, i think we should try to move away from stacking a bunch of unrelated things on one issue --- if we haven't decided what the solution to an issue is yet, it's fine to kibbitz, but in this case IMO it's pretty clear what this issue is, and it's about getting the button recipes on the page, not about other changes to the page.  If we ask for a lot of unrelated things, there's a very good chance that we'll have to struggle to remember what the original issue was and make sure we've solved it, and/or that all the unrelated requests will be lost.

**Comment by jimmosk** [comment]
Makes sense to me.  I'll open two new issues, about removing W/L/T and about adding previous win-loss.
