### ISSUE TITLE
The new-game page should say something about what it is

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1776]
The new-game page right now doesn't really clearly express what it is; if it said at the top something like "New game! Player X has challenged you to a game", right above the "your turn to accept/reject" text, I think that would look nice, and make the flow between active games and new games more smooth.

**Comment by blackshadowshade** [comment]
So, there are actually three new-game pages:
- the one where you have been challenged to a game and need to accept or reject
- the one where you have challenged someone else to a game and have the option to cancel
- the one where you are not a participant in the game

Which of these needs the extra text?

**Comment by irilyth** [comment]
Mm, I think probably all of those, or none -- I'm now no longer sure that this is necessary. (I think I originally liked it because there was this new page that looked a lot like an active-game page, but required different action from you, and that might confuse people who were used to seeing active-game pages all the time, but had never seen this new weird page before, and thus might be confused about what it was. On further reflection, and now that it's been out for a while, I think it's obvious what the new-game pages are asking you to do, and that they don't need extra callouts like I was suggesting here.)

If no one else thinks this is particularly necessary, I'd say close it as withdrawn.

**Comment by blackshadowshade** [comment]
Right, I'll leave this open for 24 hours to give others a chance to comment, but if no one else wants to keep this open, I'll close it.

**Comment by dwvanstone** [comment]
I just tried it on the dev site. I think it is great as is and doesn't need extra text.

**Comment by blackshadowshade** [comment]
Right, closing this one. If anyone feels strongly about this, feel free to reopen it.
