### ISSUE TITLE
Prompt for confirmation before rejecting a game

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1777]
Re-creating a rejected game is rather annoying now, and will probably at least somewhat annoying in the future, so it'd be nice if it prompted for confirmation, like surrendering.

**Comment by dwvanstone** [comment]
Let me add another use case for this -- because horizontal space is tighter now, the Accept/Reject options appear vertically:

Accept /
Reject

This makes it more likely (for me and my mouse skills) to accidentally hit Reject instead of Accept. I think confirmation would make it less likely to accidentally reject a game.

**Comment by irilyth** [comment]
> Let me add another use case for this -- because horizontal space is tighter now, the Accept/Reject options appear vertically:
>
> Accept /
> Reject

I think this is a browser width thing: I don't see this effect on my screen, the two appear side-by-side for me.

I agree that having them stack vertically makes it easy to click the wrong one, as you're mousing up and down in the column, especially if you're going between multiple games. Maybe they should be separated by &nbsp; characters rather than space, so they don't wrap? (Or some other JS/CSS way of forcing the contents of the cells in this column to stay on one line.)

**Comment by AdmiralJota** [comment]
The CSS way (which is preferred these days) is to do something like:

    <th style="white-space: nowrap;">Score (W/L/T (Max))</th>

**Comment by blackshadowshade** [comment]
So, my question here is whether we still want to have a confirmation popup for the *game* page, now that the accept/reject is not present on the Overview page any more.

**Comment by dwvanstone** [comment]
Yes - the Accept Game and Reject Game are adjacent and it is possible a stray click will accidentally reject the game.
