### ISSUE TITLE
The rejected-game and canceled-game pages should include a link to re-create the game

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1779]
If you cancel or reject a game, the game page for the canceled or rejected game should include a link to re-create the game, in case you want to play it after all. (Maybe you changed your mind, maybe you intended all along to play it later but didn't want to play it at the time it was created, whatever.)

**Comment by blackshadowshade** [comment]
I was actually thinking of implementing this as an "un-reject" option. That is actually quite easy to do, as far as I can tell.

**Comment by irilyth** [comment]
Huh, I was assuming that rejecting would be irrevocable, but I suppose there's not necessarily any reason it should be, and un-reject sounds pretty good. Interesting!
