### ISSUE TITLE
Allow third-party game creation

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1784]
Now that we have a way to accept or reject games, allow players to create games between two other players, which the two other players would both be prompted to accept.

(My perhaps-obvious use case for this is Mad Robin and UBFC; this would let my scripts create matches via the API, with all the right parameters, rather than having to use forum posts to ask players to create their own, and sometimes getting the parameters wrong.)

**Comment by danlangford** [comment]
another use case would be introductions. my friend starts playing and maybe there are a few players that have been particularly helpful and kind to me i could introduce my friend to them by starting a game between them. i think its worth discussing if this should be an opt-in feature via the preferences. "Allow third parties to create games with you vs other players"

**Comment by irilyth** [comment]
#1783 might cover the "allow third parties etc" preferences.

**Comment by Hurtay** [comment]
As long as we don't have tournaments implememted (which probably would be a lot of programming to do and therefore won't come anytime soon) I think this third party games are a brilliant idea. Imho this issue is something comletely different than #1783. 
Since everyone can reject games he doesn't want I'm not even sure if it's necessary to put it into the player's preferences but for being on the safe side a box to tick (or better: untick) is the perfect solution.

**Comment by Hurtay** [comment]
This is my BfotM for February 2016 (sorry for labeling as late as I do, it's my first label at all and I wasn't sure how to do it).

**Comment by blackshadowshade** [comment]
Just an update on this: I'll take a look at this once the action logging has been translated across to the new methodology, since we'll most probably want to log who created the game.

**Comment by AdmiralJota** [comment]
Ooh. It'd be nice to log that for regular games, too. I'd like to see log entries for "X created an open game", "Y joined the game", "X challenged Y", etc. Should we make another ticket for that?

**Comment by blackshadowshade** [comment]
Yeah, let's make that a new issue. I'll be forced to address it when we do this issue, but I might address parts of it beforehand too.

**Comment by irilyth** [comment]
In the course of testing this, I found two bugs with the current game-creation API, #2218 and #2219; meanwhile, this change introduces a new bug, whereby I can create a game that specifies only the player's button, but not the player, opponent, or opponent's button. This is a regression from master, which currently says "ValueError: Failed to call createGame, got: Game create failed because you must be the first player."

I think that until/unless we want to support open games with neither player specified, the API should require you to set 'player' at a minimum -- it doesn't have to be yourself any more, but it has to be *someone*.

**Comment by blackshadowshade** [comment]
I'm closing this issue, because I think we've addressed it pretty much in its entirety. I've spawned #2281 out of Jota's last suggestion.
