### ISSUE TITLE
Fix wrapping in Overview tables

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1795]
Now that the description field is being truncated, I don't think we need to put hard breaks into the table headers anymore. Also, #1777 pointed out that we really shouldn't be letting the "[Accept] / [Reject]" links wrap.

I propose something like https://www.dropbox.com/s/5v0ivse23vngqcj/Overview.js?dl=0 (untested) to address these issues.

**Comment by dwvanstone** [comment]
Copying over AdmiralJota's comment from #1777, for when someone works on this in the future.

"The CSS way (which is preferred these days) is to do something like:

<th style="white-space: nowrap;">Score (W/L/T (Max))</th>"
