### ISSUE TITLE
Should Trip Time and Space dice be able to get extra turns from Trip attacks?

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1804]
In game http://dev.buttonweavers.com/ui/game.html?game=1857 a st^(S=7) made a series of trip attacks, some successful and some un-, rolling odd each time and getting an extra turn.
I think that disagrees with the descriptive text of the dice:  ^ triggers if the die rolls odd when rerolling *after* it participates in an attack. But in a trip attack there isn't any reroll after the attack! The reroll *is* the attack, with no reroll afterwards.

Do people think the writeup of Trip needs to be changed, or the way the Time and Space skill is handled in Trip attacks?

**Comment by cgolubi1** [comment]
IMO the behavior is right and the text is unclear.  I think:

"If a Time and Space Die participates in an attack, rerolls, and ends up showing an odd number, ..."

correctly reflects what we're trying to implement, though it reads like it was written by rules lawyers.  :>)

**Comment by jimmosk** [comment]
I think it'd work to say "rerolls an odd number after (or during) an attack".
