### ISSUE TITLE
game page displayed in CHOOSE_JOIN_GAME shows useless W/L/T

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1810]
When choosing a game, we're currently shows that the (unstarted) game has a W/L/T of 0/0/0.
Remove that line since it's informationless.

**Comment by irilyth** [comment]
On the overview page, I think the plan is to show -/-/- (3) for new games; would that be ok to show here? It seems like it might be nice to be consistent, even if the information isn't very useful.

**Comment by jimmosk** [comment]
I still think it seems like a dumb thing to show when the game hasn't started. If for consistency or simplicity you want to do it, I agree that -/-/- is better... but my preference would still be for not having it at all. Though I should point out that it's important to keep the (n) that shows how many wins the game would be to.

**Comment by irilyth** [comment]
Keeping the (n) part seems important, so keeping the whole thing seems nicer to me than making it different from everywhere else we show it.

Anyone else care?

**Comment by dwvanstone** [comment]
I care that it lines up visually in the vertical column for readability, so I prefer the "-/-/- (N)" format. But we'll have to see it before we know for sure!

**Comment by AdmiralJota** [comment]
I think that the "-/-/- (N)" might stand out more than just having nothing there, making it more obvious that you're looking at a game that hasn't started yet. Plus, of course, the N is important (and might look a bit silly floating there by itself). And consistency is always a nice plus.

**Comment by blackshadowshade** [comment]
I believe that this was fixed by #1822. Can someone please check this, and if it's fixed, close the issue.

**Comment by cgolubi1** [comment]
Agree, this is fixed.
