### ISSUE TITLE
when you accept a game, the success message should include a link to the game page

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1823]
When you create a game, the game creation page modifies the success message, giving you something like this:
![create_game_success](https://cloud.githubusercontent.com/assets/2898207/11324316/161e3662-90fc-11e5-8665-bc7d87ab6dc1.png)
which includes a link to the game, so you can go there right away if you want.

When you accept a game proposed by another player, the success message should be modified the same way, so that if you want to look at the game you've accepted right away, you can, rather than having to scroll to the end of your active games list.

**Comment by cgolubi1** [comment]
If #1832 is accepted, this will no longer be necessary, because accepting games from the Overview will no longer exist.

**Comment by blackshadowshade** [comment]
Closing this, in line with Chaos's comment.
