### ISSUE TITLE
New overview tables are too wide

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1829]
The new overview tables are wider than they used to be, which makes them uglier horizontally on smaller (in my case, about 1200 pixels wide). The "Decision" column seems to be mostly to blame: Even when it's entirely empty, it causes the header of the "Score W/L/T (Max)" column to be three lines tall, and causes long descriptions (which get truncated with a "...") to be two lines tall.

**Comment by irilyth** [comment]
A screenshot:

![bm](https://cloud.githubusercontent.com/assets/4923138/11479317/4d84c18e-975f-11e5-9f10-a4075bb5e89f.png)

Off the cuff, my two cents would be to drop the "Decision" column entirely, and just let people decide about accepting/rejecting games on the game page, and not have links in the overview tables at all.

**Comment by AdmiralJota** [comment]
We could also override what's in the Inactivity column, like in http://i.imgur.com/ACaiuv2.png

Maybe rename it to "Activity" or "Status" or something if we think having those links in a column called "Inactivity" is weird.

But I agree that adding a whole extra column to the Active Games table is probably too much.

**Comment by irilyth** [comment]
Yeah, I thought about suggesting that we overload that column; I suspect that the inactivity time is pretty uninteresting for new games. It seemed weird to call that column "Inactivity" in that case, but I think "Activity" or "Status" would be a fine change.

**Comment by cgolubi1** [comment]
On Mon, 30 Nov, 2015 at 09:58:10 -0800, irilyth wrote:

> Yeah, I thought about suggesting that we overload that column; I suspect that the inactivity time is pretty uninteresting for new games. It seemed weird to call that column "Inactivity" in that case, but I think "Activity" or "Status" would be a fine change.

Disagree - i think it's just as useful to see at a glance how long a
game has been waiting for a decision if it hasn't started.  IMO let's
keep the Inactivity column present and consistent for all games.

I don't *think* i object to removing the Accept/Reject column and having
people make a decision on the game page.

Chaos

**Comment by AdmiralJota** [comment]
Given that the left column says "NEW Game 2004" rather than just "View Game 2004" (which is a reasonably good clue that clicking on it will take you to something other than just the usual "take your turn or view the game state" version of the game page), I'd be fine with that too.

**Comment by dwvanstone** [comment]
I found the blank "Decision" column under Active Games a bit baffling at first until I had some new games in that table. 

I think getting rid of the Decision column for the Active Games table is a fine solution - to accept or reject I can go into the game (which I like), and to cancel a game I created I can go into the game (which is fine.) 

This is all good. [And let me say overall...this is a great, great improvement!!]

If we're concerned that the Closed Games table will be wider than the Open Games table we could get rid of the "Inactivity" column on that table. But it's not a big deal.

We could change the title of the column from "Decision" to "Dismiss" since there is no decision to make any more in this case.

**Comment by irilyth** [comment]
The tables are likely to be different widths because of having different contents in the columns anyway, so I think it's fine if they have different numbers of columns.

**Comment by blackshadowshade** [comment]
May I suggest that we then have Chaos accept #1822 first, so that the new game page doesn't look so empty?

**Comment by irilyth** [comment]
What's in #1822 that would affect this? It just says "Fixes #1774", which is about adding button recipes to the new game page. Which I think is a fine thing to do, but I'm not sure how it relates to the suggestion to get rid of the Decision column on the overview page.

That said, I also don't mind if no one fixes this until #1822 is in. I just wasn't sure why. :^)

**Comment by blackshadowshade** [comment]
My reasoning is that the game page was previously not directly accessible, and that the obvious place for accepting/rejecting was on the overview page. Sure, people saw the game page when navigating via Next Game, but it wasn't the bit that confronted you immediately.

With the loss of the column, we are forcing people to the game page before they can make an action. That makes the New Game page all the more visible, and I think that there was some consensus (not including me) that incomplete = broken. Thus, going by this logic, the new game page is broken and will become more obviously broken simply by the fact that it becomes more obviously visible.
