### ISSUE TITLE
Add [wiki] tag to markup

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1830]
It'd be cool if `[wiki=thing]` turned into a link to `http://buttonweavers.wikia.com/wiki/thing`.

**Comment by AdmiralJota** [comment]
I've updated https://gist.github.com/AdmiralJota/f9891b7d0a22f564ccf2 (from Issue #1177) to include the "[wiki=...]" tag (in addition to [button=...] and [set=...]).
