### ISSUE TITLE
When showing New and Cancelled games in the History UI, use -/-/- for the W/L/T

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1840]
What it says on the tin.

**Comment by blackshadowshade** [comment]
I believe that this was fixed by #1815. Can someone else confirm that this isn't an issue anymore, please, and then close this issue.

**Comment by cgolubi1** [comment]
Shadowshade: this issue is about the History page, not the Overview page.  I don't believe it has been fixed, e.g. try browsing to http://dev.buttonweavers.com/ui/history.html#!status=REJECTED

**Comment by blackshadowshade** [comment]
Thanks for the clarification. I'll fix this one in the next day or two then.

**Comment by blackshadowshade** [comment]
The NEW GAME part of this relies on #1839.
