### ISSUE TITLE
Reformat count of pending games in page header

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1850]
In #1821, we added a header for the Overview or Monitor mode formatted like "(23 games waiting) - Button Men Online".  This is awkward looking, especially in a tab bar, where "(23) Button Men Online" would probably be much better.  Improve the situation.

**Comment by irilyth** [comment]
Just to clarify, "header" here refers to the page title, not the part of the page contents above the first HR (i.e. not the part where it says "Welcome to Button Men" and has links to Overview, Monitor, Create game, and stuff).

**Comment by AdmiralJota** [comment]
"(23) - Button Men Online" or "(23) Button Men Online"? I prefer the former, personally.

**Comment by blackshadowshade** [comment]
I would vote for without the dash, if only because it's consistent with Github and Facebook.
