### ISSUE TITLE
infinite loop bug when creating game between Echo or Zero and RandomBM

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1868]
![infinite_loop_while_advancing](https://cloud.githubusercontent.com/assets/2898207/11870243/e8cf04c4-a493-11e5-87e5-22615062b9b0.png)

Seems to hold for Echo or Zero vs. any type of RandomBM that i tried.

**Comment by cgolubi1** [comment]
This bug does not exist on prod --- it's a regression.  See http://www.buttonweavers.com/ui/game.html?game=8997

**Comment by AdmiralJota** [comment]
Infinite loop detected?

Halting problem: solved!
