### ISSUE TITLE
option reserve numbering bug affecting prevOptValueArray

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1883]
If bobby 5150 adds the `r!(1/30)` as the first reserve die choice, and then later adds another reserve die, the UI doesn't report the previous value that the `r!(1/30)` had.

It should be obvious why (to shadowshade) --- it's because the API reports prevOptValueArray by number, and is still reporting:
```
"prevOptValueArray":{"3":"1","4":"1"}
```

even though the `r!(1/30)` now has index 5 instead of 4.

Obligatory screencap.  I might be able to add a responderTest later, but can't be bothered right now --- like i said, i think it's pretty obvious what the problem is, and afaik it only affects bobby 5150, scourge of buttonmen devs.

![bobby5150_reserve_option](https://cloud.githubusercontent.com/assets/2898207/12066631/e8104c3e-afb8-11e5-9235-1dcd5f742fdb.png)

**Comment by blackshadowshade** [comment]
I'm going to wait until #1879 has been merged before tackling this bug, since I'll be touching prevOptValueArray.
