### ISSUE TITLE
TypeError: state is null bug in Forum

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1888]
See discussion in #1886 for details - the symptoms are something like this:
* Go to the Overview page
* Click on "(New post)" in the header - that takes me to http://localhost:8080/ui/forum.html#!threadId=1&postId=3793 and scrolls to the bottom of the post, as expected
* Click on "Mark thread as read" - that takes me to the top of the page of the Miscellaneous Chatting forum, as expected
* Click on "(New post)" in the header - that puts http://localhost:8080/ui/forum.html#!threadId=210&postId=3794 in my URL bar, and it takes me to the bottom of that post

And the underlying bug is "TypeError: state is null", i.e. (i'm pretty sure) something in that sequence of actions is causing Forum.js's state variable to be null at a time when something else expects it to not be null.

**Comment by cgolubi1** [comment]
Okay, so, the exception is being thrown in `Forum.showPage`, by line 81:
```javascript
  if (state.threadId) {
```

Here's the whole function:
```javascript
    71  Forum.showPage = function(state) {
    72    // If this was called from a popState event, the parameter might be an event
    73    // object containing a state rather than the state itself
    74    if (state.state !== undefined) {
    75      state = state.state;
    76    }
    77    if (state.originalEvent !== undefined) {
    78      state = state.originalEvent.state;
    79    }
    80    // Display the appropriate version of the page depending on the current state
    81    if (state.threadId) {
    82      Api.loadForumThread(state.threadId, state.postId, Forum.showThread);
    83    } else if (state.boardId) {
    84      Api.loadForumBoard(state.boardId, Forum.showBoard);
    85    } else {
    86      Api.loadForumOverview(Forum.showOverview);
    87    }
    88  };
```

Specifically, the issue is that on line 77, `state.originalEvent` is defined, so we're winding up redefining state per line 78.  However, `state.originalEvent.state` is defined but null in the case in which we've run through the "Mark thread as read" code, so line 78 leads to defining `state=null`, and thus to the expected blowup on line 81.

Throwing in an `&& state.originalEvent.state !== null` on line 77 changes the situation, but doesn't fix it --- doing that leads to getting redirected to (i think, too lazy to check right now) the forum overview page, presumably because `state.threadId` and `state.boardId` are not defined.

**Comment by cgolubi1** [comment]
So... `originalEvent` is a jQuery thing, and not one i understand.  To me, this looks like a pretty bad expectations mismatch between the way the forum code expects the page to be rendered to get the history it needs, and the way the footer refactor changed page load.

IMO, the *right* fix is to refactor the forum code to treat page elements and load history the same way the other pages do.  But i'm interested in the opinions of people who understand the code on whether there is an expedient fix, and later today i will be looking for an expedient fix myself.

**Comment by cgolubi1** [comment]
This issue is the right place to talk about fixes for the technical bug, if you have one to propose.

**Comment by blackshadowshade** [comment]
Just letting you know that I'm on very limited bandwidth, and that I have no real insight into this, especially I've not done anything with the forum code. If you feel like you can fix this yourself, I'd suggest getting @AdmiralJota to approve the pull request for this. I'll post if I can access your fix and test it myself.

**Comment by cgolubi1** [comment]
> Just letting you know that I'm on very limited bandwidth, and that I have no real insight into this

Understood --- no worries.

**Comment by cgolubi1** [comment]
Okay, so, thinking aloud more about this in hopes that eventually i'll either stumble across a fix or someone will help out: various comments imply that `Env.history.state` is involved here in some way.  I'm not 100% sure how that gets parsed, but it looks like how it gets set is a block like this one:
```javascript
  var state = Forum.readStateFromElement(this);
  Env.history.pushState(state, Forum.pageTitle, Forum.buildUrlHash(state));
```

where that first function is:
```javascript
Forum.readStateFromElement = function(stateElement) {
  var state = {
    'boardId': $(stateElement).attr('data-boardId'),
    'threadId': $(stateElement).attr('data-threadId'),
    'postId': $(stateElement).attr('data-postId'),
  };
  return state;
};
```

So, basically, whenever that code gets invoked, it takes the `this`, whatever it is, and looks for those named attributes, `data-boardId` etc, within the `this`.  Backing up to some more context on `this`, at least in one of the cases:
```javascript
Forum.arrangePage = function() {
  var pseudoLinks =
    Forum.page.find('.pseudoLink').add(Login.message.find('.pseudoLink'));
  pseudoLinks.each(function() {
    $(this).click(Forum.formLinkToSubPage);
    var state = Forum.readStateFromElement(this);
    $(this).attr('href', 'forum.html' + Forum.buildUrlHash(state));
  });
  ...
```

So, could that be our regression?  Is `Login.message` (or `Forum.page`) getting reset in a way it wasn't previously?

**Comment by cgolubi1** [comment]
Okay, no, i'm getting rabbitholed --- when the error is triggered (when i actually click on the "New post" link the second time), ```Forum.showPage()` is the first and only function in Forum.js which is hit before the error arises.

So the issue *must* be with the Login.js context which is being retained (or isn't being retained any longer).  And unfortunately i'm now stuck in some stuff that is deeply magical to me.

Login.js *never* invokes a `showPage` function directly (it would invoke `showLoggedInPage`), so the setup of the bad state must be tied to this invocation (in `showLoggedInPage`):
```javascript
  $(window).bind('popstate', Forum.showPage);
```

What does that mean?  What's a `popstate`?

And `Forum.showPage` takes a `state` argument --- when it's invoked in this `popstate` way, how is that `state` argument set?

Trying to find answer to those questions now.

**Comment by cgolubi1** [comment]
Here's a reference about popstate - for me, it raises more questions than it answers - https://developer.mozilla.org/en-US/docs/Web/Events/popstate

**Comment by cgolubi1** [comment]
Okay, i said i was looking for an expedient fix --- if i modify that popstate declaration so it sends the browser to `Forum.showLoggedInPage` rather than `Forum.showPage`, it appears to work correctly.  Doing some testing now.

**Comment by cgolubi1** [comment]
Assuming that works, i need to look into whether History.js needs the same fix/has the same problem --- it seems like it should based on grepping, but i haven't investigated at all yet.

**Comment by AdmiralJota** [comment]
I've added a comment to #1890, explaining why I think the current fix is a regression.

The fact that changing the popstate binding made the error message go away makes me think that the popstate event <i>is</i> being triggered when you go through those steps. And as further evidence, the object being passed into Forum.showPage() <i>has</i> an "originalEvent" field on it (even if it's null), so I think it must be a genuine popstate event object. 

So I suspect one key question to solving this bug may be: <i>why?</i>

According to the mozilla.org link, "The popstate event is only triggered by doing a browser action such as a click on the back button (or calling history.back() in JavaScript)." So what's happening during this sequence of events that would be generating a popstate event, and why is this only just happening now? 

Another note on that page is "Chrome (prior to v34) and Safari always emit a popstate event on page load, but Firefox doesn't." Is it possible that this popstate event is being triggered by the initial page load? On the one hand, that might explain why the originalEvent is empty. On the other hand, if this is a click on "(New post)" that's occurred <i>after</i> you've already been doing things on the Forum page, then the initial page load should be long past. And even if clicking on "(New post)" were performing a fresh page load, why would we be seeing the error this time and not the first time you clicked it, when it really <i>should</i> have been a new page load? And why would this only be cropping up <i>now</i>, and not before?

Does anyone else know anything about any of the other changes in this release that might be interacting with the browser history, or might be affecting/breaking click events in the Login header, or... anything else that might be relevant? Maybe any changes to which things get called when the page first loads, and in what order?

**Comment by AdmiralJota** [comment]
My best guess is that it's related to the Login.js refactor, and probably involves one of these things:

* Forum.arrangePage() looks at Login.message to find the "(New post)" link and set the click event on it. It ends by calling Login.arrangePage() (passing it the contents of the Forum page).

* Forum.showOverview() sets up an event on the Mark All Boards Read button that calls Login.addNewPostLink() (to add the "(New post)" link to the header). It ends by calling Forum.arrangePage(), mentioned above.

* Forum.showBoard() sets up an event on the Mark Board Read button that calls Login.addNewPostLink() (to add the "(New post)" link to the header). It ends by calling Forum.arrangePage(), mentioned above.

* Forum.showThread() sets up an event on the Mark Thread Read button that calls Login.addNewPostLink() (to add the "(New post)" link to the header). It ends by calling Forum.arrangePage(), mentioned above.

I expect that this bug is probably related to changes to either Login.arrangePage() (which seem to be substantial) or to how/when Login.message is constructed (since that's where the "(New post)" link appears) (e.g., if it's getting now re-built after we've already set up the click event). Or both.

**Comment by cgolubi1** [comment]
Okay, i talked to Jota offline --- the upshot is that he doesn't understand why popstate is being triggered when someone clicks on the '(New post)' link, and he thinks that didn't used to happen.  So my next step is going to be to verify that assertion --- if popstate didn't used to be triggered and now is, that tells us one thing about what's changed (and we can figure out why it has changed).  If popstate was triggered before the refactor too and it didn't used to be a problem, that tells us a different thing about what's changed.

In either event, though, we think the remaining (performance) regression should not block the January release, but that we should try to root-cause it and push a fix during the merge freeze period.

**Comment by cgolubi1** [comment]
After more discussion: we think a better short-term fix would be, after the prod release, to do an explicit check for if state is null in Forum.showPage, and regen it from the URL if so, e.g.:
```
if (state == null) {
  state = {
    'boardId': Env.getParameterByName('boardId'),
    'threadId': Env.getParameterByName('threadId'),
    'postId': Env.getParameterByName('postId'),
  };
}
```

and revert the popstate bind function change.  Like i said, i don't have time to do that before the prod release without delaying it further, so unless we find a further regression, i'll do it afterwards.
