### ISSUE TITLE
it is 2016

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1892]
Update copyright dates.

**Comment by cgolubi1** [comment]
This is not a prod-blocker just because timing, but i want to patch it during the merge freeze period because it's a trivial fix and people will complain.

**Comment by yawetag** [comment]
Couldn't the code just insert the current year, rather than change it every
year?


Andrew Senger
asenger@gmail.com

**Comment by cgolubi1** [comment]
I'm sure it could, but i'm going to do the trivial fix for the January release.

**Comment by blackshadowshade** [comment]
We'll want to basically replicate the changes in #1503.
