### ISSUE TITLE
Create forum syntax to link other forum 

### ISSUE THREAD

**Issue by danlangford** [buttonmen-dev/buttonmen#1905]
let's add [thread=172] to the forum/chat syntax to more easily route people to new or old conversations. Like "we digress let's talk about that over here X" or "ya we had that discussion here X go review the arguments" 

It would allow me in game chat to say "go here X to learn about my tournament" or in a forum say "go here X to pick up a new UBFC fighter"

Also If we combo that with the ability to Pin or Sticky a post we can make a table of contents at the top of each forum: i.e. Adoptions, Golf, UBFC, how to help Dev

**Comment by irilyth** [comment]
#1008 is the ticket for pinned threads.

**Comment by nkmcalli** [comment]
+1
