### ISSUE TITLE
Trip vs Radioactive when the Trip Attack fails

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1919]
In http://www.buttonweavers.com/ui/game.html?game=9067, I made a Trip Attack against a Radioactive die, which failed, but my Trip die didn't split. On #1432, we concluded that it should split (and, at the time, it did).

**Comment by blackshadowshade** [comment]
I've reproduced this bug. Let me see if I can track down why it's happening.
