### ISSUE TITLE
Add a page listing all die skills

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1925]
There should be a page that lists all the supported die skills, their symbols and their descriptions.

(Created in response to #1924.)

**Comment by AdmiralJota** [comment]
Here's a mockup of what it might look like:

https://gist.github.com/AdmiralJota/43b1f3cfcc00ebbe8219

![bm1](https://cloud.githubusercontent.com/assets/5848173/12374283/d77e0a10-bc64-11e5-96db-72ffc00e4e4d.png)

![bm2](https://cloud.githubusercontent.com/assets/5848173/12374284/dd330384-bc64-11e5-98a3-15e51bd655f8.png)

[....]

![bm3](https://cloud.githubusercontent.com/assets/5848173/12374285/e1654084-bc64-11e5-80d5-f59009f3e407.png)

**Comment by AdmiralJota** [comment]
Some of the logic in https://github.com/buttonmen-dev/buttonmen/blob/master/src/ui/js/Buttons.js can be re-purposed here, particularly the code that generates the skills table (around lines 112-138). And we'll need new API methods to retrieve a list of all supported skills and to retrieve a list of all supported die types.

**Comment by blackshadowshade** [comment]
I'm going to close #1115 in favour of this.

**Comment by AdmiralJota** [comment]
Ah, thanks. I'd looked for an existing ticket, but I somehow missed it.

Any thoughts on the proposed mockup?

**Comment by dwvanstone** [comment]
When I think of the skills I expect them to be listed in alphabetical order by the symbol, not the skill name. (Since that's how I see the formulas.) [I suppose that could be a quick link under "Die Skills" (By Skill Name |  By Symbol).

Could it be interactive so when you click it the description show below, rather than displaying them all vertically? I'm not sure if I like having all of the skills printed out like that -- it's too tall. Even if you link to the item in the list it's very hard to read.

Since there are 42 skills...wouldn't you want to make it six rows of seven skills, rather than five rows of eight and one of two?

How about the interactions between the buttons? (Or would that be automatically generated as well?)

Otherwise, yeah! Fantastic! This will be great! I've wanted this page for a long time!!

**Comment by AdmiralJota** [comment]
> When I think of the skills I expect them to be listed in alphabetical order by the symbol, not the skill name. 

Hmm, interesting. What does everyone else think of that?

> Could it be interactive so when you click it the description show below, rather than displaying them all vertically?

In the mocked up HTML, each name and symbol is a link to that skill's description. They're still in a vertical list, but it scrolls you directly to the one that you clicked on. It looked OK to me that way, but I'm curious if other people who try the mockup agree with you. (You'll need the skills HTML and CSS files from the gist plus https://raw.githubusercontent.com/buttonmen-dev/buttonmen/master/src/ui/gui.css file from the main site to try it out.)

> Since there are 42 skills...wouldn't you want to make it six rows of seven skills, rather than five rows of eight and one of two?

It's dynamic: the number of rows will depend on the width of your browser window. I just happened to be testing it on a machine with a resolution that fit eight skills per row. Also, those are just the 42 skills I happened to notice that were implemented on production right now. There are definitely other known skills that haven't been implemented yet, not to mention the skills that will be invented in the future.

> How about the interactions between the buttons? (Or would that be automatically generated as well?)

If you mean interaction between skills, I think that gets automatically generated by the back end. I just grabbed the skill text off a handful of individual buttons, so it probably didn't have all the interactions listed. @blackshadowshade can probably confirm or deny that, since I think he implemented the code that generates the list of interactions.

**Comment by AdmiralJota** [comment]
Another thing I was wondering about opinions on: at the moment, all the die types (option, twin, swing, etc.) in their own alphabetical order after the skills. Do we think that's OK? Or should they be handled differently, such as being mixed in together with the skills alphabetically, or being a second "Die Types" list that comes after the "Die Skills" one?

**Comment by dwvanstone** [comment]
I hadn't tried downloading the mockup and interacting with it - it is nicer to interact with it.

I think it's perfectly fine, and would be a great improvement to the site as is. I tried fiddling with the css but didn't find anything that improved it very much. If you want to get fancy with javascript and only show the description that was clicked on that could be snazzy, but it's not important.

**Comment by AdmiralJota** [comment]
I've updated the gist with the UI part of the code for this. At the moment, it's just using the basic UI from the mockup, since that was quickest and simplest to implement. I also renamed the mockup HTML to skills-mockup.html, to differentiate it from the actual skills.html.

https://gist.github.com/AdmiralJota/43b1f3cfcc00ebbe8219

**Comment by dwvanstone** [comment]
It seems like Option dice is just as interesting a skill on a die as reserve or warrior. I wouldn't separate die types from the skills.  If we're referring to them all as skills on the website than perhaps they should all just be in alphabetical order on the help page. You might try alphabetizing them by character to see how they appear to you that way but both would work for me.

**Comment by irilyth** [comment]
I haven't looked at this yet, but there's a reason why Option, Swing, and Twin are a different kind of thing than a die skill -- they're more like die *types*, although I've forgotten what the term used in the code is, and if those are all of them.

I think we should differentiate between die types and die skills, anyway.

**Comment by irilyth** [comment]
Argh, clicked the wrong button, did not mean to close this. :^p

**Comment by AdmiralJota** [comment]
So that's one vote for combining them and alphabetizing them together, and one vote for splitting them completely?

**Comment by cgolubi1** [comment]
On Wed, 20 Jan, 2016 at 11:06:53 -0800, AdmiralJota wrote:

> So that's one vote for combining them and alphabetizing them together, and one vote for splitting them completely?

My vote would be for splitting die types from die skills.

Chaos

**Comment by dwvanstone** [comment]
> I think we should differentiate between die types and die skills, anyway.

Why? A swing die is a cool special thing that the die does. A berserk die is a cool special thing that the die does. Is it more like the die types are the nouns and the die skills are the adjectives?

**Comment by dwvanstone** [comment]
I think all the matters is that people can find the skill that they're looking for, and as long as they're all visually on one page it doesn't really matter much to me how they're organized. We can always fix it later if people complain.

**Comment by cgolubi1** [comment]
On Wed, 20 Jan, 2016 at 11:12:11 -0800, dwvanstone wrote:

> Why? A swing die is a cool special thing that the die does. A berserk die is a cool special thing that the die does. Is it more like the die types are the nouns and the die skills are the adjectives?

Nouns vs adjectives matches my sense of the distinction.  Definitely agree they should all be on the same page, but i think a sorting which groups swing, option, twin, and perhaps makes a note of simply fixed-sized dice like (10) will be helpful for people.

**Comment by blackshadowshade** [comment]
My vote is also to separate die skills and die types. The reason for this is the possibility that we will have a letter in the future that will serve as, for example, both a die skill and die swing type.

**Comment by dwvanstone** [comment]
Since the recipes are always in the form with the skills in front, open parens, die type, close parens...maybe you could show the die types on the page being in parentheses? That way they would look different from the skills.

![screen shot 2016-01-20 at 8 11 49 pm](https://cloud.githubusercontent.com/assets/6751265/12468475/154d9e32-bfb2-11e5-9971-2772df0f26d9.png)

**Comment by blackshadowshade** [comment]
That works well until we hit the "Descriptions" section, where everything is currently in parentheses. If we go this way (and I support the suggestion), then we would need to lose the parentheses in the Descriptions section.

**Comment by irilyth** [comment]
Cleaning out old mail... DVS had said:

> When I think of the skills I expect them to be listed in alphabetical order by the symbol, not the skill name. (Since that's how I see the formulas.) [I suppose that could be a quick link under "Die Skills" (By Skill Name | By Symbol).

I really like that idea, and perhaps also for the "should they be split into skills vs types" question. Given a bunch of things, you might want a couple of different ways to get a list of all the things, and making it easy to get each of those ways seems nice.

**Comment by jimmosk** [comment]
I just wanted to make sure this discussion includes a link to https://github.com/buttonmen-dev/buttonmen/wiki/Tester-guide:-supported-skills so the work I did for issue #256 doesn't get reinvented.

**Comment by blackshadowshade** [comment]
The new stub page skills.html is being created to hold this skill reference page.

**Comment by blackshadowshade** [comment]
The new stub page skills.html is being created to hold this skill reference page.

Linking to #1924.

**Comment by blackshadowshade** [comment]
Right, I'm working on this now. All the skills are showing correctly.

For the swing dice, should I summarise the swing ranges with the easy-reference table of maxima and minima that I've seen elsewhere? Or should there be separate descriptions for each swing type? I can imagine there would be issues for people with limited vision using screen readers, but otherwise, perhaps the table is easier to understand?

**Comment by dwvanstone** [comment]
> For the swing dice, should I summarise the swing ranges with the easy-reference table of maxima and minima that I've seen elsewhere? Or should there be separate descriptions for each swing type? I can imagine there would be issues for people with limited vision using screen readers, but otherwise, perhaps the table is easier to understand?

Perhaps the easy-reference table could be on the wiki page, but each swing type has its own separate description that links to that wiki page?
