### ISSUE TITLE
Game page should show correct recipe even after reserve dice are used

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1939]
http://buttonweavers.com/ui/game.html?game=9945 is completed, but it's showing my opponent's button recipe as "(6) (10) (20) (20) (6) (10) r(12) r(20)". The correct recipe is "(6) (10) (20) (20) r(6) r(10) r(12) r(20)"; the page is apparently being influenced by the fact that Oaktree had added two reserve dice during the game.

**Comment by cgolubi1** [comment]
Just a note --- while a game is in progress, i use the modified recipes in the sidebar as a quick shorthand for "which reserve dice has my opponent added so far?"  There are other ways to get that information (the activity log) and it isn't foolproof (you don't know what dice started as reserves unless you have the recipe basically memorized), but for my personal BM knowledge and use case, i find it helpful.

So the simplest possible solution to this issue (store an unmodified copy of the recipe and always display that in the sidebar) would degrade gameplay for me.

**Comment by blackshadowshade** [comment]
I was intending to fix this by resetting the recipe shown at the end of the game, not during an active game.

**Comment by cgolubi1** [comment]
> I was intending to fix this by resetting the recipe shown at the end of the game, not during an active game.

Great.  I have no objection to that.

**Comment by AdmiralJota** [comment]
That would solve most of my issue. If we come up with a good way to display both the original and the modified recipe during the game, then that would be even better, but I'm happy with the proposed solution as an improvement on the current behavior.

In the meantime: what do we think about making the recipes displayed during the game behave consistently with reserve and swing? (I.e., include the "(X=7)" bit if the X is currently set to 7.) I think it would make sense for the reserve and swing decisions to be handled the same way. It would also lead players to *expect* those recipes to be modified like this, so it's less confusing when they see them with the reserve dice unreserved.

**Comment by blackshadowshade** [comment]
The fix that I've submitted has both the current recipe and the original recipe being sent, so if we wanted to do any front-end changes to display both (if they're different), we should be able to do that very easily.
