### ISSUE TITLE
Add and playtest Zodiac button set

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1944]
Kaori is currently designing a new button set. We need to add this set, allow her to playtest it, and then decide when it's ready to go across to the live site.

**Comment by blackshadowshade** [comment]
The initial recipes (sent by email to me) are as follows:

Aquarius: (6) p(6) (8) s(12) (X)
Aries: (6) s(8) z(10) (20) (X)
Cancer: p(6) g(8) (8) (12) (X)
Capricorn: (6) g(6) (10) s(12) (X)
Gemini: (4,4) (12) (12) z(V) s(V)
Leo: (4) (6) p(10) z(20) (X)
Libra: (4) g(4) (8,8) z(8,8) (V)
Pisces: (4) p(8) z(12) (12) (X)
Sagittarius: (4) (4) s(8) p(12) (X)
Scorpio: g(6) (10) (12) p(20) (V)
Taurus: g(8) (10) (20) s(20) (V)
Virgo: (4) g(8) z(12) (20) (V)

**Comment by blackshadowshade** [comment]
Yet to come: images and flavour text.

**Comment by jimmosk** [comment]
So far I've found these to be fine buttons, fairly evenly matched. Some of the poison ones like Sagittarius, seem to be a little more powerful, but every set has some variation that way, so I, at this midway point in the playtesting month, don't see any reason not to sign off on Zodiac.

**Comment by blackshadowshade** [comment]
Okay, this is finished. Closing this issue.
