### ISSUE TITLE
Morphing + Speed/Berserk/Rush

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1956]
Sorry - I hit "enter" and that created this too quickly. Hang on.

**Comment by irilyth** [comment]
We've talked about this before -- if you can easily track down some of the prior thoughts about it, that'd be cool, if not I can look around too. Forum posts and IRC logs are likely possibilities.

**Comment by dwvanstone** [comment]
Argh - I hit enter at the wrong moment, my browser took that as a command to create this issue, and have been trying to figure out how to close or destroy this issue since. 

I know we've discussed this and I was trying to find the former issue or forum message since. My apologies.

In the meantime, the discussion in #91 has changed some of the thinking of this. One of the suggestions was to "add up the sides" when morphing or "multiply the sides" or some other theory, but if morphing also takes on the die type then those are now excluded as possibilities. But I'd really like to just close this issue and keep searching for the previous discussion.

**Comment by dwvanstone** [comment]
Josh helped me find the original discussion in the Forum:

http://www.buttonweavers.com/ui/forum.html#!threadId=249

The discussion there led to some theories as to what could happen:

(1). Nothing. 

The morphing die doesn't change size or type, in theory because it can't decide which one to copy.

(2). Takes the die type & size from the leftmost die.

This is what the original site die. (Well, my memory was that it took the size but not the type.)

(3). Takes the die type & size from the rightmost die.

This fits my brain pretty well - it morphs into each die, from left to right, and ends up with the type & size of the rightmost die.

(4). Allow the user to pick which die size & type it morphs into.

This might work in a live game with actual dice, but it's not worth adding a UI page just for this rare case.

(5). Pick a die randomly from the set.

That would be fun, although folks tend to prefer deterministic results. 

(6). Create a new die type/size out of all of the dice: either an n-dimensional die, the sum of all of the sides,  the average of all of the sides.

This won't work since morphing should also copy the type of the die (Wildcard, swing, twin, etc.)


Because this is such a rare case and could only happen with the current buttons if we include "morphing" on RandomBM dice, I'd go for whichever is easiest to code between 1, 2, & 3 above.

[I like morphing dice so I'm hoping it can join the other skills on a RandomBMMixed at some point.]

**Comment by irilyth** [comment]
I still like (6) the best, but don't feel strongly about it. As to

> Because this is such a rare case and could only happen with the current buttons if we include "morphing" on RandomBM dice, I'd go for whichever is easiest to code

I think we do want to add Morphing to RandomBM buttons, and I personally play a lot of RandomBM games, so I definitely feel like this is something that's likely to affect games that I play, and isn't just a theoretical exercise. That doesn't necessarily make it more common than "rare", but I think it's more like "unusual" than like "vanishingly unlikely".

**Comment by irilyth** [comment]
This has come up again in the context of Rush dice.

**Comment by blackshadowshade** [comment]
Okay, just so I remember for the future, this issue is about what happens when a die has both Morphing and Speed/Berserk/Rush, where more than one die is captured.

**Comment by irilyth** [comment]
Mostly, but with the advent of Rush, it's also about what happens when my Morphing die captures two of your dice, one or more of which has Rush.

**Comment by irilyth** [comment]
That part came up here: http://www.buttonweavers.com/ui/forum.html#!threadId=605&postId=11790

**Comment by blackshadowshade** [comment]
So, Daefaroth's suggestion on the forum thread is to change

    "When a Morphing Die is used in any attack, it changes size, ..."

to

    "When a Morphing Die is used in any attack against a single target die, it changes size, ..."


We have support by four other players, and I think this makes sense. I'll wait another day until we hear from other players, but I'll start investigating how to implement this.
