### ISSUE TITLE
Chance interaction with Mighty/Weak isn't documented

### ISSUE THREAD

**Issue by jbscare** [buttonmen-dev/buttonmen#1966]
If you use chance to reroll a die that also has Mighty or Weak, the die changes size, but the skill help text doesn't mention this interaction, and at least one player was surprised by this.

**Comment by irilyth** [comment]
That was me, from my work account by mistake. Sigh.

**Comment by jimmosk** [comment]
The Game Activity text should also make this explicit. I just chance-rerolled a Mighty die in game http://www.buttonweavers.com/ui/game.html?game=34278 and, while the die got bigger, the Game Activity text only refers to the rerolled die's initial size, not its size change. ("(2018-03-28 14:06:09) | jimmosk rerolled a chance die, but did not gain initiative: GHc(6) rerolled 4 => 6")
