### ISSUE TITLE
Add and playtest Steven Universe button set

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1978]
I've created a set of button recipes themed off of the Steven Universe television show, and @Hurtay has created images for them. The SQL for the recipes is at https://gist.github.com/AdmiralJota/68df2efb27411f22a4c4a0ccc0867f0b. Once the Turbo skill has been implemented, I'd like to test these recipes out on the dev site.

Blocked by  #91.

**Comment by dwvanstone** [comment]
Ooh, cool! They will be fun to test!

**Comment by irilyth** [comment]
There are already buttons named Pearl and Lion, so those names will need to be different in some way. (Or we'll need to switch to a model whereby buttons are uniquely identified by set+name rather than just name, but I bet no one wants that.)

**Comment by AdmiralJota** [comment]
I suppose these two could have their names suffixed with "(SU)" in the database.

**Comment by blackshadowshade** [comment]
So that I don't forget when I create a pull request for this, the swing dice need to be wrapped in parentheses too.

**Comment by AdmiralJota** [comment]
And here are the images that Kaori has created: https://www.dropbox.com/s/ml7nqojy1t58obp/StevenUniverseButtonImages.zip?dl=0

**Comment by blackshadowshade** [comment]
Those are some good looking images!

**Comment by AdmiralJota** [comment]
Here's the flavor text to go with those buttons, in case anyone would like to look it over and make comments/suggestions:

* Garnet is current leader of the Crystal Gems which she originally joined in order to live in a place where she was free to be herself. Garnet's weapon is a pair of massive gauntlets ideal for beating people up.

* Amethyst is a member of the Crystal Gems who was created in the Kindergarten on Earth. She has never been to the Gem Homeworld and considers the Earth to be her home. Amethyst can summon a multi-tailed whip with which to beat people up.

* Pearl is a member of the Crystal Gems. She was one of Rose Quartz's closest followers in the rebellion against the Gem Homeworld and her sole confidant. Pearl wields a magic spear with a spiral blade that she uses to beat people up.

* Rose Quartz was the founder and original leader of the Crystal Gems before she gave up her physical form to become Steven's mother. She led her friends and allies in a rebellion against the Gem Homeworld over 5,000 years ago to protect the Earth from invasion. Rose Quartz was a natural leader, inspiring those around her to her beat people up.

* Peridot is a Homeworld Gem technician and certified Kindergartener who became stranded on Earth and was forced to cooperate with the Crystal Gems. She prefers to wear limb enhancers to augment her height and reach, all the better to beat people up.

* Lapis Lazuli is a Homeworld Gem who was trapped in a mirror for thousands of years until being freed by Steven. She does not trust the Crystal Gems or the Homeworld Gems. She has immense power over water, easily controlling it, reshaping it and using it to beat people up.

* Jasper is a Homeworld Gem who was a veteran of the rebellion and fought against Rose Quartz. She returned to Earth to retake it from the Crystal Gems. Jasper's crash helmet is designed to be used for headbutting her enemies, her preferred way of beating people up.

* Steven Universe is a member of the Crystal Gems and the son of Rose Quartz and Greg Universe. He is the only human/gem hybrid in existence, and his full abilities and potential are yet to be discovered. Steven prefers to use his powers to defend and protect his friends with magical shields while they beat people up.

* Greg Universe, a.k.a. "Mr. Universe", is a human being, a retired rock musician and the father of Steven Universe. He owns the local car wash and lives out of a van because all of his money goes to support Steven and the Crystal Gems. He's wary about "Gem business" but would do almost anything to support Steven, even beating people up.

* Connie Maheswaran is a human being and the best friend of Steven Universe. She is introverted, curious and intelligent. Connie has become adept at fighting with Rose Quartz's sword, pairing with Steven in a complementary combination of defense and offense to beat people up.

* Lion is a giant magical pink lion. Presumed to have originally have a creation of Rose Quartz, Steven now considers him to be his pet. Lion can create portals to travel across vast distances, has a pocket dimension hidden in his mane, and can use his roar to shatter objects and beat people up.

I've also updated the gist.

**Comment by dwvanstone** [comment]
Some typos:

Rose Quartz "inspiring those around her to **her** beat people up"
Lion: "Presumed to **have** originally **have** a creation of Rose Quartz"  (needs "been"?)

Can't wait to play them!

**Comment by AdmiralJota** [comment]
Thanks -- neither can I!

**Comment by AdmiralJota** [comment]
Once we've finished a moderate amount of initial testing, I'd like to revise some of the recipes that seem unbalanced and have a Round Two to see if the new recipes are sufficient improvements.

When that happens, would anyone object to A) adding the new recipes to the dev database as separate buttons (with names like "Connie 2"), to make it easier to keep track of their stats, and B) possibly doing some A/B testing of some recipes (such as adding both "Rose Quartz 2A" and "Rose Quartz 2B" as separate recipes) to work out which versions works best?

**Comment by cgolubi1** [comment]
Yeah, i have no problem with you adding as many test recipes as you like to get the testing job done.
