### ISSUE TITLE
Add option for email notification

### ISSUE THREAD

**Issue by blinkingline** [buttonmen-dev/buttonmen#1984]
It would be nice to have a user-configurable e-mail reminder/notification system.  By default, if a player has moves to make, they would get an email once a day reminding them. If the player has no moves in active games, they would not receive an email that day. 

Ideally, the interval at which these emails are sent could be configured based on what time the player wants to receive the email and/or how often they should receive the notifications twice a day, once a day,  once a week, etc.

**Comment by irilyth** [comment]
This seems substantially similar to #251 -- if that seems like it mostly covers what you have in mind, maybe add a comment with anything it *doesn't* cover, and close this one? Unless you think this one is substantially different, in which case maybe explain more. :^)

**Comment by blinkingline** [comment]
Agreed, this is similar enough to 251.
