### ISSUE TITLE
the UI should retry POST requests

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1988]
When the UI POSTs to an API method and gets a timeout or other evidence that the message didn't actually make it to the server, it should retry.

Note: in order for this to be a good idea, we'll need to make all API methods correctly idempotent, i.e. make them do something reasonable if the first request actually did succeed and it's just that the response was lost.  So this may take a bit of doing.  However, the short-term fix of only retrying read-only API methods like loadGameData would still reduce user pain substantially.

**Comment by jl8e** [comment]
I have JS that does this. In addition to trying to make requests not a problem if repeated, I also include an additional header that the back-end can use to identify a duplicate request. The back-end code isn’t useful (it’s Python/Django), but the JS probably is, though it’ll need some untangling from the rest of the JS library I accreted.

**Comment by blackshadowshade** [comment]
It might even be enough if you showed us an example of how this works, without bothering to untangle it, if that's more immediately convenient for you, Julian.

**Comment by jl8e** [comment]
Possibly, though it was long enough ago that I have to reread it to try to understand how it works :)

Having looked it over, it’s not actually all that entangled. There’s some utility calls to the rest of the library, but only one (callAll()) looks critical. I’ve attached the utility module as well.

It works through jQuery’s ajaxPrefilter, automatically replacing all the callbacks with ones that know how to handle retrying. It can be disabled for any given request by adding retry: false to the ajax options.

[retry.txt](https://github.com/buttonmen-dev/buttonmen/files/258389/retry.txt)
[util.txt](https://github.com/buttonmen-dev/buttonmen/files/258397/util.txt)

**Comment by jl8e** [comment]
Just to note: this code has not yet been used in production. There are tests (Quinit, depending on [mockjax](https://github.com/jakerella/jquery-mockjax) )

[retrytest.txt](https://github.com/buttonmen-dev/buttonmen/files/259654/retrytest.txt)

**Comment by cgolubi1** [comment]
I think things have changed in the underlying infrastructure and context sufficiently in the past 7 years that it is no longer useful to have this issue open.  I definitely would encourage people who see retryable failures on the site to open issues with what you're seeing now, and we can revisit starting from the present.
