### ISSUE TITLE
Problem attempting to gain initiative when there are buttons with Focus and Chance

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#2043]
http://dev.buttonweavers.com/ui/game.html?game=2454

I have a random button with a Chance die, a Focus die, and a Chance And Focus die.  I'm trying to gain initiative by rerolling the first of those by rerolling the last of those, and turning down the other two, and it gives me the error message: Bad value specified for chance action - choose "reroll"

Which I suspect means that, because that last die also has Chance, the fact that it also has focus is being ignored, and it expects me to set that die to Reroll (even though I already set the Chance die to Reroll).

![screen shot 2016-06-13 at 5 59 31 pm](https://cloud.githubusercontent.com/assets/6092544/16024765/816706fc-3191-11e6-8d1e-ce0ac2d3cc99.jpg)

(The pulldown-menu values for both dice with Focus reset to their current ones when it presents this error message, although it allows to Chance die's pulldown menu to remain at Reroll...)

**Comment by jimmosk** [comment]
Looking at it some more, I see it's asking me to choose between Take No Action, Turn Down Focus Dice, OR Reroll One Chance Die.  Am I just wrong to think I should be allowed to do both?

**Comment by cgolubi1** [comment]
On Mon, 13 Jun, 2016 at 15:09:42 -0700, Jim Moskowitz wrote:

> Looking at it some more, I see it's asking me to choose between Take No Action, Turn Down Focus Dice, OR Reroll One Chance Die.  Am I just wrong to think I should be allowed to do both?

Yeah, our implementation is that you can only take one action during REACT_TO_INITIATIVE, so if you have both focus and chance as options, you have to pick one.

**Comment by irilyth** [comment]
> Yeah, our implementation is that you can only take one action during REACT_TO_INITIATIVE, so if you have both focus and chance as options, you have to pick one.

I think that's consistent with how the old site did it.

The help text says that you may choose "either skill" to gain initiative; it doesn't say that you can't choose both, so maybe changing that to "one skill or the other" or "either skill (but not both)" or something would be good?

**Comment by jimmosk** [comment]
Okay, a second aspect of the same situation:

You are presented with the opportunity to turn down Focus dice only when that will actually enable you to gain the initiative.  You are presented with an opportunity to reroll a Chance die even if there is no way it could result in you gaining initiative.

So on the above screen, when the focus dice cannot give me initiative (note that one is also Trip, and doesn't count towards initiative)... why am I being presented with "Turn down focus dice" as one of my options?  Shouldn't "Reroll once chance die" be the only option in that pulldown menu (aside from "Take no action")?

**Comment by cgolubi1** [comment]
On Wed, 15 Jun, 2016 at 15:24:05 -0700, Jim Moskowitz wrote:

> So on the above screen, when the focus dice cannot give me initiative (note that one is also Trip, and doesn't count towards initiative)... why am I being presented with "Turn down focus dice" as one of my options?  Shouldn't "Reroll once chance die" be the only option in that pulldown menu (aside from "Take no action")?

I agree --- that's a legitimate bug report.  Probably not a high priority one (we'd have to change the API so the backend could tell the frontend what initiative actions were valid, so it's not completely trivial), but i think modulo priority it's desirable.

**Comment by cgolubi1** [comment]
The thing we decided is a bug here is what was reported in #1515 - so i'm going to close this one, because that one has the description of what's needed for the fix in it.
