### ISSUE TITLE
UI test test_OpenGames.buildGameTable() hangs on a non-fresh database

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2049]
The UI test `test_OpenGames.buildGameTable()` hangs if you run tests twice using the same buttonmen_test database.  At a glance, the underlying cause is a later open game which is created using a button which isn't in the `test_OpenGames.buildGameTable()` set of hand-coded button information.

**Comment by cgolubi1** [comment]
It's easy to work around this by just rebuilding the test database between test runs, and of course that's what jenkins does, but it's worth fixing.

**Comment by blackshadowshade** [comment]
Yeah, I've noticed this, but I thought I was just doing something wrong on my branch. This bug is highly disruptive for my development workflow, so I second getting this fixed sooner rather than later. And if I introduced the problem, I'd love to know what I did wrong.

**Comment by cgolubi1** [comment]
Nah, i'd bet money i introduced it when i did the bulk migration of responder/UI tests.  I'll fix it, and sorry!
