### ISSUE TITLE
Offer the option to reject a game

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#205]
When another player challenges you to a game, you should be able to reject it. (Ideally with an accompanying message explaining why.)

**Comment by blackshadowshade** [comment]
Just an update on this: I've got a branch now with BMInterface functions and database accessors, and this shouldn't change any current behaviour. Once I've tested a little, I'll issue a pull request for this.

**Comment by cgolubi1** [comment]
This is my best bet for BFotM (whether or not i also get a TDotM pick).  Letting people reject games is both the best way to square the uses of the site between people with different attitudes towards cheese buttons, and the currently-active step in changing the pre-start-of-game logic, which i think is a prereq for things like tournaments and different kinds of open games.

**Comment by cgolubi1** [comment]
After discussion with shadowshade, apparently there's no API work left to do on this, so never mind.

**Comment by blackshadowshade** [comment]
So, I've been thinking about this, and this is what I reckon would be easiest:

1. On the Overview page, a new section right up the top called New Games, containing the following information:
- Game number
- Game description  (this would begin to address issue #1508)
- Your Button
- Opponent's Button
- Opponent
- Some sort of accept/decline selector (should this be two buttons?)

2. Ensure that the Next Game link at the top ignores proposed but unaccepted games.

3. Make sure that there is some sort of acceptable placeholder page if someone manually tries to view a proposed game.

What do you think?

**Comment by blackshadowshade** [comment]
Oh yes, there would also be a new user preference to autoaccept games, default TRUE.

**Comment by irilyth** [comment]
I don't have strong feelings about this, but an alternative: Have them show up in the overview just like games in progress, but on the *game* page, display information about the game including the option to accept or reject it.

One thing I like about that is that you can put all kinds of information there, including the full button recipes, potentially even let people chat about the game before they accept or reject it (which would let you say "who are you and why did you challenge me" and await a reply, or "no thanks I have too many games now" so the other person knows why you rejected it, etc), and so on, with no worries about "but it has to be compact and unobtrusive on the overview page".

**Comment by blackshadowshade** [comment]
Did you miss the word placeholder?  :p 

Again, the idea is to make this change as minimal as possible, to ensure that I can actually get it working.

**Comment by blackshadowshade** [comment]
I have nothing against the placeholder evolving over time, but initially, I think that it should be extremely simple, perhaps something like: Game 20000 hasn't started yet.

**Comment by cgolubi1** [comment]
Yeah, i think the real question is whether the accept/decline should be on the Overview page, or on the game page.  Arguably, it should eventually be both, the way you can dismiss games from either the Overview or the game page.  So might as well start with whichever is easier.

**Comment by irilyth** [comment]
> Did you miss the word placeholder?  :p 

Heh, sure. But I thought that by that you meant something like a one-line page saying "this game hasn't started yet, go the Overview page (with a link there) to accept or reject it"; and the interface to actually accept or reject would be integrated into the overview page.

What I'm suggesting is to put the accept/reject interface into the "placeholder" page. If that's what you had in mind, then we're saying the same thing. :^)

**Comment by blackshadowshade** [comment]
I think we're all on the same page, in that we'd like it eventually in both places.  :)  I'll be starting out with it on the Overview page, though.

**Comment by irilyth** [comment]
> What I'm suggesting is to put the accept/reject interface into the "placeholder" page. If that's what you had in mind, then we're saying the same thing. :^)

To put it another way, since I gather that no one likes new pages, what I'm suggesting is to integrate the accept/reject interrace into the existing game page, rather than existing overview page. Minimal changes to the overview page, more substantial changes to the game page, rather than vice versa.

My somewhat uninformed prediction is that about the same number of things would need to change either way. I think that changing the game page gives you more flexibility (either immediately or in the long run) and a nicer user experience.

**Comment by irilyth** [comment]
Ok, I guess you've made up your mind. I'll let you know what I think when I see it.

**Comment by blackshadowshade** [comment]
It's not that I don't like new pages, but rather that the logic to create them is rather complex, far more than altering an existing page like the Overview page.

**Comment by irilyth** [comment]
Yep, I get that you don't want to create new pages.

I predict that it'll be hard to cram all the information that you want into the overview page. (Where would you put the game description? The button recipes?) I think it'd be trivial to put all the information that you want into the game page.

**Comment by irilyth** [comment]
To put that another way all the information that you need to accept or reject a game is already on the existing game page. If you want to put that information on the overview page, you have to figure out where to add it to the page. If you put it on the existing game page, the information is already there. That seems like a much simpler change.

-Josh (from my phone)

**Comment by dwvanstone** [comment]
I just wanted to see what this all would look like. (We need to keep in mind what the invitee sees as well as the invited, of course!)

Jimmosk invites me to a game:

![screen shot 2015-09-20 at 11 49 40 am](https://cloud.githubusercontent.com/assets/6751265/9981518/b953aff6-5f8d-11e5-8d4a-9b1e8237cd3a.png)

[I'm not suggesting the blue, I was just playing.] On Jimmosk's screen maybe he sees the game in the New Game section as well with a Accept/Reject status of "Waiting for Opponent". If I never accept the game eventually it falls into the "Stale Game" category. If I do reject the game the Accept/Reject status becomes "Rejected (_dismiss_)" or something allowing Jim to remove it from display.

Inside the game itself, I would see something like:

![screen shot 2015-09-20 at 12 11 53 pm](https://cloud.githubusercontent.com/assets/6751265/9981668/1ff20d54-5f91-11e5-8937-f185f091397a.png)

[This is slightly modified from the auxiliary die screen.]

Jimmosk would see something similar, like "Please wait for your opponent to decide whether to accept this game." If I have already rejected the game it could say "Your opponent has rejected this game" with the option to dismiss the game.

I like the idea of a preference for this, defaulted to "auto-accept". Down the line maybe there would be a list of users who are in the "auto-accept" list.

I think your idea of a first step of just implementing the Overview page changes and allowing the user to simply view the game [and not accept/reject there] is fine. I don't think you need to worry about adding the description in overview if the user can view the game itself.

**Comment by dwvanstone** [comment]
[I updated the previous post with a new screenshot of the second game to include a description.]

**Comment by blackshadowshade** [comment]
I'm thinking that games that are never accepted or rejected do not ever become stale. Instead, the game creator should have the ability to cancel a game that has never been accepted---this also means that if the creator makes a mistake during game creation, the game can then be cancelled.

**Comment by irilyth** [comment]
One easy way to do that: Have the game look similar to both players, such that either of them can click "reject" and have the right thing happen.

(And you could also use the same interface for "third party" games, which I could certainly make use of for UBFC and Mad Robin things, i.e. I create a game that you and DVS both have the option to accept or reject.)

**Comment by dwvanstone** [comment]
> I'm thinking that games that are never accepted or rejected do not ever become stale. Instead, the game creator should have the ability to cancel a game that has never been accepted---this also means that if the creator makes a mistake during game creation, the game can then be cancelled.

Just so I understand...you only will have the ability to cancel a game creation if your opponent has the preference for autoaccepting games set to FALSE, right?

**Comment by irilyth** [comment]
My recollection of the old site is that there was no auto-accept, and I think that worked fine. Do we need auto except here?

-Josh (from my phone)

**Comment by blackshadowshade** [comment]
Remind me, what did the old site offer here? Was it possible to reject a game? I ask because I genuinely don't remember, and I don't think that I would have ever rejected a game anyway.  :)

**Comment by dwvanstone** [comment]
I don't really remember the old site that well any more. I believe it required you to accept or reject an invitation. I know that other gaming sites I've been on always required accept/reject of an invitation. I recall the old site had the concept of Buddies, people who you've designated as your friends in the site. Maybe there was an auto-accept from your Buddies list option? I really don't remember.

Josh: is your suggestion that player A create a game between player B and player C (which they both have to accept to continue) a separate RFE somewhere? It does seem like a useful feature for someone running a series.

**Comment by irilyth** [comment]
Yeah, I don't really exactly what the UI on the old site looked like, but I'm pretty sure that when someone challenged you to a game, if you didn't want to play it, you could reject it (or maybe "delete" it, I don't recall). I don't think Battle Buddies auto-accepted games, but, meh.

I don't think there's a ticket for third-party game creation yet; I think it depends on this ticket, so I hadn't bothered yet.

**Comment by blackshadowshade** [comment]
So, I'm working on this at the moment, and there are a number of things I'm probably putting off for the future:
- some display of rejected games and/or a notification on the Overview page (they are currently rejected silently)
- ability to show rejected games on the History page (they are currently ignored completely)
