### ISSUE TITLE
Comment on new die backgrounds

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2070]
Die backgrounds were introduced in #2055. Here's a place where we can comment on them.

To start the ball rolling, I have the impression that the numbers are slightly below the midline in the case of the symmetric images, as viewed on Firefox.

**Comment by blackshadowshade** [comment]
This also appears to be the case with the circle and the realistic images.

**Comment by blackshadowshade** [comment]
On Chrome, this appears to be less of a problem, if at all.

**Comment by blackshadowshade** [comment]
The tops and sides of the circles appear to be partly transparent in Chrome and Firefox. I presume this has something to do with antialiasing or scaling?

**Comment by Hurtay** [comment]
Both in Firefox and Safari (ipad) the numbers in the new dice-shapes are as off-center as the numbers in the circles always have been before. 
So far I can't see the transparency in the circles.
At home I already got different opinions about which shapes look the best and are easiest to recognize. So it's a good thing we decided for user preferences.

**Comment by AdmiralJota** [comment]
I think the images _themselves_ are off-center with each other. For instance, this is what I'm seeing in Firefox for http://dev.buttonweavers.com/ui/game.html?game=2481:

![bm1](https://cloud.githubusercontent.com/assets/5848173/16733222/ae82a13c-474e-11e6-94ba-8f06e2a2113b.png)

The tops of the images line up, but the bottoms don't. E.g., the bottom of the 4-sided die is notably higher up than the bottom of the 8-sider next to it.

The images should be aligned so that they're all vertically centered within their 72px canvases; shorter images should have empty space at both the top _and_ the bottom, not just the bottom.

**Comment by Hurtay** [comment]
I don't see an easy way to change the images as you suggested. But feel free to try it yourself. I'm curious to what you'll come up with.
Right now they use up the space of their canvases as much as possible without having to change the shape. 

In your example the bottom line of the d4 is the maximum width. I could move the whole shape down but then the number would not even be readable any more since it's too high up in the shape. The die shape might be centered then but the number IN the die would be even less centered. 
The same with the d8: both diameters are the maximum possible size. If you'd like to move it up or down you'd have to decrease the size of the whole die shape. And I don't expect this to solve the original problem of easier size recognition.
And if you'd like all dice to have the same top line AND bottom line some of them would be really out of shape, i.e. the d4 which would look more like an A instead of an isosceles triangle.
What do you think?

**Comment by blackshadowshade** [comment]
I don't have any problem with the images as they are, I just think that the numbers should be a tad higher (perhaps 2 or 3 pixels) on Firefox.

**Comment by blackshadowshade** [comment]
Thinking a little more on this, I'm pretty sure that we want the centre of gravity of the image to be centred on the midline. I think that there is certainly room for discussion regarding relative sizes, but there's no way that we're going to be able line up both the tops and bottoms of all the die images, since some are top-bottom symmetric, while others are not.

**Comment by irilyth** [comment]
I think that what Jota was suggesting was that the dice should be aligned vertically by the centers, rather than their tops or bottoms, but I don't know for sure. I didn't notice, and didn't think about it until Jota mentioned it, and don't have a preference myself -- it might be nice to look at top-aligned, bottom-aligned, and middle-aligned, and compare them, if it's easy to do that?

**Comment by irilyth** [comment]
My own feedback is that they generally look ok, but I'm not used to them, so I have to think about it more when I see them, because I'm not intuitively used to seeing them and immediately thinking "oh that's a 12-sider" or whatever. I expect that'll come, and I like the look and feel overall.

**Comment by AdmiralJota** [comment]
I did mean that they should be aligned by their centers, but if you're saying that wouldn't work in cases where one end of the die is much wider than the other, then I think @blackshadowshade's suggestion of lining them up by their center of gravity makes more sense.

**Comment by blackshadowshade** [comment]
So, I've printed out the image above, and added the centres of gravity, along with help lines to make it clear how they were derived. I am satisfied that the image centres of gravity are correctly lined up with each other.

![cog](https://cloud.githubusercontent.com/assets/2898401/16789191/be1ddc50-48ee-11e6-82ee-1344f3296c1b.png)

**Comment by AdmiralJota** [comment]
I stand corrected.

**Comment by blackshadowshade** [comment]
From the dev site, devious said:

I'm trying symmetric.

It's going to take a while to get used to. I find my brain is having a hard time telling what to do with all of the new information. I may have more to say once I get used to it.

On Safari 9.1.1 on Mac the box appears too high on the 6-sided dice so the number doesn't look symmetric top to bottom.

I really like how the captured die appears in black. That looks nifty.

**Comment by blackshadowshade** [comment]
Does anyone have any insight into the different vertical alignment that appears between Chrome and the other browsers?

**Comment by irilyth** [comment]
devious suggested that the symmetric die images looked better if the showing-value was a smaller font size, and I agree. Compare the normal size:

![bm1](https://cloud.githubusercontent.com/assets/4923138/16851640/6ea1c738-49d2-11e6-975f-fe7b9c1da553.png)

One level of "zoom out":

![bm2](https://cloud.githubusercontent.com/assets/4923138/16851659/83db844a-49d2-11e6-8bc5-943e7d8acf58.png)

I don't want to just "zoom out", though, because the *other* text on the site seems like a good size to me.

Should we make the showing-value font size smaller when the symmetric die images are used?

Or perhaps, somewhat more work, have a user preference for scaling the showing-value font size, so people can fiddle with it however they personally like?

**Comment by blackshadowshade** [comment]
I think we could just make the showing-value font size generically smaller for all die backgrounds, and that would work. I don't know that it makes that much difference for the circle background, and the realistic images suffer from much the same problem.

**Comment by irilyth** [comment]
> I think we could just make the showing-value font size generically smaller for all die backgrounds, and that would work. I don't know that it makes that much difference for the circle background, and the realistic images suffer from much the same problem.

Sounds fine to me.

**Comment by cgolubi1** [comment]
The proposed change seems okay to me too.

**Comment by dwvanstone** [comment]
I have a (4,4) twin dice which is showing up as an 8-sided die background. That doesn't seem ideal, although it does function okay. Perhaps it could look like a 4-sided die with a 4-sided die right behind it with some kind of shadow effect? What do others think?

**Comment by blackshadowshade** [comment]
I think that the issue of twin dice may not be trivial to solve, especially since some buttons have twin dice with unequal sides, e.g., Anti-Llama.

**Comment by dwvanstone** [comment]
Ah yes, Anti-Llama. It would have been better if twin dice had to be the same size. Okay, I retract the suggestion of a shadow effect. I don't have a good solution for this, and I haven't played enough for the shapes to all be come intuitive. I suppose thinking of a (4,4) as a modified 8-sider isn't too bad....

**Comment by blackshadowshade** [comment]
So, it seems that it might be possible to turn off antialiasing for the die background images, which might remove the blurring that we're seeing.

http://stackoverflow.com/questions/14068103/disable-antialising-when-scaling-images

**Comment by blackshadowshade** [comment]
Okay, those solutions didn't work. Our problem arise because we have the background images at a native size of 72 px by 72 px, and we're scaling them to 49 px by 49 px. That means that the single pixel edges are being scaled to 0.68 px edges, which are apparently displayed as single pixel edges with 68% opacity.

**Comment by blackshadowshade** [comment]
I've tried replacing the circle background image with this 49 px by 49 px image

![d4active](https://cloud.githubusercontent.com/assets/2898401/17283864/a55f428a-57f8-11e6-9bbf-44c26b2fff8a.png)

but the end result is arguably worse that what we currently have. Below is a screenshot where the d4 images have been replaced.

![capture](https://cloud.githubusercontent.com/assets/2898401/17283923/34a56c58-57f9-11e6-9808-f77ab3a826ad.PNG)

**Comment by blackshadowshade** [comment]
The next obvious choice is to create a circle background image that is 98 px by 98 px with a two-pixel width border:

![d4active](https://cloud.githubusercontent.com/assets/2898401/17283996/e2ed3e26-57f9-11e6-8d6f-ce9927adb6a5.png)

This gives a pretty good end result (again, the d4 images have been replaced):

![capture](https://cloud.githubusercontent.com/assets/2898401/17284000/ef8a2bee-57f9-11e6-8364-c3a293c8413d.PNG)

**Comment by blackshadowshade** [comment]
The next step up (147 px by 147 px, three-pixel width border)

![d4active](https://cloud.githubusercontent.com/assets/2898401/17284054/a18f3410-57fa-11e6-82d4-fcfa6de330b5.png)

gives the following result:

![capture](https://cloud.githubusercontent.com/assets/2898401/17284063/b85d632e-57fa-11e6-9131-39c7aa0bc722.PNG)

**Comment by blackshadowshade** [comment]
So, what do you all think?

**Comment by Hurtay** [comment]
Somehow even the last 3px-version looks a bit blurry to me when scaled down. So I would expect the die shaped images to do the same. 
Why are they scaled down anyway? Originally you asked for 72x72 images so I thought that's the size we're using. Or is this too big? Maybe the die images should all be 49x49 then so they don't need to be scaled at all?
The version we're using right now isn't blurry. Which size is this?

**Comment by cgolubi1** [comment]
Can someone summarize where we are on this issue?  Do we think the
blurry die images are a prod blocker (i.e. we should delay the prod
release and sort them out), or should we go ahead?

Sorry if the answer to this question should be obvious --- it is not
obvious to me, and i need to know.  :>)

Chaos

**Comment by blackshadowshade** [comment]
@Hurtay, the issue is that different browsers scale images down differently. The screenshots above come from Chrome, where the blurriness is most noticeable, to my eye.

Regarding using 49x49 images, I think that the end result is not really acceptable---that was the first screenshot that I posted above. Personally, I think that we're going to need a larger image that gets scaled down, so that the pixellation is less pronounced.

@cgolubi1, I don't think that the issue is a prod-blocker, but if people are happy with either of the two solutions that I proposed, I can get a pull request in to replace the circles, and we can work on getting differently-sized images for the rest at a later date.

**Comment by cgolubi1** [comment]
On Mon, 01 Aug, 2016 at 16:01:19 -0700, James Ong wrote:

> @cgolubi1, I don't think that the issue is a prod-blocker, but if people are happy with either of the two solutions that I proposed, I can get a pull request in to replace the circles, and we can work on getting differently-sized images for the rest at a later date.

Okay.  IMO we shouldn't approve a new pull and put it in prod without
testing in dev at all, for this kind of visual thing where the unit
tests don't really give us any information.  So if i'm doing a release
tomorrow morning, let's go with the code we have right now.  (Or we can
delay the release.)

**Comment by irilyth** [comment]
I'm missing something. If the target image size is 49 x 49, why don't we just want 49 x 49 images? Why do we want to be scaling images down from a larger size?

**Comment by blackshadowshade** [comment]
@irilyth, see the image above, which uses the 49x49 px image. It's comparatively more pixelated than either of the other two images.

**Comment by blackshadowshade** [comment]
Oh, I should also address why we can't just antialias the image itself. The inside of the line would be okay, but the outside wouldn't because we use a variably-coloured background.

**Comment by blackshadowshade** [comment]
@cgolubi1, I'm happy for us to do a deploy and then comment to our users that we're working on improving the cross-browser compatibility of our images.

**Comment by AdmiralJota** [comment]
What about something that's pixelated with a transparent background, like this?

![circle](https://cloud.githubusercontent.com/assets/5848173/17311979/50d54ee2-581d-11e6-850b-48ccffc7c2f6.png)

**Comment by blackshadowshade** [comment]
Two things about that:
- I'll need to see what it looks like on various browsers, including Chrome
- How do we colour in the image white/grey/black?

**Comment by AdmiralJota** [comment]
Oh, right. Yes, that's what I would have been implying had I remembered that the inside wasn't being colored in with CSS:

![circle-black](https://cloud.githubusercontent.com/assets/5848173/17312559/886e762c-5821-11e6-9d7d-0e493ec6e896.png)
![circle-grey](https://cloud.githubusercontent.com/assets/5848173/17312558/886c0b44-5821-11e6-83ab-95beaf65b906.png)
![circle-white](https://cloud.githubusercontent.com/assets/5848173/17312560/886f42f0-5821-11e6-8586-ef9f06364ca8.png)

(World's saddest traffic light.)

**Comment by blackshadowshade** [comment]
So, here's what it looks like on Chrome with the (4)s replaced by the antialiased 49x49 image.

![capture](https://cloud.githubusercontent.com/assets/2898401/17313488/70b8c59a-589f-11e6-991b-b0b869679882.PNG)

**Comment by blackshadowshade** [comment]
So, it looks like what we need are the images native at 49x49 px, antialiased with a transparent background.

**Comment by AdmiralJota** [comment]
I agree, but I may be biased.

**Comment by irilyth** [comment]
I agree that this shouldn't be a prod blocker, and if we want to say in the release announcement that we're planning on further improving the images (and appreciate feedback, with browser info), that'd be a fine idea. I think they're good enough to go live with, for sure.

**Comment by blackshadowshade** [comment]
I'm going to close this issue. If anyone feels like there's more to discuss here, feel free to reopen it.
