### ISSUE TITLE
Fix JSDoc comments

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2079]
Currently, the JSDoc comments have an incorrect syntax, which is causing NetBeans to show me loads of warnings.

As an example, we have something like

    @param  object die      The die whose recipe is to be displayed

This should actually be

    @param  {object} die      The die whose recipe is to be displayed

See http://usejsdoc.org/tags-param.html

Also

    @return  object

should actually be

    @returns  {object}

See http://usejsdoc.org/tags-returns.html

**Comment by cgolubi1** [comment]
If you put this fix in a pull by itself, i'll merge it quickly.  It'll be much easier to look at if there are no other changes in the pull.
