### ISSUE TITLE
Two die backgrounds appear

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2100]
![screen shot 2016-08-03 at 7 49 06 pm](https://cloud.githubusercontent.com/assets/6751265/17385873/8c9eb3e0-59b3-11e6-8a61-dc41de2b2412.png)

This is in game # 15159 on the production site. My preferences state "Symmetric".

**Comment by dwvanstone** [comment]
Never mind - hadn't reloaded in a while, so CSS probably off.

**Comment by cgolubi1** [comment]
dwvanstone: if you're online, i'm looking for someone to hop on the dev site and verify that the fix in #2097 is good, so i can get a second set of eyeballs before pushing it to prod.

**Comment by dwvanstone** [comment]
I haven't found a game that I'm not in yet.

**Comment by dwvanstone** [comment]
Found one! So far it looks fine.

**Comment by dwvanstone** [comment]
It all looks good!

**Comment by cgolubi1** [comment]
Thanks!
