### ISSUE TITLE
Faye button recipe is incorrect on art

### ISSUE THREAD

**Issue by PoshFrosh** [buttonmen-dev/buttonmen#2114]
As discussed in this forum thread:

http://www.buttonweavers.com/ui/forum.html#!threadId=385

the recipe visible on the Faye button art (from the Cowboy Bebop set) is incorrect.

The current button is viewable here:
http://dev.buttonweavers.com/ui/buttons.html?button=Faye

I've put together a new button (rebuilding the art from scratch):
https://goo.gl/photos/ZfMmGN12dXUK7BfSA

If people like the new artwork, it could be used. But since the other characters in the set now look pretty shoddy in comparison, I may need to work on changing them now to match this style. Feedback welcome. Thanks.

![faye_fixed](https://cloud.githubusercontent.com/assets/22480933/18886512/2e9afa3e-84be-11e6-859f-926cf7fb232d.png)

**Comment by PoshFrosh** [comment]
Here is the updated Vicious button art to match the Faye:
![vicious_fixed](https://cloud.githubusercontent.com/assets/22480933/18886976/3c3cdf2a-84c0-11e6-8f18-ccdd152f7311.png)

**Comment by PoshFrosh** [comment]
![spike_fixed](https://cloud.githubusercontent.com/assets/22480933/18887844/ee555658-84c3-11e6-86f4-0af9222c960b.png)

**Comment by PoshFrosh** [comment]
![jet_fixed2](https://cloud.githubusercontent.com/assets/22480933/18889426/f14c71fa-84ca-11e6-8add-aa6f2fa4cfe2.png)

**Comment by PoshFrosh** [comment]
![ed_fixed](https://cloud.githubusercontent.com/assets/22480933/18890445/384b9532-84cf-11e6-8051-ea36a0f58b52.png)

**Comment by blackshadowshade** [comment]
Nice work, PoshFrosh!

One thing, though: the images that you've posted here are roughly 420 KB in size. Other button images are closer to 42 KB in size. Would you be able to resize them appropriately?

**Comment by PoshFrosh** [comment]
Yes, I can resize them tomorrow (when I will also add in Ein). Just glad I
can help out.

-Casey

**Comment by Hurtay** [comment]
I like the new images in general. But as I see you only changed the inner part of the images and left the outer rim as blurry as it was before. Any particular reason?
Faye still needs the shade. Since you've sent me the image already I can have a look into giving her a shade. But with her the blurry outer rim is even more prominent than with the other images. So maybe you'd like to change that first? The light reflex in the top left corner and the shade below can be added later (either by you or by me).

**Comment by PoshFrosh** [comment]
@Hurtay yes. I should be able to make them crisp to the edges if you can add the drop shadow later. i'll work on them more today. thanks.

**Comment by PoshFrosh** [comment]
Ok, here's what I came up with. These are resized to <70k (30% of the original size). I sent the originals to Hurtay. Feel free to use these however you see fit. Thanks, all.
![ed](https://cloud.githubusercontent.com/assets/22480933/18917396/c9a15a26-8565-11e6-97a3-ff1001bf13f4.png)
![ein](https://cloud.githubusercontent.com/assets/22480933/18917400/c9a9774c-8565-11e6-9fa4-df361cc197d8.png)
![faye](https://cloud.githubusercontent.com/assets/22480933/18917397/c9a4b0f4-8565-11e6-8c53-2fe3725742c7.png)
![jet](https://cloud.githubusercontent.com/assets/22480933/18917399/c9a95460-8565-11e6-9069-394e53fde1ca.png)
![spike](https://cloud.githubusercontent.com/assets/22480933/18917398/c9a7859a-8565-11e6-958c-9ca9d05c4b6e.png)
![vicious](https://cloud.githubusercontent.com/assets/22480933/18917401/c9b3c1c0-8565-11e6-823a-275a4e07811e.png)
