### ISSUE TITLE
Durak666 recipe is incorrect on button art

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2116]
Durak666's recipe is [swz(30) swz(30) swz(30) swz(30)], but the button art has five swz(30) circles.

**Comment by blackshadowshade** [comment]
Is anyone up to fixing this image?

**Comment by TheOrgg** [comment]
This was the easiest correction I've ever done for this site.  Any other quick-and-easy ones like that?
![durak666](https://user-images.githubusercontent.com/44233993/95160528-73746a80-0766-11eb-95a9-f1aa4d8d604b.png)
