### ISSUE TITLE
<a class="pseudolink"> doesn't open correctly on middle-click

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2119]
Taken from http://www.buttonweavers.com/ui/forum.html#!threadId=406

@ericeslinger said:

So, I'm not wild about the pseudolink code in the forums. It means I can't middle-click to open a link in a new tab, because the normal a href handler is overridden by the click handler.

Removing that clickhandler works (if I fiddle with it in the DOM inspector). If you're going to be doing stuff with the URL like that, it might be worthwhile to look at how some of the Big frameworks handle routing and state changes without window reloads. I know I can create functioning a href elements using angular.js that respect all native behaviors but are still just internal (no new network requests) state changes. It even remembers history correctly with the back button and all that.

**Comment by irilyth** [comment]
This works for me in Chrome now: If I look at http://www.buttonweavers.com/ui/forum.html#!boardId=3, and middle click on the link that's the name of the thread, it opens in the same tab, but on http://dev.buttonweavers.com/ui/forum.html#!boardId=3 it opens in a new tab. It still works as before in Firefox. Shipit!
