### ISSUE TITLE
Decide what pulls to bring to staging for December release

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2133]
Test all pulls which are currently on dev.buttonweavers.com but not on staging or prod, and decide which ones to accept for the December release by loading them onto staging and then prod.

Please note --- all testing pulls have been merged (and thus those issues are closed), so the "final" pull is a good place for discussion about whether the change is ready for prime time.

| Testing pull | Final pull | Decision | Description |
| ------------- |:-------------:| :----: | :----- |
| #2107, #2139 | #2084, #2140 | YES | Removed word 'Game' from the first column on the overview page |
| #2106 | #2083 | NO | Stopped unnecessary reroll of zero-valued dice |
| #2108 | #2103 | NO | Added logic to consider poison dice in the calculation of the "can still win" condition |
| #2110 | #2085 | NO | Stop Dead Guy from turning up in random matches |
| #2111 | #1725 | NO | Fixed default attack when fire overshooting is off |
| #2120 | #2121 | YES | Added logic to check what sort of click is used on a pseudolink |
| #2125 | #2126 | YES | Updated images for Cowboy Bebop |
| #2123 | #2124 | YES | Changed Cheese Weasel to having a button special |
| #2129 | #2130 | NO | Added Steven Universe set |
| #2127 | #2128 | YES | Changed button name Peri to Perf |
| #2134 | #2135 | YES | Define puppet_hostname for new IP for staging.buttonweavers.com so its mail will be accepted by more servers |

**Comment by cgolubi1** [comment]
Okay, so i haven't done anything about the three pulls we were on the fence about, but neither has anyone else.  So IMO the next step is to say, let's not bring any of those guys in for "December".  There are six approved pulls for December --- let's go ahead and approve those guys, do that release, and move forward with the "many dev sites" proposal for January if we can.

**Comment by cgolubi1** [comment]
Okay, so i'm going to go ahead and merge all the YES pulls from the description, comment on any merge conflicts which ensue, and then kick off a Jenkins run to see if that passes or if there are fixup pulls we need even this month.

**Comment by cgolubi1** [comment]
I believe the master jenkins run will be http://jenkins.buttonweavers.com:8080/job/buttonmen-UPSTREAM/76/ (the dev jenkins run is in progress, and i'm going to let that run in case its results are useful).  I'll check in on that later today.

**Comment by cgolubi1** [comment]
Okay, the changes have been loaded on staging.  We'll be tidying up the process for staging testing next month, but meanwhile, go ahead and check things out on that site.

**Comment by irilyth** [comment]
http://staging.buttonweavers.com/ui/forum.html#!threadId=2 is a thread on the forums on the staging site where we've been talking about this ticket.

**Comment by blackshadowshade** [comment]
Closing this.
