### ISSUE TITLE
Staging website needs favicon different from production

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2136]
The dev website has a favicon that differs from production. It would be beneficial to have the staging website also have a different favicon from production - it could even match the dev site if need be.

**Comment by irilyth** [comment]
We talked about this briefly on IRC, and liked the idea of it being different from both dev and prod, and also some things like whether the header should be gray or some other color or what. This seems like a good ticket to tackle those questions.

I suggest blue for staging (and leave dev and prod as they are).

**Comment by AdmiralJota** [comment]
Wouldn't blue make it the same as prod?

My first suggestion would be "take the current prod icon and make it grayscale". But my second suggestion would be "make the staging icon the same as dev". Both of those would require a minimal amount of image manipulation work.

**Comment by irilyth** [comment]
I think prod is currently black, not blue... If it's secretly a very dark blue, maybe staging could be a light blue?

**Comment by irilyth** [comment]
#1842 wants to use grayscale for "monitor mode, if you don't have any games to play", so I think we shouldn't use grayscale for staging in any case.

**Comment by irilyth** [comment]
> I think prod is currently black, not blue... If it's secretly a very dark blue, maybe staging could be a light blue?

Huh, check that out, it totally is blue.

Light blue for staging? Orange? I don't have a preference, but would like to do something, so I can keep my tabs straight. :^)

**Comment by blackshadowshade** [comment]
What about no favicon for the moment? I can certainly rename the favicon to another name as a temporary measure.

**Comment by cgolubi1** [comment]
I'd like to veto making manual changes to files installed by vagrant on deployed sites.  It messes up the deployment process and wastes time.

**Comment by blackshadowshade** [comment]
Since we're now using staging for the same purpose as our old dev, I think this would be fine.

**Comment by irilyth** [comment]
I'd said

> We talked about this briefly on IRC, and liked the idea of it being different from both dev and prod

I don't recall the details, and am lazy. I think it'd be nice if the mini-dev sites used dev icon, which I think they don't at the moment.

In any case, here's two yellow versions, as possible staging options:

![favicon_staging_1](https://cloud.githubusercontent.com/assets/4923138/25563980/c2281d16-2d76-11e7-87ac-17d2b72ef15e.png)

![favicon_staging_2](https://cloud.githubusercontent.com/assets/4923138/25563983/c63a81dc-2d76-11e7-9edb-c794953e5236.png)

The first is the prod one with the colors rotated and lightened; the second replaces the "BM" with the darker red from the main site.

If folks like either, I'll put in a PR. If folks have other suggestions, lemme know, keeping in mind that I'm not very good at this. :^)

**Comment by irilyth** [comment]
To clarify slightly, I think that blue for prod, yellow (or something) for staging, and red for mini-dev, would be better than using red for both staging and mini-dev.

**Comment by cgolubi1** [comment]
IMO the second one irilyth suggested is just fine; i don't think the bar is high for the graphics on this, and i think it's recognizeable a BM icon.

**Comment by blackshadowshade** [comment]
If I remember correctly, this requires a change to the database and the UI also?

**Comment by irilyth** [comment]
Jota seems to have done a bunch of stuff related to the dev favicon in #849, but some of it looks like infrastructure to distinguish the dev and prod sites in general, so I'm not sure what exactly needs to be done to add a third option.

**Comment by AdmiralJota** [comment]
If you want to set the site up to be able to recognize staging as separate from dev and prod, then I believe there are two code files you'll want to change: Login.js and Overview.js. I've created a gist containing changes that I think should work: https://gist.github.com/AdmiralJota/1dd4f2e734f4c395ec9f1ea9894df2af

(I also updated the link to Cheapass Games, since it looks like our URL for their BM page is out of date.)

If those two files (and the icon itself) get checked into the main branch, then you should be able to configure the site to be staging by updating the Config.js file; I believe that @cgolubi1's deployment process already has a clause for doing this when pushing to dev.

**Comment by cgolubi1** [comment]
Okay.  So do we think the many-dev-sites should use the dev site icon?  I think they should.  Anyone disagree?

**Comment by blackshadowshade** [comment]
Sounds fine to me.

**Comment by blackshadowshade** [comment]
@AdmiralJota, when I get a free moment today, if Chaos hasn't already done it, I'll put up a pull request with the new URL and the typo change.

**Comment by irilyth** [comment]
> Okay.  So do we think the many-dev-sites should use the dev site icon?  I think they should.  Anyone disagree?

I think they should!

**Comment by cgolubi1** [comment]
Oops, sorry for the miss there.  Thanks, shadowshade.
