### ISSUE TITLE
Why make a player confirm surrendering when the game suggested the surrender?

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#2144]
Could the confirmation box asking if a player is sure they want to surrender be bypassed in those situations where the game itself has just told the player it's probably a good idea to surrender?  Feels like the game is giving mixed messages.

**Comment by blackshadowshade** [comment]
What do others think of this suggestion?

**Comment by dwvanstone** [comment]
I think it should still give the confirmation box - I feel it's there to prevent a player from accidentally surrendering because they selected the wrong option in the dropdown list. It's possible the player is in a story game or something or are having a good conversation.

**Comment by irilyth** [comment]
I agree with devious.

**Comment by blackshadowshade** [comment]
Okay, closing this as wontfix. If anyone wants to argue for it or reopen it, feel free.
