### ISSUE TITLE
Verify Maya's recipe

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2149]
Maya's recipe here is o(6) (12) p{hs,H}(12) (20) (S), but http://www.randomdice.com/games/buttonmen/roster.asp says that the twelve-sider is "12 {SH WE / MI} [mi, pl, po, we]". In their notation, bracketed skills seem to be AND, e.g. Bluff's twelve-sider is "12 [po, sh]", but I'm still not sure how to read that.

We should verify what Maya's recipe is actually supposed to be.

**Comment by blackshadowshade** [comment]
http://www.zatrolene-hry.cz/dialog/download-file?id_soubor=871 agrees that Maya's recipe is

    6 [OR], 12, 12 {SH WE / MI} [MI, PL, PO, WE], 20, S

After looking at a number of other recipes (including Zeno's), I think our interpretation of

    o(6) (12) p{hs,H}(12) (20) (S)

is correct.

I'm going to close this issue.
