### ISSUE TITLE
Duplicate Mark Thread as Read at top

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2164]
Hi Devs,

When I am browsing forum posts using next post, I often arrive at threads that I know I don't care about.  For example tournaments I'm not in.  Currently I have to scroll all the way to the bottom to mark that thread as read.  I'd like to be able to mark that thread as read without scrolling.  Could we get a second "Mark thread as read" button at the top of the thread as well as at the bottom of the thread.

Thank you,
Nicole

**Comment by blackshadowshade** [comment]
I'm going to link this to #2034 which is not the same, but attempts to address a similar problem.

**Comment by AdmiralJota** [comment]
I agree that such a button would be pretty useful. And shouldn't be hard to implement. (Except for deciding where to put it. Any thoughts on that?)

**Comment by nkmcalli** [comment]
I thought parallel to where the button at the bottom is, but between the header and the first post.

**Comment by nkmcalli** [comment]
I really want this button now because of this:

I'm just now reading the forum posts by clicking next post.  Almost every time I land at the new post at the bottom of a thread.  I have no idea what the thread is about since I'm at the bottom.  So then I have to scroll to the top to see what the thread title is, and then scroll back to the bottom to mark the thread as read.  If the mark as thread button were at the top, I could click it as soon as I scroll up to read the title.
