### ISSUE TITLE
How about reverse-chronological order for forum threads

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2165]
Hi Devs,

I feel like this one has a low chance of getting approved, but I want to put it out there anyway:

Many of our forum threads are very long, and I hate scrolling.  What if we displayed forum threads in reverse chronological order.

Advantage of reverse-chronological:  New posts right at the top!
Advantage of chronological:  Context of the thread is set at the top.

Thank you,
Nicole

**Comment by nkmcalli** [comment]
Almost forgot:  YES, you automatically scroll to the bottom to jump to new posts.  EXCEPT, often times folks EDIT the very first post to adjust information there.  In that case, the jump to new posts at the bottom doesn't work, it just stays at the top post and users still have to scroll.  We do this a lot with threads where folks choose buttons and the first post is a list of buttons and then that post gets edited.  Editing the main post is a good thing, but it breaks the jump and means scrolling.

**Comment by blackshadowshade** [comment]
I wonder if this would be better served by a floating "Navigate to top" and "Navigate to bottom" button.

**Comment by nkmcalli** [comment]
Good question.  Let me know if you want me to test anything.  Also, you can always "won't fix.  :)

**Comment by AdmiralJota** [comment]
I wonder if some way to jump to "the next new post in this thread after this one" would be at all helpful. Say, hypothetically, person A has modified the first post in the thread, person B has modified some post in the middle of the thread, and person C has added a new post at the end. If each "NEW" post had a link to jump to the next "NEW" post in the thread, then you could use it to read all of it without having to scroll or risking missing the one in the middle if you jumped straight to the end.

**Comment by nkmcalli** [comment]
I just want new stuff at the top always, everywhere, not just here.  Think about your email inbox.  Or a threaded email message where the new content is at the top.  But I know this one is a long shot.  :)

**Comment by nkmcalli** [comment]
One more argument in favor of reverse chronological.  I'm just now reading the forum posts by clicking next post.  Almost every time I land at the new post at the bottom of a thread.  I have no idea what the thread is about since I'm at the bottom.  So then I have to scroll to the top to see what the thread title is, and then scroll back to the bottom to read the new posts or mark the thread as read.  Sigh.

**Comment by nkmcalli** [comment]
Navigate to top and navigate to bottom make it easy to move, but what if you didn't have to move?  What if the title bar, all new posts, and the mark as read button were all at the top.  You'd still have to move to the bottom for threads where authors edit the original post.  But I do that less often than I do all the other movement.

**Comment by AdmiralJota** [comment]
>  Think about your email inbox. Or a threaded email message where the new content is at the top.

To be honest, this is something I hate about most email inboxes and threaded email messages, to be honest. If we did go for reverse chronological ordering, I would feel very strongly that it would need to be optional.

And I'm not sure that this would really solve any of the problems, since if someone edited the "first" post in a thread, then you'd just get automatically scrolled to the *bottom* when you clicked "NEW", and you'd be stuck in roughly the same situation you're in now.

But I do like the idea of making the thread title and some kind of useful navigation/reading buttons (jump to top, jump to bottom, jump to next new post, mark thread as read) more conveniently accessible. A floating sidebar/control panel thingy like blackshadowshade mentions might work for all of this, but I know that some of our users (including some devs) use really, really narrow monitors, which might make things tricky.

**Comment by irilyth** [comment]
I also like the idea of having a static header or footer or sidebar or something (I prefer header or footer, but don't feel too strongly about it), and don't like the reverse chronological idea at all.

**Comment by nkmcalli** [comment]
Okay, sounds good.  I also thought about possibly sending video of me using the forum section.  Sort of like a usability test.  Sometimes video is easier than parsing words.  Let me know if that's something you're interested in.

**Comment by AdmiralJota** [comment]
Ooh, a static header sounds like a good idea... say, if the current header that looks like this:

![image](https://cloud.githubusercontent.com/assets/5848173/24886869/c6c9d75c-1e25-11e7-8f86-aae23a07836a.png)

...had some buttons added to it (jump to top, jump to bottom, next new post in thread, mark thread as read) -- or maybe had them added directly under it -- and was then fixed at the top of the page, so that the rest of the page could scroll while that stayed put? 

(That said, this could be... *interesting* to try to implement.)

I think that might work pretty well. What do you think, nkmcalli?

**Comment by nkmcalli** [comment]
I'm happy to test any change you want to try.  It sounds promising.  It could solve a lot of related problems with the forum navigation.

**Comment by AdmiralJota** [comment]
Here's a quick, crudely-implemented mock-up of how it might look:

![image](https://cloud.githubusercontent.com/assets/5848173/24887497/2c517888-1e2a-11e7-9d83-9d4f88f364ac.png)

**Comment by nkmcalli** [comment]
So it's floating and always visible?  I like that a lot.  I think it solves almost all the problems.

Small nit:  "Jump to next new post" without the uppercase and asterisks.

**Comment by AdmiralJota** [comment]
I've put together something that I think will handle this at: https://gist.github.com/AdmiralJota/6014659329e00236b1dde08b42f4ed2f

This includes one new external javascript library, jquery.floatThead.js. It came from http://mkoryak.github.io/floatThead/ and should go in /ui/js/extern. The rest is just changes to existing files.

This will probably want a bit of testing to make sure I didn't break any existing forum UI (scrolling to the right place at the right time, things lining up correctly in different browser types, etc.).

**Comment by blackshadowshade** [comment]
I've put your new files into a new branch and I ran the QUnit tests on them. They failed at test_Forum.showOverview() with the error

    TypeError: $(...).floatThead is not a function

so I presume that the new library needs to be added somewhere in the testing architecture too. However, I don't know where, so I'll leave this until @cgolubi1 gets back and can tell me how to do this.

**Comment by AdmiralJota** [comment]
I believe it'll need to be added to test/src/ui/index.html (and probably also test/src/ui/phantom-index.html), in the same section as spectrum.js and moment.js.

**Comment by blackshadowshade** [comment]
Okay, that's done it, thx Jota. Pull request is up.

**Comment by AdmiralJota** [comment]
@nkmcalli We've got this up at http://transient.dev.buttonweavers.com/ for testing now.

**Comment by nkmcalli** [comment]
Cool!  What credentials do I use for testing.  I tried my usual name and password but got rejected.  Do you need to authorize me?

**Comment by AdmiralJota** [comment]
You'll need to create a new account there (you can use the same name as usual). If it doesn't automatically send you the confirmation email, leave a note here, and someone can manually confirm your account in the database.

**Comment by nkmcalli** [comment]
https://www.nngroup.com/articles/back-to-top/

**Comment by blackshadowshade** [comment]
@nkmcalli, have you tested the floating header successfully yet? We're looking at deploying this soon, if testers are happy with it.

**Comment by nkmcalli** [comment]
I haven't had a chance.  I can try tomorrow or Thursday...
