### ISSUE TITLE
The site could be more mobile friendly.

### ISSUE THREAD

**Issue by slugmuffin** [buttonmen-dev/buttonmen#2172]
Couple quick thoughts:
1) The swing dice selection could pull up the number-only keyboard with minimal changes.
2) The hover-over / tool-tip information on special skills is inaccessible to the mobile user. I had to search in another page to find what each skill did during a game.

**Comment by irilyth** [comment]
#2072 addresses the second specifically.

For the first, that sounds like a good idea. Do you offhand know how to do it? :^)

**Comment by slugmuffin** [comment]
I believe this is how you do it:
`<input type="number" pattern="[0-9]*" inputmode="numeric" min="4" max="20" />`

I haven't tested it, but this might work:
`swinginput.append($('<input>', {
          'type': 'text',
          'inputmode': 'numeric',
          'min': range.min,
          'max': range.max,
          'pattern': '[0-9]*',
          'class': 'swing',
          'id': 'swing_' + letter,
          'size': '2',
          'maxlength': '2',
        }));`
*Note: I read there is limited support for range checking in the current browsers and validation should still also be done outside of this.

**Comment by blackshadowshade** [comment]
I've just tried out this suggestion, and it doesn't work on my Android stock browser, nor does it work on Firefox 53.0 on Android.

**Comment by blackshadowshade** [comment]
Okay, http://stackoverflow.com/questions/20164706/trigger-number-pad-on-focus-in-html-input-element implies that the type needs to be 'number' or 'tel'.

**Comment by blackshadowshade** [comment]
I've just tried out 'number', and that seems to work a treat.

**Comment by blackshadowshade** [comment]
slugmuffin, if you haven't seen it, we've put up a testing site at http://54.160.0.59 where you can see whether the proposed change does what you'd like.

If you'd like to be a member of the dev team or an official tester, let us know too, and we'll add you to the appropriate team.

**Comment by slugmuffin** [comment]
Number pad opens for me on iOS.

**Comment by slugmuffin** [comment]
On a PC with Firefox - the box is too small to see the numbers now since there are arrows for up/down. 

The box should be expanded or the up/down arrows hidden (if reasonably possible)

**Comment by blackshadowshade** [comment]
See #2178 for the solution that I've implemented. That should be deployed in the next couple of days.

**Comment by blackshadowshade** [comment]
This has been deployed to the test site, and is ready for testing again, @slugmuffin.

**Comment by irilyth** [comment]
I still see the arrows in Firefox on my laptop.

**Comment by blackshadowshade** [comment]
Did you do a refresh of the page?

**Comment by irilyth** [comment]
Yep. http://54.160.0.59/ui/ right? Do you see it when you try?

They're not there in Chrome, although the number in the box is weirdly small:

![bm](https://cloud.githubusercontent.com/assets/4923138/25620123/58e4b82c-2f1b-11e7-9403-ec83136de7f9.png)

Not sure what's up with that.

**Comment by blackshadowshade** [comment]
Ah, I'm browsing on Safari on Mac, and they're gone from there.

After I fired up Firefox, I'm also seeing the arrows there still. Looks like more CSS is necessary.

On the Chrome version, is the number in the box a smaller font size to the number on prod? I can't exactly tell from the screenshot.

**Comment by slugmuffin** [comment]
Showing arrows on firefox for me this morning. 

![firefox_arrows](https://cloud.githubusercontent.com/assets/26312415/25622026/2fc7872a-2f21-11e7-94e1-43970594e945.png)
