### ISSUE TITLE
Rush dice

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2176]
Rush dice have been added in the Kickstarter. Our current knowledge about this skill is directly from James Ernest:

> Rush Dice are exactly like Focus Dice but are worth zero points if you keep them. A small handicap for an otherwise strictly better die type.

My suggestion for the recipe encoding of this skill is to use '#'.

**Comment by blackshadowshade** [comment]
Some discussion can be found here: http://www.buttonweavers.com/ui/forum.html#!threadId=473

**Comment by blackshadowshade** [comment]
I'll close this for the moment, on the advice that James Ernest is looking for an alternative skill for the Kickstarter.

**Comment by blackshadowshade** [comment]
Okay, James Ernest is indicating that he's going to stick with the skill name, but change the definition to

> Can't participate in Skill attacks, but can make Speed attacks.

**Comment by blackshadowshade** [comment]
So, the question here is how to deal with the interaction of Berserk and Rush on the same die.

**Comment by AdmiralJota** [comment]
That seems fairly straightforward. Neither one permits skill attacks. One gives you the ability to do Berserk attacks (which cause your die to shrink and lose the Berserk skill but would have no effect on the Rush skill). The other gives you ability to do Speed attacks (which do not have any other effect on the die size or skills).

**Comment by blackshadowshade** [comment]
That makes sense.

**Comment by Daefaroth** [comment]
How about a stealth/rush interaction?  If both are allowed in RandomBM (or someone is just being silly) that d#(12) becomes an unpleasant bit of dead weight.

**Comment by irilyth** [comment]
Yeah, that comes up sometimes with Stealth Berserk now, and it's annoying and/or amusing depending on your temperament. :^) I don't think we necessarily need to do anything about it.

**Comment by blackshadowshade** [comment]
So, a new definition is currently being playtested, and we'll need to wait until this has been confirmed before continuing with this.

**Comment by Daefaroth** [comment]
Per Kickstarter Update #8:

>The fighters from Uptown have a new die type called "Rush Dice." These are powerful dice but they also have an unusual weakness. In addition to Power and Skill Attacks, Rush Dice can also make Rush Attacks, in which they capture two enemy dice that add up exactly to their value. For example, two dice showing 2 and 8 could be captured in a single Rush Attack by a die showing 10.

>However, Rush Dice are also vulnerable to the same kind of attack. Any die can make a Rush attack if the target includes at least one Rush Die.

I suspect that is going to take some interesting coding juggles to allow for opponents to make a counter Rush attack that must target a Rush die.

**Comment by AdmiralJota** [comment]
Cosmetic issue with the log message:

> Jota performed Rush attack using [(X=12)!:4] against [#(12):2,#(X=4):2]; Defender #(12) was captured; Defender #(X=4) was captured; Attacker (X=12)! rerolled from 4, changed size due to turbo

There's a missing space after the comma between "#(12):2" and "#(X=4):2".

**Comment by cgolubi1** [comment]
Jota: i think that's normal.  e.g. from an arbitrary game on the prod site: `blackshadowshade performed Skill attack using [%Ho(4,8):10,Ho(2,6):4]`

**Comment by AdmiralJota** [comment]
OK, I'll take it to a separate issue.
