### ISSUE TITLE
Add new buttons from Kickstarter

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2186]
James Ernest would like the buttons playtested before they are printed. To date, he has provided the recipes for the core set, and the other two sets will be provided as soon as he is happy with them.

The Core: (4/28/17)

Delia 4-4-12-20-X
Tony 8-8-20-20-X
Hollis 6-6-20-X-X
Porter 8-12-12-20-X
Donna 4-8-12-12-X
David 4-8-20-20-X
Charlie 4-6-6-12-X
Polly 4-4-8-20-X
Lady B 4-8-8-20-X
Smith 6-8-8-12-X
Wallace 6-6-20-20-X
Tanya 4-6-12-X-X
Stefano 6-8-12-20-X
Janet 4-12-20-20-X
Steve 6-6-12-12-X

**Comment by blackshadowshade** [comment]
What do you all think about where these sets should appear in the button selector? At the top? Below the canonical standard sets?

**Comment by cgolubi1** [comment]
So i don't think we're pushing these to prod until the recipes are finalized, so i don't think it matters - just make them their own set name and add them as usual.  I don't think we need to do anything special.

**Comment by blackshadowshade** [comment]
I'll put them up the top for the moment then, and we can always change that.

**Comment by blackshadowshade** [comment]
Updated lists:

The Core (Basic Dice Only):
Delia 4-4-12-20-X
Tony 8-8-20-20-X
Hollis 6-6-20-X-X
Porter 8-12-12-20-X
Donna 4-8-12-12-X
Ferrer 4-8-20-20-X
Charlie 4-6-6-12-X
Polly 4-4-8-20-X
Lady B 4-8-8-20-X
Smith 6-8-8-12-X
Wallace 6-6-20-20-X
Tanya 4-6-12-X-X
Stefano 6-8-12-20-X
Janet 4-12-20-20-X
Steve 6-6-12-12-X

West Side (Poison Dice)
Marin 4-4p-8-12-X
Carson 8-12-20-20p-X
Jackie 4-6-8p-12-X
Marta 6-12-12-12p-X
Bijay 4p-8-12-20-Xp
Sal 6-6p-8p-20-X
Dietrich 6p-8p-20-20-X
Hazel 4-6-6p-8-X
Rider 8-8p-12-20-X
Mickael 4p-6p-8-20-X
Beatrice 4-4-12-12-Xp
Stacie 6-8-12-20p-Xp
Prentice 4p-6p-12-20-X
Sally 6-6-12p-20-X
Mondo 4-12-20-20p-X

Delta (Shadow Dice):
Jocasta 6-12-12s-20-Xs
Lady K 4-6s-8-8s-X
Keegan 8-8s-12s-20-X
Benvenito 4-8-8-20s-Xs
Pilot Joe 4-4s-6s-20s-X
Gilroy 4s-6-8s-20-X
Jerry 6-8-8-12s-X
Fiorina 6s-6s-12-12-X
Doctor Fret 4-4-12-Xs-Xs
Ho Min-Szu 4-6-8s-20-Xs
Szechuan 4s-6s-8s-12s-X
Felicia 6-8-8s-20s-X
Brand 4-12s-12s-20-X
Windsor 6-6s-12-20s-X
Cerise 8s-12-12-20-Xs

Uptown (Rush Dice):
Ricky 6-8-8r-20-Xr
Giuseppe 8-8-12-12r-X
Heather 6-6-8r-20-Xr
Clyde 12-12r-20-20-Xr
Tasha 4-6-6r-8r-X
Ken 4-8r-12r-20-X
Mississippi 6r-8r-12r-20r-Xr
Petey 4-6-12-20r-X
Bobby 6-8-20-20r-X
Pepper 4-6-6-8-Xr
Basil 6-8r-12-12r-X
Jesse 4-4-20-20r-X
Henry 4-8-12r-20r-Xr
Stubbs 12-12r-20-X-Xr
Montserrat 4-6r-8r-12r-Xr

**Comment by blackshadowshade** [comment]
Updated recipes for the Delta set:

Jocasta 6-12-12s-20-Xs
Lady K 4-6s-8-8s-X
Keegan 8-8s-12s-20-X
Benvenito 4-8-8-20s-Xs
Pilot Joe 4-4s-6s-20s-X
Gilroy 4s-6-8s-20-X
Jerry 6-8-8-12s-X
Fiorina 6-6s-12-12-Xs
Doctor Fret 4-4-12-Xs-Xs
Min-Szu 4-6-8s-20-Xs
Szechuan 4s-6s-8s-12s-X
Felicia 6-8-8s-20s-X
Brand 4s-6-12s-20s-X
Windsor 6-6s-12-20s-X
Cerise 8s-12-12-20-Xs

**Comment by Daefaroth** [comment]
Random thought.  It seems like the intent of BM2017 is to force the swing dice to follow the dice types in the box (4,6,8,12,20).  Is it possible to limit the swing die choices like that?  Is it even worth doing it?

**Comment by blackshadowshade** [comment]
So, James Ernest is interested in making the poison recipes less powerful. His new suggestions are:

Marin 4-4p-8-12-X
Carson 8-12-20-20p-X
Jackie 4p-6-8-12-X
Marta 6-12-12-12p-X
Bijay 4-8-12-20-Xp
Sal 8-8-8p-20-X
Dietrich 6p-8p-20-20-X
Hazel 4-6-6p-20-X
Rider 8-8p-12-20-X
Mickael 4p-6p-8-20-X
Beatrice 4-4-4p-12-X
Stacie 8-12-20-X-Xp

**Comment by blackshadowshade** [comment]
He'd like feedback on these changes, and what we think about his efforts to balance the set.

In detail, the changes are:

Jackie (old): 4-6-8p-12-X
Jackie (new): 4p-6-8-12-X

Bijay (old): 4p-8-12-20-Xp
Bijay (new): 4-8-12-20-Xp

Sal (old): 6-6p-8p-20-X
Sal (new): 8-8-8p-20-X

Hazel (old): 4-6-6p-8-X
Hazel (new): 4-6-6p-20-X

Beatrice (old): 4-4-12-12-Xp
Beatrice (new): 4-4-4p-12-X

Stacie (old): 6-8-12-20p-Xp
Stacie (new): 8-12-20-X-Xp

**Comment by keiyakins** [comment]
Wait, I thought it was supposed to be 48 characters in the box, with 8 (plus Mutton Ben) in the funvelope. That's only 56 total... why are there 15 in each faction for 60 total here? Or is that secrets?

As for restricting X to the dice in the box: That's a play expedient for people who don't have buttloads of dice and the inclination to figure out how to roll weird numbers. The actual rule isn't changing, confirmed in a youtube comment on the how to play video.

**Comment by blackshadowshade** [comment]
As far as I understand, each faction is going to come with some extra (sideboarded?) characters which may not be playable with the dice in the box, but would be playable for people with extra dice.

**Comment by Daefaroth** [comment]
Since the latest update just added the stretch goal of 4 more characters in the funvelope I think that explains where the extra characters are going.  And that is fair regarding the swing dice rules.  I just thought it was interesting to note that "playable out of the box" is somewhat different than how most of us play. 

Regarding the playability of characters, I was under the impression that each individual character is playable with the core box, but not every matchup necessarily is.  If the pair exceeds either four normal dice of the same size or 2 special dice of the same size you would need extra dice.

**Comment by blackshadowshade** [comment]
So, this is just about all done. I'll close this, and open a new issue for Mutton Ben.
