### ISSUE TITLE
Fix spacing for button names with parentheses

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#2196]
Some buttons have a parenthetical note after their name to differentiate them from similarly-named buttons from other sets. It looks like they're generally missing the space between the end of the name and the opening parenthesis, like "Tony(The Core)".

This wasn't as noticeable when it was mainly just single-letter notes (like "MAX(p)"), but it's kind of ugly when it's longer. 

I suspect that this was probably due to someone trying to avoid spaces in button names entirely at some point on the old site, but I don't think we have any problems with that here, so we should go back and add the space to existing button names so that we can move forward consistently.

**Comment by blackshadowshade** [comment]
What do you think about changing the names at the same time, e.g., from "Max(p)" to "Max (promo)"?

**Comment by blackshadowshade** [comment]
There's also the question of whether we choose to prioritise official CAG buttons over other buttons, e.g., Heather. Would we rename "Heather" to "Heather (Fanatics)", or do we add the postscript to the new button?

**Comment by AdmiralJota** [comment]
> What do you think about changing the names at the same time, e.g., from "Max(p)" to "Max (promo)"?

That seems reasonable to me. It should help newbies be less confused by the parentheticals.

> There's also the question of whether we choose to prioritise official CAG buttons over other buttons, e.g., Heather. Would we rename "Heather" to "Heather (Fanatics)", or do we add the postscript to the new button?

Good question. I'm not sure which is better.

Also, are we concerned about links to pages like "http://buttonweavers.com/ui/buttons.html?button=Max(p)"? In theory, we could implement some kind of aliasing scheme to keep links like that working right. But on the other hand, maybe we don't care.
