### ISSUE TITLE
Python API client should be Python 3 compatible

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2197]
It'd be nice if the Python API client was Python 3 compatible.

**Comment by irilyth** [comment]
Some useful links I found:

- https://wiki.python.org/moin/PortingToPy3k/BilingualQuickRef
- http://python3porting.com/noconv.html
- http://python-future.org/compatible_idioms.html

I might take a stab at this if it's not too impossibly hard.

**Comment by irilyth** [comment]
Some useful links I found:

- https://wiki.python.org/moin/PortingToPy3k/BilingualQuickRef
- http://python3porting.com/noconv.html
- http://python-future.org/compatible_idioms.html

I might take a stab at this if it's not too impossibly hard.

**Comment by danlangford** [comment]
i have been using the python client more and more. i would love to submit some of the enhancements i have added (search_game_history) and am wondering is 2.x compatibility required? Python3 was released in 2008 and should be very easy to obtain on any machine at this point. what are your thoughts? I can double back on my enhancements to insure 2.7 compatibility but it will take time.

**Comment by blackshadowshade** [comment]
The main people using the Python client are @cgolubi1, @irilyth, and @AdmiralJota, so you'll want to coordinate your chat with them. Since any Python changes don't impact the game site directly, such changes should be relatively easy, as long as they don't break what others are doing with the client.

**Comment by irilyth** [comment]
I think I had a branch with some Python 3 conversion, I can dig it up if you might be interested in finishing this off. My recollection is that something in it broke with something else @AdmiralJota was doing as part of Steven Universe playtesting, but maybe now that the SU set is part of the site, we don't need that specific code any more? I don't remember the details, and don't care a lot, but can help if it turns out that I have anything helpful.

**Comment by danlangford** [comment]
thanks. ill wait for @AdmiralJota to weigh in. my concern was mostly about me wanting to send over some PRs that are probably not Python 2 compliant. i dont think at this time @irilyth you need to worry about digging up that old code. thanks

**Comment by danlangford** [comment]
its my opinion that this issue can be closed with #2667 merged. I will work on a PR for what I have to contribute for #2668

**Comment by irilyth** [comment]
I agree that this was resolved by #2885 (which superseded #2667), so let's close this one out, and I'll make a new issue for some follow-on work. Thanks @cgolubi1 and @danlangford!
