### ISSUE TITLE
Help for Fire Dice

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2200]
Recently a new player asked me how to use Fire dice.  They couldn't figure it out.  I suggested from memory how I thought it worked, and then set up a Fire vs. Fire game with the newbie to test it out.

Currently, if a person makes an attack, and selects a Fire die, we see the message "invalid attack".  We have to guess or ask or discover to NOT select the Fire die.  Then we get the intermediate screen where we can turn down the Fire dice or cancel.

My suggestion:  If a player attacks and has Fire dice selected, ignore the Fire dice for deciding if the attack is valid.  If the player has not selected any non-fire dice, then the attack is truly invalid.  Ignore the fire dice, get zero dice, report that the attack is invalid.  If the player has selected non-fire dice, then ignore the fire dice and go to the next screen where we can turn down the dice.

I think this will help new players figure out how to use the Fire dice.  Selecting the fire dice is extra work that they don't need to do, but at least it will get them where they are trying to go.

**Comment by irilyth** [comment]
I think #1143 is related to this. If we did what that ticket suggests, with a Fire turndown selector that looked a lot like the Turbo one, do you think that would be enough?

**Comment by AdmiralJota** [comment]
> If the player has selected non-fire dice, then ignore the fire dice and go to the next screen where we can turn down the dice.

Wouldn't that make it impossible to actually attack using Fire dice and other dice together? Say, if your Fire die was showing 2, so you wanted to re-roll it by doing a skill attack using it along with a Stinger die showing some large number?

**Comment by nkmcalli** [comment]
#1143 covers it.  Thanks!  Feel free to close as duplicate or whatever.

Jota:  For whatever situation currently gives the message "invalid attack" when you select fire dice, ignore the fire dice.  I don't think that would prevent a legal attack using fire dice.

**Comment by blackshadowshade** [comment]
So, I'll close this as a duplicate. However, once we're happy with the representation of turbo swing, I can imagine fire going the same way, as discussed on #1143.
