### ISSUE TITLE
reenable Gordo without its button special

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2209]
Gordo is supposed to have the "unique" skill, but we don't have time to implement that.  For now, reenable Gordo with an artificial reenable button special so the button can be played on the prod site.

**Comment by cgolubi1** [comment]
This was requested on http://www.buttonweavers.com/ui/forum.html#!threadId=511

**Comment by irilyth** [comment]
I'm not convinced this is a good idea; Gordo at somewhat more powerful without that limitation. If we didn't have Slow yet, we wouldn't enable Giant without it, would we?

I don't object in a blocking way, but I think we should think about it.

**Comment by blackshadowshade** [comment]
I'm going to close this one, because I'm implementing Gordo now.

Linking to #265.
