### ISSUE TITLE
Add user preference to change swing input fields to dropdown selects

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2212]
One of our players, Jeshyr, has mentioned that she prefers to play solely with the mouse, since any use of the keyboard is more difficult for her.

A user preference to change swing input fields to dropdown selects would enable her to use the keyboard less.

**Comment by cgolubi1** [comment]
Let's relate this to #2163 --- if the backend were always sending the list of values, it would be that much easier for the UI to choose how to display them.

**Comment by blackshadowshade** [comment]
I've just realised that this is a duplicate of #311. Closing as a duplicate.
