### ISSUE TITLE
cache busting for js / css assets, jquery.getScript()

### ISSUE THREAD

**Issue by ericeslinger** [buttonmen-dev/buttonmen#2220]
so I'm on a plane right now, with cruddy wifi. natch, this isn't the optimal place to play buttonmen in general, but it's also generally speaking not unreasonable to expect buttonmen to minimize network loads.

right now, the system loader we use is jquery.getScript, which looks like it's appending a cachebuster to the end of each url for all resources, as a query parameter derived from `Date.now()`. 

This is problematic in the extreme when (a) my waterfall has a couple of 8sec response times for these js files, and (b) they're the same files from one click to the next (I'm just clicking next game).

you can [set up jquery](https://api.jquery.com/jquery.getscript/) to not append that cachebuster, and do some manual cache-busting on your own, and that would *tremendously* speed up page load times. (the next thing to do is not reload the page each time, but instead just tear it down and build it back up, so I don't have to re-load login, validate my login, reload everything else, etc etc, when getting the results of an attack).

in my dayjob, I use gulp-rev as part of my build process, which generates an md5 hash of the file's content and renames the file (so main.js becomes main.3434aaabbaa033.js). That way, if there's a rebuild that doesn't change a file, the md5 stays the same. I don't think y'all do the same kind of transpile / build workflow, but it could even be manually revved each time you release a new version, since these files rarely change.

**Comment by blackshadowshade** [comment]
Just saying that this is a great idea, and I'll be looking at this when I have the time to spare.

**Comment by blackshadowshade** [comment]
So, on a standard load of a game page, the network traffic looks like this:

GET game.html?game=26
GET gui.css
GET jquery-1.9.0.min.js
GET Loader.js?_=1498276844976
GET jquery.cookie.js?_=1498276844977
GET moment.js?_=1498276844978
GET Api.js?_=1498276844979
GET Config.js?_=1498276844980
GET Env.js?_=1498276844981
GET Login.js?_=1498276844982
GET Game.js?_=1498276844983
POST responder
POST responder
POST responder
POST responder
GET BMdefaultRound.png
GET d4active.png
GET d2active.png
GET d8active.png
GET d10active.png
GET d20active.png

Of these requests, I think that only the POSTs to responder really need to come back every time. The others should work fine if they're cached. I'm going to play around and see if I can get these to cache.

However, it's possible I'm missing something here, so if anyone knows why we shouldn't be caching all the other files, let me know.

**Comment by blackshadowshade** [comment]
While investigating game.html, I noted that the cache-control meta doesn't pass XHTML validation.

Apparently, the correct way to control page cache behaviour is to send HTML headers from the server, and not include the meta at all.

https://www.mnot.net/cache_docs/#IMP-SERVER

**Comment by ericeslinger** [comment]
I don't know how you are serving statics, but I use nginx. It has pretty
sensible defaults for stuff like cache control and etags. (And then proxy
requests to the API service). But php is a black box to me.

**Comment by blackshadowshade** [comment]
We're using Apache, so that would do all the handling, independent of the PHP layer.

**Comment by blackshadowshade** [comment]
So, I've proposed a pull request. Is this what you were suggesting, @ericeslinger?
