### ISSUE TITLE
no known way to force a JS cache refresh in firefox

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2255]
After the cache change merged in #2224 i am not aware of any way to get firefox tabs to refresh the UI when the javascript changes.  When i change the code and do a reload or a shift-reload, nothing changes.  Closing the tab and opening a new tab, again, no impact (i still see the old JS).  I haven't yet restarted firefox because that's kind of a timesink for me, though i'll try to check the next time i restart it for some other reason.  This is on firefox 55.0.3 on a mac.

A standard page reload does the right thing in Chrome.

This is a release blocker unless we can demonstrate somehow that no one other than me sees this - we need to be able to give people a method for updating the JS on the site when we do a release, and it seems that our standing recommendation of shift-reload no longer works under firefox.

**Comment by blackshadowshade** [comment]
I'm not certain that this is actually new. I've often had trouble forcing Firefox to do a correct force reload. However, I agree that it's problematic.

**Comment by cgolubi1** [comment]
I was literally not able to do a cache refresh in firefox yesterday.  Either there's a way to do it that i've forgotten, or this is worse than the last time i did UI development.  Because i am 100% sure that my workflow when doing UI development involves making changes and reloading pages, using firefox.

**Comment by cgolubi1** [comment]
So, when i revert #2224, a page reload applies my changes the way i'd expect.  So #2224 is definitely relevant.  I'm continuing to investigate.

**Comment by blackshadowshade** [comment]
At the risk of stating the obvious, I presume you've tried the following key combinations to force a hard refresh?

- Ctrl + F5
- Ctrl + Shift + R (or Cmd + Shift + R on Mac)
- Shift + (Click reload button)

**Comment by cgolubi1** [comment]
Hmm... i wonder if i had something stale in my firefox cache for my localhost site.  I did some futzing around with various combinations of turning off cache: true on the ajax calls, and when that didn't work, i manually cleared my browser cache, and now things *seem* normal with no change of code.

Let me test that again tomorrow to make sure it's reproducibly okay now.  If it is, it sounds like it could just be a bad cache state problem.  (I don't know how we could tell that any of our users didn't have such a problem, but still.)

**Comment by cgolubi1** [comment]
Nope, i'm having this problem again on my sandbox now.  Again, i was able to do something along the lines of:
* Load Game.js and display text "A" with caching enabled
* Change Game.js so it should show text "B".  Reload, i still see "A"
* Revert the cache change (4a4d3e574b2a963529a1795da4f7dd67a705c932).  Reload, i now see "B"
* Change Game.js so it should show text "C".  Reload, i see "C"
* Revert the revert.  Reload, and i now see "A" again

And then as soon as i clear my firefox cache, i can make as many changes as i want (well, i tried 5 or 6) with caching enabled, and the changes take effect and everything works just fine.  So i expect there's some time-related behavior here, but since everything works fine after a cache refresh, i'm having trouble reproducing it.  And i kind of wonder if this has something to do with firefox treating localhost specially in some broken way --- i might try hand-hacking one of the dev sites to see what i can see.

**Comment by blackshadowshade** [comment]
Argh. Sounds involved.

I seem to remember that Firefox tends to have a 24-hour cache duration by default, so it's *possible* that we can tell people to just wait a day before complaining, or to go and manually clear their Firefox cache. I agree, though, that if we can find a better way of fixing the problem, that would be far better.

**Comment by blackshadowshade** [comment]
From the third most popular answer at https://stackoverflow.com/questions/118884/how-to-force-browser-to-reload-cached-css-js-files, it seems that there is a plugin for apache called [mod_pagespeed](http://code.google.com/p/modpagespeed/) that might fix this problem.

**Comment by cgolubi1** [comment]
Thanks for finding that answer, shadowshade - i was kind of despairing about this issue, because i reproduced it on a dev site yesterday, so it's definitely not localhost-only.

It looks to me like if we can't use mod_pagespeed, we can probably implement the `auto_version()` function mentioned earlier on that page pretty easily.  But let me see if i can get mod_pagespeed working.

**Comment by cgolubi1** [comment]
Shadowshade: i haven't done the work to get the unit tests to pass yet, but if you take a look at https://github.com/cgolubi1/buttonmen/commit/c69b8fc975627ed2f1c85dfb38cf4074d0349193 it's a proposed implementation of autoversioning for JS files using puppet.

How it works is:
* When puppet runs, it computes the current timestamp, and executes new script setup_buttonmen_ui_cache_links with that timestamp.  That script does two things:
    * Move each BM JS files from `$fname.js` to `$fname.$timestamp.js`
    * Use sed to replace `VERSION_COOKIE` in each BM `.html` file with `$timestamp`, so that we're always using the versioned copy of `Loader.js` and of whatever script Loader is trying to load
* The assumption is that browsers may cache JS files wrongly, but they're going to cache HTML files correctly.  So we can count on browsers getting the right copies of the HTML files with the right numbers in them
* So if setup_buttonmen_ui_cache_links (i.e. puppet, i.e. a deployment) hasn't run since the last time you loaded a page, your browser will continue to try to use the same filenames, and may cache them too aggressively, but we don't care, because the files haven't changed.
* But if puppet has run since the last time you loaded a page, the timestamp will be different, and your browser will need to redownload all the BM javascript files
* Since we only run puppet when we do a deployment, i don't see any harm in making everyone reload their cache post-deployment; that doesn't seem like a problem at all (in fact, it seems very good - maybe it'll mean people won't need to shift-reload after a deployment).

If you like this solution, i'll:
* think about whether we want to do the same thing with the site CSS file (i can't see why we wouldn't)
* hook things up so that jenkins tests work

**Comment by cgolubi1** [comment]
Oh, one important portability note is that i put all the guts of the system into setup_buttonmen_ui_cache_links - so i *think* that means it shouldn't be prohibitive to make this work for non-puppet-managed test sites --- all you need to do is be able to point that script at the right place and get it to run.  Let me know if you see any hardships there, but IMO that's going to be much easier to sort than making everyone who wants to run the site install and configure mod_rewrite or mod_pagespeed or whatever (especially since we'd need code changes and/or link hackeration in addition to one of those solutions).

**Comment by blackshadowshade** [comment]
So, let's go with this and see whether we can get it working right with puppet. I'll have to do a bit of thinking about how to get this working on an AMP stack, but I guess the simplest way is to do a manual global replace.

Actually, can you have any easy way to have the VERSION_COOKIE only added when we're deploying with puppet? I'm happy having cache issues locally on my local AMP stack.

**Comment by blackshadowshade** [comment]
For completeness, I'm linking this to #772. If we solve this issue, we also solve that issue.

**Comment by cgolubi1** [comment]
Your simplest approach for AMP is to just `ln -s $x.js $x.VERSION_COOKIE.js` for every file in `ui/js` - that should always do the right thing if you don't care about caches.

**Comment by blackshadowshade** [comment]
Sounds reasonable to me.

**Comment by cgolubi1** [comment]
Sounds good.  Hmm, i'm actually suspicious that i may not have to change the jenkins stuff at all to make the tests pass - i made all the changes to the HTML files, and i think our phantomjs/QUnit rig doesn't actually use those files.  I'm trying it out, anyway.

**Comment by cgolubi1** [comment]
Yep, it looks like Jenkins just passed, because it doesn't use the HTML files, so i went ahead and added gui.css to the rig (and tested that i could change the "selected" die box from red to green and see the change in firefox and chrome without a force-reload).  I've put up a PR for that, and if it's accepted, then i think we can consider the release unblocked in terms of any major UI changes we want to make.
