### ISSUE TITLE
Game showing up as "Created by undefined" in game accept UI

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2260]
I created http://staging.buttonweavers.com/ui/game.html?game=107 by clicking "Change first player", selecting irilyth, selecting blackshadowshade as the second player, and choosing Random button for both players.

The action log correctly knows that i created the game.  The header bar shows:
```
Game #107  •  irilyth (Magistra) vs. blackshadowshade (bluebec)  •  New Game  •  Created by undefined
```

Diagnose and fix.

**Comment by cgolubi1** [comment]
Clearing my browser cache fixed the problem.  Makes sense --- nothing is causing Api.js to use version cookies.

**Comment by blackshadowshade** [comment]
I've just created Game 108 the same way, and I'm seeing no bug.

> Game #108  •  glassonion (Lion) vs. irilyth (Bull)  •  New Game  •  Created by blackshadowshade

**Comment by blackshadowshade** [comment]
Ah, interesting. So, do we need to fix this or not?

**Comment by cgolubi1** [comment]
Okay, so the obvious answer, if we don't mind doubling down on the version cookie solution, is to place and substitute the magic VERSION_COOKIE string inside `Loader.js`'s `Loader.defaultScripts` array.

I think we need to fix it, because the symptom is pretty confusing --- new data that the API makes available isn't used by the UI because we don't get the new version of Api.js, so it doesn't show up in the `Api.game` variable.

**Comment by blackshadowshade** [comment]
Okay, if you get a pull request in for that over the next few days, I'll see if I can get it approved.

**Comment by cgolubi1** [comment]
Will do.
