### ISSUE TITLE
regression: button art not displayed due to #2270

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2283]
I realised on the staging site that some of the buttons whose names were changed in #2270 had art.  Button names shouldn't matter for anything in the database, but button art is loaded based on the button name not its ID.  So we'll need to update those files.

**Comment by cgolubi1** [comment]
It's probably just as fast to put up my own PR as it is to enumerate which buttons lost art, but i want to actually test it to make sure it's fixed.

At the least, Carson(p) has art.  I'll either get a PR up, or approve shadowshade's PR, whichever of us gets to it first.

**Comment by cgolubi1** [comment]
Also: i'd be grateful if someone could verify that we didn't lose pre-rename game history for these buttons.  I can't see why we should have, but i spot-checked a couple and couldnt' find any played games.  Maybe there just weren't any previously-played games for these buttons on staging?  I haven't checked that yet.

**Comment by blackshadowshade** [comment]
Okay, pull request in. I'll check for previous games now.

**Comment by blackshadowshade** [comment]
http://staging.buttonweavers.com/ui/history.html#!buttonNameA=Montague%20(Blademasters)

That shows two games currently in progress.
