### ISSUE TITLE
JS caching results in blank pages

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2288]
The new JS caching scheme doesn't work quite correctly with the "Go to your next pending game" link.  For the first several games i played after updating the site this morning, clicking that link gave me a blank page.  Shift-reloading fixed the problem each time.

The issue, per firebug, was that it was trying to load `Api.<old_datestamp>.js`.  Something in the next pending game link code path must cache the old value of that URL directly.

The behavior recovered after awhile, and now i'm no longer seeing it.  So i think the problematic script itself must also eventually time out of cache.

**Comment by cgolubi1** [comment]
I'll check and see if the issue is obvious at some point, but for now i'm mostly making an issue so that if other people see this, we'll have somewhere to record it.

**Comment by dwvanstone** [comment]
I do see what might be the same issue. When I click "Go to your next pending game" I get a blank page - hitting reload loads the page fine.

**Comment by blackshadowshade** [comment]
I too noticed that that link arrived at a blank page. However, I was battling with connection issues on my end, so I thought the blank page was a symptom of my connection issues.

**Comment by blackshadowshade** [comment]
Generally, the site feels sluggish at the moment, so I'm having trouble working out which pages will entirely fail loading, and which are simply really slow.

**Comment by AdmiralJota** [comment]
I'm getting the blank page (with the 404's for old-timestamped javascript includes) periodically from the monitor. It looks like it's happening when it tries to load the game page for the newly-updated game (with the auto=true appendix in the URL query string).

**Comment by irilyth** [comment]
I haven't checked too carefully, but my vague impression is that I'm getting one of these per game, but then not a second time for any given game.

**Comment by blackshadowshade** [comment]
Okay, just confirming that this has happened again since the December release, as expected. Looks like we'll need to address this sooner rather than later.

**Comment by cgolubi1** [comment]
Thanks.  I'll plan to get something in this month.

**Comment by blackshadowshade** [comment]
So, I'd like to revisit this issue, and possible fixes.

Is it possible, for example, to add a symbolic link from the current Api.*.js to the location of the previous Api.*.js?

**Comment by blackshadowshade** [comment]
I'd like to revisit this issue of JS and CSS caching, because it appears that there may be a number of somewhat simple solutions:

https://stackoverflow.com/questions/118884/how-to-force-the-browser-to-reload-cached-css-js-files

**Comment by blackshadowshade** [comment]
@cgolubi1, if we're going to move toward more frequent deployments (which I support fully), I think we need to take a good look at this issue and see if we can resolve it sooner rather than later.
