### ISSUE TITLE
Changing chat settings should preserve chat textbox

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2296]
I'd prefer it if hitting "Prefer private chat" or "Prefer public chat" wouldn't clear out the Chat textbox.

The use case was that I was in a game with a public chat, and as I was responding to a chat I decided partway that this was might be better as a private chat. And so I hit "Prefer private chat" which deleted all of the content I had typed in. Hitting the Back button did not bring back the chat contents, so I had to start again.

Thanks!

**Comment by irilyth** [comment]
Ugh, I just got bitten by this -- super annoying! :^(
