### ISSUE TITLE
History page shows "null" in button column when button is unspecified

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2298]
Mentioned by @dwvanstone in #2297.

> I don't know if it's an issue, but when I go to the History page and look for Unstarted games I find games 98 and 99 which are user "emuking" vs. user "null". I assume this is a data migration issue and wouldn't happen on the production site, but I wanted to check.

**Comment by cgolubi1** [comment]
With the fix, the staging site looks good to me now.  Any other issues?
