### ISSUE TITLE
radioactive trip memory exhaustion bug

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2304]
I can do a responder test for this if we want to go that route, but for the time being i think i will just share the stacktrace and a screencap, and we can all go to our rooms and think about the mistakes we've made in our lives for a few minutes, then regroup and decide what to do about it.

Stacktrace:
```
Starting game 29
could not parse return:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/engine/BMDie.php on line 324

Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1536, in log_test_game
    self.next_game_action()
  File "lib/random_ai.py", line 1520, in next_game_action
    if state == 'START_TURN': self._game_action_start_turn()
  File "lib/random_ai.py", line 1426, in _game_action_start_turn
    self.loaded_data['playerDataArray'][0])
  File "lib/random_ai.py", line 1333, in _game_action_start_turn_player
    retval and retval.message or "NULL"))
  File "lib/random_ai.py", line 1435, in bug
    raise ValueError, message
ValueError: API submit_turn(29, 1, 0, {'playerIdx_1_dieIdx_11': 'false', 'playerIdx_1_dieIdx_10': 'false', 'playerIdx_1_dieIdx_13': 'false', 'playerIdx_1_dieIdx_12': 'false', 'playerIdx_1_dieIdx_15': 'false', 'playerIdx_1_dieIdx_14': 'true', 'playerIdx_0_dieIdx_0': 'true', 'playerIdx_1_dieIdx_9': 'false', 'playerIdx_1_dieIdx_8': 'false', 'playerIdx_1_dieIdx_1': 'false', 'playerIdx_1_dieIdx_0': 'false', 'playerIdx_1_dieIdx_3': 'false', 'playerIdx_1_dieIdx_2': 'false', 'playerIdx_1_dieIdx_5': 'false', 'playerIdx_1_dieIdx_4': 'false', 'playerIdx_1_dieIdx_7': 'false', 'playerIdx_1_dieIdx_6': 'false'}, Trip, 2, 1513633959, {}) unexpectedly failed: NULL
```
![radioactive_trip_insanity](https://user-images.githubusercontent.com/2898207/34321651-9253f502-e7e2-11e7-904b-850a01ee3e1d.png)

**Comment by cgolubi1** [comment]
So: i see a couple of problems here:
* We've historically been on the fence about what should happen when you trip a radioactive die (and i've mostly stayed out of it, so apologies if i'm retreading familiar ground here).  I'd like to throw down the gauntlet --- radioactive decay should lead to removal of the radioactive skill, period.  I don't care at all whether unsuccessful trip attacks lead to decay or not, but once radioactive is triggered, it has to be lost.
* This game is stuck, but the backend hasn't figured that out.

IMO those two problems are the important ones, and the memory exhaustion symptom is not very important, because fixing either of those problems would remove the need for the game to be in this silly state.

**Comment by cgolubi1** [comment]
Ah, it doesn't have anything to do with twin --- here's a version with a non-twin trip die:
![more_wtrollkin](https://user-images.githubusercontent.com/2898207/34321738-55648682-e7e4-11e7-8209-dbbae5472f65.png)

I noticed this because it keeps crashing my master replay site, FYI.  :>(

**Comment by cgolubi1** [comment]
Hmm, wait, i'm wrong about the second thing --- the game isn't stuck.  Scrollback implies that it's only trying trip attacks with the `t(1)` dice, and there's no reason one of those couldn't eventually succeed.  So either we need to tackle the memory bug or change the behavior of radioactive+trip.   Again, my vote is for the latter.

**Comment by AdmiralJota** [comment]
While peeking at the source to see if it was obvious what was going on, I happened to notice this (mostly) unrelated comment from BMUtilityHitTable.php:

    public function __construct($dice) {
        // For building hash keys, every die needs a unique
        // identifier, no matter how many there are, but if there are
        // more than 36 dice, something is very, very wrong.
        $ids = str_split("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789");

I'm not sure that "more than 36 dice" is necessarily an implausible circumstance at this point...

But more seriously: that looks like a stack trace from the random_ai python client, but was there any server-side stack trace logged for the out of memory error?

Also, do we know who created the Radioactive skill? We could just ask them whether or not the original intention was A) for Radioactive to trigger on an unsuccessful Trip attack, and B) if so, for the Radioactive die to keep the skill after the Trip die had decayed.

**Comment by cgolubi1** [comment]
The server-side error is:
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/engine/BMDie.php on line 324
```

(which is displayed in the python trace above --- i just included the whole thing because it also shows the attack being attempted).

**Comment by cgolubi1** [comment]
I sometimes care about authorial intent, but in this case IMO it will be better for gameplay, site stability, and simplicity if the radioactive skill is always removed from the die when it triggers.  IMO the case is sufficiently strong that i'd like to hear a counterargument in which someone says "I believe it is better if radioactive is not always removed from the die when it triggers because of X reasons" --- like, i don't think we should keep the inconsistency because we think people not in the conversation might prefer it for reasons we don't know.

**Comment by blackshadowshade** [comment]
Cool bug there, Chaos!  :)

**Comment by AdmiralJota** [comment]
I was hoping we might be able to see more of the server side trace -- what had called that method, and what had called *that*, etc. -- but I guess that's not available.

Regarding authorial intent and all, I was mainly thinking that if radioactive was never intended to trigger when the die wasn't actually captured, then there's no *need* to explicitly remove it, since the die wouldn't be in play at that point anymore anyway.

**Comment by blackshadowshade** [comment]
So, linking relevant issues (where we decided and implemented that unsuccessful trip attacks cause radioactive dice to split without losing radioactive):

#1432: Should a *failed* Trip attack on a Radioactive die cause the Trip die to decay?
#1919: Trip vs Radioactive when the Trip Attack fails
#1928: Fixed bug where unsuccessful trip attacks targeting radioactive fail to split

**Comment by irilyth** [comment]
I think the question is whether it should trigger and be removed when targeted by a Trip Attack that fails, or neither of those things. I don't have a strong opinion either way. Who is the author? Could we ask them?

**Comment by cgolubi1** [comment]
> I was hoping we might be able to see more of the server side trace -- what had called that method, and what had called that, etc. -- but I guess that's not available.

It is not --- we don't log more than a single line even on the server side.  If we decide to go the route of fixing the memory exhaustion issue, i'll put up a responder test and then anyone can reproduce it at their leisure.

**Comment by blackshadowshade** [comment]
This reminds me of #1404, where Aysez broke the site. It indicates to me that the underlying code to check for valid attacks is wrong, not necessarily that the skills are inherently broken.

I *think* that I can fix this by ignoring zero-value dice from skill attack checking. Let me take a look tonight.

**Comment by blackshadowshade** [comment]
Also, 👍 for RandomAI!

**Comment by AdmiralJota** [comment]
So... given that the memory bug is presumably only tangential to the trip/radioactive situation, what *is* the argument in favor of changing how the skill works? Sure, the current situation is goofy, but aside from it helping to expose a separate memory bug, what's broken about it?

**Comment by cgolubi1** [comment]
Yeah, i think, all else equal, the idea of ignoring zero-valued dice from skill attack checking is a good plan for preventing us from being hoist by our own silliness.  :>)

IMO we should also change the behavior of radioactive on unsuccessful trip attacks --- i don't care very much in which direction, but the middle ground strikes me as simply a bug.  One suggestion is: since we discussed this at length before and wound up with trip attacks triggering radioactive, should we resolve it in that direction for now (upon trip attack, trigger and remove radioactive), and worry about the rest of it later?

**Comment by AdmiralJota** [comment]
Also, regarding ignoring 0-sided dice: don't forget that there may be cases where they do matter. E.g., when it makes a difference how many dice are participating in an attack (such as with Stealth).

**Comment by blackshadowshade** [comment]
Note to self: also need to check whether the target dice have a zero-valued die before ignoring potential zero-valued dice.

**Comment by dwvanstone** [comment]
I expect Radioactive to be similar to Jolt; I'd only expect a decay to happen once per radioactive die, and an extra turn to be granted once per Jolt die. It feels like a bug to keep decaying each trip attack.
