### ISSUE TITLE
generating 40 t(0) dice is too silly and we should do something different

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2307]
The label comes from blackshadowshade's comment about this on #2306.  My actual request is: we create and enforce a rule that, whenever radioactive is triggered (a die splits due to radioactive), all dice involved in the attack which have the radioactive skill lose it.

Note: this issue will be satisfied whether or not trip dice continue to decay after unsuccessful attacks on radioactive dice --- the request is just that IF a die decays THEN the radioactive skill is lost.

**Comment by cgolubi1** [comment]
There are several types of rationale we've historically used when deciding how skills are going to be implemented.  Here are all the ones i can think of offhand:
* Authorial intent: what did the original authors of the skill have in mind?
* Prior art: how did the DHS site implement this?
* Simplicity: what makes the rule for the skill easy to state in words and understand?
* Halting: what allows us to avoid non-terminating or broken game states in the implementation?
* Fun: what seems like people would enjoy playing it?

Prior art weighed heavily in our earlier discussions of implementation, because our site didn't work yet, and we all (thought we) remembered how the DHS site worked somewhat well.  IMO it's much less important (and harder to remember) now.

For me right now, the most important considerations are simplicity and halting, and on both of those grounds, "the radioactive skill is always removed from dice when it is triggered" strikes me as a no-brainer implementation choice:
* Simplicity: Either radioactive is triggered or it isn't.  If it is triggered, the same sequence of things (decay + loss of radioactive) always happens.  This is less complicated than any implementation in which loss of the radioactive skill sometimes does and sometimes doesn't accompany radioactive decay.
* Halting: radioactive is a destabilizing skill with a lot of weird side effects.  If you can radioact at most N times, where N is the number of dice in both players' buttons - 1 (i think), that makes the number of weird side effects we will see that much more tractable.

To me, those are going to outweigh an authorial intent or fun argument unless it's really really compelling.  But if anyone likes the current behavior (which i'm going to persist in calling "inconsistent") have at it, and remind me why we think that behavior is good.

**Comment by cgolubi1** [comment]
Can we please raise this topic again?  I feel strongly that i'm right about my initial ask: "whenever radioactive is triggered (a die splits due to radioactive), all dice involved in the attack which have the radioactive skill lose it".  I'd like to ask people who care to engage with the argument.

It turns out that i think #2306 bitrotted (how did we manage to commit that without a responder test?) when we upgraded OS, and i'll file that as a separate issue, but i think we're just plain wrong about the rules here.

![too_many_zero_sided_dice](https://user-images.githubusercontent.com/2898207/51787287-d6ae9c80-213d-11e9-8f84-d6f6831a22bf.png)

**Comment by blackshadowshade** [comment]
I have no problem with changing both the wording and the definition of the radioactive skill in favour of what @cgolubi1 is requesting here.

**Comment by blackshadowshade** [comment]
I also note that @dwvanstone is in favour of making such a change, as mentioned here:

https://github.com/buttonmen-dev/buttonmen/issues/2304#issuecomment-353889900

**Comment by irilyth** [comment]
I think it's better (more fun) to change Radioactive than to change Trip, and that changing Radioactive is fine. The actual wording you have there isn't quite right because Radioactive has a list of other skills that the decaying die loses, and I think the target die in a failed Trip Attack shouldn't lose *those* skills; so I think we want a phrasing something like "a die that decays loses these skills; and any die involved in the attack loses Radioactive".

**Comment by blackshadowshade** [comment]
The current description of Radioactive is

> If a radioactive die is either the attacking die or the target die in an attack with a single attacking die and a single target die, the attacking die splits, or "decays", into two as-close-to-equal-sized-as-possible dice that add up to its original size. All dice that decay lose the following skills: Radioactive (%), Turbo (!), Mad Swing (&), Mood Swing (?), Time and Space (^), [and, not yet implemented: Jolt (J)]. For example, a s(X=15)! (Shadow Turbo X Swing with 15 sides) that shadow attacked a radioactive die would decay into a s(X=7) die and a s(X=8) die, losing the turbo skill. A %p(7,13) on a power attack would decay into a p(3,7) and a p(4,6), losing the radioactive skill.

with interactions as follows:

            'Berserk' => 'Dice with both Radioactive and Berserk skills making a berserk attack ' .
                         'targeting a SINGLE die are first replaced with non-berserk dice with half ' .
                         'their previous number of sides, rounding up, and then decay',
            'Doppelganger' => 'Dice with both Radioactive and Doppelganger first decay, then ' .
                              'each of the "decay products" are replaced by exact copies of the ' .
                              'die they captured',
            'Mad' => 'Dice with the Mad skill lose Mad when they decay due to Radioactive',
            'Mood' => 'Dice with the Mood skill lose Mood when they decay due to Radioactive',
            'Morphing' => 'Dice with both Radioactive and Morphing skills first morph into the ' .
                          'size of the captured die, and then decay',
            'TimeAndSpace' => 'Dice with the TimeAndSpace skill lose TimeAndSpace ' .
                              'when they decay due to Radioactive',
            'Turbo' => 'Dice with the Turbo skill lose Turbo when they decay due to Radioactive',

In the next post, I'll propose how we might change the wording. As usual, suggestions or corrections are welcome.

**Comment by blackshadowshade** [comment]
So, the second sentence could be replaced by two sentences like this:

> If any die splits during an attack due to radioactive, all dice involved in the attack lose Radioactive (%). All dice that decay lose the following skills: Turbo (!), Mad Swing (&), Mood Swing (?), Time and Space (^), [and, not yet implemented: Jolt (J)].

**Comment by cgolubi1** [comment]
Your new wording sounds like what i want.  Other folks?

**Comment by cgolubi1** [comment]
Also: i'm not going to bother to make a responder test for the memory exhaustion bug RandomAI tripped over which brought this back onto my radar.  For posterity, here's the stacktrace, with the game state as screencapped above.  But we're not going to run into this if we don't have 40 zero-sided dice, so i don't think it should be a priority:

```
[Thu Jan 10 16:19:57.026699 2019] [:error] [pid 3124] [client 127.0.0.1:56848] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194312 bytes) in /var/www/engine/BMUtilityHitTable.php on line 108

Starting game 37
could not parse return: <br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194312 bytes) in <b>/var/www/engine/BMUtilityHitTable.php</b> on line <b>108</b><br />

Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1608, in log_test_game
    self.next_game_action()
  File "lib/random_ai.py", line 1592, in next_game_action
    if state == 'START_TURN': self._game_action_start_turn()
  File "lib/random_ai.py", line 1498, in _game_action_start_turn
    self.loaded_data['playerDataArray'][0])
  File "lib/random_ai.py", line 1405, in _game_action_start_turn_player
    retval and retval.message or "NULL"))
  File "lib/random_ai.py", line 1507, in bug
    raise ValueError, message
ValueError: API submit_turn(37, 1, 0, {'playerIdx_1_dieIdx_11': 'false', 'playerIdx_1_dieIdx_10': 'false', 'playerIdx_1_dieIdx_13': 'false', 'playerIdx_1_dieIdx_12': 'false', 'playerIdx_1_dieIdx_15': 'false', 'playerIdx_1_dieIdx_14': 'false', 'playerIdx_1_dieIdx_16': 'false', 'playerIdx_0_dieIdx_0': 'false', 'playerIdx_0_dieIdx_1': 'true', 'playerIdx_1_dieIdx_9': 'false', 'playerIdx_1_dieIdx_8': 'false', 'playerIdx_1_dieIdx_1': 'false', 'playerIdx_1_dieIdx_0': 'true', 'playerIdx_1_dieIdx_3': 'false', 'playerIdx_1_dieIdx_2': 'false', 'playerIdx_1_dieIdx_5': 'false', 'playerIdx_1_dieIdx_4': 'false', 'playerIdx_1_dieIdx_7': 'false', 'playerIdx_1_dieIdx_6': 'false'}, Trip, 3, 1547137188, {}) unexpectedly failed: NULL
```

**Comment by dwvanstone** [comment]
> If any die decays during an attack, all dice involved in the attack lose Radioactive (%).

This is perfect. Thank you!

**Comment by blackshadowshade** [comment]
Okay, I've started working on this, and if I implement the extra rule that targeted radioactive dice lose radioactive, then a whole pile of action logs change, because the captured radioactive dice change recipe on their way out.

Did we want this? Or did we only want those targeted radioactive dice *that remain in play* to lose radioactive?

**Comment by cgolubi1** [comment]
Yeah, i think it's slightly better for players to have captured radioactive dice keep radioactive, so if it doesn't make your logic a lot more complicated, do it that way.

But if it does make the logic too hard to cope with, it doesn't matter very much.

**Comment by cgolubi1** [comment]
If you think you need to change the wording, i think "If any die decays during an attack, all dice involved in the attack which remain in play lose Radioactive (%)" should be fine --- i don't think players really expect the rules to talk much about what happens after dice leave play for skills which don't matter after dice leave play, though, so you can probably leave the wording as you proposed it.
