### ISSUE TITLE
Add Mutton Ben

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2345]
In #2187, we added all the standard and sideboard buttons from the Kickstarter, but not the promo buttons.

Mutton Ben was part of the Funvelope, and can be seen here:
https://www.kickstarter.com/projects/cheapassgames/button-men-beat-people-up/posts/2033535

The recipe is p(8) #(12) s(20) (X) (X).

It's not clear whether this button should be considered to be tournament legal.

Some of the discussion around Mutton Ben (http://www.buttonweavers.com/ui/forum.html#!threadId=593) suggested that we add it to a promos set. Would we consider it to be a 2017 or 2018 promo?

Also, we're waiting on an button image of appropriate quality for this button.

**Comment by irilyth** [comment]
Got art!
![muttonben](https://user-images.githubusercontent.com/4923138/39336503-dff7be60-4985-11e8-9d9d-31e4f3552d95.png)

**Comment by blackshadowshade** [comment]
@Hurtay, are you good to do the standard modifications to this?

**Comment by irilyth** [comment]
Cassidy Werner <cheapasscassidy@gmail.com> confirms that Mutton Ben is NOT TL.

**Comment by blackshadowshade** [comment]
So, @Hurtay has confirmed to me that she'll put the button image in the standard format.

Any thoughts on what we call the button set? As a starting point, we have a number of alternative versions of the same sort of thing (which could probably do with some standardisation):
"1999 Rare / Promo"
"2000 Rare / Promo"
"2003 Rare-Promos"
"2005 Rare Promo"

**Comment by AdmiralJota** [comment]
Hmm. Do we want to keep all the rare promos in separate sets by year, or do we want to combine them all?

Either way, I'd suggest standardizing on "Rare Promo", mainly because the "/" makes for a weird URL.

**Comment by blackshadowshade** [comment]
I'd be fine with having a combined rare promos set.

**Comment by irilyth** [comment]
I think combining is fine; I think some way to indicate that it's both rares and promos would be good, as "Rare Promos" sounds like it's things that are both. (Maybe it is, but the previous names with / make it seem like there may have been rare buttons that weren't promos, or promos that weren't rare, or whatever.)
