### ISSUE TITLE
Fix TL status of buttons

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2347]
In http://www.buttonweavers.com/ui/forum.html#!threadId=42&postId=12420, it was noted that ConMan is not TL.

http://www.zatrolene-hry.cz/dialog/download-file?id_soubor=871 (which has been cached in https://github.com/buttonmen-dev/buttonmen/blob/master/notes/database/button-men-pravidla-cz.pdf) has a list of TL status for many of the buttons. The TL status on the site should be checked against this.

**Comment by blackshadowshade** [comment]
Differences according to this list:

Max is not TL
Bridge and Tunnel buttons are not TL (Agent Orange, Huitzilopochtli, Lisa, Nethershadow, Phuong, Uncle Scratchy)
Button Brains buttons are not TL
Apples and Green Apple are not TL
Diceland buttons are not TL
Dead Guy is TL !!!!!
Carson is not TL
Most of the Metamorphers are not TL (Daisy, Jingjing, Spencer, Talus)
Count Repugsive is TL
Angora is not TL
Amara Wintersword is not TL
Captain Bingo is not TL
Oni is not TL
Spite is not TL
Super Germ is not TL
Dr. Speculo is not TL
Harry Pudding is not TL
MothMan is not TL
Assailer is not TL
Harbinger is not TL
ConMan is not TL
Pikathulhu is not TL
Ulthar is not TL

**Comment by blackshadowshade** [comment]
One obvious question is whether this list is up to date or not. It seems to be based on www.randomdice.com, and it has the www.buttonmen.dhs.org site referenced, so it's quite possible that it accurately reflects what was on the old site.

**Comment by blackshadowshade** [comment]
Naturally, any changes here that agree with the official site https://beatpeopleup.cheapass.com/tournament-list/ should definitely be adopted. That means, for example, that Angora will definitely end up being not TL.

**Comment by irilyth** [comment]
As a random other question: Where did the TL status for buttons on the new site come from in the first place? How did we get so many of them wrong, or at least "at odds with this other list"?

**Comment by blackshadowshade** [comment]
I'm not certain that we can answer that definitively, considering that Fog was the one who did most of the work on compiling the information on the buttons.

**Comment by irilyth** [comment]
Cassidy Werner <cheapasscassidy@gmail.com> confirms that ConMan is not TL.

We could probably ask them about the others, or otherwise suggest that they update https://beatpeopleup.cheapass.com/tournament-list/ -- I'm happy to do that if that'd be useful.
