### ISSUE TITLE
skill sum bug triggered by Dead Guy

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2350]
When Dead Guy attempts to make a skill attack including more than two 0-sided dice, the attack fails with 'Attacking die values do not sum up to target die value.'

**Comment by cgolubi1** [comment]
I created a branch, dead_guy_skill_sum_bug, with a new responderTest that shows this.  It should be failing in https://circleci.com/gh/cgolubi1/buttonmen/66 as we speak.

**Comment by cgolubi1** [comment]
If you look up that error message in the code, the immediate trigger is pretty obvious --- `is_assisted_attack_valid()` is returning false because `($bounds[0] == 0 && $bounds[1] == 0)`.  But what's not clear to me is why we're even getting there --- fire has nothing to do with this attack.  I would think that `is_direct_attack_valid()` would return true, and we wouldn't even get to the fire code.  So presumably that's where the bug is, so it must have something to do with hit table generation.

**Comment by cgolubi1** [comment]
Worth noting (i couldn't figure out how to trivially include both attacks in my test, but you can validate this by hand while you're working on it) --- if you replace the attack with a should-be-identical attack containing only two 0-sided dice, it will succeed:

```
        $this->verify_api_submitTurn(
            array(0, 0, 2),
            'responder003 performed Skill attack using [(0):0,(0):0,(6):3] against [(4):3]; Defender (4) was captured; Attacker (0) rerolled 0 => 0; Attacker (0) rerolled 0 => 0; Attacker (6) rerolled 3 => 2. ',
            $retval, array(array(0, 0), array(0, 1), array(0, 5), array(1, 1)),
            $gameId, 1, 'Skill', 0, 1, '');
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Skill attack using [(0):0,(0):0,(6):3] against [(4):3]; Defender (4) was captured; Attacker (0) rerolled 0 => 0; Attacker (0) rerolled 0 => 0; Attacker (6) rerolled 3 => 2'));
```

**Comment by cgolubi1** [comment]
In terms of priority: obviously this isn't going to impact that many live players as is --- it's causing my replay test loops to fall over reasonably often, and i assume it's a regression caused by the previous work you did on radioactive zero-sided dice, because it's not something i ever saw before a few months ago, which i'm guessing is the same time that stuff was merged.

**Comment by blackshadowshade** [comment]
Okay, I've taken a look, and this bug is caused directly by my introduction of the function BMAttackSkill->strip_excess_zeros() in #2306. I'll see if I can fix this better.
