### ISSUE TITLE
turbo fire vs radioactive internal error

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2351]
When North Carolina's turbo die performs a fire-assisted power attack against a radioactive die, the attack raises an internal error:

```
Undefined property: BMGame::$turboCache in /var/www/engine/BMGame.php on line 3135, referer: http://localhost:8080/ui/game.html?game=1
```

**Comment by cgolubi1** [comment]
I've triggered this in replay testing once, and someone has tripped over it on the live site as well.  Working on a simple responder test now.

**Comment by cgolubi1** [comment]
Note: it looks like after the attack North Carolina's turbo die correctly splits and loses radioactive.  So this may be a simple problem of fixing whatever's causing the internal error to be thrown.

**Comment by cgolubi1** [comment]
I add a test in https://circleci.com/gh/cgolubi1/buttonmen/69 which will hopefully demonstrate this bug.

**Comment by blackshadowshade** [comment]
Okay, I can reproduce that manually, and it looks like the error is entirely invisible to a player. I'll take a look at what's going on here, and assuming that the error is unnecessary, I'll just remove it.
