### ISSUE TITLE
Show TL Status on Button Page

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#2352]
The page for an individual button should indicate whether or not that button is tournament legal.

**Comment by AdmiralJota** [comment]
Mock up of what it might look like:

![image](https://user-images.githubusercontent.com/5848173/39136849-221a585a-46ea-11e8-8dcb-508ae2c60944.png)

Any comments? Should it display "Not Tournament Legal" if a button isn't TL, or only display a message when it *is*?

**Comment by AdmiralJota** [comment]
A gist that I think will cover this: https://gist.github.com/AdmiralJota/f463536b8d34879bddcaf129ea3e86f3

**Comment by dwvanstone** [comment]
I think the page should display all attributes about the button, such as "Tournament Legal". Down the line we may define other attributes ("Fair") that could also be displayed here. I don't think it's useful to define when something doesn't have an attribute, unless you think "Non-Tournament Legal" is a useful attribute.

**Comment by AdmiralJota** [comment]
In theory, the page should already be displaying any other tags (like "Fair"), but we haven't implemented any actual tags yet, so there's nothing to display. Since TL was defined separately, that didn't get included.

That said, one alternative here would be to move Tournament Legal into a tag. That would require a SQL script update to every button, but it would mean we shouldn't need any code changes to the site itself. Which approach would be better?

**Comment by blackshadowshade** [comment]
I think that it *is* actually useful to display when a button is "not tournament legal".

As for the implementation, maybe @cgolubi1 could chime in here and state what her preference is.

**Comment by irilyth** [comment]
If there's a bunch of flags, I think it'd be nice to have a little table showing the value of each of them, but don't feel too strongly about it.
