### ISSUE TITLE
Allow tables in forum posts

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2356]
Our users often try to use tables in their forum posts, and we should make it possible for them to do this in a way that actually looks like a table.

Blargh also mentioned that it would be nice to be able to cut and paste the table. For that, we'd need to know what sort of formats to support.

**Comment by irilyth** [comment]
Hmm, I'm skeptical of this: I think that making a wiki page is a way better way to track the kinds of things we tend to put in tables, than constantly editing an old forum post.

If there's another use case for tables, it might be worth doing, but given that the wiki works really well for this already, I don't think this should be a very high priority.

**Comment by blackshadowshade** [comment]
@AdmiralJota has created a HTML/JQuery page that can convert tables from Excel into appropriate tables for our forums.

I've decided that it's enough to simply add this tool to our BM site as a standalone page for the moment. We could link this from our help pages eventually.
