### ISSUE TITLE
tear down jenkins site

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2399]
We are no longer using jenkins.buttonweavers.com.  Tear it down.

Acceptance criteria:
* Tear down the instance itself and any associated EBS volumes
* Remove all puppet code from the repo which is only used by the jenkins site

**Comment by cgolubi1** [comment]
I'd like to get rid of the jenkins instance and its volumes at this time.  Any objections?  Shadowshade: if it's fine with you, i probably don't need anyone else's buy-in.  (I know your thumbs-upped the initial issue, but this will be hard to undo if i'm wrong, so it can't hurt to double-check.)

**Comment by blackshadowshade** [comment]
Let's do this. Bye bye, Jenkins!

**Comment by cgolubi1** [comment]
I finally actually did this, terminated the instance, deleted its secondary volume, and released the jenkins.buttonweavers.com EIP.
