### ISSUE TITLE
Fan button set (nominally GWAR, but could also be themed to Ultimate Muscle)

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2408]
theorgg would like to test a fan button set, as mentioned here:

http://www.buttonweavers.com/ui/forum.html#!threadId=660

Discussion continued in game chat, see here:

http://www.buttonweavers.com/ui/game.html?game=43032 (and also chat from previously linked games)

Recipes and images were received by email (see next post).

**Comment by blackshadowshade** [comment]
Recipes:

1. Blothar, Berzerker Warrior
(6) (20) (30) (X) `(8) `(8) `(12)

2. Balsac the Jaws O' Death
M(6) M(8) (12) (20) (P)
(A "P" swing die is from 1 to 30.)

3. Jizmac Da'Gusha
M(4,4) (8) g(12) (12) (P)
(A "P" swing die is from 1 to 30.)

4. Pustulus Maximus
g(4) g(12) (12) (20) (X)

5. Beefcake the Mighty
H(4) H(6) (12) (20) (V,V)

6.Sleazy P. Martini
Stinger(4) (20) (X) (X) (X)

7. Dickie Duncan
(4,4) (6,6) (8,8) (Y,Y)

8. Techno Destructo
(12) (8,8) p(30) p(30) (X)

9. Sawborg Destructo
(12) (12) (20) (20) p(P)
(A "P" swing die is from 1 to 30.)

10. Bozo Destructo
p(2) (2) (6) (8)

11.Estrogina
(6) (12) M(T) (T)

12.Mr. Perfect
(1) (1) (2) (4) M(6)

13.The Master
(30) (30) (30) (U)

14.Gor-Gor
(8) (12) (20) p(30) (U)

15. Slyminstra Hymen
(4) (6) g(8,8) (12) (Y,Y)

16. Sexecutioner
(6,6) (12) (X) (X) (X)

17. Flattus Maximus
(4) (12) p(12) (20) p(X)

18. Dr. Skullheadface
g(X) (X) p(Y) (Y)

19. Morality Squad
(4) (6) H(6) (V,V) `(6) `(8)

20. Cardinal Syn
g(4,4) g(8) (8) (12) (Y)

21. Oderus Urungus
(6) (8) (10) (12,12) (X)
Any Poison dice Oderus captures are scored as standard dice, not as poison dice.

22. Porcelon, Portal Potty
(6) (8) (12) (12)
After determining who goes first, Porcelon may "flush" one of his opponent's dice, removing it from the game for the round.

23. Scroda Moon
(1) (4) (4) (12) (P)
You may remove one die from your dice pool this round to force your opponent to re-roll one of their dice on your turn before you attack.  (A "P" swing die is from 1 to 30.)

24. Flesh Column
The Flesh Column's starting dice are based on your opponent's, but one available die size lower.  If this cannot be determined, flesh column's starting dice are four "Y" swing dice. Swing dice are unaffected and you chose their size. (A "Y" swing die is from 1 to 20.)

25. World Maggot
(20) (20) (20) (30) (20/30)

26.  Bonesnapper, Cave Troll
(4) (6) (12) (20) `(1) `(1) `(1) `(2)

**Comment by blackshadowshade** [comment]
There was mention of replacing these names (and images) with alternatives from the anime Ultimate Muscle, because the GWAR names are somewhat suggestive/offensive, probably crossing the line to not being PG.

For the testing phase, we'll not be implementing any of the special skills. If P swing dice are anything but trivial to implement, then they'll be replaced with (1/30) dice during testing.

**Comment by TheOrgg** [comment]
For the Flesh Column, we can use the Y Y Y Y recepe for the testing, assuming it isn't just an easy tweak of Echo.

**Comment by blackshadowshade** [comment]
It'll be easier to test Flesh Column when we allow generic recipes to be tested on the dev sites.

**Comment by TheOrgg** [comment]
How long does it take to get a test server set up and running?

**Comment by blackshadowshade** [comment]
Nominally, not long, as long as someone has time to put up a pull request and @cgolubi1 has time to create it.

Unfortunately, I'm a bit under the pump at work, putting in an *extra* day's work on a Saturday.

Do you have a deadline that we need to know about?

**Comment by TheOrgg** [comment]
No, I don't.  Sorry to be impatient.  I'm excited to get the testing on its way, and nervous about getting enough people to actually test it out as thoroughly as I'm hoping to (each character playing every other one four times, so 100 games per character).  Can you play both sides in a test?

Best of luck with the work crunch.

**Comment by blackshadowshade** [comment]
@TheOrgg, you can start recruiting testers for the test site. It's up at 54.224.17.168, and will soon have the URL http://gwar.dev.buttonweavers.com.

One of the issues we've often noted is that new users may have trouble signing up, because their email providers block our confirmation emails. They should let us know, and we'll validate their signup manually.

**Comment by TheOrgg** [comment]
So how hard is "P" to implement?  Will we be changing to 1(or 2)/30?

**Comment by blackshadowshade** [comment]
Take a look at the test site! P swing should already be implemented.

**Comment by TheOrgg** [comment]
AH!  The P characters also had the --'s, so I thought they were not implemented.  Sweet.

**Comment by blackshadowshade** [comment]
Hmmm, if the recipes with (P) are dashed out, then the game logic isn't correctly recognising P swing. Let me take a look at whether I can get that fixed easily.

**Comment by blackshadowshade** [comment]
Okay, I forgot to make one change to the code. Once the site is updated, P swing should be playable.

**Comment by blackshadowshade** [comment]
Remember that dashed out buttons are still playable, so that shouldn't stop you testing with them. It'll also serve as a visual aid for testers that something's a bit odd with the button, namely that these buttons have a button special skill.

**Comment by blackshadowshade** [comment]
Requested changes:

> Please change Bozo Destructo to p(20) p(20) p(20) p(X) 
>
> and Dr. Skulhedface to p(X) (X) g(Y) (Y)

**Comment by blackshadowshade** [comment]
I've submitted a database update that adds two new buttons (Bozo Destructo 2 and Dr. Skullheadface 2), sets the old version to be artificially disabled (via having a button special), and removes the commas there are causing grief in #2410.

@cgolubi1, if you're happy with this, please update the GWAR site.

**Comment by TheOrgg** [comment]
How difficult would it be to add a die that is a Maximum Null d100 that removes itself from the game when used, and automatically wins initiative?  (Porcelon, but he effectively can never go first.  Should be okay)

How about a die that removes the poison attribute from any dice it captures?  (Oderus)

How about a die that gives an extra turn when you use it for a Boom attack? (Scroda)

I don't know how difficult this sort of thing is, so if it isn't easy, no worries.  I'll just make sure the buttons are balanced on their own, and these three a bit weaker than average to compensate for their abilities.

**Comment by blackshadowshade** [comment]
At the moment, none of these are doable. We're in the middle of doing the big site upgrade, and everything else is on hold. The earliest I could see these happening would be December, at the very earliest, considering that we have a number of open issues that need to be dealt with after the site upgrade happens.

**Comment by TheOrgg** [comment]
I don't know when the upgrades will be finished, but I'm ready to enter these into a secondary round of testing.  Some are power tweaks, some are mild design tweaks.  I hope the Warrior Stinger dice are possible in the system.  The special dice mentioned above are not needed for the test as long as the characters associated aren't very strong on their own (or in Oderus's case, are balanced on their own), but it would be nice to test Porcelon's first turn flush.

Oderus:  (6) (8) g(8) (12,12) (X)
Scroda Moon:  (ALL BOOM) b(4) b(4) b(12) b(P)
Estrogina:  (6) (8) M(T) (T) g'(4) g'(6)
Sexecutioner (6,6) g(12) (X) (X) (X)
Porcelon:  (6) (12) (12) (12)
Mr. Perfect:  (1) (1) (2) g'(20) g'(20)
Cardinal Syn:  (6) g(8) g(8) (8,8) (12) (X)
Balsac the Jaws O' Death: M(8) M(12) (20) (P)
Jizmac Da'Gusha: M(4-4) g(12) (20) (P)
Techno Destructo:  (12) (8,8) p(30) p(30) g(X)
Gor-Gor: (8) (6,6) (20) p(30) (U)
Slyminstra Hymen: (4) (6) (8,8) g(12) o(Y,Y)
Blothar: (6) (20) (30) (X) '(8) '(12)
Bonesnapper: (4) (6) (12) (20) '(1) '(2) '(X)
Morality Squad: g(4) H(6) (8) (V,V) '(4) '(6)

**Comment by TheOrgg** [comment]
No rush, though.  Get the site updated first!

**Comment by blackshadowshade** [comment]
The site upgrade happened! The fact that it was almost unremarked is actually a huge credit to @cgolubi1, who made it so that we had an incredibly soft landing.

I'll update those recipes when I have the chance, @TheOrgg.

**Comment by TheOrgg** [comment]
Oop.  One more.

Flattus Maximus:  (4) (12) g(12) (20) p(X)

**Comment by blackshadowshade** [comment]
Okay, @TheOrgg, Chaos has updated the GWAR test site. You should be able to start some new games with the new buttons.

**Comment by TheOrgg** [comment]
Sweet!  Excitement!  Fun!  Blood and Gore!

*tests the Warrior Stinger dice*

Crap.  This combination isn't working as I had hoped.

**Comment by blackshadowshade** [comment]
What's not working with the Warrior Stinger combination that you expected?

**Comment by TheOrgg** [comment]
Let's use Mr. Perfect as an example.  He should be able to take out the "big guns" as he's the antagonist that kills Oderus.

He's got two warrior d20's so he should be able to use them to capture the biggest two dice a character has, and if the dice are d20's or higher, Perfect should win. 

As is, if I try to take a 7 with him, choosing a 1 and a warrior stinger d20, it doesn't work.  The Warrior ability cancels the Stinger ability for some odd reason.

**Comment by blackshadowshade** [comment]
Okay, I'll take a look.

**Comment by blackshadowshade** [comment]
I've found the bug and implemented a fix in two ways:
- as a global fix for the code base in #2427, and
- as a patch for the GWAR test site

This should be live on the GWAR test site as soon as @cgolubi1 updates it.

**Comment by irilyth** [comment]
I don't think the current behavior is incorrect: Warrior dice are out of play, so they can't use any of their skills until they come into play.

This is how the old site worked, there's at least one existing button that has this behavior, and I don't think we should change it.

**Comment by TheOrgg** [comment]
Two changes are needed with the new crop, as Nala is going to help out with testing the non-warrior dice.

Please remove the 'ability not available' tag from Scroda, Oderus, and Porcelon 2, and correct Cardinal Syn's dice to be g(8) g(8) (8,8) (12) (X)

**Comment by TheOrgg** [comment]
So I think these are the final stats. None are over 60%ish, and those that were had several matches go to five rounds.  

A new wrinkle has popped up, though-- GWAR has caught wind of this.  They might want to take a spin themself to see if they'll let me release the fan expansion to the fans it was intended for.

Can the current buttons be cleared out totally, and just the following be put up on the site?

Balsac the Jaws of Death [M(8) M(12) (20) (P)]
Beefcake the Mighty [H(6) H(12) (20) (V,V)]
Blothar the Berserker [(6) (20) (30) (4/20) '(8) '(12]
Bonesnapper [(4) (6) (8) (20) '(X) '(Y)]
Cardinal Syn [g(8) g(8) (8,8) (12) (X)]
Dickie Duncan [(4,4) (6,6) (8,8) (Y,Y)]
Dr. Skulhedface [(X) (X) p(Y) g(Y)]
Estrogina [(6) (8) (T) M(T) '(4) '(8)]
Flattus Maximus [(6) (12) (12) (20) p(X)]
Gor-Gor [(8) (6,6) (20) p(30) (U)]
Jizmac Da'Gusha [M(4,4) g(12) (20) (P)]
The Master [(8) (30) (30) (30) (U)]
Morality Squad [g(4) H(6) (8) (V,V) '(4) '(6)]
Mister Perfect [(1) (1) M(2) M(3) (V)]
Oderus Urungus [(6) (8) g(8) (12,12) (4/20)]
Pustulus Maximus [g(4) (12) g(12) (20) (4/20)]
Sawborg Destructo [(12) (12) (20) (20) p(P)]
Sexecutioner [(6,6) g(12) (X) (X) (X)]
Sleazy P. Martini [g(4) (20) (X) (X) (X)]
Slyminstra [(4) (6) (8,8) g(12) o(Y,Y)]
Techno Destructo [(12) (8,8) p(30) p(30) g(4/20)]
World Maggot [(20) (20) (20) (30) (20/30)]

**Comment by blackshadowshade** [comment]
So, I'm in the middle of cleaning things up, and I notice that you've left four buttons off your list:

'Bozo Destructo', 'p(20) p(20) p(20) p(X)'
'Porcelon, Portal Potty', '(6) (12) (12) (12)'
'Scroda Moon', 'b(4) b(4) b(12) b(P)'
'Flesh Column', '(Y) (Y) (Y) (Y)'

Did you want these included in the deploy or not?

**Comment by TheOrgg** [comment]
I noticed this issue was still labelled open at the top, and I thought I'd try to comment and close it down.

**Comment by blackshadowshade** [comment]
Right, closing this issue. Cheers!
