### ISSUE TITLE
puppet on circleci can no longer download phpcs

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2430]
See e.g. https://circleci.com/gh/cgolubi1/buttonmen/189 --- my assumption is that this is affecting all new circleci builds.

**Comment by blackshadowshade** [comment]
Nasty. Hopefully the fix for this is easy.

**Comment by cgolubi1** [comment]
```
# /usr/bin/pear install pear.php.net/PHP_CodeSniffer
No releases available for package "pear.php.net/PHP_CodeSniffer"
install failed
```

**Comment by cgolubi1** [comment]
I'm getting a secure connection error from `https://pear.php.net/PHP_CodeSniffer` --- i think the site misconfigured its SSL cert and that may be what's breaking pear.  More in a bit.

**Comment by cgolubi1** [comment]
This is not just us - https://www.reddit.com/r/PHP/comments/aish4f/pearphpnet/ - pear.php.net discovered that they'd been hacked about six months ago.  Per https://thehackernews.com/2019/01/php-pear-hacked.html we are probably not affected by the hack; it involved a malicious version of `go-pear.phar` which we have never used.  But they have taken the site offline while they figure out what to do.

Given that we are not in a tearing rush to merge anything, i'm inclined to wait a few days and see if they get things back online.  If they don't have a fix by next weekend, i'll modify our circleci config to temporarily disable phpcs.
