### ISSUE TITLE
array_key_exists() warning on prod site

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2442]
We've been seeing a bunch of these since the upgrade:

```
[Sat Mar 16 00:58:17.751435 2019] [:error] [pid 3779] [client X.X.X.X:Y] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/api/ApiResponder.php on line 998, referer: http://buttonweavers.com/ui/index.html?mode=preference
```

**Comment by cgolubi1** [comment]
That's in `verify_function_access()`, so, yeah, okay, we know what this is - it's people calling the API with invalid arguments.  So:
* We really do need to have the site do something friendlier and not send these PHP warnings because they're messing up my ability to find actual stacktraces in the logs
* We should figure out who these callers actually are (obviously not on this public bug report, but in general), and make sure they're actually people using third-party clients who haven't upgraded yet (and that they can upgrade), and if that's not the case, debug further

**Comment by blackshadowshade** [comment]
It's possible that these are to do with the button filter application that was available a while ago, but otherwise, I have no good guess for what this actually is. I presume that we know who is making the calls and we can contact them directly?

**Comment by cgolubi1** [comment]
It's definitely the API format change --- the warning is because it's looking for `'type'` in the args and finding the args are null.  I'm pretty sure that's exactly what would happen if people are still sending URLencoded args.

**Comment by cgolubi1** [comment]
Oh, of course --- most of these are from the first day or two after the change, and this is the interaction of the JS caching bug (which, yes, is on my radar, thanks for continuing to ping me about it) with the change.  Until people force-reloaded, the old UI pages were still sending URLencoded queries.

Well, geez, who could have predicted that extremely surprising and unforeseeable outcome?  `:>P`  Sorry.

Anyway, the upshot is that that probably wasn't a great player experience, but it should mostly self-recover, so i only need to root-cause any warnings we're still getting, more than a couple of days out from the change.

**Comment by blackshadowshade** [comment]
Ah, that makes sense. Darn JS caching. Tricky stuff.  XD

**Comment by cgolubi1** [comment]
Closing this because i don't think we've seen any warnings since the upgrade, and we had a JS caching explanation for it.  Reopen if i'm wrong.
