### ISSUE TITLE
I can't figure out how to use the forum [forum=1,6]text[/forum] element.

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2460]
I can't figure out how to use the forum [forum=1,6]text[/forum] element.  This feature is in place, but I can't figure out how to use it.  :(  Is there any way to add help text for it?  Or how about a single help page that describes all the forum elements?  Maybe with the settings help or something.

**Comment by blackshadowshade** [comment]
I'd love to add a help page, but my pull request for that has been sitting for over three years now without any progress.

As a hint, though, every post has the forum link syntax in really light grey next to the Quote button.

**Comment by nkmcalli** [comment]
Yes, I see the syntax in the box - I'm saying that I don't know how to use the syntax.  :(

[forum=1,6]text[/forum]: Forum thread: text

What is 1 and what is 6?  I guessed that it was the forum id and the post id that I wanted to link to, but that didn't work.

Sorry to hear that there is no progress on your help page.  Can I plus one it or something?

**Comment by AdmiralJota** [comment]
blackshadowshade is referring to this very subtle text:

![image](https://user-images.githubusercontent.com/5848173/58138087-d19cbe00-7c02-11e9-99f8-2e361f456d9c.png)

It's hard to see, but if you highlight it, you can copy and paste that into a post, It'll give you the numbers you need in order to link to that post.

**Comment by nkmcalli** [comment]
Thanks!  Now please to document this super secret sauce.

**Comment by nkmcalli** [comment]
Also, I thought that's what I guessed (the numbers are in the address bar too) and it didn't work.  Let me see if I had them backwards or what.

**Comment by nkmcalli** [comment]
Okay, now that I've got the help it works - I only see 1 number in the address bar, so I don't know where I thought I saw the other number, but it was not correct.  Please document.  :)

**Comment by blackshadowshade** [comment]
Regarding the request to assist with the help page, I'll refer you to comments on #1924.

**Comment by blackshadowshade** [comment]
We now have a help page! Write me some text, and I'll include it!

**Comment by nkmcalli** [comment]
When you are posting in a forum, use the [forum] element to link to another forum post. The syntax is [forum=f,p]text[/forum], where text is the text that appears as the link. The number f is the forum id, and the number p is the post id. The numbers appear at the bottom of the post that you want to link to, in the footer of the post, to the left of the Quote button.

For example, use the synax [forum=93,1301]Learn about adopting a button[/forum] to generate a link that looks like <a href="http://www.buttonweavers.com/ui/forum.html#!threadId=93&postId=1301">Learn about adopting a button</a>

**Comment by blackshadowshade** [comment]
I'll probably incorporate this text when addressing #2461.
