### ISSUE TITLE
Remove "Forum thread:"

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2461]
The forum thread link element adds "forum thread: " to any link you create using [forum=n,m]text[/forum].  That makes it awkward to make inline links.  Not everyone wants their links to include the text "forum thread:"  Since the text part of the element lets you put whatever text you want in, including "forum thread", can you please un-hard-code "forum thread" from the forum links?

**Comment by blackshadowshade** [comment]
So, I'd love to hear discussion on this, especially from @AdmiralJota.

**Comment by AdmiralJota** [comment]
I'm a bit late to reply here, but: if I remember correctly, the main purpose of the "Forum thread:" text is to make it clear to the person clicking it where the link goes, since in theory, you could put anything into the text. Do you have a good alternate proposal for doing that? (Or do people feel that isn't necessary? I *think* @cgolubi1 may have had an opinion on that.)

**Comment by nkmcalli** [comment]
Yeah, but it makes *inline* links very awkward.  For example, "Don't forget to post your bad luck on the <RNG hates me thread>" instead reads as "Don't forget to post your bad luck on the <Forum thread: RNG hates me thread>"  Let the writer of the link / text decide where or if to include "forum thread" instead of forcing it.  You are trying to protect the clicker of the link, but I don't think sending the clicker to a forum thread on the site is a dangerous action that they need to be protected from.

**Comment by nkmcalli** [comment]
The whole point is to let users put anything into the text.

**Comment by blackshadowshade** [comment]
So, I'm leaning in favour of removing the text "Forum thread:". Keep it nice and simple. Any voices against doing this?

**Comment by dwvanstone** [comment]
I'm in favor of getting rid of the the "Forum thread:" text.

**Comment by blackshadowshade** [comment]
I'll be working on removing the "Forum thread:" text soon. If anyone else has thoughts about this, now is the time to speak up.
