### ISSUE TITLE
Create game with custom recipe fails if only opponent has custom recipe

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2471]
Use http://transient.dev.buttonweavers.com/ui/ .

Create a game where the opponent has a custom button (such as "(10) (20)") and you have a selected button (such as Avis or Bauer). 

Gives this error and doesn't create the game:

   Argument (customRecipeArray) to function createGame is invalid

However, selecting a custom button for oneself works fine.

**Comment by blackshadowshade** [comment]
My guess is that this dev site hasn't been updated with the changes I made in #2389.

**Comment by blackshadowshade** [comment]
I'd suggest waiting for @cgolubi1 to create a long-lived testing site with a fresh deploy of the code in #2389.

**Comment by blackshadowshade** [comment]
I've tested this on customrecipe.dev.buttonweavers.com, and this is fixed. Closing this now.
