### ISSUE TITLE
Non-ASCII flavour text causes internal error

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2475]
As noted on #2472, when button flavour text contains non-ASCII characters, it does not load correctly on the button page.

This should actually work, probably by explicitly encoding the JSON in UTF-8.

**Comment by blackshadowshade** [comment]
I'm going to close this, because we've got a solution that we used in #2531.

We should never have non-ASCII characters in the database representation, instead, we should use the HTML encoding.

**Comment by AdmiralJota** [comment]
I was under the impression that the reason the front-end and the back-end were separated by an API was so that different clients -- including ones that weren't HTML-based -- could connect to the API. 

Have we officially abandoned that?

**Comment by blackshadowshade** [comment]
No, we haven't abandoned that.

However, the issue here was having non-ASCII flavour text in the database, which we can prevent from happening in the future.

Any front-end client will either be able to deal with the HTML tags, or will show them---not optimal, but also not terrible.
