### ISSUE TITLE
CustomBM recipes are limited to 99 characters

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2484]
I started working on my Fanatic, and wanted something with:

- Three base dice: Gg(8) Gg(16) Gg(32)
- Five Warrior dice: `sptH(1) `sptH(2) `sptH(3) `sptH(5) `sptH(8)
- Three Reserve dice: rspoh(4,9) rspoB(9,16) rspob(16,25)

The combination adds up to 100 characters, and while my eventual recipe might not include all of those dice in the end, it'd be nice to be able to experiment with them.

**Comment by blackshadowshade** [comment]
That would require a database change at the very least, which makes this change non-trivial. @cgolubi1, what do you think?

**Comment by cgolubi1** [comment]
I mean, if it's just a single DB change to make the recipe field longer, that's probably not that big a deal.  But presumably (i haven't looked, i can maybe look tomorrow) there are also fields within game database entries where recipes are instantiated.  Do we have to worry about those too?  Do we have to worry about them *differently*?  (Like, if a recpe is exactly 99 characters in the button database, is there any chance it could become more than that in any game database?  What if a 99 character button recipe plays against a button with auxiliary?  Etc.

**Comment by blackshadowshade** [comment]
Actually, that's a good argument for making the database fields longer, even if CustomBM is restricted to a certain length. If you have a 99 character button recipe that gains an auxiliary die, currently that'll break stuff.

So, we need game_player_map to change to have alt_recipe (and maybe original_recipe) somewhat longer to accommodate this possibility. To change the restriction on CustomBM would then just require the appropriate check in BMButton to be loosened from 100 characters to something longer.

**Comment by AdmiralJota** [comment]
I imagine something like Radioactive could break this as well?

Given that @irilyth already has an actual recipe that he'd like to try that's 100 characters, my earlier rule of thumb would be to make the custom recipe's maximum length 200. And since storage is cheap, why not make the in-game recipe field 400 characters? That should be a pretty safe margin for things like Auxiliary and Radioactive dice.

**Comment by blackshadowshade** [comment]
Interestingly, no, Radioactive wouldn't break this, because only the recipe at the start of each round is updated. Otherwise, dice are held separately in the die table.

**Comment by irilyth** [comment]
Any chance this fix could be deployed to transient.dev.buttonweavers.com some time soon?
