### ISSUE TITLE
Option dice break when one of the options is a zero-sider

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2486]
The site throws an internal error if there I try to choose zero sides in a (0/4) die.

**Comment by AdmiralJota** [comment]
If you make it (4/0) instead, does it through a Divide By Zero error?

**Comment by jl8e** [comment]
I don't have the actual code to fix, but option dice set a min of one in init, and don't override it in set_optionvalue if it's a 0-sider. (Presumably need to set min to 1 explicitly if the chosen value is not 0, else it'll be rolling 0-max in at least turbo option situations.)

**Comment by blackshadowshade** [comment]
Yeah, that makes a lot of sense. I figure that it shouldn't be *too* difficult to fix. However, I'm a little hesitant to be 100% certain about that because of #2417.

**Comment by jl8e** [comment]
Both is always an option
