### ISSUE TITLE
Fix Largo's missing (X)-Swing Die

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2489]
Largo as written on the dev site is missing an (X) swing.

**Comment by blackshadowshade** [comment]
From https://buttonmen.fandom.com/wiki/Megatokyo, the recipe is:

(12) (20) (20) (X) (X)

with the button special "Cannot skill attack"

**Comment by TheOrgg** [comment]
Yeah, he's still kinda weak.  Giant dice, and a big disability.  If he had only four dice...  lol.  He'd be Golgo's best friend.
