### ISSUE TITLE
GWAR reskin with appropriate names and images ("Dürer Räwg")

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2507]
Well, how's this for the fan set?

Dürer Räwg

Anna Lee (8) (6,6) (20) p(30) (U)
Anna Lee is an undead tyrant with a rotten streak.  She likes long arms, sharp teeth, and beating people up.

Bishop (6) (20) (30) (X) \`(8) \`(12)
Bishop is an academic heavy metal singer.  He likes civil war, wrestling, and beating people up.

Brad M(8) g(12) (20) (P)
Brad plays with dogs and sticks all day, sometimes at the same time.  He likes drums, flatulence, and beating people up.

Brenda (1) (1) M(2) M(3) (V)
Brenda is a fiery woman who was vegetarian for a month.  She likes rare steak, the number five, and beating people up.

Brent g(4) (12) g(12) (20) (X)
Brent is a musician who cannot find his glasses.  He likes his country, novelty nail files, and beating people up.

Cardie g(8) g(8) (8,8) (12) (X)
Cardie is a former nun who likes airplanes, outer space, and beating people up.

Cherry (6) (8) (T) M(T) \`(4) \`(8)
Cherry is a burlesque performer and gymnast who likes eating non-foods, non-dairy desserts, and beating people up.

Chuck (6,6) g(12) (X) (X) (X)
Chuck is a leather making enthusiast.  He likes whips, seafood, and beating people up.

Cuddy (4) (6) (8) (12) \`(1) \`(2)
Albrecht Cuddy is a dwarf with excess salivation.  They like court dramas, cherry pie, and beating people up.

Dave (6) (8) g(8) (12,12) (X)
Dave is an offensive cosplay enthusiast who likes yelling at crowds, being protested, and beating people up.

Derks M(8) M(12) (20) (P)
Derks is a master chef who enjoys the challenges of fixing food for vegans, bear trap headgear, and beating people up.

Dickie (4,4) (6,6), (8,8) (Y,Y)
Dickie works as a fast food mascot and enjoys banana splits, MC Chris, and beating people up.

Don g(4) (20) (X) (X) (X)
Don has the sickest last name of anyone you will ever meet.  He likes coke, shotguns, and beating people up.

Gorman (4) (6) (12) (20) \`(X) \`(Y)
Gorman is a puppeteer with no sense of direction.  He likes turtles, soft sculpture, and beating people up.

Hedy (X) (X) p(Y) g(Y)
Hedy is a doctor specializing in flesh reconstruction.  They like ambiguity, classic pin-ups, and beating people up.

Hunter (12) (8,8) p(30) p(30) g(X)
Hunter is a cannabis activist and comic book artist.  He likes cosplay, gigantic novelty wrenches, and beating people up.

Jamie H(6) H(12) (20) (V,V)
Jamie is a former star and current bus driver.  He likes peanut butter and mayonnaise sandwiches, slightly burned french fries, and beating people up.

Maggie (20) (20) (20) (30) (20/30)
Maggie is a chiropodist who specializes in maggot therapy.  She likes lost souls, telethons, and beating people up.

Matt Ron (12) (12) (20) (20) p(P)
Matt Ron is the lost son of Anna Lee.  He and his alternate personality Deborah like chainsaws, Pascal's pressure principle, and beating people up.

Orry b(4) b(4) b(12) b(P) [When you are taking an extra turn, your dice lose the Boom skill.  When you use a Boom Attack, take an extra turn.]
Orry is an artist with a heart of mud.  He likes Roman military history, the Grand Canyon, and beating people up.

Portia w(6) w(12) w(12) w(12) [Before rolling for initiative, remove one of your opponent's dice from the game this round.]
Portia is a professional plumber who really enjoys her work.  She likes clean toilets, monsters based on common household objects, and beating people up.

Reilly g(4) H(6) (8) (V,V) \`(4) \`(6)
Reilly is a copyright hawk with a heart of hair.  He likes ceasing, desisting, and beating people up.

Ashley Jay [Ashley Jay's recipe is all Standard Dice that are one size smaller than her opponent's.  Variable dice are copied as-are.  If the opponent's dice cannot be copied, Shae's recipe is four Y-Swing Dice instead.]
Ashley Jay is almost whatever you want them to be, but not quite.  They like tartar sauce, roasted puppies, and beating people up.

Smoot (6) (12) g(12) (20) p(X)
Smoot is giant with major flatulence problems.  He enjoys poutine, colorful hair brushes, and beating people up.

Stamps (4) (6) (8,8) g(12) o(Y,Y)
Stamps is a pyromaniac singer.  She likes fire, electricity, and beating people up.

Zedna (8) (30) (30) (30) (U)
Zedna easily learns anything within two and 17/18ths of a month.  She likes big butts, defenestration, and beating people up.

Bozo p(8,8) p(12,12) p(20,20) p(30,30) p(X,X)
Bozo is a band manager and weekly call-in podcast host. He likes big hair, big chins, and beating people up.

**Comment by TheOrgg** [comment]
There's three that I can understand not implementing.  They're probably tricky.  The rest should go right in, though.

Orry b(4) b(4) b(12) b(P) [When you are taking an extra turn, your dice lose the Boom skill. When you use a Boom Attack, take an extra turn.]
Orry is an artist with a heart of mud. He likes Roman millitary history, the Grand Canyon, and beating people up.

Portia w(6) w(12) w(12) w(12) [Before rolling for initiative, remove one of your opponent's dice from the game this round.]
Portia is a professional plumber who really enjoys her work. She likes clean toilets, monsters based on common objects, and beating people up.

Shae [Shae's recipe is all Standard Dice that are one size smaller than her opponent's. Variable dice are copied as-are. If her opponent's dice cannot be copied, Shae's recipe is four Y-Swing Dice instead.]
Shae is almost whatever you want them to be, but not quite. They likes tartar sauce, roasted puppies, and beating people up.

**Comment by TheOrgg** [comment]
Here's the images ready to go.
![AnnaLee](https://user-images.githubusercontent.com/44233993/69776646-bdfa8300-1162-11ea-90dc-f5d48d970e88.png)
![Bishop](https://user-images.githubusercontent.com/44233993/69776647-bdfa8300-1162-11ea-92ff-41820b8edc2e.png)
![Brad](https://user-images.githubusercontent.com/44233993/69776648-bdfa8300-1162-11ea-97ba-595ef670df07.png)
![Brenda](https://user-images.githubusercontent.com/44233993/69776649-bdfa8300-1162-11ea-98f8-6ec4439be31e.png)
![Brent](https://user-images.githubusercontent.com/44233993/69776650-be931980-1162-11ea-98c5-d80b15b218e7.png)
![Cardie](https://user-images.githubusercontent.com/44233993/69776651-be931980-1162-11ea-89a8-4c78fa5eb57b.png)
![Cherry](https://user-images.githubusercontent.com/44233993/69776652-be931980-1162-11ea-9ca4-44c5fad39c7e.png)
![Chuck](https://user-images.githubusercontent.com/44233993/69776653-be931980-1162-11ea-8fee-7cb10389a8e8.png)
![Cuddy](https://user-images.githubusercontent.com/44233993/69776654-be931980-1162-11ea-9bcc-782fb447e5de.png)
![Dave](https://user-images.githubusercontent.com/44233993/69776655-be931980-1162-11ea-920b-b635d052ee83.png)
![Derks](https://user-images.githubusercontent.com/44233993/69776656-bf2bb000-1162-11ea-8330-fb04d4d25fe2.png)
![Dickie](https://user-images.githubusercontent.com/44233993/69776657-bf2bb000-1162-11ea-8389-63d6604aadb1.png)
![Don](https://user-images.githubusercontent.com/44233993/69776658-bf2bb000-1162-11ea-8300-80e48e4d9bfe.png)
![Gorman](https://user-images.githubusercontent.com/44233993/69776659-bf2bb000-1162-11ea-9048-702a95ddde20.png)
![Hedy](https://user-images.githubusercontent.com/44233993/69776661-bf2bb000-1162-11ea-87d7-3f6e94e4b134.png)
![Hunter](https://user-images.githubusercontent.com/44233993/69776662-bfc44680-1162-11ea-8bdb-98ba44c18a44.png)
![Jamie](https://user-images.githubusercontent.com/44233993/69776663-bfc44680-1162-11ea-9d09-15f420f93473.png)
![Maggie](https://user-images.githubusercontent.com/44233993/69776665-bfc44680-1162-11ea-8d9c-b5efedefd5ce.png)
![MattRon](https://user-images.githubusercontent.com/44233993/69776666-bfc44680-1162-11ea-9a1c-f934d10ab714.png)
![Orry](https://user-images.githubusercontent.com/44233993/69776668-bfc44680-1162-11ea-997f-d39ffa64c81b.png)
![Portia](https://user-images.githubusercontent.com/44233993/69776669-bfc44680-1162-11ea-961b-8d7ac9812219.png)
![Reilly](https://user-images.githubusercontent.com/44233993/69776670-c05cdd00-1162-11ea-8fc7-99902e88051d.png)
![Shae](https://user-images.githubusercontent.com/44233993/69776671-c05cdd00-1162-11ea-896e-25cae68ef493.png)
![Smoot](https://user-images.githubusercontent.com/44233993/69776672-c05cdd00-1162-11ea-9c85-5f0a312de351.png)
![Stamps](https://user-images.githubusercontent.com/44233993/69776673-c05cdd00-1162-11ea-9ba8-1b3b090fde68.png)
![Zedna](https://user-images.githubusercontent.com/44233993/69776674-c05cdd00-1162-11ea-801e-ac76b7c39db4.png)

**Comment by TheOrgg** [comment]
Someone reviewed this and was offended by a couple of the artwork choices.  Here's two alternate buttons so we don't alienate any users of the site.

![Cuddy2](https://user-images.githubusercontent.com/44233993/87091270-04d34f80-c1ff-11ea-8d68-d0d791373d2d.png)
![Dave2](https://user-images.githubusercontent.com/44233993/87091280-08ff6d00-c1ff-11ea-9a94-f0c5d3224b5e.png)

**Comment by TheOrgg** [comment]
Forgot to shrink them.  Here's the 150px ones.

![Cuddy2150px](https://user-images.githubusercontent.com/44233993/87091434-47952780-c1ff-11ea-8e60-b9d1d6c7bb13.png)
![Dave2150px](https://user-images.githubusercontent.com/44233993/87091435-482dbe00-c1ff-11ea-9c78-9c6afc27d7e0.png)

**Comment by TheOrgg** [comment]
Throwing another one out there for the set.  Should be fun, but awful.
Bozo  p(8,8) p(12,12) p(20,20) p(30,30) p(X,X)
![150pxBozo](https://user-images.githubusercontent.com/44233993/99162592-076e1600-26c5-11eb-99f8-fcb0fb2f6c03.png)

**Comment by danlangford** [comment]
if you want to show a Warrior backtick you can type escape the backtick by typing this
&#92;&#96;
and it will show a single backtick like
\`

OR instead of typing a backtick you can type the html char code
`&#96;`
and that will show a single backtick like
&#96;

**Comment by TheOrgg** [comment]
Slight update to one of the names to avoid duplicating a "DriveThruCards" button name.  Also, adds another Evil Dead reference, which is nice.

![Ashley Jay](https://user-images.githubusercontent.com/44233993/116460756-040eb700-a82d-11eb-8e15-5036c607ad0e.png)

**Comment by blackshadowshade** [comment]
Linking to #2408, which has the original GWAR set.

**Comment by blackshadowshade** [comment]
A number of things that I'd like to be addressed before we progress this pull request:
- Where does the button art come from, and what are the terms of use?
- What do people think about the button images?
- Are we generally okay with introducing a new Swing type (the P-swing)?

The buttons with a button special would be marked as unplayable on the live site.

**Comment by TheOrgg** [comment]
1)  Public Domain.  The artist is Albrecht Dürer, 1471-1528.  Copyrights are long lapsed.  Also, I did let a few people look at the set a bit, and made a couple of changes at their request.  Dave and Cuddy were changed as the artwork was too well known or could have been found obscene.

2)  The images are a bit sloppy, but readable.  Looks like someone just learning to use an image program made them.

3)  YES!

;)

**Comment by dwvanstone** [comment]
I'm not excited with introducing a new Swing type P (ranging from 1-30, if I understand correctly) -- it seems to me that's a slippery slope and perhaps ButtonMen itself will use that swing type in the future. Also it doesn't seem that the buttons couldn't be slightly modified to use existing swing types (Y or Z) instead.

It sounds like TheOrgg has done a lot of playtesting on the buttons to make sure the formulas are interesting/playable. That's great!

I like the artwork well enough. The descriptions don't really match the artwork, though, which is a bit confusing. The humor in the descriptions are missing context. What does "Räwg" mean? Is it just a roaring sound? I don't understand the context of that either. If the set (artwork/descriptions) is about an homage to Albrecht Dürer and the Renaissance I'd understand it better. Otherwise is seems like a joke that I just don't get.

I find the number of buttons overwhelming for a fan set. I'd like it better if the best 8-12 buttons were pulled out of this set. (And some of the formula ideas could be used in a future fan set.) Most of the recent fan sets have been about that size.

**Comment by TheOrgg** [comment]
>>P-Swing:  I did test it significantly; only one character with a P-Swing (or Power Swing) has more than four dice, and that is offset by it being Poison and having only that one die with a skill.

>>The descriptions are reflective of the people in GWAR (but without makeup, thus RAWG) who the original recipes were based upon.  Dave?  That was their former lead singer who dressed as Oderus Urungus, thus the offensive cosplay.  Bozo?  That'd be Bozo Destructo, played by Don Draculitch who also plays the band's manager and hosts a weekly livestream.  There's many references to the band GWAR in the flavor text and names.  When trying to find an alternate theme and artwork, I found Dürer's paintings (which I was unaware of, knowing him for his woodcuts).  Several of them actually favored the artists who played different characters, and the backwards-GWAR felt like it fit with the name Dürer rather well.  This is almost a public-domain version of the BROM set-- a bit more complex than usual, all the art is from a single notable artist, and the descriptions and names have nothing to do with the artwork.

>The GWAR set was concepted and designed as if it was a modern Button Men licensed set,  At the time there was only two modern (card) sets on the market, the base set one with 48 characters (60 in the Kickstarter) and the Sailor Moon Crystal Challenge set with 24.  It was playtested to be balanced within itself and when played with a wider range.  For Buttonweavers, if random-within-set becomes a favorite like I think it will, this set will have a good variety for that option.

**Comment by danlangford** [comment]
Regarding introducing a new Swing:
Are there any new skills that have been created from fan sets? If so, is there a concern that those skills shorthand will be used in future products. For example Rush was recently added officially. Is that annotated as “r”? Was “r” already in use? 

I think the concept, artwork, names, and descriptions are great. References I maybe don’t personally get but more power to ya. 

The fact that TheOrgg went out of their way to not dup a name from a random DTC card shows the level of care taken in crafting this as well as respect for the community. 

Also, in a meritocracy my opinion is meaningless

**Comment by scipiohaereticus** [comment]
I don't have too many issues with the idea of the P-Swing die, it was a range that was still missing and I think it's unlikely that an "official" P-Swing will be released (at least anytime soon).

I have no additional problems with the images.

As for the names, just to be sure, is the name "Anna Lee" a deliberate dirty pun or is that just my imagination?

**Comment by dwvanstone** [comment]
Ah - Räwg is GWAR reversed and GWAR is the heavy metal band which inspired this collection in the first place. Got it. (I can't believe the puzzler in me missed that right away.)

**Comment by TheOrgg** [comment]
I know three women named "Anna/Annah Lee."  It's a very common Southern US name.  One of them's a gamer who played BM with me occasionally while I was in college.

**Comment by scipiohaereticus** [comment]
> I know three women named "Anna/Annah Lee." It's a very common Southern US name. One of them's a gamer who played BM with me occasionally while I was in college.

Alright then, that's fine for me. And if a button is named after someone who plays Button Men, all the better!

**Comment by TheOrgg** [comment]
So it seems most people are okay with the set other than the P-Swing.  Let's tally the votes there (also including the forum thread):

For:  Scipio; AnnoDomini; JL8E;
Against:  Devious, irleth; 
Ambiguous: Bagels, BlackShadowShade

**Comment by cgolubi1** [comment]
I don't care very much whether we implement the P-swing (call me "ambiguous"), but one thing to keep in mind is that, like any other skill, it'll take quite a bit of testing to find all the places where we messed up something-or-other and therefore it'll take some iteration and wall-clock time before it's approved.  So, since i think you want to see these buttons on the site sooner rather than later, i guess i'd recommend not waiting for P-swing to be built, and planning to launch with the other buttons.

**Comment by blackshadowshade** [comment]
I've already got the code for the P-swing, we used it for testing the GWAR set.

**Comment by blackshadowshade** [comment]
Linking to #2451.

**Comment by TheOrgg** [comment]
> I've already got the code for the P-swing, we used it for testing the GWAR set.

So we just need to do one of those automated thousand-something game tests with it?

**Comment by blackshadowshade** [comment]
Once I reinstate the code and create a pull request, yes, that would be the idea.

**Comment by TheOrgg** [comment]
5 to 2 on the "Yay" / "Nay."  Any chance this set can get on the site in time for April or May's hit list?

**Comment by blackshadowshade** [comment]
I'll get onto this when I have a moment or two.

I'm currently isolating with the family because of Covid, so I might actually have more time than normal.

**Comment by TheOrgg** [comment]
Oh, no!

I'm so sorry to hear ya'll have it.

**Comment by blackshadowshade** [comment]
Currently, only my youngest has it, but we all need to isolate for 7 days.

**Comment by blackshadowshade** [comment]
Just mentioning here, I'm having to build this entire pull request from scratch since the old GWAR pull request was intimately entangled with the introduction of CustomBM to allow the testing to happen.

Also, I'm not sure what to do about the umlauts in the set name, we've had problems with this before and decided to only support special characters in the flavour text, not in button (or set) names.

**Comment by blackshadowshade** [comment]
Can I just make an observation that Räwg is a very unlikely word, partly because it's almost impossible to say.

**Comment by TheOrgg** [comment]
Drop the Umalauts; they're not important.  The band doesn't usually use them when posting about the unfortunate (but rare) RAWG performances.   ('Rawg' is what GWAR is known as when performing without the costumes, which only happens either in intimate and private events or due to an unfortunate travel mishap.)

As for how it should sound, much like 'GWAR' sounding like someone was hit in the stomach, 'RAWG' sounds like a boar grunting if said right.   Or "Raw-gh," if just casually saying it.

Sorry that you have to totally recreate the pull request.  :(  I really do appreciate it, and look forward to seeing the set on Buttonweavers!

**Comment by blackshadowshade** [comment]
The interesting thing about the a-umlaut is that it entirely changes the sound of the word if it's pronounced to reh-gh.

**Comment by TheOrgg** [comment]
Neat!

I think that's part of the joke, honestly.  Google "Gwar Hell-O" and you can see the other tracks.

**Comment by blackshadowshade** [comment]
Yeah, I figured. I see there's a Wikipedia page on the Metal Umlaut!

https://en.wikipedia.org/wiki/Metal_umlaut

**Comment by TheOrgg** [comment]
Oh, wow.  Some of those on that list are hilarious; I'll have to look up the bands.  And once again I learn another joke I missed from Spinal Tap-- never occurred to me that the umalaut was over a non-vowel in their name.  lol.
