### ISSUE TITLE
Password reset codes should only be usable once

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2512]
In #2509, it was noticed that the password reset link continues to work in perpetuity, even after being used.

The ability to password reset using that link should expire after the link is used.

**Comment by cgolubi1** [comment]
> This will also address the issue that there can only be a maximum of 5 password reset requests at any one time, which would be a problem if old password reset requests were not cleared.

This isn't true --- it's a maximum of 5 from any single IP address

**Comment by cgolubi1** [comment]
I'm also not inclined to deal with expiration as part of this issue --- that's more complicated since it involves time, and our current verification codes don't expire.  If a problem arises, we can address it.

So my plan is just to remove the password reset code from the verification table as part of using it, which should be easy.

**Comment by AdmiralJota** [comment]
Is it that complicated? Shouldn't it just be a matter of testing if the current time is >= player_reset_verification.generation_time + a bit, and rejecting it if it is?

**Comment by AdmiralJota** [comment]
I should clarify: I mean just doing that test _when they try to use the code_ -- say, include it in the SQL query that looks to see if a the code exists in the DB. The only thing that would need to change is that one query from this:

`$query = 'SELECT verification_key FROM player_reset_verification WHERE player_id = :player_id';`

to something like this:

`$query = 'SELECT verification_key FROM player_reset_verification WHERE player_id = :player_id AND CURRENT_TIMESTAMP() < DATE_ADD(generation_time, INTERVAL 1 DAY)';`

**Comment by cgolubi1** [comment]
I appreciate the syntax.  It's not worth the update and testing time to me, but i'd definitely accept the PR if someone else thought it was (and obviously y'all should open a new issue or reopen this one if it doesn't seem good enough as written).
