### ISSUE TITLE
Fanatics 2020

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2514]
Well, I'm not as good at this by far as the original Fanatics generic logo creator, but I gave it a garish shot.  The Fanatics logo feels 50's inspired, so I went with a 70's inspired design, but with a black background instead of psychedellia oil flow (as I couldn't figure out how to get that 'acid backdrop' without screencapping it)

![Fanatics2020](https://user-images.githubusercontent.com/44233993/71677715-267fe580-2d49-11ea-94e7-03935a658a5c.png)

**Comment by TheOrgg** [comment]
If someone can do better, please do.

**Comment by dwvanstone** [comment]
I wanted to keep the fanatics uploaded to issue #2346. This is a fun button and looks like a fine generic Fanatics 2020 image! (We do have a fanatic w/o an image.) So many colors!!! (And this could become a good model for 2021 and 2022 and ...) 

I was calling it "2020 Fanatics" as opposed to "Fanatics 2020", to be parallel to "Classic Fanatics" and "2017 Rare/Promo", etc.

**Comment by TheOrgg** [comment]
My bad.  I didn't see that thread.

**Comment by dwvanstone** [comment]
> My bad. I didn't see that thread.

No worries! Maybe you can go ahead and close this thread and post your suggested image there.
