### ISSUE TITLE
can we tear down dev.buttonweavers.com?

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2522]
I'd like to tear down the dev site.  For those who may have forgotten, we changed our mechanism maybe three years ago, so that instead of deploying new code via a site called dev, we deployed new code to individual dev sites, tracked on the [dev site index](https://github.com/buttonmen-dev/buttonmen/wiki/Dev-site-index), and did the final pre-prod push to a site called staging.

So as of now, the development workflow does not involve either moving new code to the site named "dev", or having people test on that site.  It has increasingly stale code (it's on my radar because there's no way it's going to get the changes to apache log grepping which would cause it to spam me a bit less, unless i hand-patch them in, which i'll do if we're not going to tear it down), and i suspect that anyone who's using it would rather be doing something else.

Looks like Kaori and Jota logged into it a couple of months ago, but no one since then, and other than them (and me just now, checking out this very situation), nobody has logged in in over half a year.

If anyone thinks i shouldn't tear it down, please comment before i get around to doing something.  I'll wait until next weekend for negative comments, and then take the site down at my leisure absent objections.

**Comment by dwvanstone** [comment]
Makes sense. Tear away!

**Comment by blackshadowshade** [comment]
Get rid of it!  :)

**Comment by cgolubi1** [comment]
Dev site is gone.  Keeping this open for a couple of days to see if anything breaks, then i'm going to release the elastic IP for the site address.  (Just being paranoid; i can't think of any reason it should matter.)

**Comment by cgolubi1** [comment]
Released the dev EIP.  This is done!
