### ISSUE TITLE
aws instances should emit cloudwatch metrics to help us figure out whether a site is up

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2536]
The database disk filling issue was exacerbated because we found out about the problem via user reports, several hours after the fact.  It would be better if we could notify ourselves that the site wasn't working.

Proposed implementation: have each instance emit some kind of cloudwatch metric about successful and unsuccessful site responses in the log.  Then we can alarm on lack of successful responses.

**Comment by cgolubi1** [comment]
Note: at a glance it seems like it might be interesting to alarm on error responses, but i'm not so interested in doing that, because a lot of error responses are likely because of player error (e.g. if you try to make an invalid attack, that'll show up as a failed API response, and nobody wants to get an alarm about that).  So i'm starting with the theory that the daily apache error log scans (which we already have) are the right way to find out about unknown bugs of the internal-error variety.

**Comment by cgolubi1** [comment]
I did some experimenting with this a month or so ago, as a result of which i know how to make an IAM role that can emit cloudwatch metrics.  So i think what i need to do here is:
* Configure vagrant to assign that role to AWS instances it brings up
* Configure vagrant to install the awscli package
* Make a cron job that emits the actual metric
* Add alarms on the instances where we care about this metric (which may be only prod, since staging doesn't get regular enough use for a "did we get a success this hour" type metric to work well)

**Comment by cgolubi1** [comment]
For the curious, here's a snapshot of the little dashboard i just made, with API success rates and call counts for prod and staging.  I'm pretty sure there's a way to export cloudwatch dashboards using IAM roles, so it might be that we could embed this in the site and everyone could see it, though that's definitely not a today project:

![bmapi_dashboard](https://user-images.githubusercontent.com/2898207/90403337-d4d56280-e06e-11ea-8c16-24fe5b607f73.png)

**Comment by blackshadowshade** [comment]
Looking forward to seeing how this goes over the next couple of weeks.

**Comment by cgolubi1** [comment]
Here's why i really wanted to get these metrics going --- this is the six replay sites i stood up yesterday (the master which records new games, and five actual test sites):

![replay_site_traffic](https://user-images.githubusercontent.com/2898207/92329044-e6d57000-f032-11ea-8696-2638bdba946c.png)

Without metrics, there are mechanisms i can use to find out whether one of the replay sites has fallen over and needs attention, but it's going to be something cumbersome and scripted.  With metrics, "look for replay sites that fall over", is just scan this graph and look for areas that have disappeared (the way the purple area disappeared yesterday while i was trying to get the state update right for doppelganger_mood); it takes 30 seconds total, which is much more feasible as part of my workflow.

Also i stuck a cloudwatch alarm on the master replay site, so that if *it* falls over, indicating some kind of logic bug in master or at the very least that i'm not getting new games, i'll get an e-mail.

**Comment by blackshadowshade** [comment]
Yup, I understood that to be the reason. Lovely to see it working.  :)

**Comment by blackshadowshade** [comment]
I'm going to close this issue since we now have Cloudwatch metrics up and running. I'm sure there'll be an evolution of which ones we use in the future.
