### ISSUE TITLE
the prod site hangs while the backup is running

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2537]
I was catching up on games on the prod site just now, and i clicked "next game", and the site didn't respond.  I tried a couple of times, no response, so i hit force-reload, and got the header only, no page load.  I noticed the time was just after midnight UTC, so i logged onto the site to take a look, and sure enough, the backup was running.

When the initial backup finished (after about 3 minutes), the site immediately loaded.  (The backup is still being compressed now, and i don't see any issue with site use.)

I assume this happens every day.  It doesn't seem totally ideal for the site to hang for 3 minutes with no information every day.

**Comment by cgolubi1** [comment]
I wonder if we could detect "you can't get a database connection because the backup is running" somehow, and just put up an informative "Site backup is running, wait a few minutes" type message.  I don't know if that would be a better user experience or not.

**Comment by irilyth** [comment]
I bumped into this tonight.

**Comment by blackshadowshade** [comment]
I believe that this issue should have been dealt with. Anyone able to confirm or deny?

**Comment by cgolubi1** [comment]
It's easy to reopen, and it links to the issue which we think should have fixed it, and since we think we fixed it, we're no longer working on it.  So i don't think there's any harm to closing it.

**Comment by blackshadowshade** [comment]
I've just checked this, and while the load delay on pages is longer than when the backup is not running, it's still less than 10 seconds, which is a huge improvement on the previous behaviour.
