### ISSUE TITLE
Found art for the first Blademasters set

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2545]
Here's the art for Blademasters 1.  (one name edited so it can be read; dark blue on black made it unreadable in the scans from the Buttonmen book)

![BlademastersArashi](https://user-images.githubusercontent.com/44233993/78842359-677d3b00-79c5-11ea-9212-b5de8b9281ab.png)
![BlademastersDanielle](https://user-images.githubusercontent.com/44233993/78842361-677d3b00-79c5-11ea-863d-7e6b30a578c3.png)
![BlademastersDanny](https://user-images.githubusercontent.com/44233993/78842362-6815d180-79c5-11ea-800f-92814865a4b6.png)
![BlademastersHorace](https://user-images.githubusercontent.com/44233993/78842363-6815d180-79c5-11ea-984f-a341b9b2a630.png)
![BlademastersInez](https://user-images.githubusercontent.com/44233993/78842364-6815d180-79c5-11ea-84bf-f31790f7b26b.png)
![BlademastersJohnny](https://user-images.githubusercontent.com/44233993/78842366-68ae6800-79c5-11ea-91bb-996b8bd86130.png)
![BlademastersKainar](https://user-images.githubusercontent.com/44233993/78842368-68ae6800-79c5-11ea-9c9b-49ec37fd5ae4.png)
![BlademastersMacky](https://user-images.githubusercontent.com/44233993/78842369-6946fe80-79c5-11ea-958d-3c7af5d2303e.png)
![BlademastersMagistra](https://user-images.githubusercontent.com/44233993/78842370-6946fe80-79c5-11ea-8be4-e7974e85beaf.png)
![BlademastersMichie](https://user-images.githubusercontent.com/44233993/78842371-6946fe80-79c5-11ea-9a19-327dcd8bd5e5.png)
![BlademastersRenee](https://user-images.githubusercontent.com/44233993/78842372-69df9500-79c5-11ea-946a-6e6213b6c28f.png)
![BlademastersScott](https://user-images.githubusercontent.com/44233993/78842373-69df9500-79c5-11ea-84da-501bf08c0b52.png)

**Comment by dwvanstone** [comment]
The formulas don't seem to line up with the images, oddly. (Great images!) Is there a source for the formulas? Or perhaps the buttons are the best source?

**Comment by TheOrgg** [comment]
Let me talk with Ligaya (if she will) and dig on the old archive.org site a bit.

I might have to edit the button names and numbers if those aren't right.  (or "remaster" the set)

**Comment by TheOrgg** [comment]
So there's multiple versions of the Blademasters set.  Buttonweavers has the 'final' stats, other than the up to date Parry die.  The last version of the Parry die couldn't be Power Attacked.  
The artwork is from the previous versions of the dice before the Parry die was changed (I assume that's why the d2s had it moved to the larger die, to make it easier to skill attack them).

I updated the wiki with this not-new-but-overlooked information.  Ligaya has not contacted back, and may not do so.  You never can tell with this project.

https://buttonmen.fandom.com/wiki/Blademasters_Trilogy

I'll work on 'remastering' the art.

**Comment by TheOrgg** [comment]
This was a PAIN, but I'm done.  Make sure these match the ones on buttonweavers.  I checked twice, but I could've missed something.

![BlademastersArashi](https://user-images.githubusercontent.com/44233993/79301624-b0def600-7eaf-11ea-8b6b-3928656f714a.png)
![BlademastersDanielle](https://user-images.githubusercontent.com/44233993/79301626-b1778c80-7eaf-11ea-9b23-8ce56cad3372.png)
![BlademastersDanny](https://user-images.githubusercontent.com/44233993/79301628-b1778c80-7eaf-11ea-9bf4-28c22b6a1bff.png)
![BlademastersHorace](https://user-images.githubusercontent.com/44233993/79301630-b2102300-7eaf-11ea-97ee-b1a7b0b6d40e.png)
![BlademastersInez](https://user-images.githubusercontent.com/44233993/79301631-b2102300-7eaf-11ea-9ce6-52c9b65d5717.png)
![BlademastersJohnny](https://user-images.githubusercontent.com/44233993/79301632-b2102300-7eaf-11ea-9b76-ab96f8f2c3d4.png)
![BlademastersKainar](https://user-images.githubusercontent.com/44233993/79301633-b2a8b980-7eaf-11ea-9270-22009a8506f0.png)
![BlademastersMacky](https://user-images.githubusercontent.com/44233993/79301634-b2a8b980-7eaf-11ea-8a70-b94b9a93581b.png)
![BlademastersMagistra](https://user-images.githubusercontent.com/44233993/79301635-b2a8b980-7eaf-11ea-8eba-4dea55a6d1ab.png)
![BlademastersMichie](https://user-images.githubusercontent.com/44233993/79301636-b3415000-7eaf-11ea-8a79-125759cf660b.png)
![BlademastersRenee](https://user-images.githubusercontent.com/44233993/79301638-b3415000-7eaf-11ea-90bd-b2b1bd57931b.png)
![BlademastersScott](https://user-images.githubusercontent.com/44233993/79301639-b3415000-7eaf-11ea-914f-b4b27ce21f2f.png)

**Comment by dwvanstone** [comment]
Brilliant - well done. They match! Thank you!!
