### ISSUE TITLE
Rediscovered Flavor Text

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2548]
Skeeve sent me a couple of old files the original BMO used.  It used UNIX text files to reference, funny enough.

In there are some new flavor texts that this sit didn't have, including the requested seven deadly sins text.

Gluttony: Gluttony enjoys eating, eating and the Fat Albert Cartoon. When not eating, or thinking about eating, he spends his time beating people up with his Double-Drumstick Fu.
Pride: Pride is a diva of the nose harmonica. When not appearing on Live TV news casts, she enjoys flinging cats, radish carvings and beating people up.

Lust: Lust is out-of-work actress who is rather top heavy. While not trying to get bit parts on VIP, Baywatch or any USA shows, she enjoys humming and the color red. She also beats people up.

Envy: Envy wants to be just like you. When not imitating everything around him, he enjoys the periodic table, prime numbers and beating people up.

Sloth: Sloth is the ultimate armchair warrior. When not watching sports, he enjoys thinking about sports and encouraging others to talk about yams in loud voices. He beats people up with his special move 'Super Slow Motion Slam'. (It may take a while to get there, but it sure packs a wallop!)

Anger: Anger spends most of his time in useless debates with his sock puppet collection. When not playing in his Punk Band, The Rancid Spleen, he enjoys beating people up.

Greed: Greed is a fanatical collector of soup labels. While not surfing the net, or in her pimp-mobile searching flea markets, she enjoy beating people up and then running them over.

**Comment by TheOrgg** [comment]
Free Radicals

Maskin: Maskin enjoys running, freaking out and bum-rushing telephones. Maskin has no occupation other than being alive and beating people up.

Tony: Tony spends his time plotting for world wide mass-transit. He has 10,000 Llamas, and has a masters in Christian Ethics. While not purchasing things on Ebay, he beats people up.

Loren: Loren is the sensei of two-fisted-game-controller fu. His skills of TV recording and if-then-else statements are unparalleled. While not beating people up, he enjoys donuts.

CynCyn: CynCyn is immune to the "Lao Wai" Stare. She works for the Great Googly Moogly, and likes glue guns. In her free time she taunts oak trees, palms state quarters and beats people up.

Lorrie: Lorrie really is the power behind Hoover Dam. During her freetime she collects batteries, books and new ways to beat people up.

Randy: Randy purchases things only in cash and enjoys sorting 3x5 cards by length. He has been known to consume an entire plate of sushi with only a chopstick, while beating people up.

**Comment by TheOrgg** [comment]
Techi Muyo!

Ayeka: Ayeka is the First Princess of the Jurai Empire.  She likes acting regal, trying to be an ideal wife for Tenchi, and beating people up.

Dr._Clay: Dr. Clay was a wannabe mad scientist, now he's just mad.  He likes being obscure, taunting people into attacking him, and beating people up.

Kagato: Kagato is the penultimate evil scientist.  He likes committing crimes, torturing the innocent, and beating people up

Kiyone: Kiyone Makibi is a Detective (First-Class) in the Galaxy Police. She is also Mihoshi's partner, this annoys her to no end.  She likes screaming at Mihoshi, fighting crime, and beating criminals up.
Mihoshi: Mihoshi Kuramitsu is a Detective (First-Class) in the Galaxy Police.  She is incompetent but manages to keep her job due to nepotism.  She likes junk food, arresting criminals, and beating people up.

Ryo-Ohki: Ryo-Ohki is a spaceship that can turn into a small furry creature.  It has destroyed 28 planets and 69 colonies (and counting). It likes to eat carrots, and being cute.

Ryoko: Ryoko is a space pirate who loves her job.  She is also Washu's daughter.  She likes sleeping, drinking, irritating Ayeka, and beating people up.

Sasami: Sasami is the Second Princess of the Jurai Empire, and Ayeka's little sister.  She has the spirit of the Space Tree, Tsunami.  She likes cooking, cleaning, and cheering people up.

Soja's_Guardians: The Guardians just like to beat people up.

Tenchi: Tenchi Masaki is the Crown Prince of the Jurai Empire, something he does not want to be.  He likes carrot farming, sword training, and he beats people up.

Washu: Washu Hakubi is the greatest genius scientist in the universe. She likes experimenting, proving herself right, and beating people up to prove scientific theory.

Zero: Zero is a robotic creation of Dr. Clay.  It can mimic individuals simply by touching them.  It likes wrecking people's lives, and beating people up.

**Comment by TheOrgg** [comment]
Four Horsemen (partial)

Famine: Famine is a drummer who often plays until she passes out.  Her turn-ons include back massages and lycanthropy.  Turn-offs include foul language and Kenny G.

Death: In his spare time Death plays bass in a band with his friends Famine, War, and Pestilence.  He enjoys firecrackers, vanilla ice cream, and beating people up.

**Comment by TheOrgg** [comment]
Vegas (https://buttonmen.fandom.com/wiki/Las_Vegas); Didn't realize it wasn't on the buttons there's text for on the site

**Comment by TheOrgg** [comment]
Majesty

Flaire: Flaire is a follower of Helia. She likes summer days, long walks in the desert and beating people up.
Dirgo: Dirgo is a visually impaired cyclops. He likes knocking down buildings and beating people up.
Nerni: Nerni is the rarest of heroes...a Gnome Champion. He enjoys laboring in filth and beating people up.
Yeti: The Yeti is really, really big, and really, really mean. He enjoys eating heroes and beating people up.

**Comment by TheOrgg** [comment]
Classic Fanatics (some of these might have their text, I only spot checked a handful)

zaph: Zaph is the two-headed, three-armed ex-head honcho of the universe. He likes cherry vanilla ice cream, yo-yo's and beating people up.

Anvil: Anvil is a Shrugging Atlas with a flair for the obtuse. He likes his caviar over easy and to get beat up.

fnord: fnord is a baker / sales creature who enjoys comic books, tasting zillions of new beers and beating people up. Normally in that particular order.

albertel: Guy is an enigma wrapped in the mystery of being beat up by people
Skeeve: Skeeve's recipe changes on a whim.

fxdirect: Ben tells other people what to do all day long. In his spare time, he runs a computer college basketball ratings system and enjoys beer, broads, and beating people up!

GripTiger: GripTiger is the quiet type who likes chocolate-peanutbutter ice cream and is normally not seen unless, of course, she's beating people up.

Pjack: Pjack is the spitting image of Mad King Ludwig. He likes mochas, cats, world domination, and not getting beaten up.

santiago: Santiago is a college student who enjoys In Nomine, painting, artificial life research, and beating people up.

myxozoa: A sixed celled metazoan, he hates being called a cnidarian. He likes collecting bottle caps, raising bonsai Chia Pets, and taking long swims in the moonlight. Oh yeah, he also likes to beat people up.

kestrel: Kestrel likes to watch old movies, whine about lost relationships, comtemplate absurdity, and, in his spare time, beat people up.

NoopMan: I'm an anti superhero with the power to talk before I think. I hurl my magic dashboard at my enemies or strangle them with my steel mouse cord. I enjoy Beating People Up!

**Comment by TheOrgg** [comment]
Lost Set:  Ice Cream.  (No stats.  Only flavor text found)

Vanilla: Vanilla is simple, yet complex.

Chocolate_Chip: One mean mother (shut your mouth!) I was only talking about Chocolate Chip! (we can dig it!)

Mint_Chip: The meanest Ice Cream of the bunch. Avoid it like the green plague!

Rocky_Road: Sometimes it's got nuts, some times fudge, sometimes marshmallows!

Swirl: Vanilla's evil cousin.

**Comment by irilyth** [comment]
Huh, neat!

Did we already get button art from Skeeve? If not, I wonder if he has any of that lying around.

**Comment by blackshadowshade** [comment]
Great work, @TheOrgg!

I'll put in a pull request with these when I can.

**Comment by dwvanstone** [comment]
Wow! Now we have to redo some of those Button Brackets with the new text! (Well done, @Theorgg!!)

**Comment by TheOrgg** [comment]
Skeeve (Dana) deserves 95% of the credit here.  He's the one digging into his BMO archives that were corrupted(?).

I'm just the guy that nagged him every three months for about a year.

**Comment by TheOrgg** [comment]
RE: The Art.

He hasn't found a working art backup yet.

**Comment by irilyth** [comment]
Ah, ok. Thanks for continuing to bug him, and thanks to him for continuing to poke at it!

**Comment by TheOrgg** [comment]
One 2001 art backup was found.  No major new items, other than a Christmas version of Angora.  They are different (and slightly lower quality) than the ones currently in use.  I haven't fine-tooth-comb'd it yet, though.
[BMJPEG.zip](https://github.com/buttonmen-dev/buttonmen/files/4534597/BMJPEG.zip)
