### ISSUE TITLE
If an opponent of Nala marks conversation private, Nala should change to private

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2552]
If a player in a game with Nala marks their conversation as private, the conversation should be private (Nala should change to private).

**Comment by irilyth** [comment]
Nala isn't any different than any other account on the server; but, as it turns out, if either player marks the chat as private, then the chat is private, regardless of what the other player does, so even if we implemented some special way to say that certain players (e.g. players marked as bots in some way) always followed the other player's chat settings, it wouldn't have any effect.

**Comment by nkmcalli** [comment]
If a player marks a conversation as private, can we get her to NOT save or use that conversation history in her AI.

**Comment by irilyth** [comment]
We can ask Jota; we can't do anything on the site to stop a player from saving whatever they want to their own files or whatever.

**Comment by blackshadowshade** [comment]
I'm happy to have Nala requests recorded and open on the issue tracker. Yes, the dev team can't directly do anything about them, but it's as good a place as any to keep track of the fact there's a problem.

You'll probably want to ping @AdmiralJota on the issues though.

**Comment by blackshadowshade** [comment]
I believe this one is also closed by the answer at http://www.buttonweavers.com/ui/forum.html#!threadId=654, where Jota mentions that Nala only saves chat once a game is completed.

**Comment by nkmcalli** [comment]
From Jota:

"* If a conversation is marked private, she can't see it. She also doesn't look at game conversation until after a game is completed. So if you mark it as private before the game is over, she'll never even know about it. If you wait until after the game is over to mark it as private, though, there's a chance that she might come across it in the meantime and add it to her database."
