### ISSUE TITLE
New Las Vegas images!

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2559]
So a friend of mine from High School is the artist behind the indie comic Bubble Gum Man.  Great satire of the Superhero genre and a big gamer in high school.  He found the idea of illustrating a set that never got its illustrations fun, and after a few months (he's busy!) this is the result!

I fixed up four 'alternate' button arts for the non-ability characters that were legal on here already.  I hope they're okay.

![Logo2](https://user-images.githubusercontent.com/44233993/81128035-ab505b00-8f05-11ea-8d87-88e956773b86.png)
![BMO21](https://user-images.githubusercontent.com/44233993/81128046-b3a89600-8f05-11ea-8b97-38baa0b5bca7.png)
![BMOBlackJack](https://user-images.githubusercontent.com/44233993/81128047-b4412c80-8f05-11ea-8033-01fd990008a3.png)
![BMOBones](https://user-images.githubusercontent.com/44233993/81128048-b4412c80-8f05-11ea-96aa-54995c8817ce.png)
![BMOCraps](https://user-images.githubusercontent.com/44233993/81128049-b4d9c300-8f05-11ea-8e88-337e2977a6ea.png)
![BMOCrypto](https://user-images.githubusercontent.com/44233993/81128050-b4d9c300-8f05-11ea-88f5-a2a541e9a4f7.png)
![BMOFrank](https://user-images.githubusercontent.com/44233993/81128051-b4d9c300-8f05-11ea-8a7a-12ce900e4d67.png)
![BMOGow](https://user-images.githubusercontent.com/44233993/81128052-b5725980-8f05-11ea-8cdc-c7514d02b2e8.png)
![BMOLadyLuck](https://user-images.githubusercontent.com/44233993/81128053-b5725980-8f05-11ea-9975-963726800e1b.png)
![BMOLola](https://user-images.githubusercontent.com/44233993/81128055-b5725980-8f05-11ea-89e6-70e0b189ede3.png)
![BMOMagician](https://user-images.githubusercontent.com/44233993/81128056-b60af000-8f05-11ea-9147-9b75220eff65.png)
![BMOSham](https://user-images.githubusercontent.com/44233993/81128057-b60af000-8f05-11ea-956e-314027b6e8d1.png)
![BMOSly](https://user-images.githubusercontent.com/44233993/81128058-b60af000-8f05-11ea-9f5c-91a41730f462.png)
![BMOWildcard](https://user-images.githubusercontent.com/44233993/81128059-b6a38680-8f05-11ea-8c8f-e65ba3184802.png)
![ButtonBlackJack](https://user-images.githubusercontent.com/44233993/81128061-b6a38680-8f05-11ea-999a-6387835f6cd4.png)
![ButtonCraps](https://user-images.githubusercontent.com/44233993/81128063-b73c1d00-8f05-11ea-8c45-2d2f801425b0.png)
![ButtonCrypto](https://user-images.githubusercontent.com/44233993/81128066-b7d4b380-8f05-11ea-9a2b-eed749c76daa.png)
![ButtonFrankie](https://user-images.githubusercontent.com/44233993/81128067-b86d4a00-8f05-11ea-84b4-17d4463afdab.png)
![ButtonGow](https://user-images.githubusercontent.com/44233993/81128068-b86d4a00-8f05-11ea-8a65-28e491bdf9e9.png)
![ButtonLola](https://user-images.githubusercontent.com/44233993/81128069-b905e080-8f05-11ea-9feb-0344caa8236d.png)
![ButtonShamrock](https://user-images.githubusercontent.com/44233993/81128071-b99e7700-8f05-11ea-9004-99f80fc8e6de.png)
![ButtonSly](https://user-images.githubusercontent.com/44233993/81128073-ba370d80-8f05-11ea-9f37-274f60cbb5c7.png)
![ButtonWildcard](https://user-images.githubusercontent.com/44233993/81128074-bacfa400-8f05-11ea-9c8b-8509d51395f5.png)

**Comment by TheOrgg** [comment]
(oops, didn't mean to upload the big ones here, but at least they are all in a clump.  lol.

**Comment by nkmcalli** [comment]
I think creatively they are great.  I'd like to see them a bit more *polished* if that makes sense.  Would it be possible to do a second iteration?

"Twenty One" and "Blackjack" are also too close.  If those are different buttons, the artwork needs to be more different than just the color and background.  Ditto "crypto" and "magician".  Are the buttons that appear so similar just working versions and final versions of the same buttons?

For the background, I'd like to see them all have the card suit background, or none of them have it.  Again, this might be an issue of some of this art being "in-progress" versus final versions of the buttons mentioned above.

So my vote is yes for the ideas, no for the execution, and hope we could bring the execution up a little bit.

**Comment by TheOrgg** [comment]
21, Lady Luck, Them Bones, and Magician are playtest or non-ability versions that are already on the site.  Having 'offshoot' artwork was to allow them to stay even when the full set was put up (with abilities and all).

  The ones with the background are the official final numbers for the set.

I can further edit the black and white ones (which are drawn from the original artwork, but edited) if need be.  They were all based on the matching final image.  I just need suggestions.  (Basically, they're not really part of the set-- they were versions put up on the old BMO site that were ported over to this one)

**Comment by nkmcalli** [comment]
That totally makes sense. Can you separate the images to make it easier to focus on the actual buttons.  I saw in the forum thread that other people were also confused by the "doubles".

Focusing only on the ones with the color and background, I'm the same: I really like the creative vision, I just wish the artwork was a little more polished.

**Comment by TheOrgg** [comment]
The roughness is part of the art style.  Partly, the illustration's lines are intended to shift the eye's focus to different parts and the lines outside the edge can be used to show motion or intent.  (BubbleGum Man's a great comic).  They do lose something when shrunk, though.

As for organization, this might help:

https://buttonmen.fandom.com/wiki/Las_Vegas

**Comment by nkmcalli** [comment]
Yeah it's easier to see on that site.  Can you paste a link to that site on the forum thread?  The artwork looks cool.

**Comment by dwvanstone** [comment]
Does Ryan McGuire have any opinions on the art on his button set? 

I'd suggest leaving the images blank on Twenty-One, Them Bones, Magician, and Lady Luck since that will make clear that they are not actually part of the set. (Maybe some day they can be moved to their own separate button set.) As AnnoDomini said, "almost any art is better than no art". (As long as they aren't offensive.)

**Comment by TheOrgg** [comment]
I haven't heard back from him since his initial reply.  He seemed pleased I had finished the set, but he never got back to me after the first response.  I was quite disappointed by that.  I had intended to send him one of the sets of it I got made.

**Comment by TheOrgg** [comment]
So in the forum thread, I think the conclusion was to use the art for the official set, but not for the 'alternate' buttons (Magician, Them Bones, Lady Luck, and 21).

Is there any more to be done?  (I had thought this happened already until I was in a game with Lola.  Sorry to be an annoyance with it.)

**Comment by blackshadowshade** [comment]
No need to apologise for bumping an issue.

I'll put up a pull request for this, and we'll discuss further there.
