### ISSUE TITLE
The open games page should show my open games section first

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2567]
On the open games page, please display the section "Your open games (waiting for other players to join)" BEFORE the section "Games you can join."  I want to see my open games first.

Also the my open games list will almost always be much smaller that the full list of open games.  So sorting my games first means much less scrolling to see my games and much less scrolling to see the open games.

**Comment by blackshadowshade** [comment]
Okay, who agrees with this? Who disagrees?

**Comment by jl8e** [comment]
Makes sense to me

**Comment by dwvanstone** [comment]
I would also find this easier as well. The list of open games I created is usually shorter than the list of open games in general.

**Comment by cgolubi1** [comment]
Sounds fine.  Definitely i have no reason to veto this if other people want it.

**Comment by nkmcalli** [comment]
Thank you!
