### ISSUE TITLE
Update button art for Mississippi

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2574]
The US state of Mississippi is changing its state flag; a new design hasn't been decided yet, but when one is, we should update the button art as well.

**Comment by TheOrgg** [comment]
Sounds excellent to me.  There's a design that's very popular and likely, but first we've gotta challenge the new law that "In God We Trust" must be on the state flag.  That law was specifically intended to stop the Hospitality flag that's been pushed for a decade.

**Comment by TheOrgg** [comment]
![mississippehh](https://user-images.githubusercontent.com/44233993/98311338-c5422780-1f94-11eb-8ac7-cebce7f845ab.png)

**Comment by blackshadowshade** [comment]
So, I'd like comment on this from those who know more than I do.  :)

Give me a feel: thumbs up, thumbs down, or something else.

**Comment by TheOrgg** [comment]
I mean, that's the new flag.  It passed with 70% to replace the rag we had.

**Comment by irilyth** [comment]
I think it's a reasonable representation of the new flag, as seen here: https://en.wikipedia.org/wiki/Flag_of_Mississippi#/media/File:Flag_of_Mississippi_(%22New_Magnolia_Flag%22).svg

I don't have any particular thoughts about this particular button-ifying of it; seems fine to me? I'm not picky. :^ )
