### ISSUE TITLE
Please update the description for Theano to remove unconscious bias language

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2575]
Please update the description for Theano.

From:

"Theano worked alongside her husband, Pythagoras, writing about mathematics, physics, medicine, and child psychology. She's best known for her work on the "Golden Mean" and the "Golden Rectangle.""

To:

"Theano wrote about mathematics, physics, medicine, and child psychology. She's best known for her work on the "Golden Mean" and the "Golden Rectangle.""

Alternatively update the description for Pythagoras to add "worked alongside his wife."

**Comment by blackshadowshade** [comment]
In principle, I'm for this.

However, it conflicts with the historical precedent that we've used previously of going with the canonical text wherever possible.

I'd like to hear what people think about this.

Personally, I'd be fine with a change here (and in #2576).

**Comment by cgolubi1** [comment]
I'm in favor, perhaps unsurprisingly.  This is flavor text about historical people, and i think nkmcalli's point is well-taken.

**Comment by jl8e** [comment]
This is a perfectly reasonable change.

**Comment by blackshadowshade** [comment]
Okay, so which way do we want to go? The first or the second change?

Personally, I'm for adding "worked alongside his wife", because I think that actually adds to the flavour.

**Comment by nkmcalli** [comment]
You should remove mention of spouses from all.  Mentioning a woman's spouse is a classic way of saying that her achievements are not her own, and her success can only be defined in terms of her husband.  I meant the "alternative" as a joke - I shouldn't have done that.

**Comment by blackshadowshade** [comment]
Okay, the very fact that I didn't pick up the slightest hint that the last comment was a joke implies to me that I'm obviously moving in rather different circles to you, @nkmcalli. I genuinely think that the part of the story where both spouses research together in a field is interesting.

Would there be another way of including this that doesn't have the implication of slighting one spouse?

**Comment by nkmcalli** [comment]
Unfortunately the way to celebrate a couple doing research together in the same field would have been to have a single button with them both on it.  As long as they have separate buttons, you have to celebrate their accomplishments individually.  Women have to fight to have their accomplishments recognized as their own, so let's do that if we can in this one small way.

**Comment by AdmiralJota** [comment]
Do we know who created the buttons, and can we consult with them on it?

**Comment by dwvanstone** [comment]
"I'm in favor, perhaps unsurprisingly. This is flavor text about historical people, and i think nkmcalli's point is well-taken."

Agreed. We want to do everything we can to not alienate newcomers to our site.

"However, it conflicts with the historical precedent that we've used previously of going with the canonical text wherever possible."
"Do we know who created the buttons, and can we consult with them on it?"

John Kaufeld (I believe at jkaufeld@aol.com) made the buttons. I'm happy to write him. (Maybe he'll come join our site?)

**Comment by AdmiralJota** [comment]
> John Kaufeld (I believe at jkaufeld@aol.com) made the buttons. I'm happy to write him. (Maybe he'll come join our site?)

Nice detective work -- that seems like a great idea.

**Comment by jl8e** [comment]
If we're going to ask the original author of the text, are we really going to be satisfied if they say "no"?  The problem would remain, and we'd just have the buck-passing excuse for it.

This is something we should be willing to own. There'd be more grounds for asking if it were any other button set, where the descriptions are purely original creative work, but these are short historical summaries.

**Comment by dwvanstone** [comment]
Good point. You're right that these are historical summaries rather than creative descriptions of fictional characters. In this case, I'd say there are no canonical texts for these buttons so we should change them.

(I'm still going to encourage John to join us on the site!)

**Comment by dwvanstone** [comment]
I did reach out to John K. who gave the golden thumbs-up: "I can absolutely see how badly it reads. Go forth and do the thing!" Btw, he hadn't known of Ron Graham's passing and was saddened. Apparently they had corresponded.

**Comment by nkmcalli** [comment]
So glad to hear he approved, and also proud of us that we didn't wait for that.  :)
