### ISSUE TITLE
Please update the description for Fan Chung Graham to remove unconscious bias language

### ISSUE THREAD

**Issue by nkmcalli** [buttonmen-dev/buttonmen#2576]
Please update the description for Fan Chung Graham.

From:

"Before becoming the Akamai Professor of Internet Mathematics at UC San Diego, Dr. Fan Chung Graham directed math research labs at Bellcore. She and her husband Ron developed semi-random routing theories that keep the Internet running."

To:

"Before becoming the Akamai Professor of Internet Mathematics at UC San Diego, Dr. Fan Chung Graham directed math research labs at Bellcore. She helped develop the semi-random routing theories that keep the Internet running."

**Comment by AdmiralJota** [comment]
I don't really like that change. The original version make it sound like they were equal partners. The revised version makes it sound like she was just an assistant on someone else's work. Why demote her from "developed" to just "helped"?

**Comment by nkmcalli** [comment]
Sure, "developed" is better

**Comment by nkmcalli** [comment]
But to be clear, the original button wording does not make her sound like an equal partner, but rather a helper to her husband. If they were equal partners, his button would have mentioned her but it does not.  Instead only her button mentions him.  That's a common pattern of naming women's husbands to give them credibility or assign ownership of their accomplishments to someone else. If you doubt this is a pattern, we've already established it here by having 4 buttons, 2 married couples, 2 of 2 wife buttons name the husband, 0 of 2 husband buttons name the wife.  If we have the ability to fix this, we should fix this.

**Comment by dwvanstone** [comment]
I think "She developed the semi-random routing..." is a good correction. I think it's a good point that gender is not being treated equally on these buttons but they should.
