### ISSUE TITLE
Alter opedog's art

### ISSUE THREAD

**Issue by jl8e** [buttonmen-dev/buttonmen#2581]
As discussed elsewhere, we want to blur out the Confederate flag in opedog''s fanatic art.

Do we have a higher-resolution or non-buttonified version to work from?

**Comment by TheOrgg** [comment]
Original and two edits.  One's got the up-to-date confederate flag, the other has no flag in the background.  I prefer the latter.

![opedog3](https://user-images.githubusercontent.com/44233993/87240010-16714e80-c3db-11ea-8ffd-99f19a89404e.png)
![opedog](https://user-images.githubusercontent.com/44233993/87240011-1709e500-c3db-11ea-91a8-65e0ae38fc9e.png)
![opedog2](https://user-images.githubusercontent.com/44233993/87240012-1709e500-c3db-11ea-93ee-0e55b411de18.png)

**Comment by TheOrgg** [comment]
Odd order to upload in, but that's what Github decided to do...

**Comment by blackshadowshade** [comment]
I like the one with no flag at all, it actually balances the button image.

**Comment by jl8e** [comment]
I agree

**Comment by cgolubi1** [comment]
Shadowshade: this would be a good one to get in the next release, if you don't mind prioritizing getting a PR up for it.

Thanks for signal-boosting, jl8e, i'd completely lost track of this issue.  :>(

**Comment by TheOrgg** [comment]
Glad I could be of service, ya'll.  I agree on the no-flag version.  How many need to comment to confirm?

I'm also all for rushing this to the main site.

**Comment by blackshadowshade** [comment]
Working on a pull request now.

@TheOrgg, I tend to wait for two responses to an issue before progressing it, unless it's a no-brainer.
