### ISSUE TITLE
possible internal error involving berserk swing dice

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2589]
The prod site threw this internal error:

```
[Thu May 28 12:21:47.624747 2020] [:error] [pid Y] [client X.X.X.X:Z] PHP Notice:  Undefined index: playerIdx_1_dieIdx_3 in /var/www/engine/BMInterfaceGame.php on line 986, referer: http://www.buttonweavers.com/ui/game.html?game=60334
[Thu May 28 12:21:47.624830 2020] [:error] [pid Y] [client X.X.X.X:Z] PHP Notice:  Undefined index: playerIdx_1_dieIdx_4 in /var/www/engine/BMInterfaceGame.php on line 986, referer: http://www.buttonweavers.com/ui/game.html?game=60334
```

This was during a speed game, so maybe it's just a race we don't need to worry about, but the IP address in question seems to be the address of blackshadowshade, who performed the attack at that timestamp:

```
blackshadowshade performed Berserk attack using [B(T=12):7] against [(10):2,(6/10=6):5]; Defender (10) was captured; Defender (6/10=6) was captured; Attacker B(T=12) changed size from 12 to 6 sides, recipe changed from B(T=12) to (T=6), rerolled 7 => 3
```

I'm suspicious there's a real (if not very impacting) bug involving e.g. a Berserk swing attacker and an option defender.

**Comment by blackshadowshade** [comment]
Hmmm, interesting! The error is quite specific, so I should be able to go back through the game log and see what might possibly be wrong here.

**Comment by blackshadowshade** [comment]
I'm sorry to say, but I can't replicate this bug. I've tested this exact attack five times with the exact die values in the attack log, and I see no errors of the type seen on the prod site.

What I did find, though, was a recurring warning that was triggered by a badly bracketed condition in BMUtilityXCYIterator. I'll put in a pull request to fix that.

**Comment by blackshadowshade** [comment]
Closing this because I can't replicate the error. Happy for this to be reopened if we find it again.
