### ISSUE TITLE
Maximum morphing die "rolled" a non-Maximum value

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2593]
In http://www.buttonweavers.com/ui/game.html?game=62506, this happened:

> irilyth performed Power attack using [IMmo(X=20):20] against [H(Y=4,Y=4):8]; Defender H(Y=4,Y=4) was captured; Attacker IMmo(X=20) changed size from 20 to 8 sides, recipe changed from IMmo(X=20) to IMmo(Y=4,Y=4), rerolled 20 => 5

Shouldn't the IMmo(Y=4,Y=4) have "rolled" an 8, because of Maximum?

**Comment by jl8e** [comment]
This is another incidence of #2511

**Comment by blackshadowshade** [comment]
Thanks for raising awareness of this bug and noticing that it's a duplicate. I'll close this issue but work on a bug fix for #2511.
