### ISSUE TITLE
Chicago Crew artwork (approved by creator and artist)

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2602]
With permission from JeffBoyArDee and FernandoBotero.com, here's artwork for the Chicago Crew, as closely matching the original cats as possible.

https://buttonmen.fandom.com/wiki/Chicago_Crew

![150Audrey](https://user-images.githubusercontent.com/44233993/91906287-91354800-ec6d-11ea-9659-554ad84d13cc.png)
![150Cheathem](https://user-images.githubusercontent.com/44233993/91906289-91cdde80-ec6d-11ea-9f05-c942f2253372.png)
![150Flint](https://user-images.githubusercontent.com/44233993/91906291-91cdde80-ec6d-11ea-82bc-3587ae7c5216.png)
![150Lizzie](https://user-images.githubusercontent.com/44233993/91906292-92667500-ec6d-11ea-9318-dcc9488cac56.png)
![150Monty](https://user-images.githubusercontent.com/44233993/91906293-92667500-ec6d-11ea-9212-ff2fef57a3b8.png)
![150Octavia](https://user-images.githubusercontent.com/44233993/91906294-92667500-ec6d-11ea-83fb-e3375011d751.png)
![150Spooky](https://user-images.githubusercontent.com/44233993/91906295-92ff0b80-ec6d-11ea-9881-1623dd11c1e2.png)

**Comment by blackshadowshade** [comment]
Very nice!

**Comment by randomlife** [comment]
Purr-fect!

**Comment by TheOrgg** [comment]
How does the "Shine" look?

**Comment by blackshadowshade** [comment]
It's subtle but okay.

**Comment by TheOrgg** [comment]
I'll keep working on it in my spare time.  It's a tricky thing to duplicate when you're not sure exactly what to do.
