### ISSUE TITLE
Rage Die skill needed

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#261]
Rage: G
- - - - - - - - - 
Rage Dice were created by Peter Hansson (aka spindisc) for his licensed Button Man, Gripen. They are represented with a 'G' before a die. If a Rage die is captured, then the owner of the Rage Die adds a new die to their pool of the same size and ability of the Rage die that was taken, except that it loses the Rage ability. If a Rage Die participates in an Attack, it loses its Rage ability. Rage dice, like Trip dice, are not counted for initative purposes.

 Clarifications: •GF (Rage Fire): Firing will not remove Rage. 
•Gw (Rage Slow): Slow is redundant. 

 Inconsistencies: •Gf (Rage Focus): Focus dice can NOT be used with dice that are not counted for initative. 

 Bugs: •G@ (Rage Chaotic): If a Chaotic die attacks, and gains Rage during reroll, then it immedately loses Rage due to attacking.

**Comment by jimmosk** [comment]
What the heck, I haven't picked a BFotM yet, and I like Rage...

**Comment by cgolubi1** [comment]
I'm leaving the BFotM tag on this one because Shadowshade hasn't commented about his progress --- i know he's made some, though, so i'm happy to see either a status update and remove the tag, or keep the tag on until you submit a pull.  Up to you.

**Comment by blackshadowshade** [comment]
Right, this is just about functional. I'm just dealing with a last bug when multiple rage dice are captured by a speed attack. Once that's dealt with, I'll be putting up a pull request.
