### ISSUE TITLE
large twin poison boom internal error

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2610]
I got an internal error on game http://customrecipe.dev.buttonweavers.com/ui/game.html?game=194 

Recipes are:
* glassonion: `(32) pb(80,90)`
* glassonion2: `(43) (23)`

The `pb(80,90)` performed a boom attack on `(43)`, and now i'm getting `Internal error when calling loadGameData` with the exception being:

```
PHP Notice:  Undefined variable: dieIdx in /var/www/engine/BMGame.php on line 3854, referer: http://customrecipe.dev.buttonweavers.com/ui/game.html?game=194
```

I can provide this in the form of a responder test when time permits.

**Comment by cgolubi1** [comment]
Err, i guess i can't, because making it a responder test would require custom recipes.  

Anyway, i also reproduced this with http://customrecipe.dev.buttonweavers.com/ui/game.html?game=196 where the buttons were `b(1,1) (1)` vs `(10) (10)`.

The bug is obvious from the code, though --- `$dieIdx` is indeed called without being defined (you define `$die` and use `$dieIdx`), so it's getting the value from some previous out of play die, i guess, and if the first out-of-play die is a boom twin, you get an internal error:

```
    /**
     * Array of info about out of play dice
     *
     * @param int $playerIdx
     * @return array
     */
    protected function get_outOfPlayDieArray($playerIdx) {
        $outOfPlayDieArray = array();

        // We never hide information for captured dice, so the requesting playerIdx
        // doesn't matter; use $playerIdx as default.
        $subdieArrayArray = $this->get_subdieArrayArray($playerIdx, 'outofplay');

        if (!empty($this->playerArray[$playerIdx]->outOfPlayDieArray)) {
            foreach ($this->playerArray[$playerIdx]->outOfPlayDieArray as $die) {
                $outOfPlayDieArray[] = array(
                    'value' => $die->value,
                    'sides' => $die->max,
                    'recipe' => $die->recipe,
                    'properties' => $this->get_dieProps($die),
                );

                if (isset($subdieArrayArray) &&
                    isset($subdieArrayArray[$playerIdx][$dieIdx])) {
                    $outOfPlayDieArray[$dieIdx]['subdieArray'] =
                        $subdieArrayArray[$playerIdx][$dieIdx];
                }
            }
        }
        return $outOfPlayDieArray;
    }
```

I recommend you fix this with a module-level regression test and we not worry about a responder test --- i can use replay testing to sanity-check.

**Comment by blackshadowshade** [comment]
Okay, that's just silly. I must have removed the $dieIdx part of the foreach.

On it.
