### ISSUE TITLE
Internal error when choosing an option die side count of 0

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2614]
In a custom button game with `(22)` vs `(0/64)`, if the second player chooses an option value of `0` it yields an internal error.

Log message:

```
Caught exception in BMInterface::submit_die_values: Invalid die value:  is not between 1 and 0 for die (0/64)
```

**Comment by cgolubi1** [comment]
I have an example of this scenario in http://customrecipe.dev.buttonweavers.com/ui/game.html?game=213

**Comment by cgolubi1** [comment]
Let me know if this needs a responder test --- i'm guessing it's straightforward enough it'll be fine with a BMDie or BMGame-level unit test.

**Comment by blackshadowshade** [comment]
I'll be addressing this so that my Fanatic is playable.  :)

**Comment by blackshadowshade** [comment]
I'm going to link this to #2486 so I don't miss it.
