### ISSUE TITLE
Full disk on prod site

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#2615]
Earlier today, the site was generating this error:

    <b>Warning</b>:  Unknown: write failed: No space left on device (28) in <b>Unknown</b> on line <b>0</b><br />
    <br />
    <b>Warning</b>:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in <b>Unknown</b> on line <b>0</b><br />

**Comment by blackshadowshade** [comment]
Don't know if it's helpful, but this is what I see right now on the live site:

Filesystem      Size  Used Avail Use% Mounted on
udev            840M     0  840M   0% /dev
tmpfs           170M   18M  152M  11% /run
/dev/xvda1      7.7G  7.7G   74M 100% /
tmpfs           848M     0  848M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           848M     0  848M   0% /sys/fs/cgroup
/dev/loop0       97M   97M     0 100% /snap/core/9665
/dev/loop2       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop3       18M   18M     0 100% /snap/amazon-ssm-agent/1566
/dev/xvdg1       50G   30G   19G  61% /srv/backup
/dev/xvdb       147G   60M  140G   1% /mnt
/dev/loop4       97M   97M     0 100% /snap/core/9804
tmpfs           170M     0  170M   0% /run/user/1102

**Comment by cgolubi1** [comment]
Shadowshade: i did some manual steps to recover the site; i just don't have time to report further while at work, so i asked Jota to file an issue.

Site should be working normally right now; we'll just need to investigate more later.

**Comment by cgolubi1** [comment]
As far as i can tell, the biggest source of stuff we definitely don't need on the prod site is something called snapd, which is an ubuntu service which makes snap packages of various things.  The disk filled while snapd was running a snapshot on prod, which it apparently does without thinking very hard about whether doing so will cause the disk to fill.

So my hack to get things running again:

```
sudo service snapd stop
cd /var/lib
sudo rm snapd/snaps/core_9993.snap.partial
```

**Comment by cgolubi1** [comment]
The second source of stuff is many versions of `/usr/src/linux-aws-headers-*` and its many friends, for which the suggestion per e.g. https://askubuntu.com/questions/1141630/why-is-usr-src-linux-aws-headers-growing is

```
sudo apt-get autoremove
sudo apt-get autoclean
```

I'm going to try those commands on staging, and if it looks good, i'll try them on prod.

**Comment by cgolubi1** [comment]
First command looked fine on staging, though it ended with:

```
Setting up mysql-server-5.7 (5.7.31-0ubuntu0.16.04.1) ...
insserv: warning: current start runlevel(s) (empty) of script `mysql' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `mysql' overrides LSB defaults (0 1 6).
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.
mysql_upgrade failed with exit status 11
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:E: Sub-process /usr/bin/dpkg returned an error code (1)
```

That seems fine, though; we did indeed stop mysql-server on these hosts.  After this command, the site still works fine.

Running those two commands freed up 2.2GB, which seems like enough that i won't have to futz around with snapd, which seems like something we don't really want, but also don't really want to spend a lot of hassle to remove.

**Comment by cgolubi1** [comment]
Those clean commands got the root volume on prod to 37% full, at which point i went ahead and turned snapd back on --- we don't want it, but why leave things in a weird state when it's no longer the priority.

**Comment by cgolubi1** [comment]
I'm going to go ahead and close this out, since presumably it'll take another couple of years for the disk to fill with header files again.
