### ISSUE TITLE
Make "Create new game" text entry case sensitive?

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2626]
No clue how hard this is, but I've been using "Create Game" as a search when looking up stuff for the wiki, like what all sets/buttons have Rage Dice (for example).

However, "R(" gives me both Rage and Reserve Dice.  Having it case sensitive would be nice.

If this isn't a hard fix, it'd be nice to have.

**Comment by irilyth** [comment]
For this particular thing, if you know (or can use) Python, you might find https://github.com/buttonmen-dev/buttonmen/blob/master/tools/api-client/python/buttons-with-skills useful, and there's some other code there that might prove helpful too.

**Comment by cgolubi1** [comment]
@TheOrgg in the Create game web UI, there's a die skill pulldown that filters buttons by which ones contain a die skill.  Doesn't that do what you want already?

**Comment by TheOrgg** [comment]
How have I never noticed that?

It looks like it'll make it much easier to comb through things with that, for sure.  Sadly, it's only the active skills, so the old way'll have to do for stuff like Plasma.

Part of the reason I'm working on a template is to artify the Classic Fanatics that are missing.  (Does anyone know the font that Fog was using for them?)

**Comment by cgolubi1** [comment]
One relevant thing you may not know is that dev sites let you use unplayable buttons if you want to.  This gives you two possibly-useful option:
* A dev site game creation page, like `http://customrecipe.dev.buttonweavers.com/ui/create_game.html` will let you search for a skill and come up with unplayable buttons that include that skill (won't help with e.g. Plasma, though)
* The buttonset pages on a dev site, like `http://customrecipe.dev.buttonweavers.com/ui/buttons.html?set=Classic%20Fanatics` will let you scan the page and find unplayable buttons.

(Just using the customrecipe site as an example --- this will work with any dev site)

**Comment by TheOrgg** [comment]
I've been using staging.buttonweavers.com for the searches.  The list mentioned (that for some reason I thought was set-releated; guess I never really looked at it) doesn't have the unimplemented skills.
