### ISSUE TITLE
Warrior Die skill needed

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#264]
Warrior: `
These are on the left side of the button as with reserve dice, but are framed in a diamond rather than a circle.
- - - - - - -
Warrior Dice are used for the Shadow Warrior Buttonman from the Sailor Moon set. They are represented with a '`' before a die. Warrior Dice are worth no points, cannot be attacked, and ALWAYS roll the highest number possible. Warrior dice can ONLY attack in a skill attack with NON warrior dice. When this happens the die looses the Warrior skill, and can attack and be captured normally.

 Clarifications: 
•`B (Warrior Berserk): Warrior Berserk dice can not skill attack. This combination is useless. 
•`w (Warrior Slow): Slow is redundant. 
•`g (Warrior Stinger): Warrior Stinger can not be used for the Stinger ability until it looses Warrior. 

 Inconsistencies: •`f (Warrior Focus): Focus dice can NOT be used with dice that are not counted for initative. 
NOTE: ALWAYS roll the highest number possible no longer applies when they lose their warrior ability.

**Comment by irilyth** [comment]
This is my December BFOTM.
