### ISSUE TITLE
Permission gotten for MegaTokyo.

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2640]
![Permission 1](https://user-images.githubusercontent.com/44233993/96357956-b53ad480-10c7-11eb-850b-cc9d0b0c7ac0.jpg)
![Permission 2](https://user-images.githubusercontent.com/44233993/96357958-b8ce5b80-10c7-11eb-9e31-bec480f4819c.jpg)

Praise artists using Twitch.  First Evil Dice, now Art Permissions!

**Comment by blackshadowshade** [comment]
Very nice!

**Comment by TheOrgg** [comment]
![150Piro](https://user-images.githubusercontent.com/44233993/96361963-9d774680-10ef-11eb-8d66-2f95d93cf2bf.png)
![150DarklyCute](https://user-images.githubusercontent.com/44233993/96361964-9e0fdd00-10ef-11eb-8dff-68dd8d515e21.png)
![150Dom](https://user-images.githubusercontent.com/44233993/96361965-9ea87380-10ef-11eb-9c06-130c1b55a139.png)
![150Erika](https://user-images.githubusercontent.com/44233993/96361966-9ea87380-10ef-11eb-83e2-744f1ce2e0b6.png)
![150Largo](https://user-images.githubusercontent.com/44233993/96361967-9ea87380-10ef-11eb-91a8-37551c8696e9.png)
![150Ping](https://user-images.githubusercontent.com/44233993/96361968-9f410a00-10ef-11eb-8cdb-1ca2d0ed5106.png)


Tiny and ready to go.
