### ISSUE TITLE
Queer and Fire interaction

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2652]
Since a Fire die increases the value of an attacking die, a Queer die performing a Power Attack needs to be fired up to an even  value.

For dice that can perform a Skill Attack, this will only really impact fire overshooting, so it's probably not a major issue.

**Comment by jl8e** [comment]
I'd say mark it as a bug and don't worry about it

**Comment by TheOrgg** [comment]
I'm with Jl8e on this one.  It's a "Fog Patch" situation.  (At one point, the rules of M:TG changed and Fog Patch stated it could be played at a point nothing else could be played, rendering it uncounterable.  Nobody cared, but it was neat for a moment)

**Comment by TheOrgg** [comment]
Here's the original issue where I found the info on this

https://github.com/buttonmen-dev/buttonmen/issues/2173

**Comment by blackshadowshade** [comment]
Ah, thanks! Closing as a duplicate then.
