### ISSUE TITLE
Ask to create a testing site for new set: BM Corpo World.

### ISSUE THREAD

**Issue by AnnoDomino** [buttonmen-dev/buttonmen#2664]
Hi,
Please kindly create a test site for testing newly proposed BM set.

Buttons in the set include:
Andrew ks(6) (8) fI(12) (X) (X)
Chad ks(4) (4) It(12) (20) (X)
Fiona (6) fM(10) st(12) (12) (X)
Gavin  (6) fM(8) Is(12) (20) (X)
Isabel  (6) It(8) fs(10) (12) (X)
Monique  kt(8) (8) fs(12) (12) (X)
Naima  (4) st(10) fI(10) (12) (X)
Sachin (6) kt(6) Is(10) (20) (X)

Flavor text - empty for now
Art - empty for now

Many thanks
AnnoDomini

**Comment by danlangford** [comment]
does "Corpo World" refer to "Corporate" like a business? Do you have art idas?

**Comment by AnnoDomino** [comment]
Hi, yes, thats the spirit. The characters would be a project manager, IT developer, CEO, business analyst ect. 
In terms of art I have initially thoguht I could use an avatar making app which advertises itself as a free to use - AvatarMaker.net.
However after some more digging I got confused, as I found out the same app at various different names (AvatarMaker, AvatarCreator, Pickaface) and I tried contacting all of those sites (via Facebook or contact forms) asking to clarify if the avatars created via this app can be used freely also for commercial purposes - but I never got any answers from anyone.

So currently I am thinking of writing a post on some website for freelance artists asking if someone would be keen to make the art for this set for a reasonable price.

**Comment by danlangford** [comment]
ill try my hand at some art using free and royalty free art work from pixabay if you want. license here: https://pixabay.com/service/license/

**Comment by TheOrgg** [comment]
Would Button Men Online be considered commercial?  Unless you're selling them, it seems BMO would be non-commercial.

**Comment by danlangford** [comment]
BMO is noncommercial, but doesn’t matter the license is the same regardless.

**Comment by TheOrgg** [comment]
![error](https://user-images.githubusercontent.com/44233993/106571233-83c20980-64fc-11eb-8666-8ac67450c4c5.png)

Something seems to have gone wrong on the test site (I tried with both TheOrgg and theorgg, getting this same message).

**Comment by AnnoDomino** [comment]
Hi BSS,

Can I please ask you to update the receipes for the 2nd round of tesitng of Corpo World set?

Changes to be made:
Set name change to: CyberSuit Corp

Buttons receipes:
Andrew ks(6) fI(8) (12) (12) (V)
Chad ks(4) (4) It(12) (20) (V)
Fiona st(6) fM(10) (12) (12) (V)
Gavin fM(6) Is(8) (12) (20) (V)
Isabel (6) It(8) fs(10) (12) (V)
Monique kt(8) (8) fs(12) (12) (V)
Nadia (6) st(10) fI(10) (12) (V)   - change of button name here, new name better suits with art
Sachin (6) kt(6) Is(10) (20) (V)

Thank you.

**Comment by TheOrgg** [comment]
Checked to see if the new characters were up yet or not and had the same password error occur.

**Comment by AnnoDomino** [comment]
HI, just cheking if there is any chance to update the buttons for Cybersuit Corp set on the testing site in the coming weeks?
Many thanks for some info on that!

**Comment by AnnoDomino** [comment]
hi,
I'd like to ask for a final (hopefully) change of receipes for 3rd round of testing on the following Buttons from the CyberSuit Corp set:

Fiona: st(4) fM(8) (12) (12) (V)
Nadia: (8) st(8) fI(10) (10) (V)
Gavin: fM(6) Is(8) (20) (20) (V) 

many thanks!

**Comment by TheOrgg** [comment]
Can we try a couple of the alternates as well to make sure the best one's used?

Fi0nah: st(6) fM(8) (12) (12) (V)

Nadia 223:  fI(6) st(10) (10) (12) (V)

Gaelvin: fM(6) Is(8) (10) (10) (V)

If Anno doesn't want to, that's cool.  I think this could be the finalizing round if we have an alternate for each.

**Comment by blackshadowshade** [comment]
@cgolubi1, I've added an update file that adds these new testing recipes to the database as Fiona1, Nadia1, Gavin1, Fiona2, Nadia2, Gavin2.

I haven't changed data.button.sql, I'll clean all this up when testing is done and I recreate the files from scratch.
