### ISSUE TITLE
Prime Swing dice needed

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#267]
I'm not sure if Prime swing is the actual name, but it's characterized by one or more prime marks (single quotes) after the swing value.  
Normally with two dice with the same swing value, the same size swing selection is applied to both dice.  
(X) (X), for example, can only be given a single value applied to both.
(X) (X)' would allow each die to be given a separate size during swing selection
(X) (X)' (X)'' would allow 3 separate values, and so on.
(X) (X)' (X)' or (X) (X) (X)' would only allow 2 values. 

I don't recall which set first required this die type, but I think it is not unique to the old site.

**Comment by irilyth** [comment]
I'm very sure that there weren't any buttons with prime Swing dice on the old site, but there could have been on the *dev* site, which shut down just around when I started playing, which could explain why you and Fog both mentioned remembering them.

**Comment by blackshadowshade** [comment]
I'm going to close this because there appears to be no need for such a skill.
