### ISSUE TITLE
Polyhedral Dice

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#268]
I think that, for the most part, when people play this game in real life they stick to regular polyhedral dice when choosing swing values.  I think there should exist an option that allows users to simulate this choice.  

This will effect Mood Swing and Turbo.  But according to beatpeopleup:
When you use a Mood Swing as part of an Attack, you must change its size randomly according to the following charts: 
X?: Roll a d6. 1: d4; 2: d6; 3: d8; 4: d10; 5: d12; 6: d20. 
V?: Roll a d4. 1: d6; 2: d8; 3: d10; 4: d12. 
(These were the first two swing dice. There's another chart out there that includes all 9 swing values.)  

This would be a player preference, as well as an option for creating games and tournaments.  I know there's some buttons with things like (15)? in their recipes, so I'm not sure how to handle these if a player's preference is for polyhedral dice.

**Comment by blackshadowshade** [comment]
I'm closing this because I don't sense any great wish or need for this. If anyone disagrees, they can reopen the issue.
