### ISSUE TITLE
Flying Squirrel made a skill attack, that should be disallowed by server

### ISSUE THREAD

**Issue by danlangford** [buttonmen-dev/buttonmen#2687]
BMAI playing Flying Squirrel made a skill attack successfully. played by user buttonbot2. http://buttonweavers.com/ui/game.html?game=68913 That should be restricted by the server. some of the initial discussion was in #369 and #1677

**Comment by blackshadowshade** [comment]
We've tested manually, and the option to do a skill attack doesn't show up in the attack list.

The next step is to see if a default attack of two dice vs one die goes through.

**Comment by danlangford** [comment]
from IRC:
```
i8bagels 21:57:29
so the Flying Squirrel has a button special that says he cannot make Skill attacks. i have a game in which BMAI made a skill attack with Flying Squirrel. So it seems that button special is not enforced on the server side. i wonder if its enforced client side. i started a game to try to test it out with BSS #6908 im going to test some other things out in that game9
@shadowshade 21:57:56
hmmm
it should be enforced on the server side
there's no logic in the UI enforcing it
i8bagels 21:59:55
in game=68913 buttonbot2 is playing Flying Squirrel and successfully made a skill attack. BMAI doesnt know about that restriction so i went searching games to see if the server allowed a skill attack
@shadowshade 22:01:45
hmmm, so it did
i8bagels 22:04:30
would you like me to make an issue in GH to track this regression? 
@shadowshade 22:05:08
I think that's a good idea
I'm just taking a look at the code base now
@shadowshade 22:07:16
hmmm, I think I see how such a loophole might occur
the UI lists the possible attack types, but I guess the API allows attacks to be submitted that are not on that list
@shadowshade 22:09:29
my guess is that the backend doesn't check the attack type against the list of possible attack types
```

**Comment by blackshadowshade** [comment]
I also tested a three die vs one die default attack, and it gave me the message "There is no valid attack corresponding to the dice selected."

Looks like the loophole is API only, the UI keeps things locked down for normal users.

**Comment by blackshadowshade** [comment]
More recently, BMAI has been able to pass when a pass should not have been a valid option.

**Comment by cgolubi1** [comment]
Drive-by note: this is absolutely something random_ai should be able to find in the wild --- i would need to add a small percent change of choosing an attack type *not* offered by the backend, and ensure that the attempt is rejected.
