### ISSUE TITLE
Fog/Tilili generic art

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2693]
Just had this idea while working on the Classic Fanatics images (PSP is NOT intuitive; might have to take the dice frames and templates into GIMP and export the names).  Generic image for Hodgepodge's Tilili (other missing images I've supplied possible substitutes) and a generic image for Fog's button in Bridge and Tunnel using elements of his CF design for each.  This seems fitting to me, as Fog has his image on his fanatic.

If ya'll don't feel this work for replacing the generic image, let me know your thoughts on it.  I'm going to try and get the currently active with no art Fanatics done within the next week, but no guarantees there.

![GenericFog](https://user-images.githubusercontent.com/44233993/104830636-1cdafa00-5846-11eb-9367-d7208c841773.png)

![150pxGenericFog](https://user-images.githubusercontent.com/44233993/104830534-ac33dd80-5845-11eb-9564-5e98ad7a9dc5.png)
![150pxTeliliGenericTeliliHodgepodge](https://user-images.githubusercontent.com/44233993/104830537-b8b83600-5845-11eb-8a77-6ce0261f7264.png)
![TeliliGenericTeliliHodgepodge](https://user-images.githubusercontent.com/44233993/104830544-c2da3480-5845-11eb-82f5-ee5372dc26d8.png)

**Comment by dwvanstone** [comment]
Is fog (the player who has a Fanatic with unimplemented skills) the same person as The Fog in the B&T set? If so, perhaps you can reuse his photo from the Fanatic.

The blue on black background doesn't work very well for that button. I'd go more for what you did really well with Tilili. (I like the Tilili button!)

**Comment by TheOrgg** [comment]
Yes, same Fog.  I did the generic look because he has an image in Fanatics.  He didn't have that image in large form in his files, though, unfortunately.  The assets used are from the Bridge and Tunnel assets he had.  I'll see what I can do with it to make it pop more.

**Comment by TheOrgg** [comment]
![150Fog2](https://user-images.githubusercontent.com/44233993/105110903-50579780-5a85-11eb-91b5-c95e0062f406.png)
Better?

**Comment by irilyth** [comment]
Is the Bridge & Tunnel button "The Fog", or just "Fog"?

**Comment by TheOrgg** [comment]
Oop!  Good catch!

**Comment by TheOrgg** [comment]
![150Fog2](https://user-images.githubusercontent.com/44233993/105117728-9f57f980-5a92-11eb-920c-7802e5a34202.png)
