### ISSUE TITLE
Active Classic Fanatics and 2 Inactive Button recipe changes

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2704]
ABCGi (X,X) to (X!,Y!)
I'd just change the recipe; doesn't look troublesome.

Cest Wha has a pk(2) on image, p(2) on recipe
Makes it worse.  Does anyone object to the pk die?

Gman has stinger but rage on image.
Hmmm.  This'd be a huge change to the character.  Gut says change the art on this one.

Prof. Booty has last two dice swapped, update recipe order
Another where just matching the art seems trivial.

RavenBlack has a Mighty in art, but a Weak in recipe.
Not sure on this one, but I'd lean towards changing it to Mighty.

Steve (Bridge and Tunnel): Update recipe as specified by Steve himself (two that would randomly occur) 

Update Blackjack, The Cheat (Inactive) to have a (10,10,1) Triplet Die.

**Comment by jl8e** [comment]
The ABCGi change requires a feature that isn't supported

**Comment by TheOrgg** [comment]
Oh.  I didn't realize there couldn't be mixed variable twin dice.  My bad.

**Comment by blackshadowshade** [comment]
We've dealt with that issue by outlawing mixed swing twin dice entirely, so no, there's no plan to support (X,Y)! dice.

**Comment by TheOrgg** [comment]
The only one of these I can fix in twenty minutes is the RavenBlack one, but I think it would be better to tweak the actual recipe to match the art.

I'd prefer some discussion on it, though.

**Comment by dwvanstone** [comment]
My leaning is towards following the creator's intentions as much as possible.

Perhaps we should change the ABCGi to (X!,Y!) and then have it removed from the playable site. Not as much fun for us all but it matches the author's intent.

I think it would be good to change CestWhat? That seems like a clear oversight, perhaps even on the old site. However, the statistics for the old CestWhat should be removed. 

ProfessorBooty should have its recipe order swapped. That wouldn't affect statistics.

RavenBlack ... that artwork was made by TheFog, right? It's not clear it if was made with RavenBlack's intent. I'd go with the recipe from the old site for this (closest we have to author's intent) and change the artwork to match.

What's the issue # for the Steve (Bridge and Tunnel) changes?

What's the argument for changing Blackjack, The Cheat to a triplet die? Was that the author's intent? Please point to the issue # where this is discussed.

Thanks!

**Comment by TheOrgg** [comment]
Steve's change is from the interview with him about the set.  His character was to have two recipes that were selected at random as the 'final boss' type character.  There's just the single one on the staging site.

I tested out the Vegas set for a few months at home after commissioning the artwork, and made the 10,11 into a triplet for playability.  Ryan later approved of the efforts, though he didn't respond to any follow-up questions.

**Comment by TheOrgg** [comment]
The reason I hesitated in changing RavenBlack is that Fog titled each of the die sections when he created the images.  Most of the errors I've seen had the right size or skill listed, but not on the image in that file.

RavenBlack has a Mighty even on the image file document.  Let me check the old BM site's list and see if RavenBlack is on it...  Nope.  I made the image, but I'll leave it to @blackshadowshade  as final arbiter.
![150RavenBlack](https://user-images.githubusercontent.com/44233993/106067338-1fe6ad80-60c4-11eb-8701-2c31d54ea96c.png)

Why do you want to reset the statistics on Cest?  There's been 65 games played.  I don't think that'd end up being statistically significant in the long run.  If it was 200+, the story would be different.

I'd also prefer to keep ABCi as is instead of deactivating him, as the change isn't that big and, again, he has 56 games.  And if the multiple turbo variable twin dice do get activated in a decade or so, change him up.  Even then, he'll probably have less than 100 games...
