### ISSUE TITLE
dropped connections on prod site

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2707]
Since late January, i've been seeing a lot more dropped connections on the prod site.  Here's an example exception:

```
[Tue Feb 02 01:03:00.392551 2021] [:error] [pid 25191] [client X.X.X.X:Y] Caught exception in mysql.inc.php: SQLSTATE[HY000] [2006]  MySQL server has gone away, referer: $SITE/ui/index.html?mode=preference
[Tue Feb 02 01:03:00.393532 2021] [:error] [pid 25191] [client X.X.X.X:Y] PHP Notice:  Undefined variable: conn in /var/www/database/mysql.inc.php on line 46, referer: $SITE/ui/index.html?mode=preference
[Tue Feb 02 01:03:00.393664 2021] [:error] [pid 25191] [client X.X.X.X:Y] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /var/www/engine/BMInterface.php:1603\nStack trace:\n#0    /var/www/engine/BMInterface.php(1709): BMInterface->get_all_games('$PLAYERID', 'NEW')\n#1 /var/www/api/ApiResponder.php(263): BMInterface->get_all_new_games('$PLAYERID')\n#2 /var/www/api/ApiResponder.php(1004):  ApiResponder->get_interface_response_loadNewGames(Object(BMInterface), Array)\n#3 /var/www/api/responder.php(23): ApiResponder->process_request(Array)\n#4 {main}\n  thrown in /var/www/engine/BMInterface.php on line 1603, referer: $SITE/ui/index.html?mode=preference
```

I used to see these maybe once a month; since late January there's been at least one every day, usually more; there's always one around 1am (UTC), often they show up at other times too.  I assume this shows up as an error for players, but i'm not aware that anyone has complained so i can't verify that.

**Comment by cgolubi1** [comment]
I would say it's probably a database and/or load thing, not a code thing, both because we didn't do a release until Feb 8th, and this pattern was pretty established by then, and because i counted up the code functions that are hitting this error, and they're all over the map:

```
     39 auth_session_exists
     14 BMDB->select_rows
      2 BMDB->update
      9 BMInterfaceForum->get_next_new_post
      2 BMInterfaceGameAction->load_game_action_log
      1 BMInterfaceGameChat->load_game_chat_log
    194 BMInterface->get_all_games
     18 BMInterface->get_next_pending_game
      1 BMInterfaceNewuser->create_user
      2 BMInterfaceNewuser->forgot_password
     17 BMInterfacePlayer->get_player_info
     13 BMInterfacePlayer->update_last_access_time
      1 BMInterfacePlayer->update_last_action_time
     30 login
```

(First column is count, second column is function name that shows up in the stacktrace.)

**Comment by cgolubi1** [comment]
I've run out of time for today, but i wanted to file an issue for this, because i haven't made a lot of progress.  I think there are two major tacks to take here:
A. Some sort of problem has cropped up between the prod site and its database which we could mitigate, e.g. a bad network path (which a restart or stop/start would probably clear up), or load has increased past some tipping point (though i'd believe the latter theory more if this happened at the same time of day as our big daily spike in traffic when Nala grabs games, and unless i have some timezone math i don't think i do, it's a different time)
B. Database connections flake out sometimes and the PHP code should be able to retry creating a connection if one falls over

I like B as an idea --- i definitely ever saw this exception before (between August and December of last year, i saw it 5 times, as opposed to ~300 in the past month as evidenced by the call counts above) --- but i have to be able to reproduce the problem to test a fix, and so far i've been trying to get my dev RDS site to show this problem by driving load, and i've had zero successes so far.

**Comment by cgolubi1** [comment]
Oh, also, i don't think 01:00 UTC is the same time we run the nightly mysqldump of the site, which we know does cause site freezes for players (but not internal errors, interestingly) --- i think that backup happens at 00:00 UTC.

**Comment by blackshadowshade** [comment]
I wonder if this is due to Bagels running something at this time.

**Comment by blackshadowshade** [comment]
Linking #1988 to this issue.

**Comment by danlangford** [comment]
that would be 6pm my time MST. i don't generally run anything on a schedule like that. so i have BMAIBagels running constantly. and by constantly i mean every couple minutes it is looking for games to join and available moves to make. 

i also generally run once a day my MMR calculations for the Hit Lists. that pulls all the COMPLETED games for a particular month and parses through the results. i don't think that would cause a problem. how can we test this? it is currently ~10:19pm UTC ill go run some MMR stuff on the month of Feb. tell me if you get a crash. 

i ran a particularly big batch. and i get all the data i need i don't think I'm crashing. most of what i am doing is hopefully not too intensive.

**Comment by cgolubi1** [comment]
Thanks for the test run, Bagels.  Short version: we didn't get any errors while you were running.

Longer version: i don't think that activity has anything to do with the problem; in terms of call count, everything everyone else is doing is much much lower than Nala's nightly batch of loadGameData calls (Nala calls loadGameData around 1200 times in 5 minutes, we basically never get out of double-digit calls in 5 minutes any other time), but, again, Nala is running at around 09:00 UTC, and that's not a time when i'm typically seeing problems.  You do seem to be the only one who calls searchGameHistory in any volume, but again it's not much volume (30-odd calls, maybe), and in practice, it doesn't seem to be triggering a problem.

So that's sad because i'd love to be able to reproduce the problem at will, but not-sad because it doesn't surprise me at all.  :>)

**Comment by cgolubi1** [comment]
I don't object to the linking, but note that #1988 is suggesting retrying at a totally different place in the system --- that's "retry if JS doesn't successfully contact the API" (e.g. if the player's network connection is flaky); this is "retry if the PHP backend doesn't successfully talk to the database".

**Comment by blackshadowshade** [comment]
Ah, I didn't catch that difference.

**Comment by cgolubi1** [comment]
For my future reference:
* These failures show up in the log as `BMStatus=-` presumably meaning the API isn't sending a well-formed response (no surprise)
* The cloudwatch metrics do successfully record these failures as failures

It occurs to me that my easiest path forward is to just hack something into the backend that drops the database connection 1% of the time --- that'll let me test logic that retries/responds cleanly to database failures, without worrying too much about reproducing the actual cause.

**Comment by danlangford** [comment]
I don’t know a lot about php DBs. Is there connection pooling? Or does PHP not maintain a long connection anyway? 

Does the increase in failures coincide with a release?

**Comment by cgolubi1** [comment]
> Does the increase in failures coincide with a release?

No, sadly.  We didn't have any releases between mid-fall and February, and the errors started happening near the end of January.
