### ISSUE TITLE
Additional image updates (Fanatics, Hodgepodge, etc)

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2721]
This issue will be for further Classic Fanatics being updated to include new images from the suggestions of their creators.

This is submitted for Limax's approval.  This is the nicest public domain picture I could find of a wombat.

Large (if he wants a button)
![LimaxFanatic](https://user-images.githubusercontent.com/44233993/114800569-927c3680-9d5f-11eb-943a-6b71d435114d.png)

150px (for the site, with shine/shade)
![150pxLimax](https://user-images.githubusercontent.com/44233993/114800616-a3c54300-9d5f-11eb-8a27-2edd6a84b31e.png)

**Comment by TheOrgg** [comment]
Limax has approved!

**Comment by TheOrgg** [comment]
I created an image for Tyler Durdan a while back, but due to copyright concerns it wasn't used.  

How about an image from the Dastardly Durdan memes instead?

![TylerDurdan150px](https://user-images.githubusercontent.com/44233993/124362936-ea5b6880-dbfd-11eb-8d54-951a80d28da4.png)

**Comment by jl8e** [comment]
Regardless of opinions of the image, the contrast on that dark purple die makes it hard to read

**Comment by TheOrgg** [comment]
Note taken.  I'll change it to white when I have the time.

**Comment by TheOrgg** [comment]
Here's the improved Durdan and...  NoopMan!!

![TylerDurdan150](https://user-images.githubusercontent.com/44233993/124641977-e6755380-de54-11eb-8073-da2505556849.png)


![NoopManFanatic](https://user-images.githubusercontent.com/44233993/124642042-fa20ba00-de54-11eb-9c8d-c98d2c4cf1c1.png)
![150pxNoopMan](https://user-images.githubusercontent.com/44233993/124642054-00169b00-de55-11eb-9c22-59028a6c7f06.png)

**Comment by TheOrgg** [comment]
Here's Wormy and Mneme!
![WTrollkinFanatic1](https://user-images.githubusercontent.com/44233993/141666127-1cf0b5fa-c7db-481b-a3c0-a91dea9f2aa2.png)
![150pxWTrollkin](https://user-images.githubusercontent.com/44233993/141666147-d7e32121-0b41-4180-aa94-117c93dd1d37.png)
![MnemeButtonNoShine](https://user-images.githubusercontent.com/44233993/141666161-4479491d-8078-42a5-b501-3f2be917e737.png)

![150pxMneme](https://user-images.githubusercontent.com/44233993/141666164-7d7c7515-5b24-4733-9174-f15fd3171534.png)

**Comment by TheOrgg** [comment]
Boot to tha' head.
![Boot2DaHead](https://user-images.githubusercontent.com/44233993/144947582-bb978534-5e21-463b-9cc1-4e7f12f8c05e.png)
![150Boot2DaHead](https://user-images.githubusercontent.com/44233993/144947605-e3ab54f6-f233-4581-9a71-966b6330f677.png)

(origins:  https://www.youtube.com/watch?v=Z8VD4JXUozM and https://www.youtube.com/watch?v=2wC2jOSj8xU )

**Comment by TheOrgg** [comment]
A few more to add...
![150pxGrayhawk](https://github.com/user-attachments/assets/ff252eea-675b-465f-99fa-fe730b3f7801)
![150pxPjack](https://github.com/user-attachments/assets/aff3012b-5c50-410c-ac18-dd8c7bfe7efc)
![150pxTasselhoffB](https://github.com/user-attachments/assets/ea2baf08-3135-4288-a066-6297c81e4e64)
![150pxZomulgustar](https://github.com/user-attachments/assets/2c73c60f-8f8d-441e-9ae1-b12695886ad8)

**Comment by TheOrgg** [comment]
Forgot the shine on Tasselhoff.  If anyone wants me to go back and fix it I can.

**Comment by TheOrgg** [comment]
@blackshadowshade

**Comment by TheOrgg** [comment]
![150pxTasslehoffB](https://github.com/user-attachments/assets/6a43cdeb-c42d-4070-8e76-feffd00356c0)

**Comment by blackshadowshade** [comment]
The colour of the font for Tasslehoff B is now gray. Is that what you were aiming for?

**Comment by TheOrgg** [comment]
Yes.  Like Elihu Root, I think the grey works better with the artwork.
