### ISSUE TITLE
grunt broke again

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2728]
Tests are failing again with another grunt/npm error, see e.g. https://circleci.com/workflow-run/3e0ec22d-d70e-40ac-ad97-1c3a6e4b6605

**Comment by blackshadowshade** [comment]
Relating to that, I received a security vulnerability advisory, happy to forward it if you didn't receive it, @cgolubi1.

**Comment by cgolubi1** [comment]
I got it as well, thanks.  And i wouldn't be surprised if people took older versions of packages we're using for testing offline as a result of it.
