### ISSUE TITLE
Default attack with trip and boom is annoying

### ISSUE THREAD

**Issue by jl8e** [buttonmen-dev/buttonmen#2736]
Everyone hates it when they click the dice for the power attack, hit the button and... "default attack is ambiguous", and we have to do All That Hard Work to click on the menu and hit the button again.

if default attack ignored non-capturing attacks unless they were the only choice, would it actually screw anyone over? 

(obviously, it's not a big deal, and it complicates the default attack logic)

**Comment by irilyth** [comment]
Is this a duplicate of #1671?

**Comment by jl8e** [comment]
Yeah, I didn't search
