### ISSUE TITLE
Jolt die skill needed

### ISSUE THREAD

**Issue by yawetag** [buttonmen-dev/buttonmen#275]
Jolt: J
(Exclusive to this website; unofficial)
Jolt Dice were created by Randy Chertkow (aka Famous) for this web site. They are represented by a "J" before a die. They are normal in all respects, except that when they attack, or are attacked. If a Jolt die attacks, or participates in an attack, the player will get to take another turn and the Jolt die losses the Jolt skill. If a Jolt die is captured, then the player who captured it takes another turn.

Inconsistencies:

```
J^ (Jolt Time & Space): Will not give more than 1 extra turn if rerolled to an odd number. 
```

**Comment by blackshadowshade** [comment]
The description of Jolt here seems to be a bit broken, so it needs to be fixed.

**Comment by irilyth** [comment]
How's this for a pretty simplified rewrite:

If a Jolt die participates in an attack, the die loses the Jolt skill, and the attacking player takes another turn. If a Jolt die is captured, the player who captured it takes another turn.

Do we need to talk about the interaction with T&S dice, or multiple Jolt dice? We could, or it might make more sense to say as a basic rule of play that a player can only gain one additional turn per turn.

**Comment by blackshadowshade** [comment]
That's great, thanks irilyth! I'll put down the interaction, although I wouldn't expect it to appear anywhere except in RandomBM.
