### ISSUE TITLE
get_friendly_time_span() broken due to bad intdiv() syntax

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2767]
Any site created with the current master codebase, the primary UI can't be loaded --- the apache log error is:

`PHP Warning:  intdiv() expects exactly 2 parameters, 1 given in /var/www/engine/BMInterface.php on line 2556`

**Comment by cgolubi1** [comment]
Well, this interface refactor is certainly drawing our attention to functions we don't test, huh?

**Comment by cgolubi1** [comment]
Ah, of course.  I broke all the cases where a game is more than 60 seconds old, which never comes up in responder-style testing.  Sigh.

**Comment by blackshadowshade** [comment]
Yup, I spotted that in my Tournaments pull request and fixed it there

**Comment by blackshadowshade** [comment]
The syntax fix is changing

    $minutes = intdiv($seconds / 60);

to

    $minutes = intdiv($seconds, 60);

**Comment by cgolubi1** [comment]
Yeah, i know.  I'm just working on making a test for it.

**Comment by cgolubi1** [comment]
Thanks!
