### ISSUE TITLE
Flavor Text for Effster and Fictitious Alan Clark

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2779]
"The Effster writes constantly, using various pseudonyms like Stephen King, John Grisham, Danielle Steel, etc., but whenever he takes a break he likes to beat people up."

"The Fictitious Alan Clark likes to strip people naked and paint gaping wounds on their bodies, then he likes to beat them up."

**Comment by danlangford** [comment]
@blackshadowshade or @cgolubi1 I was going to quickly fix this but then I realized I saw some flavor text in 

    deploy/database/updates/*.sql

and some flavor text in 

    deploy/database/data.button.sql

and wasn't quite sure the proper place to be adding this

**Comment by blackshadowshade** [comment]
Changes need to happen in both places.

data.button.sql allows us to regenerate a clean database from scratch, which is used for dev sites.

updates/*.sql are what we use when updating the live database

**Comment by danlangford** [comment]
Ohhh the dev sites don’t just run through all the update scripts. Gotcha. Thanks BSS

**Comment by TheOrgg** [comment]
So did you figure out how to update flavor text, @danlangford ?

**Comment by danlangford** [comment]
Oh man I think I got distracted on other things. My bad.
