### ISSUE TITLE
Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2808]
A standard replay loop hit this failure:

```python
Starting game 79
Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1803, in log_test_game
    self.next_game_action()
  File "lib/random_ai.py", line 1787, in next_game_action
    if state == 'START_TURN': self._game_action_start_turn()
  File "lib/random_ai.py", line 1668, in _game_action_start_turn
    self.loaded_data['playerDataArray'][1])
  File "lib/random_ai.py", line 1581, in _game_action_start_turn_player
    retval and retval.message or "NULL"))
  File "lib/random_ai.py", line 1683, in bug
    raise ValueError, message
ValueError: API submit_turn(79, 0, 1, {'playerIdx_0_dieIdx_2': 'false', 'playerIdx_0_dieIdx_0': 'false', 'playerIdx_0_dieIdx_1': 'true', 'playerIdx_1_dieIdx_1': 'true', 'playerIdx_1_dieIdx_0': 'false', 'playerIdx_1_dieIdx_2': 'false'}, Power, 2, 1641600061, {}) unexpectedly failed: Internal error while submitting turn
```

The log message is:

```
[Sat Jan 08 00:01:02.227924 2022] [:error] [pid 18424] [client 127.0.0.1:50644] Caught exception in BMInterface::save_game: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
[Sat Jan 08 00:01:02.235067 2022] [:error] [pid 18424] [client 127.0.0.1:50644] Caught exception in BMInterface::submit_turn: Game save failed
```

The game state looks like:

<img width="1150" alt="deadlock" src="https://user-images.githubusercontent.com/2898207/148629960-dcd19301-6293-4db0-87ca-68ce24e6f5e3.png">

Rerunning the same attack manually, it succeeded with no problem:

<img width="1150" alt="deadlock_rerun" src="https://user-images.githubusercontent.com/2898207/148630027-3b8b94f7-f2a5-45a3-9769-b0f8ba4187eb.png">

**Comment by cgolubi1** [comment]
I'm not going to worry about this unless it starts happening more often.  Just recording the information in case it becomes relevant later.  The internet suggests that you can hit deadlock if different code locks your tables in different orders, which makes sense, but i don't immediately see the relevance to how save_game uses transactions.

**Comment by cgolubi1** [comment]
Hit this on replay-cgolubi1-master:

```
[Thu Feb 17 00:01:02.175075 2022] [:error] [pid 2324] [client 127.0.0.1:45276] Caught exception in BMInterface::save_game: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
[Thu Feb 17 00:01:02.176730 2022] [:error] [pid 2324] [client 127.0.0.1:45276] Caught exception in BMInterface::submit_turn: Game save failed
```

Here's what the replay loop saw:

```
Starting game 37
Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1820, in log_test_game
    self.next_game_action()
  File "lib/random_ai.py", line 1804, in next_game_action
    if state == 'START_TURN': self._game_action_start_turn()
  File "lib/random_ai.py", line 1674, in _game_action_start_turn
    self.loaded_data['playerDataArray'][0])
  File "lib/random_ai.py", line 1581, in _game_action_start_turn_player
    retval and retval.message or "NULL"))
  File "lib/random_ai.py", line 1696, in bug
    raise ValueError, message
ValueError: API submit_turn(37, 1, 0, {'playerIdx_0_dieIdx_2': 'false', 'playerIdx_0_dieIdx_3': 'false', 'playerIdx_0_dieIdx_0': 'true', 'playerIdx_0_dieIdx_1': 'false', 'playerIdx_1_dieIdx_1': 'false', 'playerIdx_1_dieIdx_0': 'true'}, Power, 5, 1645056061, {}) unexpectedly failed: Internal error while submitting turn
ip-172-31-43-13,[~],00:01(1)$
```

Given the timestamp, this *must* have been caused by the nightly mysqldump.  I wonder if per https://stackoverflow.com/questions/104612/run-mysqldump-without-locking-tables we should turn off locking for mysqldump.  Presumably that increases the chances that there'd be some inconsistency in games that were being changed at the time the backup was being run.  But i'm inclined to think if we're ever in a situation where we have to restore the DB from backup, there just will be some games that get corrupted by whatever was happening at the time the backup ran, and we'll cope with it.

Table-by-table locking certainly won't prevent discrepancies --- i don't think there's any reason to believe the random mysqldump options we launched with are going to be effective at preventing issues, so i think we should find some options that are less disruptive to real-time users.

**Comment by cgolubi1** [comment]
From the mysqldump manpage:

```
       ·   --single-transaction This option sets the transaction isolation mode to REPEATABLE READ and sends a START TRANSACTION SQL statement to the
           server before dumping data. It is useful only with transactional tables such as InnoDB, because then it dumps the consistent state of the
           database at the time when START TRANSACTION was issued without blocking any applications.

           When using this option, you should keep in mind that only InnoDB tables are dumped in a consistent state. For example, any MyISAM or
           MEMORY tables dumped while using this option may still change state.

           While a --single-transaction dump is in process, to ensure a valid dump file (correct table contents and binary log coordinates), no other
           connection should use the following statements: ALTER TABLE, CREATE TABLE, DROP TABLE, RENAME TABLE, TRUNCATE TABLE. A consistent read is
           not isolated from those statements, so use of them on a table to be dumped can cause the SELECT that is performed by mysqldump to retrieve
           the table contents to obtain incorrect contents or fail.

           The --single-transaction option and the --lock-tables option are mutually exclusive because LOCK TABLES causes any pending transactions to
           be committed implicitly.

           To dump large tables, combine the --single-transaction option with the --quick option.
```

I don't see why that shouldn't work well.  Running locally, it seems to work, as in running a database backup with that option on an idle site produces a backup which is identical to one created without that flag.  Let me try some replay testing.

**Comment by cgolubi1** [comment]
My initial replay smoke test was to use the default mysqldump settings, and run the backup once a minute (rather than once a day).  With that configuration, it took 2 minutes for the replay loop to fall over with an internal error.  So the problem is reproducible.

Now i'm planning to run with the new settings, and leave that "backup once a minute" cron job installed.  I may run into problems if a backup takes more than 1 minute to run (which is only a problem caused by my test rig for this PR, not related to the issue itself; we've never seen a backup take more than a day to run), but ideally i won't see any problems with replay_loop falling over due to transaction deadlocks.  So far, it's played 40 games over 5-6 minutes, and things look fine, but obviously i want more data.

Do y'all want a dev site running a backup every minute so you can try out the user experience while a backup is running?  Or are you happy to merge if the replay testing seems good and try it out on prod when we get there?  Either way is fine with me.

**Comment by blackshadowshade** [comment]
To make the chance of the database backup being inconsistent less likely, we could also revisit the time of the backup, choosing the time where we historically have the least activity. If I understand correctly, we should now have stats on that from our usage monitoring.

**Comment by cgolubi1** [comment]
I think `--single-transaction` means we don't have to worry about when the backup is taken, because the backup will save the state as of a point-in-time, even if the DB state changes after that point in time.

I also stand by "minor inconsistency in the backup file is not that big a deal to us; at the point at which we are using the backup file, we have bigger fish to fry."  I'm not planning to worry about it any more for awhile if this PR seems to work.
