### ISSUE TITLE
backend incorrectly thinks trip attack vs maximum weak mood die won't work

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2809]
This attack should be allowed, right?  It isn't:

<img width="1150" alt="sure_it_can" src="https://user-images.githubusercontent.com/2898207/148694954-309c48b7-efda-428a-96fa-24fc15d66e51.png">

(Found this via testing to allow mad/mood in RandomBM.)  If someone can +1 that this should indeed be allowed and i'm not missing something, i'll throw together a responder test.

**Comment by cgolubi1** [comment]
I can see the bug --- here's the code snippet, in `./src/engine/BMAttackTrip.php`:

```php
    /**
     * Check whether the trip attack is disabled by the maximum die skill
     *
     * @param BMDie $att
     * @param BMDie $def
     * @return bool
     */
    protected function is_disabled_by_maximum(BMDie $att, BMDie $def) {
        if ($att->has_skill('Konstant')) {
            $attMaxVal = $att->value;
        } else {
            $attMaxVal = self::post_trip_roll_max($att);
        }

        $defMaxVal = self::post_trip_roll_max($def);

        if (is_null($attMaxVal) || is_null($defMaxVal)) {
            return FALSE;
        }

        if ($def->has_skill('Maximum') && ($attMaxVal < $defMaxVal)) {
            $this->validationMessage = 'The attacking die cannot roll high enough to capture the target die';
            return TRUE;
        }

        return FALSE;
    }

    /**
     * Calculates the die max after rolling a die because of a trip attack
     *
     * @param BMDie $die
     * @return int
     */
    public static function post_trip_roll_max($die) {
        $clone = clone $die;
        $postRollMax = $clone->max;

        if ($clone->has_skill('Weak')) {
            $clone->shrink();
            $postRollMax = $clone->max;
        }

        if ($clone->has_skill('Mighty')) {
            $clone->grow();
            $postRollMax = $clone->max;
        }

        if ($die->has_skill('Mad')) {
            if (isset($die->swingType)) {
                $postRollMax = $die->swingMax - ($die->swingMax % 2);
            }
        } elseif ($die->has_skill('Mood')) {
            if (isset($die->swingType)) {
                $postRollMax = $die->swingMax;
            }
        }

        return $postRollMax;
    }
```

So the maximum check uses `post_trip_roll_max()` to find the maximum size the defender can have after the attack, but in the mad and mood cases, that function returns the maximum number of sides the defender *could* have, not the number of sides the defender *will* have.  That's appropriate for the attacker, but not the defender --- for the defender, we need to know the minimum number of sides the die could have.

**Comment by cgolubi1** [comment]
Shadowshade, let me know if you mind, but i'm not going to bother with a responder test --- this strikes me as exactly the kind of behavior you're locking in using the tests in `test/src/engine/BMAttackTripTest.php`.  We'll get just as much information from a 10-line test in that file, as we would from a 200-line responderTest.

**Comment by blackshadowshade** [comment]
Sounds right to me. A simple test is a good test.  :)

**Comment by cgolubi1** [comment]
> Sounds right to me. A simple test is a good test. :)

Yeah, i still think there's a use for responder tests in the "this is wrong and we don't understand why what's happening at the API layer is happening" case.  But that's not this case.
