### ISSUE TITLE
CustomBM is visible on the live site

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2810]
At http://www.buttonweavers.com/ui/forum.html#!threadId=1019&postId=23491, Scipio noticed that the CustomBM set and button are visible on the live site.

Decide what to do about this.

If we decide to hide them, perhaps just setting the button_special flag to TRUE might be enough, because this allows CustomBM to be used on dev sites, but not on the live site.

**Comment by cgolubi1** [comment]
This must be because we implemented that protection at the game creation level, rather than the button special level like other buttons.  I'm pretty sure you're right that setting button_special will make this button not visible on prod (but still visible on dev and staging, which is fine/good).

**Comment by cgolubi1** [comment]
I don't think it's so harmful that we need to make an emergency prod database change --- if you don't mind, why don't you submit a PR turning the flag on, and we can get it submitted this week.
