### ISSUE TITLE
Display Wildcard value correctly in select dropdowns

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2813]
In #2722, it was noted that Fire dropdowns and Chance dropdowns display the raw HTML, not the correct symbols.

**Comment by blackshadowshade** [comment]
It appears that fixing this is not trivial.

https://stackoverflow.com/questions/3354979/styling-part-of-the-option-text

**Comment by jl8e** [comment]
We may need to use an actual unicode character, which is probably well supported by now (But which encoding?)

**Comment by blackshadowshade** [comment]
I've chosen to deal with this by simply putting the numeric equivalent in the dropdown, instead of the full card, since a turndown will not have a well-defined suit.

**Comment by TheOrgg** [comment]
Will the coin notation be used for set, non-drawn values?

**Comment by blackshadowshade** [comment]
No, I thought it would be good to use the symmetric images for the default.

**Comment by TheOrgg** [comment]
So if I use Focus the card die becomes an Ace of Squares?

That's fine with me.

I'm thinking about making a mini-sized deck for the Wildcard Die and putting it up on DriveThru Cards.  One of the features would be the fifth suit for set (and not drawn) cards.

**Comment by blackshadowshade** [comment]
If you use Focus, it is as if the person draws from the deck (and reshuffles a new deck if necessary) until an Ace is drawn, whichever suit it is.

**Comment by TheOrgg** [comment]
So in the case that I use Focus to an Ace and the next Ace is under a K, 8, 2, 4, 2, 9, 5, the game will state those were removed when the game begins?

**Comment by blackshadowshade** [comment]
The game will not state it, but those cards will be removed.

**Comment by blackshadowshade** [comment]
We *could* log the cards drawn, but I've not accommodated that yet, especially because with Warrior, if we have a few Warrior Wildcard, it could be that we discard almost two full decks.
