### ISSUE TITLE
Wildcard background image should look like a card

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2832]
In #2722, it was noted that Wildcard needs an appropriate background image, something that looks roughly like a card.

To implement this, we'll need three images of appropriate size, much like those found here: https://github.com/buttonmen-dev/buttonmen/tree/master/src/ui/images/die/circle

**Comment by TheOrgg** [comment]
You can copy and paste the circles.  Here's the Summetric ones.  The Realistic ones I'll have to work on a bit.
![CardSymmetric3](https://user-images.githubusercontent.com/44233993/151906745-2b94debd-36dd-4b14-8110-419d10ba15d8.png) 
![CardSymmetric1](https://user-images.githubusercontent.com/44233993/151906741-d8608b6f-956b-4fef-b667-73bfc002cdd5.png)
![CardSymmetric2](https://user-images.githubusercontent.com/44233993/151906744-52303a89-20e0-4f06-b67e-b4a2a0e3b0c6.png)

**Comment by TheOrgg** [comment]
Well, that was Waaay trickier than I thought it'd be, but here's an originally created card deck icon
![CardRealistic1](https://user-images.githubusercontent.com/44233993/151914240-a6f05add-bafa-4a7d-a8b8-1a676153afe3.png)
![CardRealistic2](https://user-images.githubusercontent.com/44233993/151914241-b985214a-0f51-4acb-9c56-75eeb5ce503b.png)
![CardRealistic3](https://user-images.githubusercontent.com/44233993/151914242-5e5ed235-52e9-4d60-8379-f9eb329f81e1.png)
.

**Comment by irilyth** [comment]
The spacing between the top and middle card, and the middle and bottom card, seems different along the bottom edge, but the same along the right hand edge -- is that on purpose? I don't have an opinion about whether it's better or worse than any of the other spacing options, but I figured I'd ask in case it wasn't intentional but you hadn't noticed, or something.

Thanks for working on this!

**Comment by blackshadowshade** [comment]
I wonder if we want the impression of a deck here at all, since we're talking about a single card. Just one of those tilted cards might be enough.

**Comment by TheOrgg** [comment]
I know they're not perfect, but these were a pain in the ass to create with the Gimp vector drawing tool with my limited amount of skill.  Just these took a couple of hours.  (the simplistic took five minutes, as I just stretched the d6 images for it)

If everyone wants a single card image, that'll be tough, as the realistic frame tries to have definition.  Hence why the cards under it, as I don't know how to indicate definition for a single card (not with my skills, at least).

If someone else has the ability to make a better realistic image, awesome!  I know mine's not great.

**Comment by blackshadowshade** [comment]
I was just thinking that it'd be enough to have the single card just slanted as you've done, which gives it the sense of being somewhat 3-d.

**Comment by blackshadowshade** [comment]
For the symmetric ones, is it possible to round the corners slightly?

**Comment by blackshadowshade** [comment]
Also, I'll start with these images provisionally, and post some screenshots so that testers can see if they like how they look. I know how much work it is to work on images, I appreciate the efforts, @TheOrgg.

**Comment by blackshadowshade** [comment]
<img width="787" alt="shot1" src="https://user-images.githubusercontent.com/2898401/151948352-c3e004ca-67f9-4b03-98bd-b7c67d681ccc.png">

<img width="828" alt="shot2" src="https://user-images.githubusercontent.com/2898401/151948367-1215cc68-c8dc-4fad-9632-7fb8a88051be.png">

Here are the symmetric backgrounds in a screenshot. Looks like I'm going to have to deal with getting the positioning right, somehow.

**Comment by blackshadowshade** [comment]
<img width="781" alt="shot3" src="https://user-images.githubusercontent.com/2898401/151948840-9a17a687-1952-4d5a-af1d-b633fa322452.png">

<img width="776" alt="shot4" src="https://user-images.githubusercontent.com/2898401/151948866-f43640e1-1ab5-40f8-973c-1b91e2fbc067.png">

And here are the realistic backgrounds.

**Comment by TheOrgg** [comment]
They're too tall, and the simple one is too wide.  I can work on this in a day or two.

**Comment by TheOrgg** [comment]
I think I can work on the positioning, too, by moving the image left and right some.

**Comment by blackshadowshade** [comment]
No hurry, the code appears to work fine, so we can update the images as we go, they don't need to be perfect for the first iteration.

I'll push the changes in a commit now, and that will also be available for testing.

**Comment by TheOrgg** [comment]
Ruminating on the issues, the first one is the centering issue.  What's the widest item on a Wildcard die?  I'll measure the sides as displayed with the current image and then nudge it to be as close to centered as possible (1 pixel off at most).  Then hopefully the rest are centered and it just works.

Don't have time to work on the simple card image at the moment, but my thoughts there are finding the widest, going two pixels each direction, and then going 1/3 more on the height.

**Comment by blackshadowshade** [comment]
I think the widest item is probably a 10 of something, maybe clubs.

**Comment by TheOrgg** [comment]
Single-card Realistic images, try #2.
![Realv2 3](https://user-images.githubusercontent.com/44233993/152490641-15443d99-6863-426e-9bae-facf23914f9d.png)
![Realv2 1](https://user-images.githubusercontent.com/44233993/152490643-472144cc-7f6c-45f4-833e-738d32ec2143.png)
![Realv2 2](https://user-images.githubusercontent.com/44233993/152490644-e307f9d6-f70c-45e1-b1fb-5b99a05e6244.png)

**Comment by TheOrgg** [comment]
Looks like a wallet, but maybe with the numbers on it...

**Comment by TheOrgg** [comment]
Curving the corners was much more difficult than I expected.

![Simple2 2](https://user-images.githubusercontent.com/44233993/152492467-10686442-5108-4ff0-8890-198cf0e916a6.png)
![Simple2 3](https://user-images.githubusercontent.com/44233993/152492468-97c90048-76fc-4a6a-b28f-da18177453e7.png)
![Simple2 1](https://user-images.githubusercontent.com/44233993/152492470-c8e7741a-2ec2-4fd9-9c68-8705ccd10367.png)

**Comment by blackshadowshade** [comment]
Very nice! I'll update the images on the pull request now.
