### ISSUE TITLE
reboot prod site for AWS maintenance

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2853]
The prod site needs to be rebooted.

There's no code involved --- i'm just making an issue so i have something to link to in the forum posts, so that in the unlikely event things go pear-shaped, people will have someplace to look for updates.

**Comment by irilyth** [comment]
I went to the forum to see what was up, and this is super trivial, but I think the forum link you want is actually https://www.buttonweavers.com/ui/forum.html#!threadId=1047 .

**Comment by cgolubi1** [comment]
Well, that wasn't smart at all --- i got a capacity error when i tried starting the instance again.  So we're going to be down for a few minutes while i try to figure this out.  Please stand by, everyone.

**Comment by cgolubi1** [comment]
Okay, i'm building a new instance of a slightly different size.  We'll see how that goes.

**Comment by cgolubi1** [comment]
The unencrypted site seems to be up, but the SSL site isn't, because of some vagrant/puppet errors involving mysql (not harmful ones, ones related to insufficiently good configs around the site having moved to RDS).  Working on it!

**Comment by cgolubi1** [comment]
That was a red herring; the actual issue was that letsencrypt uses an EC2 instance tag to figure out which FQDN it's supposed to use, and i don't have an automated process for setting those tags.  Now the SSL site is back up.

**Comment by cgolubi1** [comment]
Things i know i haven't fixed yet:
* I didn't mount the EC2 volume with the backups on it before declaring the all-clear, so it's going to try to run backups on the local share for now

I'm not planning to worry too much about this --- i need to migrate the site within the next month because of some changes AWS is making anyway, and i'll be able to run the backups to an EFS volume after those changes.

**Comment by cgolubi1** [comment]
This is related to https://github.com/buttonmen-dev/buttonmen/issues/2855 --- i'd rather keep it open for now, but we can close them both out once the migration to VPC is done.

**Comment by cgolubi1** [comment]
We can close this out now.
