### ISSUE TITLE
New re-found Flavor Texts! 4Horsemen and Chicago Crew!

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2860]
Dana found an old data file that's a bit of a pain to read, but looks to have at least the flavor texts of ChiCrew and the rest of the 4Horsemen flavor texts.  Possibly more, but I wanted to upload this ASAP!

Pestilence;p4 p6 10 20 S Four Horsemen Pestilence is a singer/songwriter, an amateur juggler, and an aspiring actress. She enjoys sushi, studying dynamical systems, cliff-diving, and beating people up.

Famine;zn6 8 10 (12,12) X Four Horsemen Famine is a drummer who often plays until she passes out.  Her turn-ons include back massages and lycanthropy.  Turn-offs include foul language and Kenny G.

War;z(4,4) z10 B20 (W,W)! Four Horsemen When War isn't busy sharpening his battle axe, he's often found playing with his other axe, a Fender Stratocaster, or getting rejected by his friends Famine and Pestilence. He likes hibachi grilling, singing in the rain, and beating people up.

Death;(2,2) p8 s10 16 X? Four Horsemen In his spare time Death plays bass in a band with his friends Famine, War, and Pestilence.  He enjoys firecrackers, vanilla ice cream, and beating people up.

**Comment by TheOrgg** [comment]
27;Audrey;t2 3/6 o8 12 Y;35;Chicago Crew;0;0;1;1;Audrey is an urban girl who enjoys shiney objects which make glares on the ceiling, posing for Action-shot photos and beating people up.;;;45;38;83
328;Monty Brown;t1 z6 o10 20 Y;35;Chicago Crew;0;0;1;1;Monty Brown also known as Zoomkitty, appreciates chewing on a good book, ordering in Italian and rushing out the door. Oh, by the way he likes to beat people up.;;;45;39;84
329;Lizzie;t6 s6 B10 o12 oX;35;Chicago Crew;0;0;1;1;Lizzie can break from any prison through raw determination as such she is good at beating people up.;;;30;42;72
330;Spooky;ot8 o6 o10 B15 oZ?;35;Chicago Crew;0;0;1;1;Spooky DeFerret is one rightous ornery dude. He loves going bald and being ornery and when ornery loves beating people up.;;;31;49;80
331;Flint;o(4,4) 12 o16 20 oX;35;Chicago Crew;0;0;1;1;Old man Flinter likes cramming his body into tight spaces, whining, and just being like an old man. When he's not trying to be cute he beats people up.;;;24;28;52
332;Octavia;ts4 s4 os10 s10 oX;35;Chicago Crew;0;0;1;1;Octi-Lu likes the view from her window, running for wet food, and being the boss. Don't cross her she may look scrappy but she'll beat people up.;;;13;41;54
333;Cheathem;Ho1 s6 o10 o14 sX;35;Chicago Crew;0;0;1;1;Cheatis McGinty enjoys his role at the law firm Dewey Cheathem & Howe. When not scamming through his dashing good looks, he likes to beat people up.;;;41;32;73

[SUPPORTED -.txt](https://github.com/buttonmen-dev/buttonmen/files/9295608/SUPPORTED.-.txt)

**Comment by blackshadowshade** [comment]
Very nice!

I'm happy to go through the text file you've posted and grab any others from there. One I noticed immediately is for RandomBM.

**Comment by TheOrgg** [comment]
And Fanatics!  AND THERE'S NEW SETS!!


420;fnord;zc10 ^16! tX? @oV;41;Fanatics;0;0;1;1;fnord is a baker / sales creature who enjoys comic books, tasting zillions of new beers and beating people up. Normally in that particular order. ;;;20;55;75

422;Skeeve;oV? oW? oX? oY? oZ?;41;Fanatics;0;0;1;1;Skeeve is a reject incarnation of an April holiday. Becuase of this, he spends his time untying bow-tie pasta, looking at Phil Folgio art, drinking Red Bull(tm), and doing slapdash impressions of Iron Chefs. He enjoys right angles, the color 5ca482, hunting for witches, being the Bennies, and beating people up.;;;36;75;111

432;Famous;t6 B6 f6 n6 10;41;Fanatics;0;0;1;1;Famous has no flavor text, he goes well with anything. Like Tofu. (mandatory "likes to beat things up");;;22;45;67

433;Binder;4/12 17 sp(4,20) 4/30;41;Fanatics;0;0;1;1;Binder likes to be beat up. Obviously.;;;62;43;105

434;Downen;f2 6 p13 z14 zX;41;Fanatics;0;0;1;1;Downen is a test lemur at Vanderbilt University. He enjoys procrastination, waffles, and beating people up. ;;;28;14;42

435;SC(The Deuce);z4 t6 p8 s10 12/16! +20;41;Fanatics;0;0;1;1;Social Class(The Deuce) is the sequel to the Button Man of a card game that is the representation of class struggles everywhere. The rules of the card game are located at http://www.bsfs.org/bsfssocl.htm and members of every socio-economic class encourage you to attend Balticon. And they beat people up.;;;19;30;49

436;TheMachine;pd1 B1/30! tD4 q(7,11) zrc20;41;Fanatics;0;0;1;1;TheMachine is the user Pestilence.;;;48;36;84

437;eon;t4 n6 d8 B16 BX;41;Fanatics;0;0;1;1;eon likes to make prank calls, contemplate about deep feelings, impersonate a police officer and beat people up. ;;;10;26;36

442;Jasyeman;B8 H8 p8 z8 zU?;41;Fanatics;0;0;1;1;Jasyeman is a student of the Zoological Sciences. He enjoys curried chicken, heavy doses of irony, and beating people up.;;;24;29;53

443;Grym;4 t6 d10 z12 (X,X);41;Fanatics;0;0;1;1;Grym is very very confused. He doesn't like beating people up, but he is really really good at it. ;;;13;13;26

445;spindisc;d2 p6/20! zp12 n(T,T) BX? +Y;41;Fanatics;0;0;1;1;SpinDisc is a provider of knowledge and a true collector. He likes binary digits, graphical outbursts end beating people up.;;;210;42;252

446;professorbooty;Ho6 ^z20 JV pfX;41;Fanatics;0;0;1;1;Professor Booty enjoys eating York Peppermint Patties and orange crayons. She loaths the word "slacks," but likes the smell of fresh wood chips. She puts them in her underwear when beating people up;;;53;47;100

447;jeffboyardy;o10 6/12 oX? Y? oBZ?;41;Fanatics;0;0;1;1;jeffboyardy is a strangely dressed recluse. When he is not interupting midterms or studying Ethics, he beats people up.;;;32;32;64

448;Notorious;2/12! 4/16! 8/20! 10/24! r4 r4 r6 r6;41;Fanatics;0;0;1;1;Notorious likes Looney Tunes, sunny Junes, common loons, silver spoons, half-past noons and harvest moons. When he isn't trying to rhyme, he is  beating people up.;;;20;25;45

449;Heather;Jd1 D2 ^c4 tz14 zr2 zr4 zr10 zr20;41;Fanatics;0;0;1;1;Heather likes Quantum Leap, Harry Potter, baking yummy goodies and beating people up. ;;;243;64;307

450;randomlife;@6 @10 @12 @20 @X;41;Fanatics;0;0;1;1;Randomlife has trouble making decisions so he relies on the chaotic nature of the universe to guide him. He enjoys rolling dice, shuffling his CDs, donating bone marrow, Irish dancing, and beating people up.;;;97;148;245

451;ElihuRoot;3 h10 h10 n20 n30;41;Fanatics;0;0;1;1;Secretary of War under McKinley (after the Spanish American War) and T. Roosevelt (whom he also served as Secretary of State), he later won the Nobel Peace Prize and was first president of the Carnegie Endowment for International Peace. In addition, he enjoyed beating people up. ;;;23;30;53

452;Alljazzedup80;z8 B8 p10 %12 10/20;41;Fanatics;0;0;1;1;Alljazzedup80 is a journalism major. A huge Shawn Mullins fan, she digs well-dressed guys, Duncan yo-yos and beating people up.;;;23;49;72

453;Trouble;d6 ^7 @12 B20 @oZ?;41;Fanatics;0;0;1;1;Trouble is a half-crazed superhero from another dimension. He enjoys fighting crime, eating sushi, charming the ladies, and using his  Louisville slugger to beat people up. ;;;60;43;103

454;Yagharek;p3 p5 7 11 zc13;41;Fanatics;0;0;1;1;Yagharek lives in Belgium where he likes to beat people up (provided they're smaller than him) ;;;30;24;54

455;malarson;Ho4 (5,5) z20 %20 U;41;Fanatics;0;0;1;1;malarson spends his days in his favorite easy chair, pondering whether or not everybody *has* heard about the bird, and rising periodically to beat people up.;;;29;22;51

456;Shadowkeeper;s4 s4 s4 s4 s4 sU;41;Fanatics;0;0;1;1;Shadowkeeper is the lord of the shadowrealm and makes a mean tamale pie. His finest acheivement was completeing the fourth building in "Crazy Climber" and he likes to beat people up.;;;22;33;55

458;wembley-fraggle;6 z(8,8) spg(12,12) (V,V)!;41;Fanatics;0;0;1;1;Wembley enjoys singing, dancing, eating radishes, annoying Gorgs, and Beating People Up.;;;47;57;104

459;Bodie;4 ^5 ^5 z(9,9);41;Fanatics;0;0;1;1;He is a force of nature, the rage, the silent scream that we all supress within ourselves.  ...and beat people up!!;;;29;32;61

460;birdman;z3 4/30 13 13 13;41;Fanatics;0;0;1;1;O brave new world, that has such buttons in't! ;;;11;19;30

462;Moodster;sX pX X? zX oX;41;Fanatics;0;0;1;1;Moodster greatly enjoys brooding about the past, crying over spilled milk and beating people up.;;;13;19;32

464;UncleMilo;6 p8 12 %16 B20;41;Fanatics;0;0;1;1;Uncle Milo has Peanut Butter Twix on hand and is NOT an emu.  Always happy to sing a song, throw a party, or beat people up... preferably with fruit roll-ups.;;;15;20;35

465;perlmunkee;t6 p12 12 z20 z20;41;Fanatics;0;0;1;1;When I'm not being abused online, I train an army of monkeys to beat people up... ;;;27;21;48

466;hairlesswonder;4 7 B20 B20 B20;41;Fanatics;0;0;1;1;The hairless wonder is a tall, lanky, wide-eyed, steaming, hairless, maniac monkey from Mars. He always enjoys a good game of chess and beating people up. ;;;13;15;28

467;Jennie;H6 @8 @10 z12 U;41;Fanatics;0;0;1;1;Jennie is a girl<br>Who enjoys bad haikus and<br>Beating people UP ;;;22;23;45

468;chase;4 6 %p10 12 X;41;Fanatics;0;0;1;1;chase hates his nice guy image. Hence, as a vintager by trade, he likes to poison his wine and customers with hemlock ... and beating people up! By the way, his favorite customers are soap opera fans!;;;29;16;45

469;Hrodgar;Z? T? X? X? X?;41;Fanatics;0;0;1;1;Hrodgar is an extremely moody person and has about fifty different moods every day, rangning from deleriuos to suicidal, from jubilantly happy to deadly depressed. If he ever collected his thoughts more than five minutes, he'd definetively beat people up!;;;8;16;24

470;Kaeriol;4 6 d6 s10 BX;41;Fanatics;0;0;1;1;Kæriøl is a furry little rat like thing, who loves to jump very fast around others, his organic chainsaw, to laugh mad and to  beat people up and cut them afterwards into sweet, small pieces !;;;15;27;42

471;moekon;s3 7 7 n(6,6) p17;41;Fanatics;0;0;1;1;moekon is never knows what he wants. So he tries lot's of things, never settling with one. But his all-time-favourite is beating people up.;;;36;20;56

472;CactusJack;z8/12 4/16 s6/10 zX sU;41;Fanatics;0;0;1;1;Cactus Jack is a confused but kind environmentalist. He enjoys starting controlled burns, hiding in tall trees, petting large animals  and beating people up.;;;19;16;35

478;luke ii;d6 @8 hz12 c20 C;41;Fanatics;0;0;1;1;luke_ii is a chaotic good, board game freak. He owns way too many Cheapass (and other) games. He also likes playing Nintendo and beating people up. ;;;15;22;37

479;yakboy;@o5 ms6 %pW hot20 X?;41;Fanatics;0;0;1;1;sidekick of Llama Man! Whilst fighting for truth and justice, Yak Boy really quite enjoys beating the snot out of the bad guys.  Problem is,he's a weakling. Help, Lllama Man! Help!!! ;;;21;15;36

483;Boot2daHead;Jd1 GzZ pV! n(Y,Y)! oFC;41;Fanatics;0;0;1;1;Boot2daHead is head dean at a trade school for aspiring Masters of the Flying Guillotine and One-Armed Boxers. He enjoys spending quality time with his cats, giving drive-by tauntings and booting people up. ;;;86

487;Heath;1/13! z(3,13) H13 md13 X!;41;Fanatics;0;0;1;1;When things are blackest, I just tell myself 'cheer up, things could be worse!' And sure enough, they get worse!;;;

489;Jordan;Ho10 1/20! 1/20! 20 ^o11;41;Fanatics;0;0;1;1;Jordan is half bunny, half ferret who is easily distracted by 'parklies (even when she's beating people up). ;;;31;10;41

490;Rumbles;oR oT of10 mo10;41;Fanatics;0;0;1;1;Rumbles likes to press the weather button at rest stops across the nation, eat the ears off of chocolate bunnies, and listen to the White Stripes while she beats people up. ;;;1;11;12

**Comment by blackshadowshade** [comment]
The Iron Chef flavour texts are there in that first document.

**Comment by blackshadowshade** [comment]
Also, new set: Dr. Oche.

**Comment by TheOrgg** [comment]
> Very nice!
> 
> I'm happy to go through the text file you've posted and grab any others from there. One I noticed immediately is for RandomBM.

I'm combing it at the moment, but if you want to look, too, you might catch something I overlooked (like the randomBM!  Didn't notice that!).

Sadly, one of the new sets, Dr. Oche, seems to lead to a dead-end, flavorwise.

**Comment by blackshadowshade** [comment]
Various Hodge Podge flavour texts are there.

**Comment by blackshadowshade** [comment]
Having seen what's there, I think I'll be putting in two pull requests: one adding flavour text for button we already have, and one adding sets that we don't currently have.

**Comment by blackshadowshade** [comment]
I've uploaded an Excel spreadsheet with the new bits highlighted. @TheOrgg, you can take a look and let me know if I've missed anything there.

[SUPPORTED_alt.xlsx](https://github.com/buttonmen-dev/buttonmen/files/9296014/SUPPORTED_alt.xlsx)

**Comment by blackshadowshade** [comment]
Also noting for myself that Kaeriol's flavour text is going to need special handling.

**Comment by TheOrgg** [comment]
There's also a totally new Hodgepodge button based on a famous hockey player! (Courtney Kennedy f8 f12 tz16 B20 B30; Courtney Kennedy hates penalties and warm weather. Courtney likes men smaller than her, silver jewelry, coed naked body checks, multiple shots on goal, and beating people up.)
 Also, since we have a few of the Avatars as Hodgepodge already, I'd suggest putting the rest of them with the Hodgepodge set as well.

Jazzed that we now have all four of the Horsemens' flavor texts instead of just two!

The newly found sets can probably be added with all the other un-added sets at once so the database only has to be updated once.  I'll pull them out and put up a wiki page for each; I think the only sets that are missing that people remember from the old site are Whacky Races, Simpsons, and Also-Rans.  

Checking the Fanatics earlier, I spotted that Skeeve has different flavor text; I suggest we put this new one above the old one, giving them their own paragraphs.  Gripen now has flavor text, too, and I don't think the site has it yet.

Looking at the spreadsheet, the Rickachu flavor text is different than the one on the site, too.

**It Came From The 80's**

Amadeus 5 d12 ^18 (8,6) X  Er war Superstar, er war populaer, er war so exaltiert, because he beat people up.

Der Komissar  4 f10 s10 (8,3) X?  Don't turn around...Der Komissar's in town...and if you DO turn around, Der Kommisar will beat you up.

Eileen f4 6/9 z12 (8,3) X  Eileen swears that if you don't get up off of your knees, beatings will commence in about 5 freakin' seconds.

Gloria 4 (8,2) G10 s12 X   If everybody wants you, why isn't anybody calling? Oh! Right! They're beating you up instead. Grand!

Geddy Lee - MISSING.  Saaad!

Jessie's Girl  t3 6/9 (8,1) z16 X   You know you feel so dirty when they start talking cute, you want to tell her that you love her but you'd get beaten up.

Jack and Diane  6/9 (8,2) Ho9 %20 X  A little ditty 'bout Jack and Diane...two American kids gettin' beat up in the Heartland...

Jenny B6 (7,5) 3 o9 X +30  Jenny does not appreciate the way you got her number. If you continue to call her at that number, Jenny won't bother with a restraining order. Jenny will beat you up.

Mr. Roboto (8,3) 10 %11 (10,1) X  "Domo arigato this, pal," says Mister Roboto as he beats you mercilessly.

(NEW!!)
Sherrie  4 (8,4) G10 %(9,9) X   Shoulda been gone, knowin' how you made Sherrie feel...and you shoulda been gone...after she beat you within an inch of you life.

Sister Christian Ho4 f6 (8,4) 20 X  MOTORIN'! What's her price for flight? And finding Mr. Right? She'll beat you up tonight...

Sweet Child 5 (8,8) n12 S! X Now and then when I see her face, she takes me away to that special place, and if I stare to long, I'd probably get beaten up.

Thriller t2 G12 (2,6) (8,4) X The foulest stench is in the air - the funk of forty thousand years. And grizzy ghouls from every tomb are closing in to beat you up.


**Amber**

Benedict  f4 4 12 12 r20 sr20 rd4 r4  Benedict is a connoisseur of warfare, he's spent centuries getting good at beating people up.

Brand  4 p8 12 o20 sr8 sr10 r8 hr10   Brand would be cute if he wasn't out of his mind. He beats people up not because he likes to do so but because it's part of his master plan to reshape the universes in his own image.

Caine  H8 s8 z12 R!   Caine has the heart of a pirate and likes sailing, drinking, and beating people up.

Corwin  H8 z10 S! sW

Dworkin  B2/6 sB12 pB6/20! oB20   Dworkin is often found beating people up and having out of mind experiences.

Eric  J8 H10 10 sW W?   Eric lives to beat Corwin up. But when Corwin isn't around, he likes to stay in shape by beating other people up.

Fiona   4 6 sf6 10 sr8 or8 r8 r12    Fiona would never beat anyone up. The last three people who said she did suffered mysterious ailments and never recovered.

Oberon  D6 H12 20 R!   He's the son of Dworkin and the father of everyone else and occasionally needs to beat up his scions to show them why he's King.

Gerard   HB12 B20 sB20 BZ    Big, dumb and slow are words to describe Gerard. But only when he's out of earshot, lest he beat the tar out of you.

Dierdre  8 D8 8 s10 r6 r6 rD8 r8    Dierdre is a fresh-faced innocent who doesn't really like beating people up, but it sort of comes with being in the family.

Bley  ;z10 10 10/20 p6/10 6/10    Bleys likes the finer things in life: wine, women, song, and beating people up.

Florimel  8 s8 8/12 h10/12 q10/20   Because she's so pretty in a Hollywood kind of way, people are often surprised when Florimel beats them up.

Julian   p8 o8 h10 s12 X?   The Warden of the Forest of Arden, Julian likes to beat up those he feels have slighted him. That list is incredibly inclusive. The Warden of the Forest of Arden, Julian likes to beat up those he feels have slighted him. That list is incredibly inclusive.

Llewella  8 f8 n10 10 rn4 tr4 r8 r8   She dwells in sadness beneath the sea and only beats up those who trouble her.

Random   H2/4 t4/6 4/10! 12/20   Random likes all night card games, marathon drum solos, and beating people up.


**Dr. Oche**

Dr. Oche  d1 8 d10 9/16 X!   The Doctor obtained his Medical degree in Grenada in 1983. His degree in veterinary medicine in Panama in 88. A man of mystery, you may find him making his escape from any country on the brink. Is he employed by the CIA? Who knows? All we know is where Oche is, Chaos follows, and he likes to beat people up. Please see www.droche.freeservers.com

Charlie Chaplin  t4 ^7 9 11 r1 r10 r12 r30   Dr. Oche's loyal sidekick. He somehow bends the laws of time and space to be there at Oche's side when it all falls apart. Charlie likes young women, molitov cocktails, and beating people up.

Sergent Steroid  p6 p10 B20 B20 BU?  An ex-marine and Dr. Oche's nemesis. This oversized monstrosity is thought to be the result of an Dr. Oche experiment gone horribly wrong. He has more hatred in his pinky than your entire body, partially because his pinky is larger than your entire body. He enjoys long walks on beaches, sunrises and beating people up.

Roid Rabbits h2 hp4 p6 B10 V    An army of horribly mutated bunnies. This horde is the work of Sgt Steroid as part of his plot to distroy Dr. Oche and take over the world. These rabbits like lettuce, carrots, and steroid laden hunks of beef. When not on duty, they like to beat people up.

**Radioactive**
A-BOMB  %50 %50

(NEW!)
Bio Rad %H3 %c14 %o15 %p(3,3) %s(3,5)

(NEW!)
Chain Reaction  %Ho(1,2) %Ho(1,4) %Ho(1,6) %Ho(1,8)

(NEW!)
Halflife  %4 %4 12 %z30

Hiroshima  4/13 6 %12 %16 R

(NEW!)
Ignalina;30 %30 X %X;38

(NEW!)
Kursk  2 %(3,4) %(5,6) 7 %X

Meltdown  %Ho4 %Ho6 %ho12 %ho16 %ho20

Nagasaki  4 %6 12 W %(W,W)

Testing (Still MISSING)

Tjernobyl  4 6 4/12 %20 %X


**Moody Mutants**

Armstrong  8 10 10 hp(T,T) %(T,T)

Wonko  6 %6 (4,4) s(4,16) hsp(4,20)

Crutch  %z12 %20 %40

Scythe  Jp(4,4) (6,6) 12 16 o20

Llamagirl  16 p20 20 h20 hU

Nemnottub  6 10 %12 pW W

Slurpee  6 12 Jh16 20

Beotch  %6 %10 %10 %12 %X


**Avatars**
(new Hodgepodge?)

Unruled  8 12 p16 20 X

MacGuffin  (2,2) (4,4) (8,8) s16 zR   The MacGuffin is a Hitchcockian plot device which likes suspense movies, hunting lions in the Scottish highlands and beating up  people who have been falsely accused of crimes. (kestrel's Avatar)

Kuroneko-Sama  13 s13 (4,9) o13 z13  Kuroneko-Sama is a cute little black cat that enjoys saying "nyo," spreading bad luck and beating people up (Kurosuke's Avatar)

Animal  8 8 s8 s8 r8 Hr8 zr8 r(8,8)Animal is a ferocious predator. He enjoys terrorizing rodents, chasing away scavengers, drinking apple-cinnamon tea, and beating people up. (Jasyeman's Avatar)

SnafuGirl  (2,4) %8 12 B16 S?  SnafuGirl is that weird looking girl working at the front desk of your office. The one with the big glasses, her hair in pigtails and that annoying laughter that makes her sound like a pig. You wouldn't think that's only her 'normal' alter ego, that she's really NoopMan's sidekick who always hit on her coworkers at company parties, take them home and Beat Them Up! (NoopMan's Avatar)

Nemesis  p4 p6 12 20 U    Nemesis is the goddess of vengeance. She enjoys dispensing retributive justice, doling out just punishments, and beating people up. (juelki's Avatar)

Mr. Sparkle  12 12 h12 H12 oX?  I am a magnet for foodstuffs, and I will banish dirt to the land of wind and ghosts! I'm disrespectful to dirt! Can you see I am serious! Get out of my way, all of you! This is no place for loafers. Join me or die. Can you do any less? For Lucky best wash, use Mr. Sparkle... and beat people up! (SocialClass's Avatar)

Yo Mama  6 Ho6 s10 %20 oX  Yo Mama is so fat. Yo Mama smokes crack. She's got a burnin' yearnin' and there's no turnin' back. Yo Mama's got a peg leg with a kick stand, a glass eye with a fish in it, and an afro with a chin strap. Yo Mama drinks whiskey out of a boot when beating people up. (professorbooty's Avatar)

Wilton Mithem  Ho4 8 10 15 X   Wilton likes writing letters to large corporations about new product ideas. He might be found doing a jig in a turtle costume and likes to beat people up. (jeffboyardy's Avatar)

MYGEL  4 B8 10 sS S   MYGEL is the funktion of political life, the essence that make all Tricky Dicks smile as they beat people up!

Mrs. Bates  2 p4 12 B16 Y    Mrs. Bates likes spooky houses on old coast highways. She dislikes shower curtains, vacant motel rooms, and her son Norman fraternizing with cheap women! She also likes cutting people up. (Notorious's Avatar)

Tyler Durden  o(2,2) o6 %20 B20 oX?   "This is your life, and it's ending one minute at a time. You are not the clothes you wear! You have to realize that someday you will die - until you know this, you are useless. I say: Let's evolve, and let the chips fall where they may." Tyler likes to blow stuff up and beat people up and cause Mayhem. Tyler says: Use soap. (Trouble's Avatar)

The Envoy  d4/20 6 8 d10/20 16   The Envoy like Cuban cigars, and beating people up. (Yagarek's Avatar)

Quint  6 10 hz10 20 n20   Quint often appears to lonely, troubled souls, but is always invisible to everyone else. He enjoys suggesting simple, surprising solutions to common social problems and beating people up (ElihuRoot's Avatar)

Kurt Angle  3 Ho9 20 %o20 X?    Kurt's three I's - intensity, integrity, and intelligence - have lead him to an Olympic gold medal and a lucrative career beating people up. (malarson's Avatar)

Lord Chaom sf6 sf6 10 10 10 +4    Lord Chaom is a true hero. Most of his time he is slaying dragons or rescuing young ladies. In his spare time ... beating people up. (calmon's Avatar)



...and I think that's it for the new sets.  I gotta hit the bed.  Got an early rise tomorrow.

**Comment by blackshadowshade** [comment]
Does anyone have any insights into the Avatars? I see that these are apparently avatars for players, but what does this actually mean? Were they in a roleplaying campaign?

**Comment by blackshadowshade** [comment]
Also, it'll be interesting to see if the art for any of these new buttons turns up somehow. I vaguely remember the art for the Amber set, I imagine that these might have been taken from some Amber source material somewhere?

**Comment by jl8e** [comment]
> Also, it'll be interesting to see if the art for any of these new buttons turns up somehow. I vaguely remember the art for the Amber set, I imagine that these might have been taken from some Amber source material somewhere?

Were they black-and-white? The Visual Guide to Castle Amber is a possible source.

As is the Amber RPG.

I can easily put my hands on the former, and maybe the latter.

**Comment by blackshadowshade** [comment]
I remember the Amber art being beautifully coloured, Deirdre in green, perhaps?

**Comment by blackshadowshade** [comment]
That doesn't look familiar at all. I remember well-defined pictures with a clean background and clean edges around the head-shoulder-upper torso.

**Comment by TheOrgg** [comment]
I emailed Heather to see if she remembered the sources of the images.

**Comment by TheOrgg** [comment]
I asked Elihu Root about whether he was okay with putting Avatars with Hodgepodge, and he said he didn't care one way or another.

**Comment by lauracs** [comment]
There was a private set of tarot decks done by a comic book colorist in NYC that might have been the source. I believe the art came from the B&W images in... probably the visual guide? But fully colorized.  They had the " well-defined pictures with a clean background and clean edges around the head-shoulder-upper torso" look described.

**Comment by blackshadowshade** [comment]
Could anyone post a pic from the visual guide? That might prompt my memory about whether it roughly matches my recollection, but just without colour.

**Comment by blackshadowshade** [comment]
Don't worry, I've found one of Fiona: http://www.lib.ru/ZELQZNY/visual_amber/fiona.jpg

That doesn't look familiar, even in black and white.

**Comment by lauracs** [comment]
How about something like this?  https://arkmsworld.neocities.org/trumps/bleys_arref.jpg 

If you look through this page https://arkmsworld.neocities.org/ambertrumps.html for the black and white Kucharski art (used as the base for above), that was from something official, maybe the RPG?

**Comment by blackshadowshade** [comment]
They're nice, but certainly not what I remember. Then again, does anyone else remember the art? Maybe I'm just misremembering.

**Comment by jl8e** [comment]
Yeah, that black and white art is from the RPG. (I haven't checked, but I recognize some of them, and it's not from the visual guide.)

I suspect, given only vague memories, we're not going to find the art that was used.

**Comment by TheOrgg** [comment]
If someone finds a good set of artwork for all of these (I'd assume there's a fan artist that might be willing to let us use their art?), I can whip button images together pretty easily.  I'll let someone else do the searching, as I haven't read the books.

**Comment by TheOrgg** [comment]
Looks like Chain Reaction is yet another Calmon/Anti-Llama.  

Why was that particular recipe so popular?

**Comment by TheOrgg** [comment]
Can we somehow quickly check to see if there's any recipe deviations?  I spotted that Boot's first die doesn't have Jolt anymore.  I heard Dana removed a bunch of Jolt dice from Fanatics at one point, and I'm guessing this is one of those cases.

**Comment by blackshadowshade** [comment]
I can do that with a simple script. I'll check when I have time.

**Comment by craw-daddy** [comment]
Wow, I created the Four Horsemen!  Surprised to see them back.  Will have to see if I can log in to the website (my username was Stick there).

**Comment by TheOrgg** [comment]
Awesome!  I'd love to interview you about both the set (and its creation) as well as your Fanatic!

**Comment by TheOrgg** [comment]
@blackshadowshade, did you ever do the scrypt to check and see what recipes were different from what we have on the site to the refound list?

**Comment by blackshadowshade** [comment]
No, I did not. I was going to do that as part of the pull request review process.

**Comment by blackshadowshade** [comment]
Flavour texts have been accepted. I haven't done a comparison of recipes because this is not at all trivial (comparing old site format to new site format), but I'm not particular bothered if there is a mismatch, I think what we have now is okay.

If anyone happens to spot a difference, I think it would be fine to raise an issue with the mismatch, and we can then consider what we do with it.

**Comment by TheOrgg** [comment]
Do we want to add the newly discovered sets at some point, or wait until they have button images made?

**Comment by blackshadowshade** [comment]
I'm not aware of anything still open from this issue. If there's new stuff, it's probably best to open a new issue.
