### ISSUE TITLE
"Magician" into Crypto?

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2907]
So I was playing the Magician button and noticed that the recipe is identical to Crypto, the Vegas character with an Iconic Special Ability.

Should we change Magician into Crypto the Magician and wait for its Iconic to be activated by the Iconics of the Tench Moon buttons?

**Comment by blackshadowshade** [comment]
I thought the entire point was that we have two versions of certain buttons, one with the iconic ability and one without?

see #2559

**Comment by TheOrgg** [comment]
My memory is awful.  My bad.  :P
