### ISSUE TITLE
Change links to wiki to redirect to new site

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2914]
A number of our members have migrated the Fandom Button Men wiki (https://buttonmen.fandom.com/wiki/Main_Page) and Buttonweavers wiki (https://buttonweavers.fandom.com/wiki/Main_Page) to a new wiki ~~on Miraheze (https://buttonmen.miraheze.org/wiki/Main_Page)~~ at https://buttonmen.wiki/wiki/Main_Page.

We should update both the direct wiki links and the help to reflect this migration.

**Comment by blackshadowshade** [comment]
Just thinking aloud about this, ideally we'd avoid breaking a whole pile of forum links when we do this change, I'll need to take a look at a couple of existing links and make sure those are migrated correctly.

**Comment by blackshadowshade** [comment]
I tried going to the new page today via the URL above and found that it was invalid.

Can someone tell me what the correct new URL is?

**Comment by craw-daddy** [comment]
It’s found a stable home at https://buttonmen.wiki/wiki/Main_Page
