### ISSUE TITLE
Port the tools in /tools/api-client/python to Python 3

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2932]
Now that bmapi supports Python 3, port the tools in /tools/api-client/python to Python 3.

**Comment by blackshadowshade** [comment]
#2933 dealt with this at least partly. Is there anything left to do here?

**Comment by irilyth** [comment]
Ah, indeed not, I just forgot how to indicate that PR resolves an issue. This one's all set from my point of view!

**Comment by blackshadowshade** [comment]
The trigger word for pull requests here is Fixes.  :)
