### ISSUE TITLE
Idea:  Combine identical buttons with a choice of art?

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2982]
A long-term idea here, but would it be possible to store buttons as recipes and not by name?

What I mean is this:  Something like Sydney and Angora are identical in recipe, but their play stats are different.

Would it be possible to have the stats combined and the button identified by its dice/specials?

If yes, could a dropdown menu allow you to change the artwork on the fly for the button?  This could also work for Kublai and all the Soldiers with alternative phone game artwork, too.

**Comment by dwvanstone** [comment]
I think it's perfectly fine for different buttons to have identical recipes. I'm sure that some people who play on the site want to play a character from a set rather than play a specific recipe.

**Comment by irilyth** [comment]
What problem are we trying to solve?

**Comment by TheOrgg** [comment]
The stats would be more accurate?
