### ISSUE TITLE
Fix a grammatical error in some flavor texts

### ISSUE THREAD

**Issue by TheOrgg** [buttonmen-dev/buttonmen#2984]
Several flavor texts are missing the comma after their second-to-last list item.  Nonce found this and used it as a trivia question.

To quote Nonce:

AnnoDomini, Gluttony, Pride, Pisces, Taurus, Farrell, Lorrie, CynCyn, Maskin, Flaire, Floriano, Queen Serenity, Von Pinn, Connie, Lapis Lazuli, Kaeriol and zaph.

I only counted it for those with a list of three or more items.  Most buttons use the Oxford Comma, but usage is inconsistent within most sets.

**Comment by blackshadowshade** [comment]
I would disagree that this is a grammatical error.

I seem to remember that I've discussed this before and decided not to change it.

Unless people feel strongly about this issue, I'm inclined to mark it as wontfix and close it.
