### ISSUE TITLE
Make new game obvious to person being challenged

### ISSUE THREAD

**Issue by yawetag** [buttonmen-dev/buttonmen#354]
The overview should make it obvious which games were recently challenged by another player. Right now, it's only obvious if you keep track of game numbers. The most logical would be to have the game information in bold (or even a different background color) on the overview page. This would tie in with #205, especially if a database column is made to indicate a game in "acceptance" mode.

**Comment by blackshadowshade** [comment]
This was apparently solved by #1821, so I'm closing this one.
