### ISSUE TITLE
choose codes for all die types

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#356]
Just to be clear, by codes and coding I am referring to the characters used to represent the various die types.  I don't know if that's the best way to word it, but it's what I've been using.  Anyhow . . . 

I want to get this out of the way before I continue putting button recipes into the database.  I was told to use my judgment - but since I want to change some of the coding (for example, Rage should be 'R' instead of 'G') I think it's important to get feedback.  Things I've considered while trying to come up with die codes are how the die type was represented on the physical buttons, what codes were used on the old site, and what does the die type do.  

What follows is my most recent compilation of information regarding die types, containing all 62 die types I've found so far.   FYI - I haven't coded the dice for Buzzing Weasel.  I figure that can be handled with special button rules.  

---

DIE TYPES FROM OLD SITE THAT HAVE NO PHYSICAL BUTTONS
```
Chaotic: @
Doppleganger: D
Jolt: J
Maximum: M, same as Loaded, PROPOSED CHANGE: L
Mighty: H
Morphing: m
Ornery: o
Plasma: P{}, PROPOSED CHANGE: {} (P in code seems unnecessary)
Radioactive: %
Slow: w (implied die type)
Value: v
Weak: h
Unique: u (implied die type)
Wildcard: C (note: can't find Las Vegas button set images)
```

DIE TYPES FROM OLD SITE WHOSE CODE IS AT LEAST CLOSE MATCH TO PHYSICAL BUTTONS
```
Berserk: B
Chance: c (physical buttons use copyright symbol)
Fire: F
Konstant: k (should perhaps be K)
Mood Swing: ?
Null: n, PROPOSED CHANGE: N (to more closely match physical dice)
Poison: p
Queer: q, PROPOSED CHANGE: Q (to more closely match physical dice)
Speed: z (looks close enough to a lightning bolt)
Time and Space: ^, PROPOSED CHANGE: > (both match physical button)
Turbo Swing: !
Auxiliary: +
Twin: (,)
```

DIE TYPES FROM OLD SITE THAT DO *NOT* MATCH PHYSICAL BUTTONS
```
Focus: f (no changes proposed)
Rage: G, PROPOSED CHANGE: R
Shadow: s, PROPOSED CHANGE: _ (note: s is used on some later sets)
Stealth: d, PROPOSED CHANGE: ^ (both d and ^ for Delta used on button images)
Stinger: g (no changes proposed; no ASCII symbol to match physical buttons)
Trip: t, PROPOSED CHANGE: -
Warrior: ` (no proposed changes; no symbol to match physical buttons)
reserve: r (no proposed changes; no symbol to match physical buttons)
```

DIE TYPES LACKING ON OLD SITE THAT HAVE PHYSICAL BUTTONS TO MATCH
```
Game: G (Rage will no longer need it; can't comfirm match to button image)
Rebound: = (close match to button image)
Sleep: Z (as in ZZZZZZ)
Winslow: NOTE: *not* used in any button recipe, adds special rules to game play
```

DIE TYPES LACKING ON OLD SITE THAT HAVE NO PHYSICAL BUTTONS TO MATCH
```
(Japanese) Beetle: I (implied die type; same as Insult Dice)
Pai Gow: : (colon symbol to represent dominoes)
Socrates: S (implied die type)
(Flying) Squirrel: q (implied die type; q for squirrel?)
```

DIE TYPES FOR SETS THAT DID NOT EXIST ON OLD SITE W/ PHYSICAL BUTTONS PROPOSED CODE MATCHES PHYSICAL BUTTONS
```
Evil: E (Gaming Guardians)
Insult: I (Gaming Guardians)
Loaded: L (Gaming Guadians; same as Maximum)
Teleport: T (Gaming Guardians)
```

DIE TYPES FOR SETS THAT DID NOT EXIST ON OLD SITE W/ PHYSICAL BUTTONS PROPOSED CODE DOES *NOT* MATCH PHYSICAL BUTTONS
```
Armor: A (Nodwick; no symbol to match physical buttons)
Boom: b (Unexploded Cow; die frame is a bomb)
Deception: $ (Gaming Guardians; labeled with a D)
Dodge: d (unofficial Japanese Beetle; D represents die type and size)
Mad Swing: & (Unexploded Cow; represented by upside-down question mark)
Specialty: {I,L,p,s,z,-} (Gaming Guardians; labeled with an asterisk; see note) 
Sideboard: s (High School Drama; extra die on left side of button)
Take Five: CODE NEEDED (Fightball; implied die type; choose 5 from listed dice)
```

DIE TYPES FOR SETS THAT DID NOT EXIST ON OLD SITE W/OUT PHYSICAL BUTTONS
```
Assassin: a (Order of the Dolls)
Attacker: < (Blademasters 2; pointy weapon?)
Cross: x (Blademasters 2; x as in multiply)
Defender: | (Blademasters 2; flat shield?)
Parry: I (Blademasters; same as Insult)
Thief: t (Everything to Gain)
```

*WITH PHYSICAL BUTTONS: OR VIRTUAL BUTTONS IMAGES NOT EXLUSIVE TO OLD SITE

*WITHOUT PHYSICAL BUTTONS: THEY MIGHT EXIST, BUT I CAN'T FIND THEM

*LACKING ON OLD SITE: SOME BUTTON SETS ON THE OLD SITE WERE INCOMPLETE OR 
IMPROPERLY IMPLEMENTED BECAUSE OF MISSING DIE TYPES

*IMPLIED DIE TYPES: THOSE CREATED TO IMPLEMENT SPECIAL BUTTON RULES
(Japanese) Beetle: Japanese Beetle from official Japanese Beetle
(Flyiing) Squirrel: Flying Squirrel from official Japanese Beetle
Slow: Giant from BROM
Socrates: Socrates from Fantasy
Unique: Guillermo from Renaissance
Take Five: Fightball set by Cheapass Games

*SAME AS, or SIMILAR TO:  THERE ARE A FEW CASES WHERE THE SAME (OR NEARLY 
IDENTICAL) DIE TYPES WERE CREATED BY DIFFERENT GROUPS INDEPENDENT OF EACH OTHER
Beetle (Japanese Beetle) = Parry (Blademasters) = Insult (Gaming Guardians)
Maximum (Dana Huyler) = Loaded (Gaming Guardians)

*SPECIALTY DICE: IT MAY BE POSSIBLE TO IMPLEMENT WITHOUT GIVING A DIE CODE GAMING GUARDIANS INTRODUCE 6 DIE TYPES IN AN 8 BUTTON SET - GREEDY BASTARDS!

From the Randomdice Button Men Roster:
Specialty Dice are labeled with an "*". Can be one type of dice from the 
following: Insult, Loaded, Poison, Shadow, Speed or Trip.
QUESTION: Is this done randomly, or by choice?  Is this done only when option, 
swing die are selected, or can it vary per turn?  Is this like Plasma dice or 
like limited Chance dice?

SUMMARY OF PROPOSED CHANGES:
```
Maximum:        M  ->  L ; M free for potential future use
Plasma:       P{}  ->  {}
Null:           n  ->  N
Queer:          q  ->  Q ; q now used for Flying Squirrel
Time and Space: ^  ->  >
Rage:           G  ->  R ; G now used for Game Dice
Shadow:         s  ->  _ ; s now used for Sideboard Dice
Stealth:        d  ->  ^ ; d now used for Dodge
Trip:           t  ->  - ; t now used for Thief
```
NOTE: Reasons for choosing L to code both Loaded and Maximum: 
1) Loaded dice exist on buttons not exclusive to the old site.
2) L matches physical buttons
3) Five die types begin with M as opposed to one L, so it's more likely
   M will be needed for a future set's die type
Reasons to keep M for Maximum and also apply it to Loaded Dice:
1) It's easier
2) Out of respect to Dana Huyler and the old site, as it was created 
   for that site's one year anniverary
NOTE: I feel very strongly about changing the codes for Rage, Stealth, 
      Time & Space, and Trip, and strongly about Shadow. They seem like 
      poor when compared to the physical button representations. 

SHOULD THESE BE CHANGED?
```
Konstant:     k  ->  K
Doppleganger: D  ->  d
Dodge:        d  ->  D
Warrior:      ` -> CODE NEEDED
```
NOTES: If uppercase K is closer match to physical buttons, change Konstant
Dodge uses D on physical buttons, so maybe it and Doppleganger should swap
I don't think a single quote can be used in die codes, so ` might be useful if Prime Swing dice are ever to be implemented

BUTTONS WHOSE RECIPE HAS A VISUAL RATHER THAN STRATETGIC MEANING:
```
Hodge Podge:
Butthead:       B(U) t(T) H(3) @d(5)
 translates to  Thief(T), Chaotic Dodge(5)
 or becomes     B(U) T(T) H(3) @D(5)
                Teleport(T), Chaotic Doppleganger(5)
 or becomes     B(U) -(T) H(3) @^(5)
Crosswords:     c(R) o(S) s(W) o(R) d(S)
 translates to  Sideboard(W), Dodge(S)
      or        c(R) o(S) S(W) o(R) D(S)
                Socrates(W), Doppleganger(S)
 or becomes     c(R) o(S) _(W) o(R) ^(S)
FANATICS: 
anthony:        v?(X,X) vst(16) stomp(10) {zf,Bp}(V) fF(15)
    becomes     v?(X,X) v_-(16) _-omp(10) {zf,Bp}(V) fF(15)
  or translates to:
    stomp(10):  Sideboard Ornery Morphing Poison Thief(10)
    STomp(10):  Ornery Morphing Poison Socrates Teleport(10)
```

CODE NEEDED FOR:
Take Five
The Fightball buttons have 7 or 8 dice listed on their recipes, but only five 
dice are chosen for play.  This is at the beginning of the game and after a 
match is lost, the same as with swing or option dice. 

AVAILABLE CODES: 
e i j K (or k) l M n O P U V W X [ ] . ~ *
NOTE: DEPENDING ON SKILL INTERPRETATION, SHOULD HOLD * FOR SPECIALTY DICE

**Comment by blackshadowshade** [comment]
I believe that this is complete for the moment. Closing the issue.
