### ISSUE TITLE
limited chaotic dice

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#365]
I know there's enough to do without inventing new dice skills, but I just want to throw this out there since (I'm hoping) the new site will have a bunch of skills not available on the old site.  This can make chaotic messier than it already is.  So I'm thinking of something that can probably be compared to randomly implemented Plasma dice. For example, 

```
<tszg>p(X) 
```

will randomly add any combination of trip, shadow, speed, and stinger to the poison X swing die.

**Comment by blackshadowshade** [comment]
I'm going to close this because I think it's clear that when we implement chaotic dice, we're going to have to put restrictions on the skills that might appear.
