### ISSUE TITLE
Chat allows 500 characters

### ISSUE THREAD

**Issue by yawetag** [buttonmen-dev/buttonmen#367]
I'm okay with it allowing only 500 characters. However, there should be an indication on how many characters are remaining as someone is typing.

**Comment by jimmosk** [comment]
I can understand there being a limit, but I think 500 characters is too low. Looking back at some of the Story Tournaments on the previous site, there were many times when I or my opponent made additions to the story that were longer than 500 characters. Never more than 1000 in my experience, but to be safe I'd raise the character limit in the chat box to 2000 or even 4000.
