### ISSUE TITLE
Specialty Dice

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#510]
Specialty: {I,M,p,s,z,t}
Specialty Dice are labeled with an "*".  
I'm assuming it works just like Plasma dice with the specified skills, so I decided not to give it its own code. 

---

Specialty Dice appear in the Gaming Guardians set by XIG games.  They be one type of dice from the following: Insult, Loaded, Poison, Shadow, Speed or Trip.
Question: is this done randomly, or by choice?  Is this done only when option, swing die are selected?  Is this like Plasma dice or like limited Chance dice?

**Comment by TheOrgg** [comment]
The Specialty Dice are just Plasma Dice.

**Comment by blackshadowshade** [comment]
Linking to #260.
