### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#551]
We need a privacy policy for the site that specifies what we do with people's details, especially their email addresses.

**Comment by blackshadowshade** [comment]
This is my BotM for Feb 2016. Basically, I'm looking for a start on actually formulating a privacy policy. If this takes the form of a discussion, then fine, but we may actually need a first draft to stimulate discussion.

**Comment by blackshadowshade** [comment]
I'm looking to do a privacy policy somewhat similar to https://basecamp.com/about/policies/privacy, in as close to plain English as I can manage.

**Comment by blackshadowshade** [comment]
Looks like I'm wrangling this on my own then.

I'll be basing our privacy policy on https://m.signalvnoise.com/privacy-policy/.

**Comment by dwvanstone** [comment]
I'm happy to review this but I don't know what we actually keep on the site about people. What can I do to help?

**Comment by blackshadowshade** [comment]
I'm happy to write a first draft, at that stage I'd welcome input.  :)

**Comment by blackshadowshade** [comment]
Right. What do people think about this? And yes, I'm willing to rewrite parts to avoid directly plagiarising the privacy policy above.

-----
Privacy Policy

Personal data

To create an account on buttonweavers.com, you need to provide us with a valid
e-mail address. This is used to allow the site to provide you with a password
reset link if you forget your password. It may also be used to allow a site
administrator to contact you with important news about the website, like a
major site disruption.

In your personal preferences, you may choose to make more information
available about yourself on your personal profile. Such information should be
considered to be publicly available, even if have attempted to hide this
information from other players.

Cookies

You may opt-in to stay logged into the site, which will set a number of
cookies on your browser. These cookies last for one year, unless you log out
of your account, in which case the login cookies will be removed.

Comments

It is possible to leave comments in-game and on the forums. These should be
considered to be publicly accessible, even if the in-game chat has been set
to private.

How long we retain your data

All data on the site is retained indefinitely. All users can see, edit, or
delete their personal information at any time, except that they cannot change
their username. Website administrators can also see and edit that information.

Your rights over your data

If you have an account on this site, you can request to receive an exported
file of the personal data we hold about you, including any data you have
provided to us. You can also request that we erase any personal data we hold
about you. This does not include any data we are obliged to keep for
administrative, legal, or security purposes.

We will not use your personal data for any purpose other than that necessary to
administer the buttonweavers.com website. We will not share unanonymised or
personal data with third parties.

**Comment by dwvanstone** [comment]
This looks good! Some quick thoughts:

**Personal data**: "even if have attempted to hide this information from other players" <--- I think this is missing the word "you" after "if"?

**How long we retain your data**:  You might switch the order of these to clarify:

All users can see, edit, or delete their personal information at any time, except that they cannot change their username. Website administrators can also see and edit that information. However, edited or deleted data will still be available on backups and should be considered to be retained indefinitely.

**Your rights over your data**: If a user wants to have a transcript from all of their chats (if that's considered data) will they be able to get that?

Are comments in the Forum or in-game chat considered personal data?

**Comment by blackshadowshade** [comment]
> This looks good! Some quick thoughts:
> 
> **Personal data**: "even if have attempted to hide this information from other players" <--- I think this is missing the word "you" after "if"?

Yup.

> **How long we retain your data**: You might switch the order of these to clarify:
> 
> All users can see, edit, or delete their personal information at any time, except that they cannot change their username. Website administrators can also see and edit that information. However, edited or deleted data will still be available on backups and should be considered to be retained indefinitely.

Okay.

> **Your rights over your data**: If a user wants to have a transcript from all of their chats (if that's considered data) will they be able to get that?

Yes, I would think so, it should be pretty easy to get this.

> Are comments in the Forum or in-game chat considered personal data?

I don't believe so. It is *technically* possible to accommodate a request to delete all chat and contents of forum posts of a user, but I'll defer to @cgolubi1 on whether this is something that we'll want to do or not.

**Comment by dwvanstone** [comment]
We could look at other organizations and how they handle forum posts. For instance:

https://www.washingtonpost.com/news/ask-the-post/discussion-and-submission-guidelines/
