### ISSUE TITLE
fanatics images

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#623]
I might be thinking of something else - but I don't think the old site hosted fanatics images.  I remember needing to provide a link to the image for my fanatic.  I think this might be why some fanatics were broken jpegs.

**Comment by Hurtay** [comment]
Is there a chance to contact the players who - back then - created the classic fanatic buttons to send their images? Some of them are still active players, right? I could i.e. just send them game challenges and ask them via ingame chat if that's ok with you. Or has this been done already?
I've mailed Skeeve a few weeks ago who'd promised to look in his archives for his old image files. He might not have any fanatic images though even if he'll find his old files. So we'll still be looking for the original fanatic images. As nice as Fog's general image is I think it would be pretty cool to have more fanatics with their original image.

**Comment by AdmiralJota** [comment]
We could theoretically also post to the forum.

**Comment by blackshadowshade** [comment]
I'm going to close this because I think we've gotten all the images that we're going to get easily. Any that we find can be added on a case by case basis. If anyone wants to go on a crusade to find fanatic images, you can certainly reopen this issue.
