### ISSUE TITLE
add unofficial sets

### ISSUE THREAD

**Issue by ManvilleFog** [buttonmen-dev/buttonmen#670]
. . . last of the database additions until other new sets are release.  
In addition to those already listed, but commented out in the current database, there's:
Kubla Con (I think this is an official set, but I didn't have stats on it previously) 
Cowboy Bebop
MegaTokyo
Thrust Interactive (original buttons from the iPhone app)
BM Trading Cards (I haven't found stats on these, but their on Kuni's checklist)

I've also found image files with fan sets:
Game of Thrones - 18 buttons (I think images are from books - they're not screen caps)Board Games (AmeriTrash vs. EuroGames) - 6 buttons for each set.
Touhou Project - this looks like a full deck of printed button cards, only a few of which are fully visible in the photo.

**Comment by dwvanstone** [comment]
(This is also to follow up on a comment in #1927)

We're getting close to releasing some of the buttoons on kaufman's 50 States. However, there are some recipes that may have worked on the DHS site but no longer make sense and may, in fact, make new players confused. (They certainly look like bugs.)

Mood Option is currently not supported, so we may need to change Connecticut. (Or decide to implement Mood Option, which is what #1927 is about.)

Illinois has "shadow stealth", but that makes no sense on our current set. I propose we remove "shadow".

**Comment by irilyth** [comment]
Huh, I hadn't realized that 50 States was kaufman's. Maybe we can actually ask him, if we have questions, he's around. :^ )

There's a couple of buttons that will trigger known bugs, which are out of the set on the dev site right now. If we can't support Connecticut as-is, I think it'd also be fine to disable it until we can.

I don't think meaningless skills are necessarily problematic, although they could be confusing. grend has a a z(8,8)?, where the ? is obviously meaningless, and three of GorgorBey's five dice have meaningless skills, presumably both for some non-game related purpose (humor, would be my guess). I think that if we think (or kaufman thinks) the 50 States buttons are funnier (or whatever) with meaningless skills, there's not necessarily anything wrong with that.

**Comment by dwvanstone** [comment]
I think the intention of GorgorBey's dice was to be funny - there's nothing wrong with that one! However, I have a sense that kaufman didn't add the meaningless skills to be funny but that they were just a mistake (or are now a mistake). If he's around we can certainly ask him!

**Comment by AdmiralJota** [comment]
I agree with @dwvanstone that *intentionally* meaningless skills are fine, but *unintentionally* meaningless skills are a different matter. And I agree with @irilyth that we should just disable the button for now until we either change Mood to support Option or ask kaufman if he wants to modify the recipe. (I'm in favor of the former, personally. It seems more intuitive, and likely in line with what the original devs would have done if the question had come up.)

**Comment by dwvanstone** [comment]
Okay, we took care of Connecticut for now in #1931.

What about Illinois?   (10/20) G(12) (8,8) (R) rsd(4) rsd(6)

It has shadow stealth dice. I believe from reading #83 that the old DHS site allowed shadow stealth dice to do shadow attacks, so kaufman's original recipe made sense there. I don't think they were added to be funny, and I think they will be confusing to new users to the site. 

Could we either remove Illinois from the list to be sent to production, or decide to remove shadow from the reserve dice for this button?

**Comment by AdmiralJota** [comment]
I think that, unless we conclude that kaufman is no longer available to answer questions like this, we shouldn't just decide to change the recipes on our own. We should defer to him, as the creator of the recipe. (So if sd doesn't work on the site, we should ask him what he thinks and temporarily disable the button until we find out.)

I believe that @irilyth said he had his email address?

**Comment by irilyth** [comment]
I think Shadow Stealth is a useless combination, but not a problematic one, and that we shouldn't change it, or disable Illinois.

I like the idea of asking kaufman -- I'll drop him a note, or ask him in the game we're playing. Should I encourage him to write to one of the dev mailing lists so the whole group can talk to him, or to post in a forum, or ... ?

**Comment by dwvanstone** [comment]
When I read the Shadow skill under the Illinois button it clearly states that dice with the Shadow skill can make Shadow Attacks. If we want to include Shadow Stealth dice I ask then that we add "Interaction with Stealth" to the Shadow skill description which specifies that dice with both shadow and stealth can not perform Shadow attacks.

(And yeah, I am troubled by grend's z(8,8)? die, but I think it's okay if the fanatics sets get to have nonsensical recipes.)

**Comment by irilyth** [comment]
I'd be ok with that, but then I think we'd also want to add an interaction note to every skill that gives you a new kind of attack (Trip, Speed, Berserk, etc) saying that Foo Stealth dice can't make Foo attacks.

**Comment by dwvanstone** [comment]
Could we add that interaction note only when a new button appears with that combination? Or is the intent of interaction notes to cover all possible cases?

**Comment by AdmiralJota** [comment]
> Should I encourage him to write to one of the dev mailing lists so the whole group can talk to him, or to post in a forum, or ... ?

If he's up for creating a github account, I think it'd be great if he could join in the discussions here. But if he doesn't want to do that (perfectly understandable), the dev mailing list is probably the next best option.

**Comment by irilyth** [comment]
Sounds good, I've asked him.

**Comment by kauftaxman** [comment]
Hi, Ken here.  Of course, some imposter took my username (and that with my first name).  Anyway, to answer a bit, yes, I did create that monstrosity.  It's a long time ago, and I forget all of what was going through my head.  And no, I probably wasn't aware of and/or a stickler on legal combinations.  As for some specifics:

Connecticut:  Much of the recipe relates to its small size and high population density.  The mood swing between two values, one low and one high (Connecticut Compromise), may have been supported on the old system.  If not, something like an R? would probably be the best cononical way to represent this.

Illinois:  I definitely saw shadow stealth on dhs.  Can't claim credit for that monstrosity.  Nasty things.  Only killable by skill and able to attack with skill or shadow.  As for the whys and wherefores, think of the legion of legendary dead voters!

**Comment by dwvanstone** [comment]
> Illinois: I definitely saw shadow stealth on dhs. Can't claim credit for that monstrosity. Nasty things. Only killable by skill and able to attack with skill or shadow. As for the whys and wherefores, think of the legion of legendary dead voters!

I've been enjoying all of the 50 states, and it would be fun to learn more about the origins of some of the fun buttons! I hope you'll come to the buttonweavers site and play them once we have them on production!!

As to Illinois: can you suggest a modification that doesn't have shadow stealth, or would you prefer to leave it with shadow stealth even though they can't do shadow attacks on our new system?

**Comment by cgolubi1** [comment]
FWIW, i don't have any problem with shadow stealth appearing on a button and not doing anything useful -- i think players will figure it out.  Mood option struck me as a lot more surprising, because it's difficult to guess, as irilyth eventually did, that you're always getting the same value because the feature isn't implemented and not just because you're getting unlucky or whatnot.

**Comment by irilyth** [comment]
> that you're always getting the same value because the feature isn't implemented

Indeed, and I also think this is very different from "you can never make Shadow Attacks with this die because Stealth trumps Shadow", which is a pretty clear interpretation of the rules, and the site implements that interpretation correctly -- whereas "the feature isn't implemented" has nothing to do with the rules of the game, and is just about coding.

To bring grend back into it, there's the argument that the z(8,8)? doesn't have this problem because clearly Mood Swing only affects a Swing die and clearly an (8,8) isn't a Swing die. I think one *could* also argue that clearly Mood Swing only affects a Swing die, and clearly a (4/20) isn't a Swing die. I think that's less intuitive, because a (4/20) is a lot more like a Swing die than an (8,8) is. The description even says: "They function like Swing Dice and can be changed at any time a Swing Die could be changed." So in that context, saying "oh, but not due to Mood Swing, because that's only for Swing, not for Option" seems confusing. (Especially since Turbo, when we have Turbo, will presumably affect both Swing and Option, unless we rewrite the various buttons with Turbo Option dice, which I recall there being at least a few of.)

**Comment by kauftaxman** [comment]
I guess if rsd weren't going to be allowed to operate as stealth that could also make shadow attacks, I'd support the affected Illi-dice becoming Reserve Warrior Shadow instead, and ditching the Stealth ability.

**Comment by irilyth** [comment]
Yeah, I think it's pretty well established at this point that Stealth trumps other skills (and the fact that it didn't was a bug on the old site), so if you'd like to change the recipe, that seems reasonable.

**Comment by blackshadowshade** [comment]
I'm going to close this one, because I'm pretty sure that we have found all the unofficial BM sets that we are going to find for the moment. The fan sets for Game of Thrones and Board Games were problematic because of their images, I think (from memory).

If anyone disagrees, feel free to reopen this issue.
