### ISSUE TITLE
better deployment tools for database updates

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#711]
We're pushing out code containing half a dozen database updates a week to two sites.  Any database update which is missed leads one of the sites to be unusable.  It's too easy to make mistakes.  Make better tools for this.

**Comment by blackshadowshade** [comment]
I'm pretty sure you've got this covered, @cgolubi1. Can we close the issue?

**Comment by cgolubi1** [comment]
Yeah, i don't think this issue is useful as written any more.
