### ISSUE TITLE
Morphing Trip dice

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#802]
Do Morphing Trip dice morph before they trip? They should, since otherwise they might roll a number higher than their range (e.g. if a tm(20) trips a (4), rolls a 9, and then morphs to 4).

(This came up in chat in a game, and we wanted to check; we can't test it since no currently-playable buttons have the combination.)

**Comment by edpegg** [comment]
In the current skill_order_array , Konstant is listed twice.

https://github.com/buttonmen-dev/buttonmen/blob/master/src/engine/BMSkill.php:
protected static function skill_order_array() {

**Comment by blackshadowshade** [comment]
So is morphing. Apparently, that was a merge gone bad. Let me take a look at what was intended.

**Comment by blackshadowshade** [comment]
Also, Fire seems to be missing from being explicitly listed.

**Comment by blackshadowshade** [comment]
Closing this, and shifting the bug to #1526.
