### ISSUE TITLE
During take initiative, indicate which dice are not relevant

### ISSUE THREAD

**Issue by Caligari** [buttonmen-dev/buttonmen#835]
I've often thought that it shouldn't be hard to show the player which dice are not part of the initiative process, to avoid confusion when using focus and chance dice.

Mostly, for me, I puzzle over situations where I or my opponent have Trip dice, but perhaps there are other dice which are ignored in the initiative process that I'm forgetting.

Anyway, I'd think it should be fairly easy to dim such dice (and include a note in the rollover to explain?) to clarify things a bit.

**Comment by nkmcalli** [comment]
Plus one.  Came here to file this.  Do the easiest possible thing - on the focus / chance screen - just mark the dice rows that count in any way possible.

And no one said it explicitly: you have to hover and read the text for each die skill to see which count for initiative.  For battles between dice with lots of different skills, this is very difficult.

**Comment by blackshadowshade** [comment]
So, I'm not ignoring this issue, but the most obvious way of addressing this changes the API response, which makes it difficult for the pull request to be accepted (based on the pull requests that have been open for a number of years without successful resolution).

Chaos has said that she's almost there with putting in place monitoring metrics, which may make it easier for us to spot errors arising from API changes, so I'm going to wait until that's up and running.

**Comment by blackshadowshade** [comment]
We're making progress on accepting the difficult pull requests, so I'm actively thinking about this one and digging through the code to explore how it might be implemented.
