### ISSUE TITLE
Players should be able to set their profile image

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#909]
Probably by uploading it from the preferences page, but maybe by some other means (like gravatar).

**Comment by blackshadowshade** [comment]
This was solved by #1075, so I'm closing this.

**Comment by irilyth** [comment]
I thought there was still some question about whether we wanted to allow people who didn't use Gravatar to set a profile image. If we don't, then I agree this is done.

**Comment by blackshadowshade** [comment]
I'm happy with requiring the use of Gravatar, since we don't currently have any on-site way of managing profile images.
