### ISSUE TITLE
Radioactive skill needed

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#95]

**Comment by PoshFrosh** [comment]
> Considering that radioactive morphing dice apply morphing first then radioactive, I would think that the most consistent with that would be to apply doppelganger first then radioactive.
> 
> Of course, if anyone wants to argue for morphing to be applied AFTER radioactive, I'm open to hearing that argument. :)

PoshFrosh [raises his hand](https://www.buttonweavers.com/ui/forum.html#!threadId=1221&postId=29515).
